CREATE OR REPLACE FUNCTION APPS.XX_30_DAYS_CONSUM_FN (P_PR_APP_DT IN DATE,P_ITEM IN  NUMBER,P_ORG IN NUMBER)
RETURN number IS
V_QTY number(10) :=0;
BEGIN
SELECT ABS(NVL(SUM(NVL(PRIMARY_QUANTITY,0)),0))  INTO V_QTY 
FROM MTL_MATERIAL_TRANSACTIONS
WHERE TRUNC(TRANSACTION_DATE) BETWEEN (TRUNC(P_PR_APP_DT)-30) AND TRUNC(P_PR_APP_DT)
AND INVENTORY_ITEM_ID=P_ITEM
AND ORGANIZATION_ID=P_ORG
AND PRIMARY_QUANTITY<0;
RETURN V_QTY;
EXCEPTION 
WHEN OTHERS THEN
RETURN 0;
END;
/