SELECT * FROM RCV_SHIPMENT_HEADERS WHERE RECEIPT_NUM= 80003012 AND SHIP_TO_ORG_ID=166

SELECT* FROM RCV_TRANSACTIONS WHERE PO_HEADER_ID = 879988 AND TRANSACTION_TYPE = 'DELIVER' 

SELECT ITEM_DESCRIPTION, SUM(QUANTITY_SHIPPED) FROM RCV_SHIPMENT_LINES WHERE SHIPMENT_HEADER_ID= 1074826 GROUP BY ITEM_DESCRIPTION

select * from PO_HEADERS_ALL WHERE PO_HEADER_ID=879988

SELECT * FROM XX_LC_DETAILS WHERE PO_HEADER_ID= '34001'

--============================================
-- LC, PO, GRN DATA DATE WISE
--============================================

SELECT OU_ID, GET_OU_NAME_FROM_ID(OU_ID) OU_NAME, LC_NUMBER,SUPPLIER_NAME, ITEM_DESCRIPTION,UOM,CURRENCY,PO_NUMBER,PO_QUANTITY,PRICE , GRN_NUMBER,GRN_QUANTITY,GRN_DATE ,(GRN_QUANTITY*PRICE) GRN_VALUE FROM XXKBG_BI_PO_GRN WHERE OU_ID=104 
--AND GRN_DATE BETWEEN '01-FEB-2022' and '28-FEB-2022' 
and CURRENCY <>'BDT'





SELECT * FROM XX_LC_DETAILS_DT

SELECT 
distinct PHA.org_id,
 PHA.PO_HEADER_ID,
 LCD.LC_ID,
SUBSTR(XX_GET_HR_OPERATING_UNIT (PHA.ORG_ID),5) OPERATING_UNIT,
--XX_INV_PKG.XXGET_ORG_LOCATION (PHA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
       ASP.VENDOR_NAME,
       ASP.SEGMENT1 VENDOR_NO,
      PHA.SEGMENT1 PO_NUMBER,
      PLA.QUANTITY PO_QTY,
      PLA.UNIT_PRICE UNIT_PRICE,
       PHA.APPROVED_DATE  PO_APPROVED_DATE,
           PLA.ITEM_DESCRIPTION,
            XXGET_ITEM_CODE(PLA.ITEM_ID) ITEM_CODE,
            PLA.UNIT_MEAS_LOOKUP_CODE,    
            PHA.CURRENCY_CODE,      
   --  (PLA.UNIT_PRICE* PLA.QUANTITY) PO_AMOUNT,
          RT.QUANTITY GRN_QTY,
          (PLA.UNIT_PRICE* RT.QUANTITY) GRN_AMOUNT,
          RH.RECEIPT_NUM GRN_NUMBER, 
          RT.CREATION_DATE GRN_DATE,
         XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
 from PO_HEADERS_ALL PHA, PO_LINES_ALL PLA, PO_LINE_LOCATIONS_ALL PLL,PO_DISTRIBUTIONS_ALL PDA, AP_SUPPLIERS ASP,
 RCV_TRANSACTIONS RT,RCV_SHIPMENT_LINES RL, RCV_SHIPMENT_HEADERS RH,  XX_LC_DETAILS LC,
 XX_LC_DETAILS_DT LCD
 WHERE PHA.PO_HEADER_ID =PLA.PO_HEADER_ID
 and PHA.po_header_id = PLA.po_header_id
 and PLA.po_line_id= pll.po_line_id
 and PHA.po_header_id= pll.po_header_id
 and PHA.PO_HEADER_ID= PLA.PO_HEADER_ID
 AND PLA.PO_LINE_ID= PDA.PO_LINE_ID
 AND PLA.QUANTITY <> 0
 AND PHA.PO_HEADER_ID= RT.PO_HEADER_ID
 AND PLA.PO_LINE_ID= RT.PO_LINE_ID
 AND PDA.GL_CANCELLED_DATE is NULL
 AND RT.TRANSACTION_TYPE= 'DELIVER'
    AND PDA.PO_DISTRIBUTION_ID NOT IN
      (SELECT PO_DISTRIBUTION_ID FROM PO_DISTRIBUTIONS_ALL PDA
       WHERE PO_DISTRIBUTION_ID IN (SELECT DISTINCT  PO_DISTRIBUTION_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL))
 AND RH.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID
 AND RH.SHIPMENT_HEADER_ID= RL.SHIPMENT_HEADER_ID
 AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
 AND ASP.VENDOR_ID= PHA.VENDOR_ID
   AND (:P_ORG_ID IS NULL OR PHA.ORG_ID = :P_ORG_ID)
  AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
  AND (:P_PO_NO IS NULL OR PHA.segment1 = :P_PO_NO) 
  AND (:P_GRN_NO IS NULL OR rh.receipt_num = :P_GRN_NO) 
  and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
   and PHA.VENDOR_ID = NVL(:P_VENDOR_ID, PHA.VENDOR_ID)
   AND RT.ORGANIZATION_ID = 166 
   AND PHA.PO_HEADER_ID= LC.PO_HEADER_ID(+)
 AND LC.LC_ID= LCD.LC_ID(+)
AND RH.SHIPMENT_HEADER_ID = LCD.SHIPMENT_HEADER_ID(+)
 AND RL.SHIPMENT_LINE_ID = LCD.SHIPMENT_LINE_ID(+)
   --AND PHA.PO_HEADER_ID=34001
   
   
   SELECT * FROM PO_HEADERS_ALL 
   
   SELECT * FROM XX_LC_DETAILS WHERE ORG_ID= 104
   
   SELECT * FROM XX_AP_LC_DETAILS_VK WHERE ORG_ID= 104
   
   --LC REGISTER REPORT FINAL
SELECT ORG.ORGANIZATION_CODE,RL.SHIPMENT_LINE_ID,RH.SHIPMENT_HEADER_ID,
SUBSTR(XX_GET_HR_OPERATING_UNIT(:P_ORG),5) ORG_HEADER_NAME,
NVL((SELECT NVL(SUM(B.QUANTITY),0) FROM RCV_TRANSACTIONS B WHERE B.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID  AND B.SHIPMENT_LINE_ID = RL.SHIPMENT_LINE_ID AND B.TRANSACTION_TYPE='DELIVER')-
(SELECT SUM(A.QUANTITY)  FROM RCV_TRANSACTIONS A  WHERE   A.TRANSACTION_TYPE = 'RETURN TO VENDOR' AND A.SHIPMENT_LINE_ID=RL.SHIPMENT_LINE_ID --AND A.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID
 ),(SELECT NVL(SUM(B.QUANTITY),0) FROM RCV_TRANSACTIONS B WHERE B.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID  AND B.SHIPMENT_LINE_ID = RL.SHIPMENT_LINE_ID AND B.TRANSACTION_TYPE='DELIVER')) DELV_QTY,
(SELECT SUM(A.QUANTITY)  FROM RCV_TRANSACTIONS A  WHERE   A.TRANSACTION_TYPE = 'RETURN TO VENDOR' AND A.SHIPMENT_LINE_ID=RL.SHIPMENT_LINE_ID --AND A.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID
 ) RET_QTY,
 LC.LC_NUMBER,
 LC.LC_OPENING_DATE,
LC. LC_AMDT_DATE,
RH.SHIPMENT_NUM,
LC.FOB_CF DEL_TERMS, 
LC.BANK_NAME,
DECODE(LC.LC_TYPE,'D','Defferd','S','Sight','C','CAD','U','UPAS','T','TT',LC.LC_TYPE) LC_TYPE,
ROUND(IND.GRN_DT-LC.LC_OPENING_DATE)LEAD_TIME,
POL.ITEM_DESCRIPTION,
 POH.SEGMENT1 ,
POH.PO_HEADER_ID,
POL.PO_LINE_ID,
XX_FND_EMP_NAME(POH.CREATED_BY) USER_NAME,
(LC.SUPPLIER_NAME||' ( '||    LC.SUPPLIER_NUMBER||') ')SUPPLIER,
LC.SUPPLIER_BANK_NAME,
PLL.QUANTITY PO_QTY,
POL.UNIT_MEAS_LOOKUP_CODE UOM,
POL.LINE_NUM,
RL.QUANTITY_SHIPPED,
POL.UNIT_PRICE,
(PLL.QUANTITY)*POL.UNIT_PRICE AMOUNT,
POH.CURRENCY_CODE,
 POH.SEGMENT1 PO_NO,
 TO_CHAR(POH.CREATION_DATE,'DD-MON-RRRR') CREATION_DATE,
 LC.PROFORMA_INVOICE_NUM PI_NO,
 LC.PROFORMA_INVOICE_DATE PI_DATE,
 POL.ATTRIBUTE2 ORIGIN,
 POH.REVISION_NUM PO_AMEND_NO,
 LC.HS_CODE,
 RH.RECEIPT_NUM DEEP_SEA_GRN,
 NVL(LCD.GRN_QTY,0) PORT_QTY,
 LCD.GRN_VALUE GRN_VALUE,
 PLL.QUANTITY-NVL(LCD.GRN_QTY,0) PENDING_QTY,
NVL(PLL.QUANTITY-NVL(LCD.GRN_QTY,0),0)*POL.UNIT_PRICE PENDING_QTY_VALUE,
 LC.ETA,
 LC.ETD,
 DEL_QTY*POL.UNIT_PRICE FAC_GRN_VALUE,
 POH.RATE,
 NVL(NVL(PLL.QUANTITY,0)*NVL(POH.RATE,0)*NVL(POL.UNIT_PRICE,0),0) CONV_AMNT_BDT, 
   NVL(NVL(NVL((SELECT NVL(SUM(B.QUANTITY),0) FROM RCV_TRANSACTIONS B WHERE B.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID  AND B.SHIPMENT_LINE_ID = RL.SHIPMENT_LINE_ID AND B.TRANSACTION_TYPE='DELIVER')-
(SELECT SUM(A.QUANTITY)  FROM RCV_TRANSACTIONS A  WHERE   A.TRANSACTION_TYPE = 'RETURN TO VENDOR' AND A.SHIPMENT_LINE_ID=RL.SHIPMENT_LINE_ID --AND A.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID
 ),(SELECT NVL(SUM(B.QUANTITY),0) FROM RCV_TRANSACTIONS B WHERE B.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID  AND B.SHIPMENT_LINE_ID = RL.SHIPMENT_LINE_ID AND B.TRANSACTION_TYPE='DELIVER')),0)*NVL(POL.UNIT_PRICE,0),0) GRN_AMNT_USD12,
  NVL(NVL(NVL((SELECT NVL(SUM(B.QUANTITY),0) FROM RCV_TRANSACTIONS B WHERE B.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID  AND B.SHIPMENT_LINE_ID = RL.SHIPMENT_LINE_ID AND B.TRANSACTION_TYPE='DELIVER')-
(SELECT SUM(A.QUANTITY)  FROM RCV_TRANSACTIONS A  WHERE   A.TRANSACTION_TYPE = 'RETURN TO VENDOR' AND A.SHIPMENT_LINE_ID=RL.SHIPMENT_LINE_ID --AND A.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID
 ),(SELECT NVL(SUM(B.QUANTITY),0) FROM RCV_TRANSACTIONS B WHERE B.SHIPMENT_HEADER_ID=RH.SHIPMENT_HEADER_ID  AND B.SHIPMENT_LINE_ID = RL.SHIPMENT_LINE_ID AND B.TRANSACTION_TYPE='DELIVER')),0)*NVL(POH.RATE,0)*NVL(POL.UNIT_PRICE,0),0) GRN_AMNT_BDT12, 
 DEL_QTY FAC_QTY,
ABS(LCD.GRN_QTY-PLL.QUANTITY) DEEP_SEA_ACCESS_QTY,
 DEL_DT DELIVERY_DT,
 LC.LATEST_SHIPMENT_DATE LSD,
      LC.LC_EXPIRE_DATE EXP1,
        LCD.ORIGINAL_DOC_DATE ORG_DOC_DT,---?
        LCD.DUTY_PAID_DATE DUTY_DT,
        LC.LCA_NO LCA_NO,
       LC.COVER_NO COVER_NOTE,
       LC.COVER_DATE COVER_DT,
       LCD.POLICY_NO POLICY_NO,
       LC.INSURANCE_NAME,
        LCD.BL_AWB_CONSIGNMENT_NO BL_NO,
        LCD.BL_AWB_CONSIGNMENT_DATE BL_DT,
        LCD.BILL_OF_ENTRY_NO BE_NO,
        LCD.BILL_OF_ENTRY_DATE BE_DT ,   
DECODE(LC.LC_STATUS,'O','Open','C','Closed') LC_STATUS,
 LCD.COMMERCIAL_INVOICE_NO COMMERCIAL_INVOICE_NO,
 LCD.COMMERCIAL_INVOICE_DATE COMMERCIAL_INVOICE_DATE,
 LCD.VESSEL_NAME AIR_VESSEL_NAME,
 LCD.PORT_OF_LOADING PORT_OF_LOADING,
  LCD.ORIGINAL_DOC_DATE ORIGINAL_DOC_ARRIVAL_DATE,
  LCD.MATURITY_DATE,
 LCD.ACCEPTANCE_DATE ACCEPTANCE_DATE,
 RH.ATTRIBUTE9 FORWARDING_SCHEDULE_DATE,---?
 LCD.ASSESSABLE_VALUE ASSESSABLE_VALUE,
 LCD.TOTAL_NO_PACKAGE TOTAL_NO_OF_PACKAGE,
 RH.ATTRIBUTE3 TOTAL_NO_OF_ITEMS,
 LCD.GROSS_WEIGHT GROSS_WEIGHT,
 LCD.NET_WEIGHT NET_WEIGHT,
 LCD.COUNTRY_OF_ORIGIN COUNTRY_OF_ORIGIN,
RT.ATTRIBUTE10 LIGHTER_MOTHER_VESSEL,
RT.ATTRIBUTE11 CONTAINER_NUMBER,
RT.ATTRIBUTE13 CONTAINER_SIZE,
RT.ATTRIBUTE14 CARRYING_CONTRACTOR_NAME,
RT.ATTRIBUTE2 CRANE_SUPPLIER,
LCD.CNF_NAME C_F_AGENT,
RT.ATTRIBUTE15 C_F_CHALLAN_NO,
 (SELECT VENDOR_NAME FROM AP_SUPPLIERS WHERE VENDOR_ID=:P_VENDOR_ID) P_SUPPLIER,
(SELECT DISTINCT DESCRIPTION FROM MTL_SYSTEM_ITEMS_KFV WHERE INVENTORY_ITEM_ID=:P_ITEM_ID) P_ITEM,
(SELECT LC_NUMBER FROM XX_LC_DETAILS WHERE LC_ID=:P_LC_ID) P_LC,
 (SELECT DISTINCT DECODE(LC_TYPE,'D','Defferd','S','Sight','C','CAD','U','UPAS','T','TT',LC_TYPE) FROM XX_LC_DETAILS WHERE LC_TYPE=:P_LC_TYPE) P_LC_TYPE,
(SELECT BANK_NAME FROM CE_BANKS_V WHERE BANK_PARTY_ID=:P_BANK_ID) P_BANK,
TO_CHAR(:P_FR_DT,'DD-MON-RRRR') FROM_DATE,
TO_CHAR(:P_TO_DT,'DD-MON-RRRR') TO_DATEE
 FROM PO_HEADERS_ALL POH , 
PO_LINES_ALL POL ,
PO_LINE_LOCATIONS_ALL PLL,
RCV_SHIPMENT_HEADERS RH,
RCV_SHIPMENT_LINES RL,
RCV_TRANSACTIONS RT,
XX_LC_DETAILS LC,
 XX_LC_DETAILS_DT LCD,
 XX_IND_PAY_V IND,
ORG_ORGANIZATION_DEFINITIONS ORG
 WHERE 1 = 1 
 AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
 AND POL.PO_LINE_ID= PLL.PO_LINE_ID
 AND POH.PO_HEADER_ID = RL.PO_HEADER_ID(+)
 AND POH.CANCEL_FLAG <> 'Y'
AND RH.SHIPMENT_HEADER_ID(+)= RL.SHIPMENT_HEADER_ID
AND RH.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID(+)
 AND RL.SHIPMENT_LINE_ID = RT.SHIPMENT_LINE_ID(+)
AND POH.PO_HEADER_ID= LC.PO_HEADER_ID 
 AND LC.LC_ID= LCD.LC_ID(+)
AND RH.SHIPMENT_HEADER_ID = LCD.SHIPMENT_HEADER_ID(+)
 AND RL.SHIPMENT_LINE_ID = LCD.SHIPMENT_LINE_ID(+)
AND RH.SHIPMENT_HEADER_ID = IND.SHIPMENT_HEADER_ID(+)
AND RL.SHIPMENT_LINE_ID = IND.SHIPMENT_LINE_ID(+)
AND POH.PO_HEADER_ID = IND.PO_HEADER_ID(+)
AND POL.PO_LINE_ID = IND.PO_LINE_ID(+)
 AND PLL.LINE_LOCATION_ID= IND.PO_LINE_LOCATION_ID
 AND PLL.SHIP_TO_ORGANIZATION_ID =ORG.ORGANIZATION_ID
 AND   RT.TRANSACTION_TYPE IN ('RECEIVE', 'DELIVER') 
--AND   POH.TYPE_LOOKUP_CODE IN ('BLANKET','STANDARD')
AND POH.ORG_ID=NVL(:P_ORG,POH.ORG_ID)
AND LC.VENDOR_ID=NVL(:P_VENDOR_ID, LC.VENDOR_ID)
AND POL.ITEM_ID=NVL(:P_ITEM_ID,POL.ITEM_ID)
AND LC.LC_ID=NVL(:P_LC_ID,LC.LC_ID)
AND LC.LC_TYPE=NVL(:P_LC_TYPE,LC.LC_TYPE)
AND LC.BANK_ID=NVL(:P_BANK_ID,LC.BANK_ID)
AND TRUNC(LC.LC_OPENING_DATE) BETWEEN  NVL(:P_FR_DT, TRUNC(LC.LC_OPENING_DATE)) AND NVL(:P_TO_DT, TRUNC(LC.LC_OPENING_DATE))
AND TRUNC(DEL_DT) BETWEEN  NVL(:P_FR_GRN_DT, TRUNC(DEL_DT)) AND NVL(:P_TO_GRN_DT, TRUNC(DEL_DT))
AND RT.SHIPMENT_HEADER_ID= 1074826
GROUP BY ORG.ORGANIZATION_CODE,
 LC.LC_NUMBER,
 LC.LC_OPENING_DATE,
LC. LC_AMDT_DATE,
RH.SHIPMENT_NUM,
RL.SHIPMENT_LINE_ID,
LC.FOB_CF , 
LC.BANK_NAME,
LC.LC_TYPE,
ROUND(IND.GRN_DT-LC.LC_OPENING_DATE),
POL.ITEM_DESCRIPTION,
POH.CREATED_BY,
(LC.SUPPLIER_NAME||' ( '||    LC.SUPPLIER_NUMBER||') '),
LC.SUPPLIER_BANK_NAME,
PLL.QUANTITY ,
POL.UNIT_MEAS_LOOKUP_CODE ,
RL.QUANTITY_SHIPPED,
POL.UNIT_PRICE,
POH.CURRENCY_CODE,
 POH.SEGMENT1 ,
 TO_CHAR(POH.CREATION_DATE,'DD-MON-RRRR') ,
 LC.PROFORMA_INVOICE_NUM ,
 LC.PROFORMA_INVOICE_DATE ,
 POL.ATTRIBUTE2 ,
 POH.REVISION_NUM ,
 LC.HS_CODE,
 LCD.GRN_NO ,
 LCD.GRN_QTY ,
 LCD.GRN_VALUE ,
 PLL.QUANTITY-NVL(LCD.GRN_QTY,0) ,
NVL(PLL.QUANTITY-NVL(LCD.GRN_QTY,0),0)*POL.UNIT_PRICE ,
 LC.ETA,
 LC.ETD,
 DEL_QTY*POL.UNIT_PRICE ,
 POH.RATE,
 PLL.QUANTITY*POH.RATE , 
 DEL_QTY ,
ABS(LCD.GRN_QTY-PLL.QUANTITY) ,
 DEL_DT ,
LC.LATEST_SHIPMENT_DATE,
        LCD.ORIGINAL_DOC_DATE ,
        LCD.DUTY_PAID_DATE ,
        LC.LCA_NO ,
       LC.COVER_NO ,
       LC.COVER_DATE ,
       LCD.POLICY_NO ,
       LC.INSURANCE_NAME,
        LCD.BL_AWB_CONSIGNMENT_NO ,
        LCD.BL_AWB_CONSIGNMENT_DATE ,
        LCD.BILL_OF_ENTRY_NO ,
        LCD.BILL_OF_ENTRY_DATE  ,   
DECODE(LC.LC_STATUS,'O','Open','C','Closed') ,
LCD.COMMERCIAL_INVOICE_NO ,
 LCD.COMMERCIAL_INVOICE_DATE ,
 LCD.VESSEL_NAME ,
 LCD.PORT_OF_LOADING ,
  LCD.ORIGINAL_DOC_DATE ,
  LCD.MATURITY_DATE,
 LCD.ACCEPTANCE_DATE ,
 RH.ATTRIBUTE9 ,---?
 LCD.ASSESSABLE_VALUE ,
 LCD.TOTAL_NO_PACKAGE ,
 RH.ATTRIBUTE3 ,
 LCD.GROSS_WEIGHT ,
 LCD.NET_WEIGHT ,
 LCD.COUNTRY_OF_ORIGIN ,
RT.ATTRIBUTE10 ,
RT.ATTRIBUTE11 ,
RT.ATTRIBUTE13 ,
RT.ATTRIBUTE14 ,
POL.LINE_NUM,
RT.ATTRIBUTE2 ,
LCD.CNF_NAME ,
 LC.LC_EXPIRE_DATE,
RT.ATTRIBUTE15 ,
RH.RECEIPT_NUM ,
RH.SHIPMENT_HEADER_ID,
POL.PO_LINE_ID,
POH.PO_HEADER_ID
  