--Month and OU  WISE  Payment ,AP INvoice ,GRN ,PO,LC Number--IN GRN  Month

SELECT   DISTINCT  A.OU,A.ORGANIZATION_CODE,A.VENDOR_NAME,A.PO_NUMBER, AI.INVOICE_NUM, AI.DOC_SEQUENCE_VALUE VOUCHER_NUMBER, 
AD.ACCOUNTING_DATE GL_DATE,AI.DESCRIPTION, AIL.LINE_TYPE_LOOKUP_CODE,
RECEIPT_NUMBER,RECEIPT_DATE,TRUNC(A.CREATION_DATE) RECEIPT_CREATION_DATE,LC_NUMBER, DECODE (PE.DESCRIPTION, NULL, '', PE.DESCRIPTION) LC_CHARGE_TYPE,
 CK.DOC_SEQUENCE_VALUE PAY_VOUCHER_NUMBER,TRUNC (CK.CHECK_DATE) PAYMENT_GL_DATE,CK.BANK_ACCOUNT_NAME,CK.CHECK_NUMBER,ck.DOC_CATEGORY_CODE,
AI.INVOICE_AMOUNT, CK.AMOUNT PAYMENT_AMOUNT,
NVL (AD.BASE_AMOUNT, AD.AMOUNT) Dis_AMOUNT
 FROM XX_PO_RECEIPT A, AP_INVOICE_LINES_ALL AIL, AP_INVOICES_ALL AI, AP_INVOICE_DISTRIBUTIONS_ALL AD,PON_PRICE_ELEMENT_TYPES_TL PE,AP_INVOICE_PAYMENTS_ALL PM,AP_CHECKS_ALL CK
WHERE A.PO_HEADER_ID=AIL.PO_HEADER_ID
AND A.TRANSACTION_ID=AIL.RCV_TRANSACTION_ID
AND AI.INVOICE_ID= AIL.INVOICE_ID
AND A.ORG_ID=AI.ORG_ID
AND AI.INVOICE_ID= AD.INVOICE_ID
AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
AND AI.CANCELLED_DATE IS NULL
AND A.RECEIPT_DATE in ('Oct-18') 
AND AI.ORG_ID=104
AND AD.INVOICE_LINE_NUMBER=LINE_NUMBER
AND AIL.COST_FACTOR_ID = PE.PRICE_ELEMENT_TYPE_ID(+)
AND AI.INVOICE_ID=PM.INVOICE_ID(+)
AND PM.CHECK_ID=CK.CHECK_ID(+) 
AND NVL (CK.STATUS_LOOKUP_CODE, 'XX') <> 'VOIDED'
 AND NVL (PM.REVERSAL_FLAG, 'N') <> 'Y'
--AND B.ACCOUNTING_DATE NOT BETWEEN :P_DATE_FROM AND :P_DATE_TO_ONE
AND AD.ACCOUNTING_DATE  NOT BETWEEN '01-oct-2018' and '31-oct-2018'
AND AIL.LINE_TYPE_LOOKUP_CODE='MISCELLANEOUS'
ORDER BY AI.DOC_SEQUENCE_VALUE


--Month and OU  WISE  Payment ,AP INvoice ,GRN ,PO,LC Number--NOT IN GRN  Month

SELECT   DISTINCT  A.OU,A.ORGANIZATION_CODE,A.VENDOR_NAME,A.PO_NUMBER, AI.INVOICE_NUM, AI.DOC_SEQUENCE_VALUE VOUCHER_NUMBER, 
AD.ACCOUNTING_DATE GL_DATE,AI.DESCRIPTION, AIL.LINE_TYPE_LOOKUP_CODE,
RECEIPT_NUMBER,RECEIPT_DATE,TRUNC(A.CREATION_DATE) RECEIPT_CREATION_DATE,LC_NUMBER, DECODE (PE.DESCRIPTION, NULL, '', PE.DESCRIPTION) LC_CHARGE_TYPE,
 CK.DOC_SEQUENCE_VALUE PAY_VOUCHER_NUMBER,TRUNC (CK.CHECK_DATE) PAYMENT_GL_DATE,CK.BANK_ACCOUNT_NAME,CK.CHECK_NUMBER,ck.DOC_CATEGORY_CODE,
AI.INVOICE_AMOUNT, CK.AMOUNT PAYMENT_AMOUNT,
NVL (AD.BASE_AMOUNT, AD.AMOUNT) Dis_AMOUNT
 FROM XX_PO_RECEIPT A, AP_INVOICE_LINES_ALL AIL, AP_INVOICES_ALL AI, AP_INVOICE_DISTRIBUTIONS_ALL AD,PON_PRICE_ELEMENT_TYPES_TL PE,AP_INVOICE_PAYMENTS_ALL PM,AP_CHECKS_ALL CK
WHERE A.PO_HEADER_ID=AIL.PO_HEADER_ID
AND A.TRANSACTION_ID=AIL.RCV_TRANSACTION_ID
AND AI.INVOICE_ID= AIL.INVOICE_ID
AND A.ORG_ID=AI.ORG_ID
AND AI.INVOICE_ID= AD.INVOICE_ID
AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
AND AI.CANCELLED_DATE IS NULL
AND A.RECEIPT_DATE NOT IN ('Oct-18') 
AND AI.ORG_ID=104
AND AD.INVOICE_LINE_NUMBER=LINE_NUMBER
AND AIL.COST_FACTOR_ID = PE.PRICE_ELEMENT_TYPE_ID(+)
AND AI.INVOICE_ID=PM.INVOICE_ID(+)
AND PM.CHECK_ID=CK.CHECK_ID(+) 
AND NVL (CK.STATUS_LOOKUP_CODE, 'XX') <> 'VOIDED'
 AND NVL (PM.REVERSAL_FLAG, 'N') <> 'Y'
--AND B.ACCOUNTING_DATE NOT BETWEEN :P_DATE_FROM AND :P_DATE_TO_ONE
AND AD.ACCOUNTING_DATE BETWEEN '01-oct-2018' and '31-oct-2018'
AND AIL.LINE_TYPE_LOOKUP_CODE='MISCELLANEOUS'
ORDER BY AI.DOC_SEQUENCE_VALUE

