CREATE TABLE VENDOR
(
V_ID NUMBER,
V_NAME VARCHAR2(50) NOT NULL,
V_ADDRESS VARCHAR2(100),
V_CONTACT VARCHAR2(12) NOT NULL,

PRIMARY KEY(V_ID)
);


CREATE TABLE PRODUCT
(
P_ID NUMBER,
P_NAME VARCHAR2(50) NOT NULL,
P_UOM VARCHAR2(5),
V_CONTACT VARCHAR2(12) NOT NULL,

PRIMARY KEY(P_ID)
);


CREATE TABLE SALES (
    S_ID NUMBER ,
	V_NAME VARCHAR2(50),
	P_NAME VARCHAR2(100),
    UOM VARCHAR2(5),
	QUANTITY NUMBER,
	PRICE NUMBER,
	TOTAL NUMBER,
	
	PRIMARY KEY(S_ID)
);

--=================================
CREATE TABLE  "SALES" 
   (	"S_ID" NUMBER NOT NULL ENABLE, 
	"P_ID" NUMBER, 
	"V_ID" NUMBER, 
	"UOM" VARCHAR2(5), 
	"QUANTITY" NUMBER, 
	"PRICE" NUMBER(8,2), 
	"TOTAL" NUMBER, 
	"NEED_BY_DATE" DATE, 
	 CONSTRAINT "SALES_PK" PRIMARY KEY ("S_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "SALES" ADD CONSTRAINT "SALES_FK" FOREIGN KEY ("P_ID")
	  REFERENCES  "PRODUCT" ("P_ID") ENABLE
/
ALTER TABLE  "SALES" ADD CONSTRAINT "VENDOR_FK" FOREIGN KEY ("V_ID")
	  REFERENCES  "VENDOR" ("V_ID") ON DELETE CASCADE ENABLE
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_SALES" 
  before insert on "SALES"               
  for each row  
begin   
  if :NEW."S_ID" is null then 
    select "SALES_SEQ1".nextval into :NEW."S_ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_SALES" ENABLE
/







sequence
=========
CREATE  SEQUENCE MY_SEQ START WITH 1 INCREMENT BY 1  NOCACHE;

CREATE  SEQUENCE PROD_SEQ START WITH 1 INCREMENT BY 1  NOCACHE;
