-- BACKEND DATA FOR ARAFAT
--============================

--=========================
-- 1 EMPTY CYLINDER RECIVING WITH CHALLAN NUMBER FOR ARAFAT
--=========================
SELECT CUSTOMER_NAME, CHALLAN_NO,  CHALLAN_DATE, CHALLAN_QTY, RECEIPT_QTY RECEIVE_QTY, CHALLAN_QTY - RECEIPT_QTY BALANCE  FROM  XX_CHALLAN_MO_TEMP 
WHERE CHALLAN_DATE BETWEEN '01-AUG-2018' and '5-JAN-2023'
ORDER BY CHALLAN_DATE 

--=======================================
-- 2 ALL EMPTY CYLINDER RECIVING WITHOUT CHALLAN NUMBER FOR ARAFAT , Attribute3= challan number
--=======================================
SELECT (SELECT TRANSACTION_TYPE_NAME from  MTL_TRANSACTION_TYPES WHERE  TRANSACTION_TYPE_ID=a.TRANSACTION_TYPE_ID) Transaction_Type, 
(SELECT DISTINCT ITEM_DESC  FROM WBI_XXKBGITEM_MT_D D where A.INVENTORY_ITEM_ID = D.INVENTORY_ITEM_ID) ITEM_DESC,
a.TRANSACTION_QUANTITY,a.TRANSACTION_DATE, Attribute3 CHALLAN_NO
 FROM MTL_MATERIAL_TRANSACTIONS a  WHERE INVENTORY_ITEM_ID IN(66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867,
                  787861)
  and ATTRIBUTE3 is   null  --and transaction_date between '01-DEC-2022' and '31-DEC-2022'
  AND  (SELECT TRANSACTION_TYPE_NAME from  MTL_TRANSACTION_TYPES WHERE  TRANSACTION_TYPE_ID=a.TRANSACTION_TYPE_ID)  = 'Empty Cylinder Receive'



SELECT * FROm XX_CHALLAN_MO_TEMP ORDER BY CHALLAN_DATE desc

select*from MTL_ONHAND_QUANTITIES where INVENTORY_ITEM_ID=428 --428    FA|OTFA|OLVA|000003    EMPTY CYLINDER (9.8 M3)
select sum(TRANSACTION_QUANTITY)  from MTL_ONHAND_QUANTITIES where INVENTORY_ITEM_ID=428 ----428    FA|OTFA|OLVA|000003    EMPTY CYLINDER (9.8 M3)

select*from MTL_ONHAND_QUANTITIES where INVENTORY_ITEM_ID=75 -- 75    FG|CYLN|O2|000047    FILLED OXYGEN CYLINDER (9.8 M3)
select sum(TRANSACTION_QUANTITY) from MTL_ONHAND_QUANTITIES where INVENTORY_ITEM_ID=75 -- 75    FG|CYLN|O2|000047    FILLED OXYGEN CYLINDER (9.8 M3) --> STOCK:2951

--=============
-- FOR MAMUN BOS
--=============
SELECT b.TRANSACTION_TYPE_NAME,XXGET_ITEM_DESCRIPTION(a.INVENTORY_ITEM_ID,a.ORGANIZATION_ID) INVENTORY_ITEM,
A.TRANSACTION_ID,a.ORGANIZATION_ID,
(SELECT ORGANIZATION_CODE FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_ID=a.ORGANIZATION_ID) ORGANIZATION_CODE,
a.TRANSACTION_QUANTITY,a.TRANSACTION_DATE,a.SOURCE_CODE,a.SHIPMENT_NUMBER
 FROM MTL_MATERIAL_TRANSACTIONS a , MTL_TRANSACTION_TYPES B 
WHERE   a.INVENTORY_ITEM_ID IN(66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867,
                  787861)
and  a.TRANSACTION_TYPE_ID= b.TRANSACTION_TYPE_ID
AND b.TRANSACTION_TYPE_NAME NOT IN('Internal Order Pick', 'Sales Order Pick')
--and TRANSACTION_DATE between '1-AUG-2018' and '05-JAN-2023'
AND TRANSACTION_TYPE_NAME IN ('Opening Stock Receipts','Opening Stock Correction')


SELECT * FROm MTL_TRANSACTION_TYPES where TRANSACTION_TYPE_NAME LIKE '%Opening%'


--V3 Customer wise challan and receive transactions with item 
SELECT CUSTOMER_NAME ,XXGET_ITEM_DESCRIPTION(INVENTORY_ITEM_ID,ORGANIZATION_ID) INVENTORY_ITEM,  SUM(CHALLAN_QTY) CHALLAN_QTY, SUM(RECEIPT_QTY) RECEIVED_QTY, nvl(SUM(CHALLAN_QTY),0) - nvl(SUM(RECEIPT_QTY),0) BALANCE  
FROM XX_CHALLAN_MO_TEMP WHERE CHALLAN_DATE  between '31-AUG-2018' and '05-JAN-2023' GROUP BY CUSTOMER_NAME,INVENTORY_ITEM_ID,ORGANIZATION_ID

--V2 Customer wise challan and receive transactions
SELECT CUSTOMER_NAME , SUM(CHALLAN_QTY) CHALLAN_QTY, SUM(RECEIPT_QTY) RECEIVED_QTY, SUM(CHALLAN_QTY) - SUM(RECEIPT_QTY) BALANCE  
FROM XX_CHALLAN_MO_TEMP WHERE CHALLAN_DATE  between '31-AUG-2018' and '05-JAN-2023' GROUP BY CUSTOMER_NAME


--V1
SELECT SUM(CHALLAN_QTY) CHALLAN_QTY, SUM(RECEIPT_QTY) RECEIVED_QTY, SUM(CHALLAN_QTY) - SUM(RECEIPT_QTY) BALANCE  FROM XX_CHALLAN_MO_TEMP WHERE CHALLAN_DATE  between '31-AUG-2018' and '05-JAN-2023'




SELECT SUM(CHALLAN_QTY) CHALLAN_QTY, SUM(RECEIPT_QTY) FROM XX_CHALLAN_MO_TEMP

1353742    1341918
1357438    1343822



-- AL FG CYLINDER  CHALLAN STATUS
--======================
SELECT  DISTINCT 
ROWNUM SL_NO,
WDD.ORG_ID,  
(SELECT DISTINCT OPERATING_UNIT  FROM XX_OPERATING_UNITS_V  WHERE ORGANIZATION_ID=WDD.ORG_ID )ORG_NAME,
XX_INV_PKG.XXGET_ORG_LOCATION (WDD.ORG_ID) ORG_ADDRESS, 
WDD.ORGANIZATION_ID SHIP_FROM_ORG_ID,
B.ORGANIZATION_NAME, 
WDD.CUSTOMER_ID,
(SELECT DISTINCT CUSTOMER_NAME FROM XX_AR_CUSTOMER_SITE_V WHERE CUSTOMER_ID = WDD.CUSTOMER_ID)  CUSTOMER_NAME,
OH.INVOICE_TO_ORG_ID,
(SELECT DISTINCT ADDRESS FROM XX_ONT_PARTY_LOCATION_V
 WHERE SHIP_TO_ORG_ID=OH.INVOICE_TO_ORG_ID) BILL_TO_ADDRESS,
NVL(WDD.ATTRIBUTE15,NVL(OH.SHIPPING_INSTRUCTIONS,(SELECT DISTINCT ADDRESS FROM XX_ONT_PARTY_LOCATION_V WHERE SHIP_TO_ORG_ID=OH.SHIP_TO_ORG_ID))) SHIP_TO_ADDRESS,
OH.SALESREP_ID,
(SELECT DISTINCT SALESREP_NAME FROM XX_SALESREP_ROLE_TERRITORY_V1 WHERE SALESREP_ID=OH.SALESREP_ID AND ORG_ID = OH.ORG_ID) SALES_PERSON_NAME,
(SELECT DISTINCT SOURCE_PHONE FROM XX_SALESREP_ROLE_TERRITORY_V1 WHERE SALESREP_ID=OH.SALESREP_ID AND ORG_ID = OH.ORG_ID) SALES_PERSON_PHONE_NO,
OH.CUST_PO_NUMBER PO_NUMBER,
D.NAME CHALLAN_NO,
TO_CHAR(D.CONFIRM_DATE, 'dd-Mon-yyyy HH:MI:SS AM') CHALLAN_DATE, 
OH.ORDER_NUMBER SO_NUMBER,
TO_CHAR(OH.ORDERED_DATE, 'dd-Mon-yyyy HH:MI:SS AM') SO_DATE,
WDD.TRACKING_NUMBER OD_NUMBER,
TRUNC(TO_DATE(TO_DATE(WDD.ATTRIBUTE14,'YYYY-MM-DD HH24:MI:SS'))) OD_DATE,
--F.TRIPSYS_NO TRIP_NUMBER,
TO_CHAR(F.TRIP_DATE, 'dd-Mon-yyyy HH:MI:SS AM') TRIP_DATE,
WDD.INVENTORY_ITEM_ID,
OL.ORDERED_ITEM,
(SELECT DISTINCT DESCRIPTION FROM MTL_SYSTEM_ITEMS_B WHERE INVENTORY_ITEM_ID = OL.INVENTORY_ITEM_ID AND  ORGANIZATION_ID = WDD.ORGANIZATION_ID) ITEM_DESCRIPTION,
/*
-----========================================================================================================
(SELECT SUM( B.ATTRIBUTE2) NO_OF_BUNDLE
FROM MTL_MATERIAL_TRANSACTIONS A,MTL_TRANSACTION_LOT_NUMBERS B,WSH_DELIVERY_DETAILS WSH
WHERE TRANSACTION_TYPE_ID=33
AND A.TRANSACTION_ID=B.TRANSACTION_ID
AND A.TRX_SOURCE_LINE_ID=WSH.SOURCE_LINE_ID
AND A.INVENTORY_ITEM_ID=WSH.INVENTORY_ITEM_ID
AND WSH.ORGANIZATION_ID=A.ORGANIZATION_ID
AND A.TRX_SOURCE_DELIVERY_ID=D.NAME
AND A.INVENTORY_ITEM_ID=A.INVENTORY_ITEM_ID) BUNDLE,
*/
LOT.ATTRIBUTE2 BUNDLE,
----=================
WDD.SHIPPED_QUANTITY QTY,
WDD.REQUESTED_QUANTITY_UOM UOM,
''PCS,
''QTY_IN_WORDS,
F.REG_NO TRANSPORT_NUMBER,
DECODE(F.EMPLOYEE_ID,NULL,UNLISTED_DRIVER,(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = F.EMPLOYEE_ID)) DRIVER_NAME,
F.DRIVER_CONTACT DRIVER_PHONE_NO,
--A.TRANSPORT_TYPE TRANSPORT_COMPANY,
OH.FREIGHT_TERMS_CODE DELIVERY_MODE,
(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS WHERE VENDOR_ID = F.SUPPLIER_ID ) TRANSPORT_COMPANY,
D.ATTRIBUTE8 PREPARED_BY, 
D.ATTRIBUTE10 RECIEVED_BY,
D.ATTRIBUTE11 GATE_SIGN_BY,
--(SELECT DISTINCT FULL_NAME FROM WBI_HR_EMPLOYEE_DETAILS_D WHERE PERSON_ID = D.ATTRIBUTE1) LOADED_BY,
D.ATTRIBUTE1 LOADED_BY,
NVL(WDD.ATTRIBUTE11,DFF.CONTACT_PERSON_NAME) CONTACT_PERSON_NAME,
NVL(WDD.ATTRIBUTE12,DFF.CONTACT_PERSON_NUMBER) CONTACT_PERSON_NO,
WDD.ATTRIBUTE13 REMARKS,
E.ATTRIBUTE_CATEGORY MO_ATTRIBUTE_CATEGORY,
E.ATTRIBUTE1 MO_PRODUCT_TYPE,
E.ATTRIBUTE1 MO_PRODUCT_GRADE,
LOT.ATTRIBUTE6 STANDARD_PCS, 
LOT.ATTRIBUTE3 ADDITIONAL_PCS,
LOT.ATTRIBUTE2 BUNDLE_NUMBER,
WDD.MOVE_ORDER_LINE_ID,
XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
FROM  
OE_ORDER_HEADERS_ALL OH
LEFT JOIN
OE_ORDER_LINES_ALL OL
ON OH.HEADER_ID = OL.HEADER_ID 
LEFT JOIN WSH_DELIVERY_DETAILS WDD
ON OL.HEADER_ID = WDD.SOURCE_HEADER_ID
AND OL.LINE_ID = WDD.SOURCE_LINE_ID
LEFT JOIN WSH_DELIVERY_ASSIGNMENTS WDA
ON WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
LEFT JOIN WSH_NEW_DELIVERIES D
ON WDA.DELIVERY_ID=D.DELIVERY_ID
LEFT JOIN MTL_MATERIAL_TRANSACTIONS E
ON  WDD.MOVE_ORDER_LINE_ID = E.MOVE_ORDER_LINE_ID
AND E.SUBINVENTORY_CODE = 'STAGIN'
AND E.ATTRIBUTE_CATEGORY = 'DISTRIBUTION'
LEFT JOIN XX_ONT_TRIP_MT F  
ON D.ATTRIBUTE4 = F.TRIPSYS_NO
LEFT JOIN WBI_INV_ORG_D B
ON WDD.ORGANIZATION_ID = B.ORGANIZATION_ID
AND OH.SOLD_FROM_ORG_ID = B.OPERATING_UNIT
LEFT JOIN MTL_TRANSACTION_LOT_NUMBERS LOT
ON WDD.LOT_NUMBER = LOT.LOT_NUMBER
AND WDD.TRANSACTION_ID = LOT.TRANSACTION_ID
AND UPPER(LOT.ATTRIBUTE_CATEGORY) = 'DISTRIBUTION KSPL'
LEFT JOIN
XX_ONT_ORDER_HEADER_DFF_V DFF
ON OH.HEADER_ID = DFF.HEADER_ID
LEFT JOIN
XX_ONT_CASH_CUST_V CASH
ON OH.SOLD_TO_ORG_ID = CASH.CUSTOMER_ID
AND OH.ORG_ID = CASH.ORG_ID
WHERE 
WDD.RELEASED_STATUS = 'C'
--AND D.NAME=:P_CHALLAN_NO
--AND OH.ORDER_NUMBER ='2190000000394'
AND WDD.INVENTORY_ITEM_ID IN(
76,
102,
66,
118,
774910,
75,
787867,
77
) --- ALL FG Cylinder
AND (SELECT DISTINCT CUSTOMER_NAME FROM XX_AR_CUSTOMER_SITE_V WHERE CUSTOMER_ID = WDD.CUSTOMER_ID)  = 'SK Enterprise' 
AND TO_CHAR(D.CONFIRM_DATE, 'dd-Mon-yyyy HH:MI:SS AM')  BETWEEN 
ORDER BY ROWNUM

SK Enterprise.xlsx


-- AL EMPTY CYLINDER  RECIEVE STATUS
--==========================

SELECT*  FROM WBI_XXKBGITEM_MT_D

SELECT (SELECT TRANSACTION_TYPE_NAME from  MTL_TRANSACTION_TYPES WHERE  TRANSACTION_TYPE_ID=a.TRANSACTION_TYPE_ID) Transaction_Type,a.TRANSACTION_TYPE_ID,
A.INVENTORY_ITEM_ID, 
(SELECT DISTINCT ITEM_DESC  FROM WBI_XXKBGITEM_MT_D D where A.INVENTORY_ITEM_ID = D.INVENTORY_ITEM_ID) ITEM_DESC,
 a.*
 FROM MTL_MATERIAL_TRANSACTIONS a  WHERE INVENTORY_ITEM_ID=428 and ATTRIBUTE3 is  null  and transaction_date between '01-DEC-2022' and '31-DEC-2022'


--=======================================
--ALL EMPTY CYLINDER RECIVING WITH CHALLAN NUMBER, Attribute3= challan number
--=======================================
SELECT (SELECT TRANSACTION_TYPE_NAME from  MTL_TRANSACTION_TYPES WHERE  TRANSACTION_TYPE_ID=a.TRANSACTION_TYPE_ID) Transaction_Type,a.TRANSACTION_TYPE_ID, 
A.INVENTORY_ITEM_ID, 
(SELECT DISTINCT ITEM_DESC  FROM WBI_XXKBGITEM_MT_D D where A.INVENTORY_ITEM_ID = D.INVENTORY_ITEM_ID) ITEM_DESC,
a.*
 FROM MTL_MATERIAL_TRANSACTIONS a  WHERE INVENTORY_ITEM_ID IN(66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867,
                  787861)
  and ATTRIBUTE3 is not  null  --and transaction_date between '01-DEC-2022' and '31-DEC-2022'
  AND  (SELECT TRANSACTION_TYPE_NAME from  MTL_TRANSACTION_TYPES WHERE  TRANSACTION_TYPE_ID=a.TRANSACTION_TYPE_ID)  = 'Empty Cylinder Receive'
  order by ATTRIBUTE3







--V1
SELECT (SELECT TRANSACTION_TYPE_NAME from  MTL_TRANSACTION_TYPES WHERE  TRANSACTION_TYPE_ID=a.TRANSACTION_TYPE_ID) Transaction_Type,a.TRANSACTION_TYPE_ID, 
A.INVENTORY_ITEM_ID, 
(SELECT DISTINCT ITEM_DESC  FROM WBI_XXKBGITEM_MT_D D where A.INVENTORY_ITEM_ID = D.INVENTORY_ITEM_ID) ITEM_DESC,
a.*
 FROM MTL_MATERIAL_TRANSACTIONS a  WHERE INVENTORY_ITEM_ID IN(66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867,
                  787861)
  and ATTRIBUTE3 is   null  --and transaction_date between '01-DEC-2022' and '31-DEC-2022'
  AND  (SELECT TRANSACTION_TYPE_NAME from  MTL_TRANSACTION_TYPES WHERE  TRANSACTION_TYPE_ID=a.TRANSACTION_TYPE_ID)  = 'Empty Cylinder Receive'


-- XXKSRM Cylinder Stock All

SELECT DISTINCT
WXMD.ORGANIZATION_NAME,WXMD.INVENTORY_ITEM_ID,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MOQ.ORGANIZATION_ID) ORG_ADD,
WXMD.ORGANIZATION_code,
MOQ.ORGANIZATION_ID,
MOQ.SUBINVENTORY_CODE,
WXMD.ITEM_CODE,
WXMD.ITEM_DESC,
WXMD.UOM1 UOM,
NVL (XX_INV_PKG.XXGET_INV_OPENING_STOCK (MOQ.INVENTORY_ITEM_ID, MOQ.ORGANIZATION_ID, MOQ.SUBINVENTORY_CODE, MOQ.LOCATOR_ID, :P_DATE),0) OPENING_QTY ,
--NVL (XX_INV_PKG.XXGET_INV_OPENING_STOCK (MOQ.INVENTORY_ITEM_ID,MOQ.ORGANIZATION_ID,NULL, NULL, :P_DATE),0) GLOBAL_STOCK,
---NULL GLOBAL_STOCK,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
:P_DATE PDATE
FROM WBI_XXKBGITEM_MT_D WXMD,
MTL_ONHAND_QUANTITIES MOQ
WHERE     WXMD.INVENTORY_ITEM_ID = MOQ.INVENTORY_ITEM_ID
AND TRUNC(MOQ.DATE_RECEIVED) <=:P_DATE
--AND WXMD.ATTRIBUTE13='KOM_CYLINDER'
AND WXMD.ORGANIZATION_ID = MOQ.ORGANIZATION_ID     
AND WXMD.ORGANIZATION_ID=173
--AND ITEM_CODE LIKE '%CYL%'
AND    WXMD.INVENTORY_ITEM_ID IN  (66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867,
                  787861 )  
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE)

UNION 

SELECT 
DISTINCT 
(SELECT INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL  WHERE INV_ORGANIZATION_ID=KCV.ORGANIZATION_ID) ORGANIZATION_NAME,
KCV.INVENTORY_ITEM_ID,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=KCV.ORGANIZATION_ID) ORG_ADD,
(SELECT INV_ORGANIZATION_CODE FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=KCV.ORGANIZATION_ID) ORGANIZATION_CODE,
KCV.ORGANIZATION_ID  ORGANIZATION_ID,
'PARTY'  SUBINVENTORY_CODE,
KCV.ITEMCODE ITEM_CODE,
KCV.ITEM_DESCRIPTION ITEM_DESC,
KCV.UOM_CODE UOM,
XX_TAB.PARTY_BALANCE OPENING_QTY ,
----NULL GLOBAL_STOCK,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
:P_DATE PDATE
FROM XXKSRM_KOL_CHALLAN_V KCV,
 (SELECT ORGANIZATION_ID,ITEMCODE,
            SUM(PARTY_BALANCE)  PARTY_BALANCE
            FROM XXKSRM_KOL_CHALLAN_V
            WHERE TO_DATE(CHALLAN_DATE)<=(:P_DATE) AND PARTY_BALANCE>0
            GROUP BY ORGANIZATION_ID,ITEMCODE) 
            XX_TAB
WHERE KCV.ORGANIZATION_ID=XX_TAB.ORGANIZATION_ID
AND KCV.ITEMCODE=XX_TAB.ITEMCODE
AND  KCV.ITEMCODE=NVL(:P_ITEM_CODE,KCV.ITEMCODE)


SELECT * FROM XXKSRM_KOL_CHALLAN_V

SELECT 
--(SELECT distinct CUSTOMER_NAME FROM XX_AR_CUSTOMER_SITE_V where CUSTOMER_ID=a.CUSTOMER_ID GROUP BY CUSTOMER_ID  )cust_name,
SUM(CHALLAN_QTY), SUM(RECEIPT_QTY),SUM(QUANTITY_DETAILED),SUM(PARTY_BALANCE) FROM XXKSRM_KOL_CHALLAN_V a --where INVENTORY_ITEM_ID = 75

GROUP BY (SELECT distinct CUSTOMER_NAME FROM XX_AR_CUSTOMER_SITE_V where CUSTOMER_ID=a.CUSTOMER_ID)

select  CUSTOMER_ID , 
(SELECT distinct CUSTOMER_NAME FROM XX_AR_CUSTOMER_SITE_V where CUSTOMER_ID=a.CUSTOMER_ID )cust_name
 from XXKSRM_KOL_CHALLAN_V a


SELECT  FROM MTL_MATERIAL_TRANSACTIONS WHERE INVENTORY_ITEM_ID IN(76,
102,
66,
118,
774910,
75,
787867,
77)


SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE INVENTORY_ITEM_ID IN(76,
102,
66,
118,
774910,
75,
787867,
77)

SELECT * FROM 

 select * from WBI_XXKBGITEM_MT_D  where  INVENTORY_ITEM_ID =428 --ITEM_DESC like'%Cylinder%'

 select DISTINCT INVENTORY_ITEM_ID, ITEM_CODE,ITEM_DESC from WBI_XXKBGITEM_MT_D  where  INVENTORY_ITEM_ID IN
  (66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867)

--===========================
--GET DUPLOCATE DATA FROM THIS QUERY
--===========================


SELECT CHALLAN_NO, COUNT(CHALLAN_NO)
FROM XX_CHALLAN_MO_TEMP
GROUP BY CHALLAN_NO
HAVING COUNT(CHALLAN_NO) > 1
ORDER BY CHALLAN_NO  

--=======================================
-- DELIVERY CHALLAN COMPLETE BUT NOT RECEIVED
--======================================
 

 SELECT distinct CUSTOMER_ID, CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP where CHALLAN_NO= '4211020057261' --CUSTOMER_NAME = 'IQBAL HASAN ENTERPRISE'
 
  SELECT * FROM XX_CHALLAN_MO_TEMP where CUSTOMER_ID = 20958 and RECEIPT_QTY is null
 
 SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP where CUSTOMER_ID = 20958 and RECEIPT_QTY is null  AND  TO_DATE(CHALLAN_DATE)<=(:P_DATE)
 
 SELECT * FROM XXKSRM_KOL_CHLN_RCV_PENDING where ID = 20958 and BAL>0
 AND  TO_DATE(CHALLAN_DATE)<=(:P_DATE)
               
 SELECT ID,
 -- CHALLAN_DATE,
 (SELECT DISTINCT  CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP where CUSTOMER_ID=XXKSRM_KOL_CHLN_RCV_PENDING.ID),
   SUM(BAL) FROM XXKSRM_KOL_CHLN_RCV_PENDING 
 where 1=1
-- and ID = 19142
AND (SELECT DISTINCT  CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP where CUSTOMER_ID=XXKSRM_KOL_CHLN_RCV_PENDING.ID) is not null
  and BAL>0
 -- AND TRUNC(CHALLAN_DATE)  BETWEEN '01-AUG-2018' and '31-DEC-2022'
  -- AND CHALLAN_DATE <= '31-DEC-2021'
 --  AND  TO_DATE(CHALLAN_DATE)<=(:P_DATE)
  AND ID = 20958
 GROUP BY ID --,CHALLAN_DATE






-- 4. XXKSRM Customer Wise Empty Cylinder Recieve Details V1
--========================================

select 
 ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=ORGANIZATION_ID) COMPANY_NAME,
MMT.ATTRIBUTE_CATEGORY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
 XXGET_ITEM_SC(INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 ) CUSTOMER_NAME ,
MMT.ATTRIBUTE3 CHALLAN_NO,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3),0) CHALLAN_QTY ,
(SELECT NVL(SUM(WDD.SHIPPED_QUANTITY),0)
       FROM WSH_DELIVERY_DETAILS WDD,
            WSH_DELIVERY_ASSIGNMENTS WDA,
            WSH_NEW_DELIVERIES WND
      WHERE     WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
            AND WDA.DELIVERY_ID = WND.DELIVERY_ID
            AND STATUS_CODE = 'CL'
            and WND.NAME=MMT.ATTRIBUTE3 -- '4211020063799'
            ) OE_CHALLAN_QTY,
SUM(NVL(TRANSACTION_QUANTITY,0))TRANSACTION_QUANTITY , MAX(TRUNC(TO_DATE(TRANSACTION_DATE))) EMPT_CYLINDER_RCV_DATE,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3) - SUM(TRANSACTION_QUANTITY),0)  Pending_Quantity,
 ORGANIZATION_ID,GET_ORG_CODE_FROM_ID(ORGANIZATION_ID) INV_ORG_CODE,GET_ORG_NAME_FROM_ID(ORGANIZATION_ID) INV_ORG_NAME,
  MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.ATTRIBUTE10 CUSTOMER_ID ,
  :P_RECEIVE_DATE_FROM P_DATE_FROM,:P_RECEIVE_DATE_TO
from MTL_MATERIAL_TRANSACTIONS MMT, MTL_TRANSACTION_TYPES MTT
where MMT.TRANSACTION_TYPE_ID= MTT.TRANSACTION_TYPE_ID
--and TRUNC(MMT.CREATION_DATE) BETWEEN '9-JUN-2021' AND '9-JUN-2021' 
and MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive'
 AND ORGANIZATION_ID='173'       ----> 
AND MMT.ATTRIBUTE3 =NVL(:P_CHALLAN_NO,MMT.ATTRIBUTE3) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
--AND MMT.ATTRIBUTE10 = NVL(:P_CUSTOMER,MMT.ATTRIBUTE10)  
AND    (SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10)  = NVL(:P_CUSTOMER, (SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10))
--AND MMT.ATTRIBUTE3 IN ('4211020063799')
AND TRUNC(TO_DATE(TRANSACTION_DATE)) BETWEEN NVL(:P_RECEIVE_DATE_FROM,TRUNC(TO_DATE(TRANSACTION_DATE)))  AND NVL(:P_RECEIVE_DATE_TO,TRUNC(TO_DATE(TRANSACTION_DATE)))
GROUP BY ORGANIZATION_ID,MMT.ATTRIBUTE_CATEGORY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,MMT.ATTRIBUTE3 ,MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.ATTRIBUTE10
ORDER BY MMT.ATTRIBUTE3



--XXKSRM Customer Wise Empty Cylinder Recieve SUMMARY V1
--========================================

SELECT CUSTOMER_NAME , SUM(OPENING_BALANCE),  SUM(TRANSACTION_QUANTITY) RECEIVE_QTY, SUM(CHALLAN_QTY) ISSUE_QTY, SUM(CLOSING_QUANTING) CLOSING_BALANCE
FROM
(
SELECT 
(SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP where CUSTOMER_ID = MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3  AND  TO_DATE(CHALLAN_DATE)<=(:P_RECEIVE_DATE_TO)) OPENING_BALANCE,
(SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP where CUSTOMER_ID = MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3  AND  TO_DATE(CHALLAN_DATE)<=(:P_RECEIVE_DATE_TO)) + --OPENING_BALANCE
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3),0) - --CHALLAN_QTY
SUM(NVL(TRANSACTION_QUANTITY,0)) CLOSING_QUANTING ,--TRANSACTION_QUANTITY
 ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=ORGANIZATION_ID) COMPANY_NAME,
MMT.ATTRIBUTE_CATEGORY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
 XXGET_ITEM_SC(INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 ) CUSTOMER_NAME ,
MMT.ATTRIBUTE3 CHALLAN_NO,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3),0) CHALLAN_QTY ,
(SELECT NVL(SUM(WDD.SHIPPED_QUANTITY),0)
       FROM WSH_DELIVERY_DETAILS WDD,
            WSH_DELIVERY_ASSIGNMENTS WDA,
            WSH_NEW_DELIVERIES WND
      WHERE     WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
            AND WDA.DELIVERY_ID = WND.DELIVERY_ID
            AND STATUS_CODE = 'CL'
            and WND.NAME=MMT.ATTRIBUTE3 -- '4211020063799'
            ) OE_CHALLAN_QTY,
SUM(NVL(TRANSACTION_QUANTITY,0))TRANSACTION_QUANTITY , MAX(TRUNC(TO_DATE(TRANSACTION_DATE))) EMPT_CYLINDER_RCV_DATE,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3) - SUM(TRANSACTION_QUANTITY),0)  Pending_Quantity,
 ORGANIZATION_ID,GET_ORG_CODE_FROM_ID(ORGANIZATION_ID) INV_ORG_CODE,GET_ORG_NAME_FROM_ID(ORGANIZATION_ID) INV_ORG_NAME,
  MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.ATTRIBUTE10 CUSTOMER_ID ,
  :P_RECEIVE_DATE_FROM P_DATE_FROM,:P_RECEIVE_DATE_TO
from MTL_MATERIAL_TRANSACTIONS MMT, MTL_TRANSACTION_TYPES MTT
where MMT.TRANSACTION_TYPE_ID= MTT.TRANSACTION_TYPE_ID
--and TRUNC(MMT.CREATION_DATE) BETWEEN '9-JUN-2021' AND '9-JUN-2021' 
and MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive'
 AND ORGANIZATION_ID='173'       ----> 
AND MMT.ATTRIBUTE3 =NVL(:P_CHALLAN_NO,MMT.ATTRIBUTE3) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)  
--AND MMT.ATTRIBUTE10 = NVL(:P_CUSTOMER,MMT.ATTRIBUTE10)  
AND    (SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10)  = NVL(:P_CUSTOMER, (SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10))
--AND MMT.ATTRIBUTE3 IN ('4211020063799')
AND TRUNC(TO_DATE(TRANSACTION_DATE)) BETWEEN NVL(:P_RECEIVE_DATE_FROM,TRUNC(TO_DATE(TRANSACTION_DATE)))  AND NVL(:P_RECEIVE_DATE_TO,TRUNC(TO_DATE(TRANSACTION_DATE)))
GROUP BY ORGANIZATION_ID,MMT.ATTRIBUTE_CATEGORY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,MMT.ATTRIBUTE3 ,MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.ATTRIBUTE10
ORDER BY MMT.ATTRIBUTE3
)
WHERE 1= 1
GROUP BY CUSTOMER_NAME


-- 3. XXKSRM Customer Wise Empty Cylinder Recieve Details
--========================================

select 
 ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=ORGANIZATION_ID) COMPANY_NAME,
TRANSACTION_ID,
MMT.ATTRIBUTE_CATEGORY,MMT.CREATION_DATE,XX_GET_EMP_NAME_FROM_USER_ID (MMT.CREATED_BY) CREATED_BY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
 XXGET_ITEM_SC(INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 ) CUSTOMER_NAME ,
MMT.ATTRIBUTE3 CHALLAN_NO,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3),0) CHALLAN_QTY ,
NVL(TRANSACTION_QUANTITY,0) TRANSACTION_QUANTITY ,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3) - TRANSACTION_QUANTITY,0)  Pending_Quantity,
 ORGANIZATION_ID,GET_ORG_CODE_FROM_ID(ORGANIZATION_ID) INV_ORG_CODE,GET_ORG_NAME_FROM_ID(ORGANIZATION_ID) INV_ORG_NAME,
  MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.TRANSACTION_DATE,MMT.ATTRIBUTE10 CUSTOMER_ID ,
  :P_RECEIVE_DATE_FROM P_DATE_FROM,:P_RECEIVE_DATE_TO
from MTL_MATERIAL_TRANSACTIONS MMT, MTL_TRANSACTION_TYPES MTT
where MMT.TRANSACTION_TYPE_ID= MTT.TRANSACTION_TYPE_ID
--and TRUNC(MMT.CREATION_DATE) BETWEEN '9-JUN-2021' AND '9-JUN-2021' 
and MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive'
 AND ORGANIZATION_ID='173'       ----> 
AND MMT.ATTRIBUTE3 =NVL(:P_CHALLAN_NO,MMT.ATTRIBUTE3) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
AND MMT.ATTRIBUTE10 = NVL(:P_CUSTOMER,MMT.ATTRIBUTE10)  
AND MMT.ATTRIBUTE3 IN ('4211020063799')
--'4181010011294'
--,'4211020025303'
--,'4181010006431'
--,'4181010001426'
--,'4181010007563'
--,'6.11585418101002E18'
--,'4181010003627'
--)
 --and TRUNC(CHALLAN_DATE)  BETWEEN '01-SEP-2018' and   '31-AUG-2021'
 -- AND (SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 ) ='KBIL Manufacturing Unit' 
AND TRUNC(TO_DATE(TRANSACTION_DATE)) BETWEEN NVL(:P_RECEIVE_DATE_FROM,TRUNC(TO_DATE(TRANSACTION_DATE)))  AND NVL(:P_RECEIVE_DATE_TO,TRUNC(TO_DATE(TRANSACTION_DATE)))
ORDER BY MMT.ATTRIBUTE3


--===============================================================================================================================





--==================================
--EMPTY CYLINDER SUMMARY REPORT  HOBE  ETA
--================================
SELECT TMP.CUSTOMER_NAME,TMP.CHALLAN_NO,TMP.CHALLAN_QTY,TMP.RECEIPT_QTY, TMP.CHALLAN_QTY - TMP.RECEIPT_QTY PENDING_QTY ,TMP.CREATED_BY,MMT.TRANSACTION_DATE,MMT.ATTRIBUTE_CATEGORY,MMT.ORGANIZATION_ID
 from MTL_MATERIAL_TRANSACTIONS MMT ,  XX_CHALLAN_MO_TEMP  TMP
WHERE  TO_CHAR(MMT.ATTRIBUTE3)= TO_CHAR(TMP.CHALLAN_NO)
AND  MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' 
--and ATTRIBUTE3= '4211020064899'
 AND MMT.ORGANIZATION_ID='173' 
 AND TRUNC(MMT.TRANSACTION_DATE) BETWEEN '01-SEP-2018' and '31-DEC-2021' 




--========================================
--XXKSRM Customer Wise Empty Cylinder Recieve Details
--========================================
select 
 ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=ORGANIZATION_ID) COMPANY_NAME,
TRANSACTION_ID,
MMT.ATTRIBUTE_CATEGORY,MMT.CREATION_DATE,XX_GET_EMP_NAME_FROM_USER_ID (MMT.CREATED_BY) CREATED_BY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
MY_PACKAGE.XXGET_ITEM_DESCRIPTION(INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 ) CUSTOMER_NAME ,
MMT.ATTRIBUTE3 CHALLAN_NO,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3),0) CHALLAN_QTY ,
NVL(TRANSACTION_QUANTITY,0) TRANSACTION_QUANTITY ,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3) - TRANSACTION_QUANTITY,0)  Pending_Quantity,
 ORGANIZATION_ID,GET_ORG_CODE_FROM_ID(ORGANIZATION_ID) INV_ORG_CODE,GET_ORG_NAME_FROM_ID(ORGANIZATION_ID) INV_ORG_NAME,
  MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.TRANSACTION_DATE,MMT.ATTRIBUTE10 CUSTOMER_ID ,
  :P_RECEIVE_DATE_FROM P_DATE_FROM,:P_RECEIVE_DATE_TO
from MTL_MATERIAL_TRANSACTIONS MMT, MTL_TRANSACTION_TYPES MTT
where MMT.TRANSACTION_TYPE_ID= MTT.TRANSACTION_TYPE_ID
--and TRUNC(MMT.CREATION_DATE) BETWEEN '9-JUN-2021' AND '9-JUN-2021' 
and MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive'
 AND ORGANIZATION_ID='173'        ----
AND MMT.ATTRIBUTE3 =NVL(:P_CHALLAN_NO,MMT.ATTRIBUTE3) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
AND MMT.ATTRIBUTE10 = NVL(:P_CUSTOMER,MMT.ATTRIBUTE10)  
AND TRUNC(TO_DATE(TRANSACTION_DATE)) BETWEEN NVL(:P_RECEIVE_DATE_FROM,TRUNC(TO_DATE(TRANSACTION_DATE)))  AND NVL(:P_RECEIVE_DATE_TO,TRUNC(TO_DATE(TRANSACTION_DATE)))
ORDER BY MMT.ATTRIBUTE3




--=============================================
--XXKSRM Customer Wise Empty Cylinder Recieve SUMMARY
--==============================================

select * from WSH_NEW_DELIVERIES where NAME = '4211020063799' and ORGANIZATION_ID= 173     --order by name 

SELECT * FROM WSH_DELIVERY_DETAILS WHERE DELIVERY_DETAIL_ID =1114445

SELECT COMPANY_NAME,INVENTORY_ITEM_ID,ITEM_CODE,CUSTOMER_NAME,SUM(CHALLAN_QTY) CHALLAN_QTY ,SUM(OE_CHALLAN_QTY) OE_CHALLAN_QTY,SUM(TRANSACTION_QUANTITY) RECEIVE_QTY, 
SUM(Pending_Quantity) PENDING_QTY
FROM 
(
select 
 ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=ORGANIZATION_ID) COMPANY_NAME,
TRANSACTION_ID,
MMT.ATTRIBUTE_CATEGORY,MMT.CREATION_DATE,XX_GET_EMP_NAME_FROM_USER_ID (MMT.CREATED_BY) CREATED_BY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
--MY_PACKAGE.XXGET_ITEM_DESCRIPTION(INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 ) CUSTOMER_NAME ,
MMT.ATTRIBUTE3 CHALLAN_NO,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3),0) CHALLAN_QTY ,
(SELECT NVL(SUM(WDD.SHIPPED_QUANTITY),0)
       FROM WSH_DELIVERY_DETAILS WDD,
            WSH_DELIVERY_ASSIGNMENTS WDA,
            WSH_NEW_DELIVERIES WND
      WHERE     WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
            AND WDA.DELIVERY_ID = WND.DELIVERY_ID
            AND STATUS_CODE = 'CL'
            and WND.NAME=MMT.ATTRIBUTE3 -- '4211020063799'
            ) OE_CHALLAN_QTY,
NVL(TRANSACTION_QUANTITY,0) TRANSACTION_QUANTITY ,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3) - TRANSACTION_QUANTITY,0)  Pending_Quantity,
 ORGANIZATION_ID,GET_ORG_CODE_FROM_ID(ORGANIZATION_ID) INV_ORG_CODE,GET_ORG_NAME_FROM_ID(ORGANIZATION_ID) INV_ORG_NAME,
  MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.TRANSACTION_DATE,MMT.ATTRIBUTE10 CUSTOMER_ID ,
  :P_RECEIVE_DATE_FROM P_DATE_FROM,:P_RECEIVE_DATE_TO
from MTL_MATERIAL_TRANSACTIONS MMT, MTL_TRANSACTION_TYPES MTT
where MMT.TRANSACTION_TYPE_ID= MTT.TRANSACTION_TYPE_ID
--and TRUNC(MMT.CREATION_DATE) BETWEEN '9-JUN-2021' AND '9-JUN-2021' 
and MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive'
 AND ORGANIZATION_ID='173'        ----
AND MMT.ATTRIBUTE3 =NVL(:P_CHALLAN_NO,MMT.ATTRIBUTE3) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
AND MMT.ATTRIBUTE10 = NVL(:P_CUSTOMER,MMT.ATTRIBUTE10)  
AND TRUNC(TO_DATE(TRANSACTION_DATE)) BETWEEN NVL(:P_RECEIVE_DATE_FROM,TRUNC(TO_DATE(TRANSACTION_DATE)))  AND NVL(:P_RECEIVE_DATE_TO,TRUNC(TO_DATE(TRANSACTION_DATE)))
ORDER BY MMT.ATTRIBUTE3
)
WHERE 1=1
GROUP BY 
COMPANY_NAME,INVENTORY_ITEM_ID,ITEM_CODE,CUSTOMER_NAME


--===========================TO UPDATE Data more than Challan =============================

-- TWO TABLE NEED TO UPDATE  MTL_ONHAND_QUANTITIES AND  MTL_MATERIAL_TRANSACTIONS 



SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE ATTRIBUTE3= '4201010037618'  

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID = 12027918  
     
SELECT * FROM MTL_ONHAND_QUANTITIES WHERE  TRUNC(CREATION_DATE) BETWEEN '01-SEP-2018' AND '31-DEC-2020'    AND ORGANIZATION_ID = 173  






select * from MTL_ONHAND_QUANTITIES,  MTL_MATERIAL_TRANSACTIONS WHERE  CREATE_TRANSACTION_ID = 12027918  --- 12027918 UAT

MTL_ONHAND_QUANTITIES.CREATE_TRANSACTION_ID = MTL_MATERIAL_TRANSACTIONS.TRANSACTION_ID  

--=======================================================





SELECT DISTINCT(CUSTOMER_ID) CUSTOMER_ID ,  CUSTOMER_NAME FROM XX_AR_CUSTOMER_SITE_V WHERE ORG_ID=106 and CUSTOMER_ID=19142

SELECT * FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_NAME='IQBAL HASAN ENTERPRISE'  AND CHALLAN_NO='4201010037618' 

SELECT ORGANIZATION_ID,CUSTOMER_NAME, CHALLAN_NO, TO_CHAR(TRUNC(CHALLAN_DATE),'DD-MON-RRRR') CHALLAN_DATE , NVL(CHALLAN_QTY,0) CHALLAN_QTY,NVL(RECEIPT_QTY,0) RECEIPT_QTY , NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) PENDING_QTY 
 FROM XX_CHALLAN_MO_TEMP
 WHERE  1=1
 and TRUNC(CHALLAN_DATE)  BETWEEN '01-SEP-2018' and '31-OCT-2021' 
 --and  CHALLAN_NO='4201010078505' 
 and NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) <> 0
 AND CUSTOMER_NAME='IQBAL HASAN ENTERPRISE' 
order by CHALLAN_NO     



--====================================
 -- RECEIPT_QTY > CHALLAN_QTY   FROM SEP-18 To Dec-20
 --====================================

SELECT ORGANIZATION_ID,CUSTOMER_NAME, CHALLAN_NO, TO_CHAR(TRUNC(CHALLAN_DATE),'DD-MON-RRRR') CHALLAN_DATE , NVL(CHALLAN_QTY,0) CHALLAN_QTY,NVL(RECEIPT_QTY,0) RECEIPT_QTY , NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) PENDING_QTY 
 FROM XX_CHALLAN_MO_TEMP
 WHERE  1= 1
 --and TRUNC(CHALLAN_DATE)  BETWEEN '01-JAN-2021' and '14-NOV-2021'
 -- and TRUNC(CHALLAN_DATE)  BETWEEN '01-SEP-2018' and '31-DEC-2020'
 --and  CHALLAN_NO='4201010037370'
 --AND CUSTOMER_NAME='IQBAL HASAN ENTERPRISE'
 AND NVL(RECEIPT_QTY,0) > NVL(CHALLAN_QTY,0)
order by CHALLAN_NO

--====================================
 -- CHALLAN_QTY > RECEIPT_QTY  FROM SEP-18 To Dec-20
 --====================================

SELECT ORGANIZATION_ID,CUSTOMER_NAME, CHALLAN_NO, TO_CHAR(TRUNC(CHALLAN_DATE),'DD-MON-RRRR') CHALLAN_DATE , NVL(CHALLAN_QTY,0) CHALLAN_QTY,NVL(RECEIPT_QTY,0) RECEIPT_QTY , NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) PENDING_QTY 
 FROM XX_CHALLAN_MO_TEMP
 WHERE  1= 1
 --and TRUNC(CHALLAN_DATE)  BETWEEN '01-JAN-2021' and '14-NOV-2021'
  and TRUNC(CHALLAN_DATE)  BETWEEN '01-SEP-2018' and '31-DEC-2020'
 --and  CHALLAN_NO='4201010037370'
 --AND CUSTOMER_NAME='IQBAL HASAN ENTERPRISE'
 AND  NVL(CHALLAN_QTY,0) > NVL(RECEIPT_QTY,0) 
order by CHALLAN_NO



--- KOL RAIHAN   

-- NEW REPORT NAME: XXKSRM Customer Wise Empty Cylinder Recieve Details      11-JUL-2021 16:00:35

select MMT.ATTRIBUTE10,MMT.TRANSACTION_ID,
 ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=ORGANIZATION_ID) COMPANY_NAME,
TRANSACTION_ID,
MMT.ATTRIBUTE_CATEGORY,MMT.CREATION_DATE,XX_GET_EMP_NAME_FROM_USER_ID (MMT.CREATED_BY) CREATED_BY,MTT.TRANSACTION_TYPE_NAME,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
MY_PACKAGE.XXGET_ITEM_DESCRIPTION(INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT DISTINCT CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 ) CUSTOMER_NAME ,
MMT.ATTRIBUTE3 CHALLAN_NO,
NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3),0) CHALLAN_QTY ,
NVL(TRANSACTION_QUANTITY,0) TRANSACTION_QUANTITY ,
NVL(primary_QUANTITY,0) primary_QUANTITY ,
--NVL((SELECT SUM(CHALLAN_QTY)  FROM XX_CHALLAN_MO_TEMP WHERE CUSTOMER_ID=MMT.ATTRIBUTE10 and TO_CHAR(CHALLAN_NO) = MMT.ATTRIBUTE3) - TRANSACTION_QUANTITY,0)  Pending_Quantity,
 ORGANIZATION_ID,GET_ORG_CODE_FROM_ID(ORGANIZATION_ID) INV_ORG_CODE,GET_ORG_NAME_FROM_ID(ORGANIZATION_ID) INV_ORG_NAME,
  MMT.TRANSACTION_TYPE_ID,TRANSACTION_UOM,MMT.TRANSACTION_DATE,MMT.ATTRIBUTE10 CUSTOMER_ID ,
  :P_RECEIVE_DATE_FROM P_DATE_FROM,:P_RECEIVE_DATE_TO
from MTL_MATERIAL_TRANSACTIONS MMT, MTL_TRANSACTION_TYPES MTT
where MMT.TRANSACTION_TYPE_ID= MTT.TRANSACTION_TYPE_ID
--and TRUNC(MMT.CREATION_DATE) BETWEEN '9-JUN-2021' AND '9-JUN-2021' 
and MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive'
 AND ORGANIZATION_ID='173'        ----
AND MMT.ATTRIBUTE3 =NVL(:P_CHALLAN_NO,MMT.ATTRIBUTE3) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
AND MMT.ATTRIBUTE10 = NVL(:P_CUSTOMER,MMT.ATTRIBUTE10)  
AND TRUNC(TO_DATE(TRANSACTION_DATE)) BETWEEN NVL(:P_RECEIVE_DATE_FROM,TRUNC(TO_DATE(TRANSACTION_DATE)))  AND NVL(:P_RECEIVE_DATE_TO,TRUNC(TO_DATE(TRANSACTION_DATE)))
ORDER BY MMT.ATTRIBUTE3  


-- NEW REPORT NAME: XXKSRM Customer Wise Empty Cylinder Recieve SUMMARY      11-JUL-2021 16:00:35
--======================================================================

SELECT ORGANIZATION_ID,CUSTOMER_NAME, CHALLAN_NO, TO_CHAR(TRUNC(CHALLAN_DATE),'DD-MON-RRRR') CHALLAN_DATE , NVL(CHALLAN_QTY,0) CHALLAN_QTY,NVL(RECEIPT_QTY,0) RECEIPT_QTY , NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) PENDING_QTY 
 FROM XX_CHALLAN_MO_TEMP
 WHERE  1=1
 and TRUNC(CHALLAN_DATE)  BETWEEN '28-OCT-2021' and   '28-NOV-2021'
 --and  CHALLAN_NO='4201010078505' 
 --and NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) <> 0
 --AND CUSTOMER_NAME='IQBAL HASAN ENTERPRISE' 
order by CHALLAN_NO 





--============================================================================================================
--WE TAKE A PLAN TO UPDATE PREVIOUS DATA ACCORDING TO ACTUAL MANUAL AND UPDATE SYSTEM DATA
--================================================== SCRIPT FOR UPDATE DATA =========================================


-- UPDATE SCRIPT FOR RCV QTY GREATER THAN CHALLAN QTY IN ONE LINE 
--======================================




-- UPDATE SCRIPT FOR PERTIAL QUANTITY RECEIPT  Against A challan 
--
--UPDATE  MTL_MATERIAL_TRANSACTIONS 
--SET TRANSACTION_QUANTITY = 0,
--PRIMARY_QUANTITY=0,
--Attribute3= NULL     -- CHALLAN NO
--WHERE TRANSACTION_ID= 707666



 -- UPDATE SCRIPT FOR SAME CHALLAN RECEIPT DOUBLE
 --====================================
 
--UPDATE  MTL_MATERIAL_TRANSACTIONS 
--SET TRANSACTION_QUANTITY = 0,
--PRIMARY_QUANTITY=0,
--Attribute3= NULL     -- CHALLAN NO
--WHERE TRANSACTION_ID= 780476








---====================================================================================

SELECT TRANSACTION_QUANTITY, MMT.TRANSACTION_DATE,MMT.ATTRIBUTE_CATEGORY,ORGANIZATION_ID from MTL_MATERIAL_TRANSACTIONS MMT 
WHERE  MMT.ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' 
 AND ORGANIZATION_ID='173' AND TRUNC(MMT.TRANSACTION_DATE) BETWEEN '26-NOV-2021' and '26-NOV-2021' 
 

select  CHALLAN_NO, CUSTOMER_NAME,CHALLAN_DATE, CHALLAN_QTY,  RECEIPT_QTY, CHALLAN_QTY - RECEIPT_QTY Pending    from XX_CHALLAN_MO_TEMP


XX_CHALLAN_MO_TEMP_PROCESS






--XXKSRM Customer Wise Cylinder Stock Summary
SELECT ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=CM.ORGANIZATION_ID) COMPANY_NAME,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=CM.ORGANIZATION_ID) IO_ADDRESS,
CUSTOMER_NAME, NVL(SUM(CHALLAN_QTY),0) CHALLAN_QTY,NVL(SUM(RECEIPT_QTY),0) RETURN_QTY,NVL(SUM(CHALLAN_QTY),0) - NVL(SUM(RECEIPT_QTY),0)  CUSTOMER_BALANCE ,  CREATED_BY,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
MY_PACKAGE.XXGET_ITEM_DESCRIPTION(CM.INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT FULL_NAME  FROM WBI_HR_EMPLOYEE_DETAILS_D WHERE FIRST_NAME =CM.CREATED_BY) FULL_NAME, -- 'KG-4079'
  XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
  XXGET_EMP_DEPT_FROM_KGID(CM.CREATED_BY) DEPARTMENT,
:P_CHALLAN_DATE_FROM,
:P_CHALLAN_DATE_TO  
FROM XX_CHALLAN_MO_TEMP CM
WHERE 1=1
AND  NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) >0
AND CHALLAN_NO=NVL(:P_CHALLAN_NO,CHALLAN_NO) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
AND CUSTOMER_ID = NVL(:P_CUSTOMER,CUSTOMER_ID)  
AND TRUNC(TO_DATE(CHALLAN_DATE)) BETWEEN NVL(:P_CHALLAN_DATE_FROM,TRUNC(TO_DATE(CHALLAN_DATE)))  AND NVL(:P_CHALLAN_DATE_TO,TRUNC(TO_DATE(CHALLAN_DATE)))
GROUP BY  ORGANIZATION_ID,CUSTOMER_NAME,CREATED_BY,INVENTORY_ITEM_ID


--====================XX_ONT_CHALLAN_NO_KOL_V =========================


CREATE OR REPLACE FORCE VIEW XX_ONT_CHALLAN_NO_KOL_V
(
   ORG_ID,
   CHALLAN_NO,
   CUSTOMER_ID,
   CUSTOMER_NAME,
   CHALLAN_DATE,
   ORGANIZATION_ID
)
AS
SELECT DISTINCT WDD.ORG_ID,
                     NAME CHALLAN_NO, WND.CUSTOMER_ID,
                     (SELECT DISTINCT CUSTOMER_NAME FROM XX_AR_CUSTOMER_SITE_V WHERE CUSTOMER_ID= WND.CUSTOMER_ID) CUSTOMER_NAME,
                     CONFIRM_DATE CHALLAN_DATE,
                     WDD.ORGANIZATION_ID
       FROM WSH_DELIVERY_DETAILS WDD,
            WSH_DELIVERY_ASSIGNMENTS WDA,
            WSH_NEW_DELIVERIES WND
      WHERE     WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
            AND WDA.DELIVERY_ID = WND.DELIVERY_ID
            AND STATUS_CODE = 'CL'
   ORDER BY NAME 
   
   --====================================================




select * from MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_ID = 27 -- IN (61,62,63,52,53,33,44)

select * from MTL_TRANSACTION_TYPES where TRANSACTION_TYPE_NAME like '%Empty%'

  select DISTINCT INVENTORY_ITEM_ID,SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4 ITEM_CODE, DESCRIPTION
 from MTL_SYSTEM_ITEMS_B where INVENTORY_ITEM_ID= 75 




-- 15-NOV-2020
select * from XXKSRM_KOL_CHALLAN_V

SELECT * FROM XX_CHALLAN_MO_TEMP WHERE TRUNC(CHALLAN_DATE)  BETWEEN '4-NOV-2021' AND'6-NOV-2021'   --and CHALLAN_NO= 4201010071930 

SELECT * FROM XX_CHALLAN_MO_TEMP WHERE CHALLAN_NO= 4201010071930 -- BETWEEN '1-JUN-2020' AND '8-JUN-2021'

SELECT DISTINCT CUSTOMER_ID,CUSTOMER_NAME  FROM XX_CHALLAN_MO_TEMP


select FULL_NAME  from WBI_HR_EMPLOYEE_DETAILS_D where FIRST_NAME = 'KG-4079'

select * from MTL_SYSTEM_ITEMS_B WHERE INVENTORY_ITEM_ID = 75 and organization_id= 173
XX_INV_PKG.xxget_item_code

select * from XXKSRM_KOL_CHLN_RCV_PENDING where CHALLAN_NO not like '%4%' 

Select ORGANIZATION_ID ,CUSTOMER_NAME, CHALLAN_NO, CHALLAN_DATE,CHALLAN_QTY,INVENTORY_ITEM_ID, RECEIPT_QTY RETURN_QTY,  CREATED_BY  from XX_CHALLAN_MO_TEMP where CHALLAN_DATE between '15-nov-2020' and '16-nov-2020'  

--====================DETAILS===================================


select * from XX_CHALLAN_MO_TEMP where CUSTOMER_NAME LIKE  '%303-S. R. Shipping Ltd.%' 

SELECT ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=CM.ORGANIZATION_ID) COMPANY_NAME,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=CM.ORGANIZATION_ID) IO_ADDRESS,
CUSTOMER_NAME,CHALLAN_NO,CHALLAN_DATE,NVL(CHALLAN_QTY,0) CHALLAN_QTY,NVL(RECEIPT_QTY,0) RETURN_QTY,NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) CUSTOMER_BALANCE ,  CREATED_BY,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
MY_PACKAGE.XXGET_ITEM_DESCRIPTION(CM.INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT FULL_NAME  FROM WBI_HR_EMPLOYEE_DETAILS_D WHERE FIRST_NAME =CM.CREATED_BY) FULL_NAME, -- 'KG-4079'
  XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
  XXGET_EMP_DEPT_FROM_KGID(CM.CREATED_BY) DEPARTMENT,
  :P_CHALLAN_DATE_FROM,
:P_CHALLAN_DATE_TO  
FROM XX_CHALLAN_MO_TEMP CM
WHERE 1=1
AND  NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) >0
--AND CHALLAN_NO=NVL(:P_CHALLAN_NO,CHALLAN_NO) 
--AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
--AND CUSTOMER_ID = NVL(:P_CUSTOMER,CUSTOMER_ID) 
--AND TRUNC(TO_DATE(CHALLAN_DATE)) BETWEEN NVL(:P_CHALLAN_DATE_FROM,TRUNC(TO_DATE(CHALLAN_DATE)))  AND NVL(:P_CHALLAN_DATE_TO,TRUNC(TO_DATE(CHALLAN_DATE)))

--====================SUMMARY===================================

SELECT ORGANIZATION_ID, (SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=CM.ORGANIZATION_ID) COMPANY_NAME,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=CM.ORGANIZATION_ID) IO_ADDRESS,
CUSTOMER_NAME, NVL(SUM(CHALLAN_QTY),0) CHALLAN_QTY,NVL(SUM(RECEIPT_QTY),0) RETURN_QTY,NVL(SUM(CHALLAN_QTY),0) - NVL(SUM(RECEIPT_QTY),0)  CUSTOMER_BALANCE ,  CREATED_BY,
INVENTORY_ITEM_ID,
XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) ITEM_CODE,
MY_PACKAGE.XXGET_ITEM_DESCRIPTION(CM.INVENTORY_ITEM_ID) ITEM_DESCRIPTION,
(SELECT FULL_NAME  FROM WBI_HR_EMPLOYEE_DETAILS_D WHERE FIRST_NAME =CM.CREATED_BY) FULL_NAME, -- 'KG-4079'
  XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
  XXGET_EMP_DEPT_FROM_KGID(CM.CREATED_BY) DEPARTMENT,
:P_CHALLAN_DATE_FROM,
:P_CHALLAN_DATE_TO  
FROM XX_CHALLAN_MO_TEMP CM
WHERE 1=1
AND  NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0) >0
AND CHALLAN_NO=NVL(:P_CHALLAN_NO,CHALLAN_NO) 
AND ORGANIZATION_ID = NVL(:P_ORG_ID,ORGANIZATION_ID)
AND CUSTOMER_ID = NVL(:P_CUSTOMER,CUSTOMER_ID)  
AND TRUNC(TO_DATE(CHALLAN_DATE)) BETWEEN NVL(:P_CHALLAN_DATE_FROM,TRUNC(TO_DATE(CHALLAN_DATE)))  AND NVL(:P_CHALLAN_DATE_TO,TRUNC(TO_DATE(CHALLAN_DATE)))
GROUP BY  ORGANIZATION_ID,CUSTOMER_NAME,CREATED_BY,INVENTORY_ITEM_ID






Valuset Name: XXKSRM_CUSTOMER_KOM





SELECT STATEMENT: 
(SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME, CUST_ACT.ACCOUNT_NUMBER CUSTOMER_NUMBER, CUST_ACT.CUST_ACCOUNT_ID CUSTOMER_ID FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID) X

SELECT  DISTINCT  PARTY.PARTY_NAME
FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT 
WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID
and  CUST_ACT.CUST_ACCOUNT_ID =4077 -- CUST_ACT.PARTY_ID



SELECT * FROM XX_CHALLAN_MO_TEMP 

-- PREVIOUS WHERE  CONDITION :
WHERE  X.CUSTOMER_ID IN (SELECT DISTINCT CUSTOMER_ID FROM XX_CHALLAN_MO_TEMP)

--MY WHERE CONDITION:
Valuset Name: XXKSRM_CUSTOMER_FOR_KOL

(SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME, CUST_ACT.ACCOUNT_NUMBER CUSTOMER_NUMBER, CUST_ACT.CUST_ACCOUNT_ID CUSTOMER_ID FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID) X


and CUST_ACT.CUST_ACCOUNT_ID = 4041


WHERE  X.CUSTOMER_ID IN (SELECT DISTINCT CUSTOMER_ID FROM XXKSRM_KOL_CHALLAN_V)

SELECT * FROM HZ_PARTIES where PARTY_NAME =  'LINK UP STEEL MILLS LTD'

select * from HZ_CUST_ACCOUNTS where CUST_ACCOUNT_ID = 7933 --4135 --4077



SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME, CUST_ACT.ACCOUNT_NUMBER CUSTOMER_NUMBER, CUST_ACT.CUST_ACCOUNT_ID CUSTOMER_ID 
FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_NAME= CUST_ACT.PARTY_ID

WHERE  X.CUSTOMER_ID IN (SELECT DISTINCT CUSTOMER_ID FROM XXKSRM_KOL_CHALLAN_V)






AND XKCV.CHALLAN_NO=NVL(:P_CHALLAN_NO,XKCV.CHALLAN_NO) 



WHERE CUSTOMER_NAME = NVL(:P_CUSTOMER,CUSTOMER_NAME)  
AND CHALLAN_NO = NVL(:P_CHALLAN_NO, CHALLAN_NO)
--AND INVENTORY_ITEM_ID = :P_ITEM_ID,INVENTORY_ITEM_ID
AND XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID) = NVL(:P_ITEM_CODE,XX_INV_PKG.XXGET_ITEM_CODE(INVENTORY_ITEM_ID))
AND CREATED_BY =  NVL(:P_CREATED_BY,CREATED_BY)
AND CHALLAN_DATE BETWEEN NVL(:FROM_DATE,CHALLAN_DATE) AND NVL(:TO_DATE,CHALLAN_DATE)



--CREATE OR REPLACE FUNCTION XXGET_ITEM_DESCRIPTION(P_ITEM_ID IN NUMBER)
RETURN VARCHAR2
IS
V_ITEM_DESC VARCHAR2(200);
BEGIN
  SELECT DESCRIPTION INTO V_ITEM_DESC
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID= P_ITEM_ID;
RETURN(V_ITEM_DESC);
EXCEPTION WHEN OTHERS THEN
 RETURN(NULL);
END;






SELECT * FROM MTL_SYSTEM_ITEMS_VL MSI

(select DISTINCT   (   MSI.SEGMENT1|| '|' || MSI.SEGMENT2  || '|' || MSI.SEGMENT3|| '|'|| MSI.SEGMENT4) ITEM_CODE, MSI.DESCRIPTION from MTL_SYSTEM_ITEMS_VL MSI where INVENTORY_ITEM_ID =CM.INVENTORY_ITEM_ID)






-- XXKSRM Customer Wise Cylinder Stock  OLD
SELECT 
(SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=XKCV.ORGANIZATION_ID) COMPANY_NAME,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=XKCV.ORGANIZATION_ID) IO_ADDRESS,
XKCV.ORGANIZATION_ID,
XKCV.ITEMCODE,
XKCV.ITEM_DESCRIPTION,
XKCV.CHALLAN_QTY,
XKCV.CHALLAN_NO,
XKCV.CHALLAN_DATE,
XKCV.CUSTOMER_ID,
(SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XKCV.CUSTOMER_ID ) CUSTOMER_NAME,
NVL(XKCV.RECEIPT_QTY,0)  RETURN_QTY,
XKCV.PARTY_BALANCE CUSTOMER_BALANCE,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
  XX_INV_PKG.XXGET_EMP_DEPT(XKCV.CREATED_BY) DEPARTMENT,
:P_CHALLAN_DATE_FROM PDATE_FROM,
:P_CHALLAN_DATE_TO PDATE_TO
FROM 
XXKSRM_KOL_CHALLAN_V XKCV
WHERE
XKCV.PARTY_BALANCE>0
AND XKCV.ORGANIZATION_ID=NVL(:P_ORG_ID,XKCV.ORGANIZATION_ID)
AND XKCV.CUSTOMER_ID=NVL(:P_CUSTOMER_ID,XKCV.CUSTOMER_ID)
AND TO_DATE(XKCV.CHALLAN_DATE) BETWEEN NVL(:P_CHALLAN_DATE_FROM,TO_DATE(XKCV.CHALLAN_DATE))  AND NVL(:P_CHALLAN_DATE_TO,TO_DATE(XKCV.CHALLAN_DATE))
AND XKCV.CHALLAN_NO=NVL(:P_CHALLAN_NO,XKCV.CHALLAN_NO) 



--=============================== Valuset for dept/customer===================================
(SELECT USE_AREA,USE_AREA_TYPE,TO_NUMBER(USE_AREA_ID) CUSTOMER_ID FROM XXKSRM_INV_USE_AREA_V union all SELECT DISTINCT A.PARTY_NAME,B.ACCOUNT_NUMBER,B.CUST_ACCOUNT_ID FROM HZ_PARTIES A, HZ_CUST_ACCOUNTS B WHERE A.PARTY_ID=B.PARTY_ID) X


CUSTOMER_ID IN (SELECT Distinct CUSTOMER_ID FROM XXKSRM_KOL_CHALLAN_V) OR CUSTOMER_ID IN (SELECT DISTINCT DEPARTMENT_ID CUSTOMER_ID FROM XXKSRM_KOL_MO_V)

SELECT Distinct CUSTOMER_ID FROM XXKSRM_KOL_CHALLAN_V where CUSTOMER_ID =  '19142'

--========================= TESTING 

SELECT USE_AREA,USE_AREA_TYPE,TO_NUMBER(USE_AREA_ID) CUSTOMER_ID FROM XXKSRM_INV_USE_AREA_V 
union all 

SELECT DISTINCT A.PARTY_NAME,B.ACCOUNT_NUMBER,B.CUST_ACCOUNT_ID FROM HZ_PARTIES A, HZ_CUST_ACCOUNTS B 
WHERE A.PARTY_ID=B.PARTY_ID
and B.CUST_ACCOUNT_ID = '19142'







--=========================== FINAL FOR PRODUCTION SERVER -- Date : 14-NOV-2020 ===========================
--==============================================================================================


Select * from XX_CHALLAN_MO_TEMP where challan_no = '4181010003671' 


--CREATE TABLE XX_CHALLAN_MO_TEMP(
--ORGANIZATION_ID NUMBER,
--CHALLAN_NO NUMBER ,
--CHALLAN_DATE  DATE,
--CHALLAN_QTY NUMBER,
--INVENTORY_ITEM_ID NUMBER,
--CUSTOMER_NAME VARCHAR2(200),
--RECEIPT_QTY NUMBER ,
--CREATED_BY VARCHAR2(100),
--CHILD_INVENTORY_ITEM_ID NUMBER,
--CUSTOMER_ID NUMBER
--)


-- ==========================================SELECT STATEMENT=============

       SELECT ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE ,sum(QUANTITY) CHALLAN_QTY ,INVENTORY_ITEM_ID,RECEIPT_QTY RECEIVE_QTY,CONFIRMED_BY, CHILD_INVENTORY_ITEM_ID,CUSTOMER_ID,
       (SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID ) CUSTOMER_NAME
         FROM XXKSRM_KOL_CHALLAN_V
WHERE  ORGANIZATION_ID = 173
and challan_no = '4201010057565' 
GROUP BY CHALLAN_NO, CHALLAN_DATE, INVENTORY_ITEM_ID , ORGANIZATION_ID,RECEIPT_QTY,XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID,CONFIRMED_BY,CHILD_INVENTORY_ITEM_ID,CUSTOMER_ID


-- INCLUDE SELECT STATEMENT IN MERGE STATEMENT=============

SELECT * FROM XXKSRM_KOL_CHALLAN_V WHERE challan_no = '4191010050556' 




select * from XX_CHALLAN_MO_TEMP -- 16,896
minus
select * from XX_CHALLAN_MO_TEMP_test -- 16,910


select * from XX_CHALLAN_MO_TEMP  where challan_NO='4211020084551'
UNION ALL
select * from XX_CHALLAN_MO_TEMP_TEST  where challan_NO='4211020084551'


MERGE INTO XX_CHALLAN_MO_TEMP_TEST L
USING ( SELECT ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE ,sum(QUANTITY) CHALLAN_QTY ,INVENTORY_ITEM_ID,CONFIRMED_BY,CHILD_INVENTORY_ITEM_ID,CUSTOMER_ID,
         (SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID ) CUSTOMER_NAME,
       RECEIPT_QTY RECEIPT_QTY
         FROM XXKSRM_KOL_CHALLAN_V
WHERE  ORGANIZATION_ID = 173
--and challan_no = '4181010003671' 
GROUP BY CHALLAN_NO, CHALLAN_DATE, INVENTORY_ITEM_ID , ORGANIZATION_ID,RECEIPT_QTY,XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID,CONFIRMED_BY,CHILD_INVENTORY_ITEM_ID,CUSTOMER_ID) S
ON (L.CHALLAN_NO = S.CHALLAN_NO)
WHEN MATCHED THEN
  UPDATE SET-- L.ORGANIZATION_ID = S.ORGANIZATION_ID,
  --L.CHALLAN_NO= S.CHALLAN_NO,
--  L.CHALLAN_DATE = S.CHALLAN_DATE,
  L.CHALLAN_QTY= S.CHALLAN_QTY,
 -- L.INVENTORY_ITEM_ID = S.INVENTORY_ITEM_ID,
  L.RECEIPT_QTY = S.RECEIPT_QTY
   WHERE L.CHALLAN_NO = S.CHALLAN_NO
WHEN NOT MATCHED THEN 
INSERT (L.ORGANIZATION_ID, L.CHALLAN_NO, L.CHALLAN_DATE,L.CHALLAN_QTY,L.INVENTORY_ITEM_ID,CUSTOMER_NAME,L.RECEIPT_QTY,L.CREATED_BY,L.CHILD_INVENTORY_ITEM_ID,L.CUSTOMER_ID)
VALUES (S.ORGANIZATION_ID, S.CHALLAN_NO, S.CHALLAN_DATE,S.CHALLAN_QTY,S.INVENTORY_ITEM_ID,S.CUSTOMER_NAME,S.RECEIPT_QTY,S.CONFIRMED_BY,S.CHILD_INVENTORY_ITEM_ID,S.CUSTOMER_ID);





--============ CREATE A PROCEDURE  FROM THE MERGE STATEMENT , SO THAT ALL DATA GOES TO  TEMP TABLE: XX_CHALLAN_MO_TEMP 

--CREATE OR REPLACE procedure XX_CHALLAN_MO_TEMP_PROCESS(
errbuf OUT VARCHAR2,
 retcode OUT NUMBER)
 AS
 BEGIN

MERGE INTO XX_CHALLAN_MO_TEMP L
USING ( SELECT ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE ,sum(QUANTITY) CHALLAN_QTY ,INVENTORY_ITEM_ID,CONFIRMED_BY,CHILD_INVENTORY_ITEM_ID,CUSTOMER_ID,
         (SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID ) CUSTOMER_NAME,
       RECEIPT_QTY RECEIPT_QTY
         FROM XXKSRM_KOL_CHALLAN_V
WHERE  ORGANIZATION_ID = 173
--and challan_no = '4181010003671' 
GROUP BY CHALLAN_NO, CHALLAN_DATE, INVENTORY_ITEM_ID , ORGANIZATION_ID,RECEIPT_QTY,XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID,CONFIRMED_BY,CHILD_INVENTORY_ITEM_ID,CUSTOMER_ID) S
ON (L.CHALLAN_NO = S.CHALLAN_NO)
WHEN MATCHED THEN
  UPDATE SET-- L.ORGANIZATION_ID = S.ORGANIZATION_ID,
  --L.CHALLAN_NO= S.CHALLAN_NO,
--  L.CHALLAN_DATE = S.CHALLAN_DATE,
  L.CHALLAN_QTY= S.CHALLAN_QTY,
 -- L.INVENTORY_ITEM_ID = S.INVENTORY_ITEM_ID,
  L.RECEIPT_QTY = S.RECEIPT_QTY
   WHERE L.CHALLAN_NO = S.CHALLAN_NO
WHEN NOT MATCHED THEN 
INSERT (L.ORGANIZATION_ID, L.CHALLAN_NO, L.CHALLAN_DATE,L.CHALLAN_QTY,L.INVENTORY_ITEM_ID,CUSTOMER_NAME,L.RECEIPT_QTY,L.CREATED_BY,L.CHILD_INVENTORY_ITEM_ID,L.CUSTOMER_ID)
VALUES (S.ORGANIZATION_ID, S.CHALLAN_NO, S.CHALLAN_DATE,S.CHALLAN_QTY,S.INVENTORY_ITEM_ID,S.CUSTOMER_NAME,S.RECEIPT_QTY,S.CONFIRMED_BY,S.CHILD_INVENTORY_ITEM_ID,S.CUSTOMER_ID);

commit;

EXCEPTION
    WHEN OTHERS THEN
    NULL;
END;
/


--=========FINAL:  XXKSRM_KOL_CHLN_RCV_PENDING  DATE: 14-NOV-2020 =======


CREATE OR REPLACE FORCE VIEW XXKSRM_KOL_CHLN_RCV_PENDING  
(
   CHALLAN_NO,
   CHALLAN_DATE,
   BAL,
    ID,
   CHILD_INVENTORY_ITEM_ID
)
AS
   SELECT 
          TO_CHAR (CHALLAN_NO),
          CHALLAN_DATE,
         (NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0)) BAL,
         TO_CHAR (CUSTOMER_ID) ID,
          TO_CHAR(CHILD_INVENTORY_ITEM_ID)   
     FROM XX_CHALLAN_MO_TEMP
   UNION ALL
   SELECT 
          REQUEST_NUMBER,
          DATE_REQUIRED,
          NVL (PARTY_BALANCE, 0) BAL,
          DEPT_ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KCMD;

--===================================================== END FINAL FOR PRODUCTION =======================================================






/*==================
1. Find a query to send arafat for reconcile with negatiive balance and pending Challan Qty

QUERY: SELECT ORGANIZATION_ID,
          TO_CHAR (CHALLAN_NO) CHALLAN_NO,
          NVL(CHALLAN_QTY,0) CHALLAN_QTY ,
          NVL(RECEIPT_QTY,0) RECEIPT_QTY,
          CHALLAN_DATE,
          (NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0)) BALANCE
     FROM XX_CHALLAN_MO_TEMP
     
     
2. Take the feedback mail from arafat for testing in UAT server and its ok 
Taken

3. Update exist Pending View 

. Make a mail and 
*/


SELECT ORGANIZATION_ID,
          TO_CHAR (CHALLAN_NO) CHALLAN_NO,
          NVL(CHALLAN_QTY,0) CHALLAN_QTY ,
          NVL(RECEIPT_QTY,0) RECEIPT_QTY,
          CHALLAN_DATE,
          (NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0)) BALANCE
     FROM XX_CHALLAN_MO_TEMP

SELECT  from XXKSRM_KOL_CHLN_RCV_PENDINGK WHERE BAL <> 0

select * from SYSTEM_ITEM_KFV


SELECT *   FROM XX_CHALLAN_MO_TEMP WHERE  CHALLAN_DATE between '1-NOV-2020' and '15-NOV-2020'   -- 8 ta line


WHERE CHALLAN_NO= 4181010003671


select * from WSH_NEW_DELIVERIES where ORGANIZATION_ID= 173     --order by name

SELECT * FROM ORG_ORGANIZATION_DEFINITIONS 

 --- TOTAL 14 line ashse lunch kore abar check korbo

--challan_no = '4181010003671' 

SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERe ORGANIZATION_CODE='KSO'

SELECT * FROM per_all_people_f WHERE FIRST_NAME = 'KG-72'


select * from 

select * from XX_CHALLAN_MO_TEMP WHERE CHALLAN_NO='4181010003671' -- '4201010057565' 

select * from XXKSRM_KOL_CHLN_RCV_PENDING WHERE CHALLAN_NO= '4201010057565' 

SELECT ORGANIZATION_ID,
          TO_CHAR (CHALLAN_NO) CHALLAN_NO,
          NVL(CHALLAN_QTY,0) CHALLAN_QTY ,
          NVL(RECEIPT_QTY,0) RECEIPT_QTY,
          CHALLAN_DATE,
          (NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0)) BALANCE
     FROM XX_CHALLAN_MO_TEMP
     --WHERE (NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0)) <> 0
     
     WHERE CHALLAN_NO= '4201010038459'


select * from  XX_CHALLAN_MO_TEMP

select * from XXKSRM_KOL_CHLN_RCV_PENDINGK WHERE BAL > 0

select  DISTINCT CHILD_INVENTORY_ITEM_ID FROM XXKSRM_KOL_CHALLAN_V


   SELECT 
          TO_CHAR (CHALLAN_NO),
          CHALLAN_DATE,
         (NVL(CHALLAN_QTY,0) - NVL(RECEIPT_QTY,0)) BAL,
         NULL,
          CHILD_INVENTORY_ITEM_ID   
     FROM XX_CHALLAN_MO_TEMP


select * from XXKSRM_KOL_CHLN_RCV_PENDING





-- /*VIEW UPDATED DATE: 9-NOV-2020 ITS OK NOW* /

--==============================================
/*  Baten Vaii er query   */

CREATE OR REPLACE FORCE VIEW APPS.XXKSRM_KOL_CHLN_RCV_PENDING
(
   CHALLAN_NO,
   CHALLAN_DATE,
   BAL,
   ID,
   CHILD_INVENTORY_ITEM_ID
)
AS
   SELECT CHALLAN_NO,
          CHALLAN_DATE,
          NVL (PARTY_BALANCE, 0) BAL,
          TO_CHAR (CUSTOMER_ID) ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KOL_CHALLAN_V
   UNION ALL
   SELECT REQUEST_NUMBER,
          DATE_REQUIRED,
          NVL (PARTY_BALANCE, 0) BAL,
          DEPT_ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KCMD;

     
     --=============================================













/* Formatted on 11/4/2020 5:35:26 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW APPS.XXKSRM_KOL_CHLN_RCV_PENDING
(
ORGANIZATION_ID,
   CHALLAN_NO,
   CHALLAN_DATE,
   BAL,
   ID,
   CHILD_INVENTORY_ITEM_ID
)
AS
   SELECT ORGANIZATION_ID,TO_CHAR (CHALLAN_NO),
          CHALLAN_DATE,
          (CHALLAN_QTY - RECEIPT_QTY) BAL,
          NULL,
          NULL
     FROM XX_CHALLAN_MO_TEMP
   UNION ALL
   SELECT ORGANIZATION_ID,REQUEST_NUMBER,
          DATE_REQUIRED,
          NVL (PARTY_BALANCE, 0) BAL,
          DEPT_ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KCMD;

--==================== FOR TESTING=====================================
SELECT ORGANIZATION_ID, CHALLAN_NO,CHALLAN_DATE, CHALLAN_QTY, INVENTORY_ITEM_ID, RECEIPT_QTY, (CHALLAN_QTY-RECEIPT_QTY) balance      
FROM XX_CHALLAN_MO_TEMP
where CHALLAN_QTY-RECEIPT_QTY <> 0
and CHALLAN_QTY-RECEIPT_QTY <0
--and challan_no = '4201010048543' 
order by CHALLAN_DATE desc






select * from XX_CHALLAN_MO_TEMP where  CHALLAN_NO ='4201010037370' 

select * from APPS.XXKSRM_KOL_CHLN_RCV_PENDING where CHALLAN_NO ='4201010037370' 

select * from XXKSRM_KOL_CHALLAN_V where CHALLAN_NO ='4201010037370'  

select * from MTL_MATERIAL_TRANSACTIONS WHERE ATTRIBUTE3='4201010037370'


SELECT CHALLAN_NO,NVL(PARTY_BALANCE,0) BAL,TO_CHAR(CUSTOMER_ID) ID,CHILD_INVENTORY_ITEM_ID
 FROM XXKSRM_KOL_CHALLAN_V
 --where CHALLAN_NO ='4201010038456' 
  UNION ALL 
 SELECT REQUEST_NUMBER,NVL(PARTY_BALANCE,0) BAL,DEPT_ID,CHILD_INVENTORY_ITEM_ID
  FROM XXKSRM_KCMD




CREATE OR REPLACE PROCEDURE UPSERT_XX_CHALLAN_MO_TEMP(
CHALLAN_NO IN NUMBER
) AS
  err_num NUMBER;
  err_msg VARCHAR2(4000);
  BEGIN
  MERGE INTO XX_CHALLAN_MO_TEMP L
USING (SELECT ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE ,sum(QUANTITY) CHALLAN_QTY ,INVENTORY_ITEM_ID,RECEIPT_QTY   FROM XXKSRM_KOL_CHALLAN_V WHERE ORGANIZATION_ID = 173
GROUP BY ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE,INVENTORY_ITEM_ID,RECEIPT_QTY  ) S
ON (L.CHALLAN_NO = S.CHALLAN_NO)
WHEN MATCHED THEN
  UPDATE SET
  L.CHALLAN_QTY= S.CHALLAN_QTY,
  L.RECEIPT_QTY = S.RECEIPT_QTY
   WHERE L.CHALLAN_NO = S.CHALLAN_NO
WHEN NOT MATCHED THEN 
INSERT (L.ORGANIZATION_ID, L.CHALLAN_NO, L.CHALLAN_DATE,L.CHALLAN_QTY,L.INVENTORY_ITEM_ID,L.RECEIPT_QTY)
VALUES (S.ORGANIZATION_ID, S.CHALLAN_NO, S.CHALLAN_DATE,S.CHALLAN_QTY,S.INVENTORY_ITEM_ID,S.RECEIPT_QTY);
Response_out := '';
    EXCEPTION
      WHEN OTHERS THEN
        err_num := SQLCODE;
        err_msg := SUBSTR(SQLERRM, 1, 3900);
        Response_out := TO_CHAR (err_num) || ': ' || err_msg;
  END; 



SELECT ORGANIZATION_ID, CHALLAN_NO,CHALLAN_DATE, CHALLAN_QTY, INVENTORY_ITEM_ID, RECEIPT_QTY, (CHALLAN_QTY-RECEIPT_QTY) balance      
FROM XX_CHALLAN_MO_TEMP
where CHALLAN_QTY-RECEIPT_QTY <> 0
and CHALLAN_QTY-RECEIPT_QTY <0
--and challan_no = '4201010048543' 
order by CHALLAN_DATE desc







select * from XX_CHALLAN_MO_TEMP -- TOTAL : 8,371 


DROP TABLE XX_CHALLAN_MO_TEMP;

CREATE TABLE XX_CHALLAN_MO_TEMP(
ORGANIZATION_ID NUMBER,
CHALLAN_NO NUMBER ,
CHALLAN_DATE  DATE,
CHALLAN_QTY NUMBER,
INVENTORY_ITEM_ID NUMBER,
CUSTOMER_NAME VARCHAR2(200),
RECEIPT_QTY NUMBER 
)





INSERT INTO XX_CHALLAN_MO_TEMP
       SELECT ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE ,sum(QUANTITY) CHALLAN_QTY ,INVENTORY_ITEM_ID,
         (SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID ) CUSTOMER_NAME,
       RECEIPT_QTY RECEIPT_QTY
         FROM XXKSRM_KOL_CHALLAN_V
WHERE  ORGANIZATION_ID = 173
--and challan_no = '4181010003671' 
GROUP BY CHALLAN_NO, CHALLAN_DATE, INVENTORY_ITEM_ID , ORGANIZATION_ID,RECEIPT_QTY,XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID;



SELECT ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE ,sum(QUANTITY) CHALLAN_QTY ,INVENTORY_ITEM_ID,RECEIPT_QTY RECEIVE_QTY,
       (SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID ) CUSTOMER_NAME
         FROM XXKSRM_KOL_CHALLAN_V
WHERE  ORGANIZATION_ID = 173
and challan_no = '4181010003671' 
GROUP BY CHALLAN_NO, CHALLAN_DATE, INVENTORY_ITEM_ID , ORGANIZATION_ID,RECEIPT_QTY,XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID;

select * from XXKSRM_KOL_CHALLAN_V where challan_no = '4181010003671' 

--YOU CANNOT UPDATE A COLUMN WHICH IS USED IN THE ON CLAUSE. MOVE THE CONDITION TO THE WHERE CLAUSE THEN:

select CHALLAN_NO,CHALLAN_QTY,RECEIPT_QTY, CHALLAN_QTY- RECEIPT_QTY Balance    from XX_CHALLAN_MO_TEMP where CHALLAN_QTY- RECEIPT_QTY<>0


MERGE INTO XX_CHALLAN_MO_TEMP L
USING ( SELECT ORGANIZATION_ID,CHALLAN_NO, CHALLAN_DATE ,sum(QUANTITY) CHALLAN_QTY ,INVENTORY_ITEM_ID,
         (SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID ) CUSTOMER_NAME,
       RECEIPT_QTY RECEIPT_QTY
         FROM XXKSRM_KOL_CHALLAN_V
WHERE  ORGANIZATION_ID = 173
--and challan_no = '4181010003671' 
GROUP BY CHALLAN_NO, CHALLAN_DATE, INVENTORY_ITEM_ID , ORGANIZATION_ID,RECEIPT_QTY,XXKSRM_KOL_CHALLAN_V.CUSTOMER_ID) S
ON (L.CHALLAN_NO = S.CHALLAN_NO)
WHEN MATCHED THEN
  UPDATE SET-- L.ORGANIZATION_ID = S.ORGANIZATION_ID,
  --L.CHALLAN_NO= S.CHALLAN_NO,
--  L.CHALLAN_DATE = S.CHALLAN_DATE,
  L.CHALLAN_QTY= S.CHALLAN_QTY,
 -- L.INVENTORY_ITEM_ID = S.INVENTORY_ITEM_ID,
  L.RECEIPT_QTY = S.RECEIPT_QTY
   WHERE L.CHALLAN_NO = S.CHALLAN_NO
WHEN NOT MATCHED THEN 
INSERT (L.ORGANIZATION_ID, L.CHALLAN_NO, L.CHALLAN_DATE,L.CHALLAN_QTY,L.INVENTORY_ITEM_ID,CUSTOMER_NAME,L.RECEIPT_QTY)
VALUES (S.ORGANIZATION_ID, S.CHALLAN_NO, S.CHALLAN_DATE,S.CHALLAN_QTY,S.INVENTORY_ITEM_ID,S.CUSTOMER_NAME,S.RECEIPT_QTY);






SELECT ORGANIZATION_ID,CHALLAN_NO, TRUNC(CHALLAN_DATE),INVENTORY_ITEM_ID, SUM(QUANTITY), SUM(RECEIPT_QTY) FROM XXKSRM_KOL_CHALLAN_V
WHERE  ORGANIZATION_ID = 173
and challan_no = '4181010003671' 
GROUP BY CHALLAN_NO, CHALLAN_DATE, INVENTORY_ITEM_ID , ORGANIZATION_ID



SELECT * FROM XXKSRM_KOL_CHALLAN_V WHERE challan_no = '4191010050556' 

select * from MTL_MATERIAL_TRANSACTIONS where ATTRIBUTE3= '4181010003671' 



select * FROM XXKSRM_KOL_CHALLAN_V WHERE challan_no = '4181010003671' 

select CHALLAN_NO,RECEIPT_QTY,INVENTORY_ITEM_ID, SUM(CHALLAN_QTY) FROM XXKSRM_KOL_CHALLAN_V WHERE challan_no = '4181010003671' 
GROUP BY CHALLAN_NO,INVENTORY_ITEM_ID,RECEIPT_QTY

select SUM(TRANSACTION_QUANTITY)  FROM MTL_MATERIAL_TRANSACTIONS WHERE ATTRIBUTE3='4181010003671'


SELECT   GET_QTY_FROM_CHALLAN_NO(SUM(WND.NAME)) CHALLAN_QTY, SUM(MMT.TRANSACTION_QUANTITY) RECEIVE_QUANTITY
FROM MTL_MATERIAL_TRANSACTIONS MMT,  WSH_NEW_DELIVERIES WND
WHERE MMT.ATTRIBUTE3 = WND.NAME
and MMT.ATTRIBUTE3=
--'4201010048543' 
--'4181010003671'
--'4201010040533' 








select * from PO_HEADERS_ALL 

select * from WSH_NEW_DELIVERIES WND where WND.NAME=4201010040533
--'4181010003671'

select * from    MTL_TXN_REQUEST_LINES MTRL where header_id=534631 --MTRL.QUANTITY_DELIVERED  CHALLAN_QUANTITY

select * from MTL_TXN_REQUEST_HEADERS MTRH where HEADER_ID = 534631




--============================== FUNCTION===========================
--CREATE  OR REPLACE FUNCTION GET_QTY_FROM_CHALLAN_NO(P_CHALLAN IN NUMBER )
RETURN NUMBER
IS
V_QTY NUMBER;
BEGIN
SELECT  SUM( MTRL.QUANTITY_DELIVERED) INTO V_QTY
 FROM WSH_NEW_DELIVERIES WND, 
 MTL_TXN_REQUEST_LINES MTRL,
 WSH_DELIVERY_ASSIGNMENTS WDA,
 WSH_DELIVERY_DETAILS WDD
WHERE  WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
and WDA.DELIVERY_ID = WND.DELIVERY_ID(+)
AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
and WND.ORGANIZATION_ID = 173
AND WND.NAME=P_CHALLAN; 
RETURN V_QTY;
EXCEPTION WHEN OTHERS THEN
RETURN NULL;
END;


SELECT * FROM WSH_DELIVERY_ASSIGNMENTS WDA

SELECT * FROM WSH_DELIVERY_DETAILS WDD where DELIVERY_DETAIL_ID IN(1391180,
1395616,
1386893)

SELECT   COUNT(DELIVERY_DETAIL_ID) SUM(MTRL.QUANTITY_DELIVERED)  FROM(
SELECT SUM(SHIPPED_QUANTITY) FROM  
)

SELECT COUNT(WDD.DELIVERY_DETAIL_ID),  SUM(MTRL.QUANTITY_DELIVERED) 
 FROM WSH_NEW_DELIVERIES WND, 
 MTL_TXN_REQUEST_LINES MTRL,
 WSH_DELIVERY_ASSIGNMENTS WDA,
 WSH_DELIVERY_DETAILS WDD
WHERE  WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
and WDA.DELIVERY_ID = WND.DELIVERY_ID(+)
AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
AND WND.NAME=4201010040533 --'4201010048543'
HAVING COUNT(WDD.DELIVERY_DETAIL_ID)  >2
--GROUP BY WDD.DELIVERY_DETAIL_ID


SELECT  SUM(MTRL.QUANTITY_DELIVERED) 
 FROM WSH_NEW_DELIVERIES WND, 
 MTL_TXN_REQUEST_LINES MTRL,
 WSH_DELIVERY_ASSIGNMENTS WDA,
 WSH_DELIVERY_DETAILS WDD
WHERE  WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
and WDA.DELIVERY_ID = WND.DELIVERY_ID(+)
AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
and WND.ORGANIZATION_ID = 173
AND WND.NAME=4201010040533 --P_CHALLAN

select SUM(TRANSACTION_QUANTITY),
(SELECT  SUM(MTRL.QUANTITY_DELIVERED )
 FROM WSH_NEW_DELIVERIES WND, MTL_TXN_REQUEST_LINES MTRL,WSH_DELIVERY_ASSIGNMENTS WDA,WSH_DELIVERY_DETAILS WDD,
MTL_TXN_REQUEST_HEADERS MTRH 
WHERE 1=1
 AND WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
and WDA.DELIVERY_ID = WND.DELIVERY_ID(+)
AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
AND MTRL.HEADER_ID = MTRH.HEADER_ID
AND WND.NAME=MMT.ATTRIBUTE3
--'4181010003671'
)
  FROM MTL_MATERIAL_TRANSACTIONS MMT WHERE ATTRIBUTE3='4181010003671'








SELECT  SUM(MTRL.QUANTITY_DELIVERED )
 FROM WSH_NEW_DELIVERIES WND, MTL_TXN_REQUEST_LINES MTRL,WSH_DELIVERY_ASSIGNMENTS WDA,WSH_DELIVERY_DETAILS WDD,
MTL_TXN_REQUEST_HEADERS MTRH 
WHERE 1=1
 AND WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
and WDA.DELIVERY_ID = WND.DELIVERY_ID(+)
AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
AND MTRL.HEADER_ID = MTRH.HEADER_ID
AND WND.NAME='4181010003671'






SELECT SUM()

SELECT * FROM 



--==========================================
SELECT TRANSACTION_ID, ATTRIBUTE3, TRANSACTION_QUANTITY, ATTRIBUTE_CATEGORY,ATTRIBUTE11 REASON,CREATION_DATE,TRANSACTION_DATE,TRANSACTION_TYPE_ID,DISTRIBUTION_ACCOUNT_ID  FROM MTL_MATERIAL_TRANSACTIONS
WHERE ATTRIBUTE3 IN(4181010001208,
4181010002412,
4181010002412,
4181010002638,
4181010002638,
4181010003450,
4181010003450,
4181010003671,
4181010003671,
4181010003959,
4181010005496,
4181010005496,
4181010008493,
4181010008493,
4181010012567,
4181010012567,
4181010016672,
4181010016672,
4181010017535,
4181010017535,
4181010018783,
4181010018783,
4181010020327,
4181010020327,
4181010022065,
4181010022065,
4191010001418,
4191010001418,
4191010001884,
4191010002797,
4191010002797,
4191010002797,
4191010002797,
4191010002797,
4191010002797,
4191010011573,
4191010011573,
4191010011573,
4191010033518,
4191010050050,
4191010050050,
4191010050237,
4191010050237,
4191010050556,
4191010050556,
4191010051135,
4191010051135,
4191010051135,
4191010051349,
4191010051349,
4191010051670,
4191010051670,
4191010051670,
4191010052232,
4191010052232,
4191010059523,
4191010059523,
4201010014018,
4201010014018,
4201010014545,
4201010014545,
4201010014545,
4201010015269,
4201010015269,
4201010015308,
4201010015308,
4201010018011,
4201010018011,
4201010018011,
4201010018791,
4201010018791,
4201010019068,
4201010019068,
4201010019068,
4201010019070,
4201010019070,
4201010020743,
4201010020743,
4201010023685,
4201010023685,
4201010023828,
4201010023828,
4201010023828,
4201010025363,
4201010025363,
4201010026568,
4201010026568,
4201010026801,
4201010026801,
4201010026802,
4201010026802,
4201010026805,
4201010026805,
4201010027049,
4201010027049,
4201010027205,
4201010027205,
4201010027749,
4201010027749,
4201010027749,
4201010027753,
4201010027753,
4201010027776,
4201010027776,
4201010027861,
4201010027861,
4201010027906,
4201010027906,
4201010028499,
4201010028499,
4201010028672,
4201010028672,
4201010028808,
4201010028808,
4201010028983,
4201010028983,
4201010029551,
4201010029551,
4201010029553,
4201010029553,
4201010030164,
4201010030164,
4201010030302,
4201010030302,
4201010030399,
4201010030399,
4201010030684,
4201010030684,
4201010030694,
4201010030694,
4201010030875,
4201010030875,
4201010030875,
4201010030917,
4201010030917,
4201010031392,
4201010031392,
4201010031621,
4201010031621,
4201010031638,
4201010031638,
4201010031638,
4201010031681,
4201010031681,
4201010032622,
4201010032622,
4201010033303,
4201010033303,
4201010033305,
4201010033305,
4201010034482,
4201010034482,
4201010034693,
4201010034693,
4201010034723,
4201010034723,
4201010035968,
4201010035968,
4201010036435,
4201010036435,
4201010037434,
4201010037434,
4201010037444,
4201010037444,
4201010037615,
4201010037615,
4201010037618,
4201010037618,
4201010038654,
4201010038654,
4201010039890,
4201010039890,
4201010040532,
4201010040532,
4201010040533,
4201010040533,
4201010040533,
4201010041329,
4201010041329,
4201010041354,
4201010041354,
4201010042465,
4201010042465,
4201010048543,
4201010048543,
4201010049766,
4201010049766,
4201010050942,
4201010050942
)

--===================================================  7,166
/* Formatted on 10/13/2020 1:47:58 PM (QP5 v5.163.1008.3004)   MY CREATE */
--CREATE OR REPLACE FORCE VIEW APPS.XXKSRM_KOL_CHLN_RCV_PENDING
(
   CHALLAN_NO,
   CHALLAN_DATE,
   BAL,
   ID,
   CHILD_INVENTORY_ITEM_ID
)
AS
   SELECT CHALLAN_NO,
          CHALLAN_DATE,
         CHALLAN_QTY - RECEIPT_QTY BAL,
          NULL ,--TO_CHAR (CUSTOMER_ID) ID,
          NULL --CHILD_INVENTORY_ITEM_ID
     FROM XX_CHALLAN_MO_TEMP
   UNION ALL
   SELECT REQUEST_NUMBER,
          DATE_REQUIRED,
          NVL (PARTY_BALANCE, 0) BAL,
          DEPT_ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KCMD;
     
     --===================================


/* Formatted on 10/13/2020 1:47:58 PM (QP5 v5.163.1008.3004)   MAIN*/
--CREATE OR REPLACE FORCE VIEW APPS.XXKSRM_KOL_CHLN_RCV_PENDING
(
   CHALLAN_NO,
   CHALLAN_DATE,
   BAL,
   ID,
   CHILD_INVENTORY_ITEM_ID
)
AS
   SELECT CHALLAN_NO,
          CHALLAN_DATE,
          NVL (PARTY_BALANCE, 0) BAL,
          TO_CHAR (CUSTOMER_ID) ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KOL_CHALLAN_V
   UNION ALL
   SELECT REQUEST_NUMBER,
          DATE_REQUIRED,
          NVL (PARTY_BALANCE, 0) BAL,
          DEPT_ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KCMD;
     
     
     --=====================================
     
     SELECT * FROM XXKSRM_KOL_CHLN_RCV_PENDING where CHALLAN_NO = '4181010015062'

SELECT * FROM XXKSRM_KOL_CHALLAN_V where CHALLAN_NO = '4181010015062'

select * from MTL_MATERIAL_TRANSACTIONS where attribute3='4181010015062'


select * from MTL_MATERIAL_TRANSACTIONS MMT where MMT.TRANSACTION_ID = 8026864

UPDATE  MTL_MATERIAL_TRANSACTIONS MMT
SET
MMT.ATTRIBUTE4 = 1629802
WHERE 
MMT.TRANSACTION_ID = 8026864


UPDATE  MTL_MATERIAL_TRANSACTIONS MMT
SET
MMT.ATTRIBUTE4 = 1629803
WHERE 
MMT.TRANSACTION_ID = 8026865

/*UPDATE  MTL_MATERIAL_TRANSACTIONS MMT
SET
MMT.ATTRIBUTE4 = 1629802
WHERE 
MMT.TRANSACTION_ID = 8026864

UPDATE  MTL_MATERIAL_TRANSACTIONS MMT
SET
MMT.MOVE_ORDER_LINE_ID = 1629803
WHERE 
MMT.TRANSACTION_ID = 8026865
: 
*/*/


--============================= 24-OCT-2020=============================
/*DOUBLE LINE ASE EMON SOB CHALLAN ER DETAILS QUERY*/
SELECT CHALLAN_NO,LINE_NUMBER, SUM(CHALLAN_QTY),SUM(RECEIPT_QTY), SUM(PARTY_BALANCE) FROM(   
SELECT 
(SELECT SUM (TRANSACTION_QUANTITY)
             FROM MTL_MATERIAL_TRANSACTIONS
            WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)            ---= 42
                  AND ATTRIBUTE3 = WND.NAME
               --   AND MOVE_ORDER_LINE_ID = MTRL.LINE_ID
                  AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' ---- 'KOM Delivery challan'
                 and ATTRIBUTE4= MTRL.LINE_ID 
                  -- and ATTRIBUTE4 is not null
                  AND INVENTORY_ITEM_ID =
                         (SELECT ATTRIBUTE2
                            FROM MTL_SYSTEM_ITEMS_B
                           WHERE INVENTORY_ITEM_ID = WDD.INVENTORY_ITEM_ID
                                 AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
                  AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
             RECEIPT_QTY,
             MTRL.CREATION_DATE, 
             MTRL.QUANTITY_DELIVERED CHALLAN_QTY ,
             WND.NAME CHALLAN_NO,
               (NVL (MTRL.QUANTITY_DELIVERED, 0)
           - NVL (
                ( (SELECT SUM (TRANSACTION_QUANTITY)
                     FROM MTL_MATERIAL_TRANSACTIONS
                    WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)    ---= 42
                          AND ATTRIBUTE3 = WND.NAME
                       --   AND MOVE_ORDER_LINE_ID = MTRL.LINE_ID
                          AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' --- 'KOM Delivery challan'
                  and  ATTRIBUTE4= MTRL.LINE_ID 
                   and ATTRIBUTE4 is not null
                          AND INVENTORY_ITEM_ID =
                                 (SELECT ATTRIBUTE2
                                    FROM MTL_SYSTEM_ITEMS_B
                                   WHERE INVENTORY_ITEM_ID =
                                            WDD.INVENTORY_ITEM_ID
                                         AND ORGANIZATION_ID =
                                                WDD.ORGANIZATION_ID)
                          AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)),
                0))
             PARTY_BALANCE,
MTRL.LINE_NUMBER,
 WND.NAME from  WSH_NEW_DELIVERIES WND ,WSH_DELIVERY_ASSIGNMENTS WDA ,
 MTL_TXN_REQUEST_LINES MTRL, WSH_DELIVERY_DETAILS WDD
 where WDA.DELIVERY_ID= WND.DELIVERY_ID
 and WND.NAME= '4201010050942'  --'4201010048543' -- '4201010048543'
 AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
   AND WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
   AND MTRL.LINE_NUMBER <> 0
   AND WDD.RELEASED_STATUS = 'C'
          AND WDD.ORGANIZATION_ID = 173
       --    AND TRUNC(MTRL.CREATION_DATE) BETWEEN '01-OCT-2020' AND '30-OCT-2020'
          AND WDD.INVENTORY_ITEM_ID IN
                 (66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867))
                GROUP BY CHALLAN_NO,LINE_NUMBER
                ORDER BY LINE_NUMBER
                                   -- HAVING  COUNT(LINE_NUMBER)>1  
                                   
--==============================24-OCT-2020======================================

/*DOUBLE LINE ASE EMON SOB CHALLAN ER QUERY*/
SELECT CHALLAN_NO,COUNT(LINE_NUMBER), SUM(CHALLAN_QTY),SUM(RECEIPT_QTY), SUM(PARTY_BALANCE) FROM(   
SELECT 
(SELECT SUM (TRANSACTION_QUANTITY)
             FROM MTL_MATERIAL_TRANSACTIONS
            WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)            ---= 42
                  AND ATTRIBUTE3 = WND.NAME
               --   AND MOVE_ORDER_LINE_ID = MTRL.LINE_ID
                  AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' ---- 'KOM Delivery challan'
                 and ATTRIBUTE4= MTRL.LINE_ID 
                  -- and ATTRIBUTE4 is not null
                  AND INVENTORY_ITEM_ID =
                         (SELECT ATTRIBUTE2
                            FROM MTL_SYSTEM_ITEMS_B
                           WHERE INVENTORY_ITEM_ID = WDD.INVENTORY_ITEM_ID
                                 AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
                  AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
             RECEIPT_QTY,
             MTRL.CREATION_DATE, 
             MTRL.QUANTITY_DELIVERED CHALLAN_QTY ,
             WND.NAME CHALLAN_NO,
               (NVL (MTRL.QUANTITY_DELIVERED, 0)
           - NVL (
                ( (SELECT SUM (TRANSACTION_QUANTITY)
                     FROM MTL_MATERIAL_TRANSACTIONS
                    WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)    ---= 42
                          AND ATTRIBUTE3 = WND.NAME
                       --   AND MOVE_ORDER_LINE_ID = MTRL.LINE_ID
                          AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' --- 'KOM Delivery challan'
                  and  ATTRIBUTE4= MTRL.LINE_ID 
                   and ATTRIBUTE4 is not null
                          AND INVENTORY_ITEM_ID =
                                 (SELECT ATTRIBUTE2
                                    FROM MTL_SYSTEM_ITEMS_B
                                   WHERE INVENTORY_ITEM_ID =
                                            WDD.INVENTORY_ITEM_ID
                                         AND ORGANIZATION_ID =
                                                WDD.ORGANIZATION_ID)
                          AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)),
                0))
             PARTY_BALANCE,
MTRL.LINE_NUMBER,
 WND.NAME from  WSH_NEW_DELIVERIES WND ,WSH_DELIVERY_ASSIGNMENTS WDA ,
 MTL_TXN_REQUEST_LINES MTRL, WSH_DELIVERY_DETAILS WDD
 where WDA.DELIVERY_ID= WND.DELIVERY_ID
-- and WND.NAME= '4191010002797' --'4201010048543' -- '4201010048543'
 AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
   AND WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
   AND WDD.RELEASED_STATUS = 'C'
          AND WDD.ORGANIZATION_ID = 173
           AND TRUNC(MTRL.CREATION_DATE) BETWEEN '01-OCT-2020' AND '30-OCT-2020'
          AND WDD.INVENTORY_ITEM_ID IN
                 (66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867))
                GROUP BY CHALLAN_NO
                                    HAVING  COUNT(LINE_NUMBER)>1  

--======================================================================









--DROP VIEW APPS.XXKSRM_KOL_CHLN_RCV_PENDING;

/* Formatted on 10/22/2020 12:34:34 PM (QP5 v5.163.1008.3004) */
--CREATE OR REPLACE FORCE VIEW APPS.XXKSRM_KOL_CHLN_RCV_PENDING
(
   CHALLAN_NO,
   CHALLAN_DATE,
   BAL,
   ID,
   CHILD_INVENTORY_ITEM_ID
)
AS
   SELECT CHALLAN_NO,
          CHALLAN_DATE,
          NVL (PARTY_BALANCE, 0) BAL,
          TO_CHAR (CUSTOMER_ID) ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KOL_CHALLAN_V
   UNION ALL
   SELECT REQUEST_NUMBER,
          DATE_REQUIRED,
          NVL (PARTY_BALANCE, 0) BAL,
          DEPT_ID,
          CHILD_INVENTORY_ITEM_ID
     FROM XXKSRM_KCMD;
--=====================APPS.XXKSRM_KOL_CHALLAN_V==============================
--DROP VIEW APPS.XXKSRM_KOL_CHALLAN_V;

/* Formatted on 10/21/2020 1:02:25 PM (QP5 v5.163.1008.3004) */
--CREATE OR REPLACE FORCE VIEW XXKSRM_KOL_CHALLAN_V
(
   DELIVERY_ID,
   CREATED_BY,
   CHALLAN_NO,
   CHALLAN_DATE,
   OD_NUMBER,
   MO_NUMBER,
   MO_LINE_NUMBER,
   MO_LINE_ID,
   FROM_SUBINVENTORY_CODE,
   TO_SUBINVENTORY_CODE,
   UOM_CODE,
   QUANTITY,
   CHALLAN_QTY,
   RECEIPT_QTY,
   PARTY_BALANCE,
   QUANTITY_DETAILED,
   SO_ORDER_NUMBER,
   SO_LINE_NUMBER,
   SO_HEADER_ID,
   SO_LINE_ID,
   INVENTORY_ITEM_ID,
   ITEMCODE,
   REQUESTED_QUANTITY,
   UNIT_PRICE,
   REQUESTED_QUANTITY_UOM,
   ITEM_DESCRIPTION,
   CHILD_INVENTORY_ITEM_ID,
   ORGANIZATION_ID,
   RELEASED_STATUS,
   CUSTOMER_ID
)
AS
   SELECT WND.DELIVERY_ID,
          MTRL.CREATED_BY,
          WND.NAME CHALLAN_NO,
          WND.LAST_UPDATE_DATE CHALLAN_DATE,
          WDD.TRACKING_NUMBER OD_NUMBER,
          MTRH.REQUEST_NUMBER MO_NUMBER,
          MTRL.LINE_NUMBER MO_LINE_NUMBER,
          MTRL.LINE_ID MO_LINE_ID,
          MTRL.FROM_SUBINVENTORY_CODE,
          MTRL.TO_SUBINVENTORY_CODE,
          ---MTRL.LOT_NUMBER,
          MTRL.UOM_CODE,
          MTRL.QUANTITY,
          MTRL.QUANTITY_DELIVERED CHALLAN_QTY,
          (SELECT SUM (TRANSACTION_QUANTITY)
             FROM MTL_MATERIAL_TRANSACTIONS
            WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)            ---= 42
                  AND ATTRIBUTE3 = WND.NAME
               --   AND MOVE_ORDER_LINE_ID = MTRL.LINE_ID
                  AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' ---- 'KOM Delivery challan'
--                   and  ATTRIBUTE4= MTRL.LINE_ID 
--                   and ATTRIBUTE4 is not null
                  AND INVENTORY_ITEM_ID =
                         (SELECT ATTRIBUTE2
                            FROM MTL_SYSTEM_ITEMS_B
                           WHERE INVENTORY_ITEM_ID = WDD.INVENTORY_ITEM_ID
                                 AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
                  AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
             RECEIPT_QTY,
          (NVL (MTRL.QUANTITY_DELIVERED, 0)
           - NVL (
                ( (SELECT SUM (TRANSACTION_QUANTITY)
                     FROM MTL_MATERIAL_TRANSACTIONS
                    WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)    ---= 42
                          AND ATTRIBUTE3 = WND.NAME
                       --   AND MOVE_ORDER_LINE_ID = MTRL.LINE_ID
                          AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' --- 'KOM Delivery challan'
--                   and  ATTRIBUTE4= MTRL.LINE_ID 
--                   and ATTRIBUTE4 is not null
                          AND INVENTORY_ITEM_ID =
                                 (SELECT ATTRIBUTE2
                                    FROM MTL_SYSTEM_ITEMS_B
                                   WHERE INVENTORY_ITEM_ID =
                                            WDD.INVENTORY_ITEM_ID
                                         AND ORGANIZATION_ID =
                                                WDD.ORGANIZATION_ID)
                          AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)),
                0))
             PARTY_BALANCE,
          MTRL.QUANTITY_DETAILED,
          WDD.SOURCE_HEADER_NUMBER SO_ORDER_NUMBER,
          OOLA.LINE_NUMBER SO_LINE_NUMBER,
          WDD.SOURCE_HEADER_ID SO_HEADER_ID,
          WDD.SOURCE_LINE_ID SO_LINE_ID,
          WDD.INVENTORY_ITEM_ID,
          (   MSI.SEGMENT1
           || '|'
           || MSI.SEGMENT2
           || '|'
           || MSI.SEGMENT3
           || '|'
           || MSI.SEGMENT4)
             ITEMCODE,
          WDD.REQUESTED_QUANTITY,
          WDD.UNIT_PRICE,
          WDD.REQUESTED_QUANTITY_UOM,
          MSI.DESCRIPTION ITEM_DESCRIPTION,
          (SELECT ATTRIBUTE2
             FROM MTL_SYSTEM_ITEMS_B
            WHERE INVENTORY_ITEM_ID = WDD.INVENTORY_ITEM_ID
                  AND ORGANIZATION_ID = 0)
             CHILD_INVENTORY_ITEM_ID,
          ---(SELECT INVENTORY_ITEM_ID FROM MTL_SYSTEM_ITEMS_B  WHERE ATTRIBUTE2 = WDD.INVENTORY_ITEM_ID AND ORGANIZATION_ID =WDD.ORGANIZATION_ID )  CHILD_INVENTORY_ITEM_ID,
          WDD.ORGANIZATION_ID,
          WDD.RELEASED_STATUS,
          WDD.CUSTOMER_ID
     FROM MTL_SYSTEM_ITEMS_VL MSI,
          OE_ORDER_LINES_ALL OOLA,
          MTL_TXN_REQUEST_LINES MTRL,
          MTL_TXN_REQUEST_HEADERS MTRH,
          WSH_DELIVERY_DETAILS WDD,
          WSH_DELIVERY_ASSIGNMENTS WDA,
          WSH_NEW_DELIVERIES WND
    WHERE     WDA.DELIVERY_ID = WND.DELIVERY_ID(+)
          AND WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
          AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
          AND MTRL.HEADER_ID = MTRH.HEADER_ID
          AND WDD.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID(+)
          AND WDD.ORGANIZATION_ID = MSI.ORGANIZATION_ID(+)
          AND WDD.SOURCE_LINE_ID = OOLA.LINE_ID
          AND WDD.SOURCE_HEADER_ID = OOLA.HEADER_ID
          AND WDD.RELEASED_STATUS = 'C'
          AND WDD.ORGANIZATION_ID = 173
          AND WDD.INVENTORY_ITEM_ID IN
                 (66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867)               ----IN (76,77,66,102,75,118,448,428);;
--AND WDD.INVENTORY_ITEM_ID IN (75, 77, 102);
--AND WDD.INVENTORY_ITEM_ID IN (66,75,76,77,102,118,774910,787867),
;



     
     SELECT Transaction_id, SUM(TRANSACTION_QUANTITY)
                     FROM MTL_MATERIAL_TRANSACTIONS
                    WHERE    1=1
                --    and  TRANSACTION_TYPE_ID IN (42, 163, 129)    ---= 42
                          --AND ATTRIBUTE3 = WND.NAME
                         -- AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' --- 'KOM Delivery challan'
                         AND INVENTORY_ITEM_ID in( 75,428) --'FILLED OXYGEN CYLINDER (9.8 M3)'
                          and TRANSACTION_ID=8026864
                          group by Transaction_id
                          
                          
                          
                                 (SELECT ATTRIBUTE2
                                    FROM MTL_SYSTEM_ITEMS_B
                                   WHERE INVENTORY_ITEM_ID =
                                            WDD.INVENTORY_ITEM_ID)
                                         AND ORGANIZATION_ID =
                                                WDD.ORGANIZATION_ID)
                        --  AND ORGANIZATION_ID = WDD.ORGANIZATION_ID
                        
                        select * from MTL_SYSTEM_ITEMS_B where DESCRIPTION IN ('EMPTY CYLINDER (9.8 M3)',  'FILLED OXYGEN CYLINDER (9.8 M3)')
                        
                        SELECT * FROM INVFV_MATERIAL_TRANSACTIONS where TRANSACTION_SRC_HDR = '4201010048543'
                        
                        GET_CHALLAN_QTY_FROM_NUMBER
                        
                   select * from MTL_MATERIAL_TRANSACTIONS where TRANSACTION_ID= 8026864


--========================== VIEW MAIN=============================
--DROP VIEW APPS.XXKSRM_KOL_CHALLAN_V;

/* Formatted on 10/13/2020 1:58:04 PM (QP5 v5.163.1008.3004) */
--CREATE OR REPLACE FORCE VIEW APPS.XXKSRM_KOL_CHALLAN_V
(
   DELIVERY_ID,
   CHALLAN_NO,
   CHALLAN_DATE,
   OD_NUMBER,
   MO_NUMBER,
   MO_LINE_NUMBER,
   MO_LINE_ID,
   FROM_SUBINVENTORY_CODE,
   TO_SUBINVENTORY_CODE,
   UOM_CODE,
   QUANTITY,
   CHALLAN_QTY,
   RECEIPT_QTY,
   PARTY_BALANCE,
   QUANTITY_DETAILED,
   SO_ORDER_NUMBER,
   SO_LINE_NUMBER,
   SO_HEADER_ID,
   SO_LINE_ID,
   INVENTORY_ITEM_ID,
   ITEMCODE,
   REQUESTED_QUANTITY,
   UNIT_PRICE,
   REQUESTED_QUANTITY_UOM,
   CREATED_BY,
   ITEM_DESCRIPTION,
   CHILD_INVENTORY_ITEM_ID,
   ORGANIZATION_ID,
   RELEASED_STATUS,
   CUSTOMER_ID
)
AS
   SELECT WND.DELIVERY_ID,
          WND.NAME CHALLAN_NO,
          WND.LAST_UPDATE_DATE CHALLAN_DATE,
          WDD.TRACKING_NUMBER OD_NUMBER,
          MTRH.REQUEST_NUMBER MO_NUMBER,
          MTRL.LINE_NUMBER MO_LINE_NUMBER,
          MTRL.LINE_ID MO_LINE_ID,
          MTRL.FROM_SUBINVENTORY_CODE,
          MTRL.TO_SUBINVENTORY_CODE,
          ---MTRL.LOT_NUMBER,
          MTRL.UOM_CODE,
          MTRL.QUANTITY,
          MTRL.QUANTITY_DELIVERED CHALLAN_QTY,
          (SELECT SUM (TRANSACTION_QUANTITY)
             FROM MTL_MATERIAL_TRANSACTIONS
            WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)            ---= 42
                  AND ATTRIBUTE3 = WND.NAME
                  AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' ---- 'KOM Delivery challan'
                  AND INVENTORY_ITEM_ID =
                         (SELECT ATTRIBUTE2
                            FROM MTL_SYSTEM_ITEMS_B
                           WHERE INVENTORY_ITEM_ID = WDD.INVENTORY_ITEM_ID
                                 AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
                  AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)
             RECEIPT_QTY,
          (NVL (MTRL.QUANTITY_DELIVERED, 0)
           - NVL (
                ( (SELECT SUM (TRANSACTION_QUANTITY)
                     FROM MTL_MATERIAL_TRANSACTIONS
                    WHERE     TRANSACTION_TYPE_ID IN (42, 163, 129)    ---= 42
                          AND ATTRIBUTE3 = WND.NAME
                          AND ATTRIBUTE_CATEGORY = 'Empty Cylinder Receive' --- 'KOM Delivery challan'
                          AND INVENTORY_ITEM_ID =
                                 (SELECT ATTRIBUTE2
                                    FROM MTL_SYSTEM_ITEMS_B
                                   WHERE INVENTORY_ITEM_ID =
                                            WDD.INVENTORY_ITEM_ID
                                         AND ORGANIZATION_ID =
                                                WDD.ORGANIZATION_ID)
                          AND ORGANIZATION_ID = WDD.ORGANIZATION_ID)),
                0))
             PARTY_BALANCE,
          MTRL.QUANTITY_DETAILED,
          WDD.SOURCE_HEADER_NUMBER SO_ORDER_NUMBER,
          OOLA.LINE_NUMBER SO_LINE_NUMBER,
          WDD.SOURCE_HEADER_ID SO_HEADER_ID,
          WDD.SOURCE_LINE_ID SO_LINE_ID,
          WDD.INVENTORY_ITEM_ID,
          (   MSI.SEGMENT1
           || '|'
           || MSI.SEGMENT2
           || '|'
           || MSI.SEGMENT3
           || '|'
           || MSI.SEGMENT4)
             ITEMCODE,
          WDD.REQUESTED_QUANTITY,
          WDD.UNIT_PRICE,
          WDD.REQUESTED_QUANTITY_UOM,
          WDD.CREATED_BY,
          MSI.DESCRIPTION ITEM_DESCRIPTION,
          (SELECT ATTRIBUTE2
             FROM MTL_SYSTEM_ITEMS_B
            WHERE INVENTORY_ITEM_ID = WDD.INVENTORY_ITEM_ID
                  AND ORGANIZATION_ID = 0)
             CHILD_INVENTORY_ITEM_ID,
          ---(SELECT INVENTORY_ITEM_ID FROM MTL_SYSTEM_ITEMS_B  WHERE ATTRIBUTE2 = WDD.INVENTORY_ITEM_ID AND ORGANIZATION_ID =WDD.ORGANIZATION_ID )  CHILD_INVENTORY_ITEM_ID,
          WDD.ORGANIZATION_ID,
          WDD.RELEASED_STATUS,
          WDD.CUSTOMER_ID
     FROM MTL_SYSTEM_ITEMS_VL MSI,
          OE_ORDER_LINES_ALL OOLA,
          MTL_TXN_REQUEST_LINES MTRL,
          MTL_TXN_REQUEST_HEADERS MTRH,
          WSH_DELIVERY_DETAILS WDD,
          WSH_DELIVERY_ASSIGNMENTS WDA,
          WSH_NEW_DELIVERIES WND
    WHERE     WDA.DELIVERY_ID = WND.DELIVERY_ID(+)
          AND WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID
          AND WDD.MOVE_ORDER_LINE_ID = MTRL.LINE_ID
          AND MTRL.HEADER_ID = MTRH.HEADER_ID
          AND WDD.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID(+)
          AND WDD.ORGANIZATION_ID = MSI.ORGANIZATION_ID(+)
          AND WDD.SOURCE_LINE_ID = OOLA.LINE_ID
          AND WDD.SOURCE_HEADER_ID = OOLA.HEADER_ID
          AND WDD.RELEASED_STATUS = 'C'
          AND WDD.ORGANIZATION_ID = 173
          AND WDD.INVENTORY_ITEM_ID IN
                 (66,
                  75,
                  76,
                  77,
                  102,
                  118,
                  386,
                  448,
                  428,
                  23076,
                  23077,
                  23078,
                  23079,
                  774910,
                  774911,
                  787867)               ----IN (76,77,66,102,75,118,448,428);;
--AND WDD.INVENTORY_ITEM_ID IN (75, 77, 102);
--AND WDD.INVENTORY_ITEM_ID IN (66,75,76,77,102,118,774910,787867),
;


--==================================================== FOR PARAMETER======================================

SELECT DISTINCT(INVENTORY_ITEM_ID),ITEM_DESCRIPTION FROM WBI_XXKBGITEM_MT_D WHERE ITEM_DESC LIKE  '%FILLED%CYLINDER%' -- and   ITEM_DESC like   '%EMPTY%CYLINDER%'
650153,
806756,
76,
774910,
118,
787867,
66,
75,
77,
102,
650154,
796567,
796566,
796569,
650152,
796568


SELECT DISTINCT(INVENTORY_ITEM_ID),ITEM_DESCRIPTION FROM WBI_XXKBGITEM_MT_D WHERE ITEM_DESC LIKE  '%EMPTY%CYLINDER%' 

796376,
386,
796563,
21526,
125078,
629,
796489,
787861,
448,
796661,
428,
774911,
796562,
709,
447,
796564,
796565


(select  DISTINCT(ITEM_ID) ,ITEM_CODE ,ITEM_DESC  from WBI_XXKBGITEM_MT_D) X
WHERE ITEM_ID IN (
650153, -- FILLED
806756,
76,
774910,
118,
787867,
66,
75,
77,
102,
650154,
796567,
796566,
796569,
650152,
796568,
796376, -- EMPTY
386,
796563,
21526,
125078,
629,
796489,
787861,
448,
796661,
428,
774911,
796562,
709,
447,
796564,
796565
)
--and ITEM_DESC LIKE  '%EMPTY%CYLINDER%' 
