
SELECT B.ORGANIZATION_CODE, A.* FROM MTL_MATERIAL_TRANSACTIONS A, ORG_ORGANIZATION_DEFINITIONS B
WHERE INVENTORY_ITEM_ID= 180
AND A.ORGANIZATION_ID=152
and TRUNC(Transaction_date) between '01-SEP-2018' and '30-DEC-2020'



select * from ORG_ORGANIZATION_DEFINITIONS 

154=TRN
152=TRM



--- QUERY FOR DIESEL DATA FOR AREFIN VAI (Dayta Provided) -- this is EBS procure to pay query 
--============================================================

SELECT 
distinct aia.org_id,
SUBSTR(XX_GET_HR_OPERATING_UNIT (AIA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (AIA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
 APS.VENDOR_NAME,
 APS.SEGMENT1 VENDOR_NO,
 POH.SEGMENT1 PO_NUMBER,
 POH.APPROVED_DATE  PO_APPROVED_DATE,
   (
 SELECT DESCRIPTION
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_DESCRIPTION,
    (
 SELECT SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_CODE,
 -- XXGET_ITEM_CODE(ITEM_ID) ITEM_CODE,
  POL.QUANTITY* POL.UNIT_PRICE PO_AMOUNT,
RL.QUANTITY_SHIPPED *POL.UNIT_PRICE  GRN_AMOUNT,
--  (
--  SELECT SUM ( (PLA.UNIT_PRICE * PLA.QUANTITY)) PRICE
--   FROM PO_LINES_ALL PLA, PO_HEADERS_ALL PHA
--   WHERE PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
--   AND PHA.ORG_ID = AIA.ORG_ID
--   AND PHA.SEGMENT1 =POH.SEGMENT1
--         ) PO_AMOUNT,
 RSH.RECEIPT_NUM GRN_NUMBER, 
RT.CREATION_DATE GRN_DATE,
--RL.QUANTITY_RECEIVED,
--RT.QUANTITY QUANTITY_DELIVERED,
 AIA.INVOICE_NUM,
 AIA.INVOICE_DATE,
AIA.GL_DATE ,
AIA.INVOICE_AMOUNT, 
 AIA.DOC_SEQUENCE_VALUE INV_VOUCHER_NO,
 XX_GET_EMP_NAME_FROM_USER_ID (AIA.CREATED_BY) INV_CREATED_BY,
 ( SELECT CONCATENATED_SEGMENTS
 FROM GL_CODE_COMBINATIONS_KFV
 WHERE CODE_COMBINATION_ID = AIDA.DIST_CODE_COMBINATION_ID
 ) DIST_GL_CODE,
ACA.DOC_SEQUENCE_VALUE PAYMENT_VOUCHER,
ACA.CREATION_DATE PAY_CREATE_DATE
,ACA.DOC_CATEGORY_CODE PAYMENT_TYPE
,ACA.STATUS_LOOKUP_CODE PAYMENT_STATUS
,ACA.AMOUNT PAY_AMOUNT
,XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
FROM AP_INVOICES_ALL AIA,
 AP_INVOICE_LINES_ALL AILA,
 AP_SUPPLIERS APS,
 AP_SUPPLIER_SITES_ALL APSS,
 AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
 PO_HEADERS_ALL POH,
 PO_LINES_ALL POL,
 PO_LINE_LOCATIONS_ALL PLL,
 PO_DISTRIBUTIONS_ALL PDA,
 RCV_SHIPMENT_HEADERS RSH,
 RCV_SHIPMENT_LINES RL,
  RCV_TRANSACTIONS RT,
AP_INVOICE_PAYMENTS_ALL AIPA, 
AP_CHECKS_ALL ACA
WHERE AIA.INVOICE_ID = AILA.INVOICE_ID
AND AILA.ORG_ID = AIA.ORG_ID
AND AILA.PO_HEADER_ID = POH.PO_HEADER_ID
AND AILA.PO_LINE_ID = POL.PO_LINE_ID
AND AILA.INVOICE_ID =AIDA.INVOICE_ID
AND AIA.VENDOR_ID = APS.VENDOR_ID
AND AIA.VENDOR_SITE_ID = APSS.VENDOR_SITE_ID
AND AIA.VENDOR_ID = APSS.VENDOR_ID
AND APSS.ORG_ID = AIA.ORG_ID
AND AIDA.INVOICE_LINE_NUMBER = AILA.LINE_NUMBER
AND AIDA.ORG_ID= AILA.ORG_ID
AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND PLL.PO_HEADER_ID = POH.PO_HEADER_ID
AND PLL.PO_LINE_ID = POL.PO_LINE_ID
AND PLL.LINE_LOCATION_ID = PDA.LINE_LOCATION_ID
AND PLL.PO_HEADER_ID = PDA.PO_HEADER_ID
AND PLL.PO_LINE_ID = PDA.PO_LINE_ID
AND POL.ORG_ID = PDA.ORG_ID
AND POH.ORG_ID = PLL.ORG_ID
AND AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
AND RT.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
AND RSH.SHIPMENT_HEADER_ID =RL.SHIPMENT_HEADER_ID 
AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
AND AIA.INVOICE_ID=AIPA.INVOICE_ID(+)
AND AIPA.CHECK_ID=ACA.CHECK_ID(+)
AND PDA.GL_CANCELLED_DATE is NULL
AND (:P_ORG_ID IS NULL OR AIA.ORG_ID = :P_ORG_ID) --AP org id
--AND (:P_VENDOR_NO IS NULL OR aps.segment1 = :P_VENDOR_NO) --aps.segment1 for supplier/vendor name
AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
AND (:P_PO_NO IS NULL OR poh.segment1 = :P_PO_NO) 
AND (:P_GRN_NO IS NULL OR rsh.receipt_num = :P_GRN_NO)
and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
 and AIA.VENDOR_ID = NVL(:P_VENDOR_ID, AIA.VENDOR_ID)
  AND    (SELECT SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) LIKE '%FL|F%LB|DSEL|000066%'
union all
SELECT 
distinct PHA.org_id,
SUBSTR(XX_GET_HR_OPERATING_UNIT (PHA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (PHA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
       ASP.VENDOR_NAME,
       ASP.SEGMENT1 VENDOR_NO,
      PHA.SEGMENT1 PO_NUMBER,
       PHA.APPROVED_DATE  PO_APPROVED_DATE,
           PLA.ITEM_DESCRIPTION,
            XXGET_ITEM_CODE(PLA.ITEM_ID) ITEM_CODE,
     (PLA.UNIT_PRICE* PLA.QUANTITY) PO_AMOUNT,
     RL.QUANTITY_SHIPPED *PLA.UNIT_PRICE  GRN_AMOUNT,
          RH.RECEIPT_NUM GRN_NUMBER, 
          RT.CREATION_DATE GRN_DATE,
--          RL.QUANTITY_RECEIVED,
--         RT.QUANTITY QUANTITY_DELIVERED,
            NULL INVOICE_NUM,
            NULL INVOICE_DATE,
            NULL GL_DATE,
            NULL INVOICE_AMOUNT,
            NULL INV_VOUCHER_NO,
            NULL INV_CREATED_BY,
          NULL DIST_GL_CODE,
          NULL PAYMENT_VOUCHER,
          NULL PAY_CREATE_DATE,
          NULL PAYMENT_TYPE,
          NULL PAYMENT_STATUS,
          NULL PAY_AMOUNT,
         XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
 from PO_HEADERS_ALL PHA, PO_LINES_ALL PLA, PO_LINE_LOCATIONS_ALL PLL,PO_DISTRIBUTIONS_ALL PDA, AP_SUPPLIERS ASP,
 RCV_TRANSACTIONS RT,RCV_SHIPMENT_LINES RL, RCV_SHIPMENT_HEADERS RH
 WHERE PHA.PO_HEADER_ID =PLA.PO_HEADER_ID
 and PHA.po_header_id = PLA.po_header_id
 and PLA.po_line_id= pll.po_line_id
 and PHA.po_header_id= pll.po_header_id
 and PHA.PO_HEADER_ID= PLA.PO_HEADER_ID
 AND PLA.PO_LINE_ID= PDA.PO_LINE_ID
 AND PLA.QUANTITY <> 0
 AND PHA.PO_HEADER_ID= RT.PO_HEADER_ID
 AND PLA.PO_LINE_ID= RT.PO_LINE_ID
 AND PDA.GL_CANCELLED_DATE is NULL
 AND RT.TRANSACTION_TYPE= 'DELIVER'
    AND PDA.PO_DISTRIBUTION_ID NOT IN
      (SELECT PO_DISTRIBUTION_ID FROM PO_DISTRIBUTIONS_ALL PDA
       WHERE PO_DISTRIBUTION_ID IN (SELECT DISTINCT  PO_DISTRIBUTION_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL))
 AND RH.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID
 AND RH.SHIPMENT_HEADER_ID= RL.SHIPMENT_HEADER_ID
 AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
 AND ASP.VENDOR_ID= PHA.VENDOR_ID
   AND (:P_ORG_ID IS NULL OR PHA.ORG_ID = :P_ORG_ID)
  AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
  AND (:P_PO_NO IS NULL OR PHA.segment1 = :P_PO_NO) 
  AND (:P_GRN_NO IS NULL OR rh.receipt_num = :P_GRN_NO) 
  and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
   and PHA.VENDOR_ID = NVL(:P_VENDOR_ID, PHA.VENDOR_ID)
   AND XXGET_ITEM_CODE(PLA.ITEM_ID)  LIKE '%FL|F%LB|DSEL|000066%'
   
   
  --=======================================



--OPENING BALANCE : LC LEDGER REPORT

select * from AP_INVOICE_DISTRIBUTIONS_ALL

select * from ap_invoices_all

select* from FND_FLEX_VALUES_VL

select * from HR_OPERATING_UNITS

select * from GL_PERIOD_STATUSES where application_id= 101

select * from GL_CODE_COMBINATIONS order by SEGMENT4


select * from HR_OPERATING_UNITS

--LEGAL_ENTITY: XX_OU_FROM_SET_OF_BOOK
HR_OPERATING_UNITS
 
--PERIOD_NAME : XXX_PERIOD_NAME
(SELECT DISTINCT(SET_OF_BOOKS_ID),PERIOD_NAME FROM GL_PERIOD_STATUSES WHERE PERIOD_NAME NOT LIKE '%Adj%') A 


SELECT DISTINCT PERIOD_NAME FROM GL_PERIOD_STATUSES WHERE PERIOD_NAME NOT LIKE '%Adj%'   --and PERIOD_NAME = 'Oct-18'

-- ACCOUNT_CODE: XX_NATURAL_ACCOUNT
SELECT DISTINCT SEGMENT4 ACCOUNT_CODE,XX_GET_ACCT_FLEX_SEG_DESC (4, SEGMENT4)||'-'||SEGMENT4 ACCOUNT_NAME FROM GL_CODE_COMBINATIONS

-- LC_NUMBER: XX_LC_NUMBER_SET



 select * from XX_LC_DETAILS where LC_NUMBER='2083-18-01-0042'
 
 select DISTINCT(SEGMENT4), SEGMENT1,CODE_COMBINATION_ID from GL_CODE_COMBINATIONS where SEGMENT4 = 2010201 order by SEGMENT1
 
 
 SELECT * FROM GL_CODE_COMBINATIONS
 
-- 20-JUL-2020  
---> CHARGE TYPE IS ADDED IN  AP PART


--=============================================================26-JUL-2020 V4 FOR REPORT===================================================

SELECT SUM(ACCOUNTED_DR), SUM(ACCOUNTED_CR)
FROM(
SELECT
POH.ORG_ID,
 GET_OU_NAME_FROM_ID(POH.ORG_ID),
AH.PERIOD_NAME,
  AI.INVOICE_ID,
  AI.INVOICE_NUM,
--  ACCOUNTING_DATE  GL_DATE ,
   TO_CHAR(TRUNC(AL.ACCOUNTING_DATE),'DD-MON-RRRR') GL_DATE,
  NULL VOUCHAR_NUMBER,
  POH.PO_HEADER_ID,
  POH.SEGMENT1 PO_NUMBER,
  LC.LC_ID,
   LC.LC_NUMBER,
    RT.TRANSACTION_ID,  
    GET_GRN_FROM_TRANSACTION_ID(RT.TRANSACTION_ID) GRN_NUMBER,
    GMFV.CHARGE_LINE_TYPE_CODE CHARGE_LINE__FOR_TESTING,
        DECODE(GMFV.CHARGE_LINE_TYPE_CODE,NULL,'ERV',GMFV.CHARGE_LINE_TYPE_CODE) CHARGE_LINE_TYPE_CODE,
    GMFV.COMPONENT_NAME, 
GXEH.EVENT_ID,
AL.AE_HEADER_ID, 
AL.AE_LINE_NUM,
  AL.CODE_COMBINATION_ID,
   (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  AH.DESCRIPTION,
  NVL(ENTERED_DR,0) ENTERED_DR,
  NVL(ENTERED_CR,0) ENTERED_CR,
  NVL(ACCOUNTED_DR,0) ACCOUNTED_DR,
  NVL(ACCOUNTED_CR,0) ACCOUNTED_CR, 
  AH.EVENT_TYPE_CODE
 FROM XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS COM , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, AP_INVOICES_ALL AI -- , MTL_MATERIAL_TRANSACTIONS MMT
WHERE AL.CODE_COMBINATION_ID=COM.CODE_COMBINATION_ID
AND AH.AE_HEADER_ID = AL.AE_HEADER_ID
AND GXEH.EVENT_ID(+)= AH.EVENT_ID
AND RT.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND RT.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
AND AI.PO_HEADER_ID(+) = POH.PO_HEADER_ID
AND POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
AND POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
AND GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
AND POH.PO_HEADER_ID IS NOT NULL
--AND AH.LEDGER_ID =NVL(:P_LEGAL_ENTITY,  AH.LEDGER_ID ) 
AND POH.ORG_ID = NVL(:P_OPERATING_UNIT,POH.ORG_ID)
--AND COM.CODE_COMBINATION_ID =NVL(:P_ACCOUNT_CODE,COM.CODE_COMBINATION_ID )
--AND COM.SEGMENT4 =NVL(:P_ACCOUNT_CODE,COM.SEGMENT4 )
-- and COM.SEGMENT4 = 2010201
--and com.CODE_COMBINATION_ID IN (652553,14026)
and com.CODE_COMBINATION_ID IN (
652553,
14026,
15569,
15572,
14014,
652554,
642555,
14011,
14017,
1085887,
14022,
15575,
14020)
--AND  LC.LC_ID = NVL(:P_LC_NUMBER, LC.LC_ID)  
AND AH.PERIOD_NAME =NVL(:P_PERIOD_NAME,AH.PERIOD_NAME) 
AND  NVL(LC.LC_ID,0)= NVL(:P_LC_NUMBER,NVL(LC.LC_ID,0))
AND  POH.SEGMENT1 = NVL(:P_PO_NUMBER, POH.SEGMENT1)
UNION ALL
 SELECT
 AI.ORG_ID,
 GET_OU_NAME_FROM_ID(AI.ORG_ID),
 AD.PERIOD_NAME,
         AI.INVOICE_ID, 
                   AI.INVOICE_NUM,
                   TO_CHAR(TRUNC(AI.GL_DATE),'DD-MON-RRRR') GL_DATE,
                   AI.DOC_SEQUENCE_VALUE VOUCHAR_NUMBER,
                             LCD.PO_HEADER_ID,
                               LCD.PO_NUMBER,
                                 LCD.LC_ID,
                                         LCD.LC_NUMBER,
                                         AD.RCV_TRANSACTION_ID TRANSACTION_ID,
                                          GET_GRN_FROM_TRANSACTION_ID( AD.RCV_TRANSACTION_ID) GRN,
                                          NVL(PPET.DESCRIPTION, AD.LINE_TYPE_LOOKUP_CODE)  CHARGE_LINE__FOR_TESTING,
                                         NVL(PPET.DESCRIPTION, AD.LINE_TYPE_LOOKUP_CODE)  CHARGE_LINE_TYPE_CODE,
                                         NULL COMPONENT_NAME,
                                         NULL EVENT_ID,
                                         NULL AE_HEADER_ID,
                                         NULL AE_LINE_NUM,
                                         AD.DIST_CODE_COMBINATION_ID CODE_COMBINATION_ID,
                                            (GET_GL_CODE_DESC_FROM_CCID ( AD.DIST_CODE_COMBINATION_ID)) CODE_COMBINATION,
                                              NULL DESCRIPTION,
                                            DECODE(NULL, NULL,0,0) ENTERED_DR,
                                            DECODE(NULL, NULL,0,0) ENTERED_CR,
                                           -- NULL ENTERED_DR, 
                                            --NULL ENTERED_CR,                                           
          GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0) ACCOUNTED_DR,
          (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))) ACCOUNTED_CR,
          NULL EVENT_TYPE_CODE
    FROM AP_INVOICES_ALL AI,
          AP_INVOICE_DISTRIBUTIONS_ALL AD,
          GL_CODE_COMBINATIONS GC,
          AP_INVOICE_LINES_ALL AIL,
          PON_PRICE_ELEMENT_TYPES_TL PPET,
          XX_LC_DETAILS LCD
    WHERE     AI.INVOICE_ID = AD.INVOICE_ID
          AND AD.DIST_CODE_COMBINATION_ID = GC.CODE_COMBINATION_ID
          AND AD.LINE_TYPE_LOOKUP_CODE NOT IN ('PREPAY')
          AND AIL.INVOICE_ID = AD.INVOICE_ID
          AND AIL.COST_FACTOR_ID=PPET.PRICE_ELEMENT_TYPE_ID (+)
          AND AIL.LINE_NUMBER = AD.INVOICE_LINE_NUMBER
      --   AND AI.CANCELLED_DATE IS  NULL
       -- AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
          AND NVL (AD.BASE_AMOUNT, AD.AMOUNT) <> 0
          AND XX_GET_INVOICE_STATUS (AI.INVOICE_ID) NOT IN
                 ('Needs Revalidation', 'Never Validated', 'Unpaid')
          AND AIL.PO_HEADER_ID = LCD.PO_HEADER_ID(+)
          AND AI.ORG_ID = LCD.ORG_ID(+)
       --   AND LCD.LC_ID IS NOT NULL
          AND (AD.ATTRIBUTE_CATEGORY IS NULL
               OR AD.ATTRIBUTE_CATEGORY <> 'LC Details')
             -- AND AD.SET_OF_BOOKS_ID =NVL(:P_LEGAL_ENTITY, AD.SET_OF_BOOKS_ID) 
              and AI.ORG_ID   =NVL(:P_OPERATING_UNIT,AI.ORG_ID)
             -- AND AD.DIST_CODE_COMBINATION_ID =NVL(:P_ACCOUNT_CODE, AD.DIST_CODE_COMBINATION_ID) 
           --  AND GC.SEGMENT4 =NVL(:P_ACCOUNT_CODE,GC.SEGMENT4 )
           --and GC.SEGMENT4 = 2010201
 and ad.DIST_CODE_COMBINATION_ID  IN(652553,
14026,
15569,
15572,
14014,
652554,
642555,
14011,
14017,
1085887,
14022,
15575,
14020 )
            AND AD.PERIOD_NAME =NVL(:P_PERIOD_NAME,AD.PERIOD_NAME) 
             AND  NVL(LCD.LC_ID,0)= NVL(:P_LC_NUMBER,NVL(LCD.LC_ID,0))
             AND NVL(LCD.PO_HEADER_ID,0)= NVL(:P_PO_NUMBER, NVL(LCD.PO_HEADER_ID,0)))
            -- and AI.INVOICE_ID=1422705 --1422705 --1050345 --1053023 --1050345  
             --and ai.org_id=81
--==========================================23-JUL-2020  FINAL V3=====================================================================

SELECT  SUM(ACCOUNTED_DR), SUM(ACCOUNTED_CR)
FROM(
SELECT
POH.ORG_ID,
 GET_OU_NAME_FROM_ID(POH.ORG_ID),
AH.PERIOD_NAME,
  AI.INVOICE_ID,
  AI.INVOICE_NUM,
  NULL VOUCHAR_NUMBER,
  POH.PO_HEADER_ID,
  POH.SEGMENT1 PO_NUMBER,
  LC.LC_ID,
   LC.LC_NUMBER,
    RT.TRANSACTION_ID,  
    GET_GRN_FROM_TRANSACTION_ID(RT.TRANSACTION_ID) GRN_NUMBER,
    GMFV.CHARGE_LINE_TYPE_CODE CHARGE_LINE__FOR_TESTING,
        DECODE(GMFV.CHARGE_LINE_TYPE_CODE,NULL,'ERV',GMFV.CHARGE_LINE_TYPE_CODE) CHARGE_LINE_TYPE_CODE,
    GMFV.COMPONENT_NAME, 
GXEH.EVENT_ID,
AL.AE_HEADER_ID, 
AL.AE_LINE_NUM,
  AL.CODE_COMBINATION_ID,
   (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  AH.DESCRIPTION,
  NVL(ENTERED_DR,0) ENTERED_DR,
  NVL(ENTERED_CR,0) ENTERED_CR,
  NVL(ACCOUNTED_DR,0) ACCOUNTED_DR,
  NVL(ACCOUNTED_CR,0) ACCOUNTED_CR, 
  AH.EVENT_TYPE_CODE
 FROM XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS COM , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, AP_INVOICES_ALL AI -- , MTL_MATERIAL_TRANSACTIONS MMT
WHERE AL.CODE_COMBINATION_ID=COM.CODE_COMBINATION_ID
AND AH.AE_HEADER_ID = AL.AE_HEADER_ID
AND GXEH.EVENT_ID(+)= AH.EVENT_ID
AND RT.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND RT.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
AND AI.PO_HEADER_ID(+) = POH.PO_HEADER_ID
AND POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
AND POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
AND GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
AND AH.PERIOD_NAME =NVL(:P_PERIOD_NAME,AH.PERIOD_NAME) 
AND POH.PO_HEADER_ID IS NOT NULL
--AND AH.LEDGER_ID =NVL(:P_LEGAL_ENTITY,  AH.LEDGER_ID ) 
AND POH.ORG_ID = NVL(:P_OPERATING_UNIT,POH.ORG_ID)
--AND COM.CODE_COMBINATION_ID =NVL(:P_ACCOUNT_CODE,COM.CODE_COMBINATION_ID )
--AND COM.SEGMENT4 =NVL(:P_ACCOUNT_CODE,COM.SEGMENT4 )
-- and COM.SEGMENT4 = 2010201
--and com.CODE_COMBINATION_ID IN (652553,14026)
and com.CODE_COMBINATION_ID IN (
652553,
14026,
15569,
15572,
14014,
652554,
642555,
14011,
14017,
1085887,
14022,
15575,
14020)
AND  LC.LC_ID = NVL(:P_LC_NUMBER, LC.LC_ID)  
AND  POH.SEGMENT1 = NVL(:P_PO_NUMBER, POH.SEGMENT1)
UNION ALL
 SELECT
 LCD.ORG_ID,
 GET_OU_NAME_FROM_ID(LCD.ORG_ID),
 AD.PERIOD_NAME,
         AI.INVOICE_ID, 
                   AI.INVOICE_NUM,
                   AI.DOC_SEQUENCE_VALUE VOUCHAR_NUMBER,
                             LCD.PO_HEADER_ID,
                               LCD.PO_NUMBER,
                                 LCD.LC_ID,
                                         LCD.LC_NUMBER,
                                         AD.RCV_TRANSACTION_ID TRANSACTION_ID,
                                          GET_GRN_FROM_TRANSACTION_ID( AD.RCV_TRANSACTION_ID) GRN,
                                          NVL(PPET.DESCRIPTION, AD.LINE_TYPE_LOOKUP_CODE)  CHARGE_LINE__FOR_TESTING,
                                         NVL(PPET.DESCRIPTION, AD.LINE_TYPE_LOOKUP_CODE)  CHARGE_LINE_TYPE_CODE,
                                         NULL COMPONENT_NAME,
                                         NULL EVENT_ID,
                                         NULL AE_HEADER_ID,
                                         NULL AE_LINE_NUM,
                                         AD.DIST_CODE_COMBINATION_ID CODE_COMBINATION_ID,
                                            (GET_GL_CODE_DESC_FROM_CCID ( AD.DIST_CODE_COMBINATION_ID)) CODE_COMBINATION,
                                              NULL DESCRIPTION,
                                            DECODE(NULL, NULL,0,0) ENTERED_DR,
                                            DECODE(NULL, NULL,0,0) ENTERED_CR,
                                           -- NULL ENTERED_DR, 
                                            --NULL ENTERED_CR,                                           
          GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0) ACCOUNTED_DR,
          (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))) ACCOUNTED_CR,
          NULL EVENT_TYPE_CODE
    FROM AP_INVOICES_ALL AI,
          AP_INVOICE_DISTRIBUTIONS_ALL AD,
          GL_CODE_COMBINATIONS GC,
          AP_INVOICE_LINES_ALL AIL,
          PON_PRICE_ELEMENT_TYPES_TL PPET,
          XX_LC_DETAILS LCD
    WHERE     AI.INVOICE_ID = AD.INVOICE_ID
          AND AD.DIST_CODE_COMBINATION_ID = GC.CODE_COMBINATION_ID
          AND AD.LINE_TYPE_LOOKUP_CODE NOT IN ('PREPAY')
          AND AIL.INVOICE_ID = AD.INVOICE_ID
          AND AIL.COST_FACTOR_ID=PPET.PRICE_ELEMENT_TYPE_ID (+)
          AND AIL.LINE_NUMBER = AD.INVOICE_LINE_NUMBER
         AND AI.CANCELLED_DATE IS  NULL
       -- AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
          AND NVL (AD.BASE_AMOUNT, AD.AMOUNT) <> 0
          AND XX_GET_INVOICE_STATUS (AI.INVOICE_ID) NOT IN
                 ('Needs Revalidation', 'Never Validated', 'Unpaid')
          AND AIL.PO_HEADER_ID = LCD.PO_HEADER_ID
          AND AI.ORG_ID = LCD.ORG_ID
          AND LCD.LC_ID IS NOT NULL
          AND (AD.ATTRIBUTE_CATEGORY IS NULL
               OR AD.ATTRIBUTE_CATEGORY <> 'LC Details')
             -- AND AD.SET_OF_BOOKS_ID =NVL(:P_LEGAL_ENTITY, AD.SET_OF_BOOKS_ID) 
              and LCD.ORG_ID   =NVL(:P_OPERATING_UNIT,LCD.ORG_ID)
             -- AND AD.DIST_CODE_COMBINATION_ID =NVL(:P_ACCOUNT_CODE, AD.DIST_CODE_COMBINATION_ID) 
           --  AND GC.SEGMENT4 =NVL(:P_ACCOUNT_CODE,GC.SEGMENT4 )
           --and GC.SEGMENT4 = 2010201
 and ad.DIST_CODE_COMBINATION_ID  IN(652553,
14026,
15569,
15572,
14014,
652554,
642555,
14011,
14017,
1085887,
14022,
15575,
14020 )
              AND AD.PERIOD_NAME =NVL(:P_PERIOD_NAME,AD.PERIOD_NAME) 
              AND  LCD.LC_ID= NVL(:P_LC_NUMBER, LCD.LC_ID)
              AND LCD.PO_HEADER_ID= NVL(:P_PO_NUMBER,LCD.PO_HEADER_ID))
            -- and AI.INVOICE_ID= 1384899


--==========================================22-JUL-2020  FINAL V2=====================================================================
181616.56    175582.74

SELECT SUM(ACCOUNTED_DR), SUM(ACCOUNTED_CR)
FROM(
SELECT
POH.ORG_ID,
 GET_OU_NAME_FROM_ID(POH.ORG_ID),
AH.PERIOD_NAME,
  AI.INVOICE_ID,
  AI.INVOICE_NUM,
  NULL VOUCHAR_NUMBER,
  POH.PO_HEADER_ID,
  POH.SEGMENT1 PO_NUMBER,
  LC.LC_ID,
   LC.LC_NUMBER,
    RT.TRANSACTION_ID,  
    GET_GRN_FROM_TRANSACTION_ID(RT.TRANSACTION_ID) GRN_NUMBER,
    GMFV.CHARGE_LINE_TYPE_CODE CHARGE_LINE__FOR_TESTING,
        DECODE(GMFV.CHARGE_LINE_TYPE_CODE,NULL,'ERV',GMFV.CHARGE_LINE_TYPE_CODE) CHARGE_LINE_TYPE_CODE,
    GMFV.COMPONENT_NAME, 
GXEH.EVENT_ID,
AL.AE_HEADER_ID, 
AL.AE_LINE_NUM,
  AL.CODE_COMBINATION_ID,
   (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  AH.DESCRIPTION,
  NVL(ENTERED_DR,0) ENTERED_DR,
  NVL(ENTERED_CR,0) ENTERED_CR,
  NVL(ACCOUNTED_DR,0) ACCOUNTED_DR,
  NVL(ACCOUNTED_CR,0) ACCOUNTED_CR, 
  AH.EVENT_TYPE_CODE
 FROM XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS COM , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, AP_INVOICES_ALL AI -- , MTL_MATERIAL_TRANSACTIONS MMT
WHERE AL.CODE_COMBINATION_ID=COM.CODE_COMBINATION_ID
AND AH.AE_HEADER_ID = AL.AE_HEADER_ID
AND GXEH.EVENT_ID(+)= AH.EVENT_ID
AND RT.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND RT.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
AND AI.PO_HEADER_ID(+) = POH.PO_HEADER_ID
AND POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
AND POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
AND GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
AND AH.PERIOD_NAME =NVL(:P_PERIOD_NAME,AH.PERIOD_NAME) 
AND POH.PO_HEADER_ID IS NOT NULL
--AND AH.LEDGER_ID =NVL(:P_LEGAL_ENTITY,  AH.LEDGER_ID ) 
AND POH.ORG_ID = NVL(:P_OPERATING_UNIT,POH.ORG_ID)
--AND COM.CODE_COMBINATION_ID =NVL(:P_ACCOUNT_CODE,COM.CODE_COMBINATION_ID )
--AND COM.SEGMENT4 =NVL(:P_ACCOUNT_CODE,COM.SEGMENT4 )
and com.CODE_COMBINATION_ID =14026
--and  (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID))='2010201 - L/C in Transit'
AND  LC.LC_ID = NVL(:P_LC_NUMBER, LC.LC_ID)  
AND  POH.SEGMENT1 = NVL(:P_PO_NUMBER, POH.SEGMENT1)
UNION ALL
 SELECT
 LCD.ORG_ID,
 GET_OU_NAME_FROM_ID(LCD.ORG_ID),
 AD.PERIOD_NAME,
         AI.INVOICE_ID, 
                   AI.INVOICE_NUM,
                   AI.DOC_SEQUENCE_VALUE VOUCHAR_NUMBER,
                             LCD.PO_HEADER_ID,
                               LCD.PO_NUMBER,
                                 LCD.LC_ID,
                                         LCD.LC_NUMBER,
                                         AD.RCV_TRANSACTION_ID TRANSACTION_ID,
                                          GET_GRN_FROM_TRANSACTION_ID( AD.RCV_TRANSACTION_ID) GRN,
                                          NVL(PPET.DESCRIPTION, AD.LINE_TYPE_LOOKUP_CODE)  CHARGE_LINE__FOR_TESTING,
                                         NVL(PPET.DESCRIPTION, AD.LINE_TYPE_LOOKUP_CODE)  CHARGE_LINE_TYPE_CODE,
                                         NULL COMPONENT_NAME,
                                         NULL EVENT_ID,
                                         NULL AE_HEADER_ID,
                                         NULL AE_LINE_NUM,
                                         AD.DIST_CODE_COMBINATION_ID CODE_COMBINATION_ID,
                                            (GET_GL_CODE_DESC_FROM_CCID ( AD.DIST_CODE_COMBINATION_ID)) CODE_COMBINATION,
                                              NULL DESCRIPTION,
                                            DECODE(NULL, NULL,0,0) ENTERED_DR,
                                            DECODE(NULL, NULL,0,0) ENTERED_CR,
                                           -- NULL ENTERED_DR, 
                                            --NULL ENTERED_CR,                                           
          GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0) ACCOUNTED_DR,
          (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))) ACCOUNTED_CR,
          NULL EVENT_TYPE_CODE
    FROM AP_INVOICES_ALL AI,
          AP_INVOICE_DISTRIBUTIONS_ALL AD,
          GL_CODE_COMBINATIONS GC,
          AP_INVOICE_LINES_ALL AIL,
          PON_PRICE_ELEMENT_TYPES_TL PPET,
          XX_LC_DETAILS LCD
    WHERE     AI.INVOICE_ID = AD.INVOICE_ID
          AND AD.DIST_CODE_COMBINATION_ID = GC.CODE_COMBINATION_ID
          AND AD.LINE_TYPE_LOOKUP_CODE NOT IN ('PREPAY')
          AND AIL.INVOICE_ID = AD.INVOICE_ID
          AND AIL.COST_FACTOR_ID=PPET.PRICE_ELEMENT_TYPE_ID (+)
          AND AIL.LINE_NUMBER = AD.INVOICE_LINE_NUMBER
         --AND AI.CANCELLED_DATE IS  NULL
       -- AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
          AND NVL (AD.BASE_AMOUNT, AD.AMOUNT) <> 0
          AND XX_GET_INVOICE_STATUS (AI.INVOICE_ID) NOT IN
                 ('Needs Revalidation', 'Never Validated', 'Unpaid')
          AND AIL.PO_HEADER_ID = LCD.PO_HEADER_ID
          AND AI.ORG_ID = LCD.ORG_ID
          AND LCD.LC_ID IS NOT NULL
          AND (AD.ATTRIBUTE_CATEGORY IS NULL
               OR AD.ATTRIBUTE_CATEGORY <> 'LC Details')
             -- AND AD.SET_OF_BOOKS_ID =NVL(:P_LEGAL_ENTITY, AD.SET_OF_BOOKS_ID) 
              and LCD.ORG_ID   =NVL(:P_OPERATING_UNIT,LCD.ORG_ID)
             -- AND AD.DIST_CODE_COMBINATION_ID =NVL(:P_ACCOUNT_CODE, AD.DIST_CODE_COMBINATION_ID) 
           --  AND GC.SEGMENT4 =NVL(:P_ACCOUNT_CODE,GC.SEGMENT4 )
            and ad.DIST_CODE_COMBINATION_ID = 14026 
          --  and   (GET_GL_CODE_DESC_FROM_CCID ( AD.DIST_CODE_COMBINATION_ID))='2010201 - L/C in Transit'
              AND AD.PERIOD_NAME =NVL(:P_PERIOD_NAME,AD.PERIOD_NAME) 
              AND  LCD.LC_ID= NVL(:P_LC_NUMBER, LCD.LC_ID)
              AND LCD.PO_HEADER_ID= NVL(:P_PO_NUMBER,LCD.PO_HEADER_ID))
            -- and AI.INVOICE_ID= 1384899

--=================================================14-JUL-2020  FINAL V1================================================
 -- PON_PRICE_ELEMENT_TYPES_TL
SELECT SUM(ACCOUNTED_DR), SUM(ACCOUNTED_CR)
FROM(
 SELECT
  AI.INVOICE_ID,
  AI.INVOICE_NUM,
  POH.SEGMENT1 PO_NUMBER,
   LC.LC_NUMBER,
    RT.TRANSACTION_ID,     -- rh.RECEIPT_NUM GRN_NUMBER,
    GET_GRN_FROM_TRANSACTION_ID(RT.TRANSACTION_ID) GRN_NUMBER,
  --  rt.TRANSACTION_ID,
    GMFV.CHARGE_LINE_TYPE_CODE,
    GMFV.COMPONENT_NAME, 
    --GMFV.TRANSACTION_ID,
GXEH.EVENT_ID,
AL.AE_HEADER_ID, 
AL.AE_LINE_NUM,
  AL.CODE_COMBINATION_ID,
   (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  ah.DESCRIPTION,
  ENTERED_DR,
  ENTERED_CR,
  ACCOUNTED_DR,
  ACCOUNTED_CR, 
  AH.EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, ap_invoices_all AI -- , MTL_MATERIAL_TRANSACTIONS MMT
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID
and GXEH.EVENT_ID(+)= AH.EVENT_ID
and rt.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND rt.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
--and al.RCV_TRANSACTION_ID = rt.transaction_id
and AI.PO_HEADER_ID(+) = poh.PO_HEADER_ID
and POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
and POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
--and GXEH.TRANSACTION_ID= RT.TRANSACTION_ID(+)
and GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
--and GXEH.ledger_id = AH.ledger_id
and ah.PERIOD_NAME =:P_PERIOD_NAME -- 'Oct-18'
and POH.PO_HEADER_ID is not null
and ah.ledger_id = 2021
--and com.segment4=2010201    -- 2010201 - L/C in Transit
and com.CODE_COMBINATION_ID =14026
--AND AL.AE_HEADER_ID= 22385998   --20623414
UNION ALL
 SELECT
         AI.INVOICE_ID, 
                   AI.INVOICE_NUM,
                               LCD.PO_NUMBER,
                                         LCD.LC_NUMBER,
                                         AD.RCV_TRANSACTION_ID TRANSACTION_ID,
                                          GET_GRN_FROM_TRANSACTION_ID( AD.RCV_TRANSACTION_ID) GRN,
                                         NULL CHARGE_LINE_TYPE_CODE,
                                         NULL COMPONENT_NAME,
                                         NULL EVENT_ID,
                                         NULL AE_HEADER_ID,
                                         NULL AE_LINE_NUM,
                                         AD.DIST_CODE_COMBINATION_ID CODE_COMBINATION_ID,
                                            (GET_GL_CODE_DESC_FROM_CCID ( AD.DIST_CODE_COMBINATION_ID)) CODE_COMBINATION,
                                            NULL DESCRIPTION,
                                            NULL ENTERED_DR, 
                                            NULL ENTERED_CR,                                           
          GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0) ACCOUNTED_DR,
          (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))) ACCOUNTED_CR,
          NULL EVENT_TYPE_CODE
--          (CASE
--              WHEN (NVL (AD.BASE_AMOUNT, AD.AMOUNT)) > 0 THEN 'DR'
--              ELSE 'CR'
--           END)
    FROM AP_INVOICES_ALL AI,
          AP_INVOICE_DISTRIBUTIONS_ALL AD,
          GL_CODE_COMBINATIONS GC,
          AP_INVOICE_LINES_ALL AIL,
          XX_LC_DETAILS LCD
    WHERE     AI.INVOICE_ID = AD.INVOICE_ID
          AND AD.DIST_CODE_COMBINATION_ID = GC.CODE_COMBINATION_ID
          AND AD.LINE_TYPE_LOOKUP_CODE NOT IN ('PREPAY')
          AND AIL.INVOICE_ID = AD.INVOICE_ID
          AND AIL.LINE_NUMBER = AD.INVOICE_LINE_NUMBER
          AND AI.CANCELLED_DATE IS NULL
          AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
          AND NVL (AD.BASE_AMOUNT, AD.AMOUNT) <> 0
          AND XX_GET_INVOICE_STATUS (AI.INVOICE_ID) NOT IN
                 ('Needs Revalidation', 'Never Validated', 'Unpaid')
          AND AIL.PO_HEADER_ID = LCD.PO_HEADER_ID
          AND AI.ORG_ID = LCD.ORG_ID
          AND LCD.LC_ID IS NOT NULL
          AND (AD.ATTRIBUTE_CATEGORY IS NULL
               OR AD.ATTRIBUTE_CATEGORY <> 'LC Details')
              and ad.SET_OF_BOOKS_ID = 2021  
              and ad.DIST_CODE_COMBINATION_ID = 14026 
              and ad.PERIOD_NAME =:P_PERIOD_NAME -- 'Oct-18'
               )--and  ad.invoice_id=512962
             --AND AI.LEGAL_ENTITY_ID = 2021 -- :P_ORG_ID
          --  AND LCD.LC_NUMBER = :P_LC_NUMBER   


--============================= 8-JUL-2020 FIRST FINAL FOR CHAKING-========================================
SELECT SUM(ACCOUNTED_DR),SUM(ACCOUNTED_CR)
FROM(
  SELECT
  AI.INVOICE_ID,
  AI.INVOICE_NUM,
  POH.PO_HEADER_ID,
  POH.SEGMENT1 PO_NUMBER,
   LC.LC_NUMBER,rh.RECEIPT_NUM GRN_NUMBER, rt.TRANSACTION_ID,GMFV.CHARGE_LINE_TYPE_CODE,GMFV.COMPONENT_NAME, GMFV.TRANSACTION_ID,
GXEH.EVENT_ID,
AL.AE_HEADER_ID, 
AL.AE_LINE_NUM,
  AL.CODE_COMBINATION_ID,
   (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  ah.DESCRIPTION,ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, AH.EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, ap_invoices_all AI -- , MTL_MATERIAL_TRANSACTIONS MMT
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID
and GXEH.EVENT_ID(+)= AH.EVENT_ID
and rt.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND rt.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
--and al.RCV_TRANSACTION_ID = rt.transaction_id
and AI.PO_HEADER_ID(+) = poh.PO_HEADER_ID
and POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
and POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
--and GXEH.TRANSACTION_ID= RT.TRANSACTION_ID(+)
and GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
--and GXEH.ledger_id = AH.ledger_id
and ah.PERIOD_NAME =:P_PERIOD_NAME -- 'Nov-18'
and POH.PO_HEADER_ID is not null
and ah.ledger_id = 2021
and com.segment4=2010201    -- 2010201 - L/C in Transit
UNION ALL 
 select distinct AI.INVOICE_ID, 
 AI.INVOICE_NUM,
 AL.PO_HEADER_ID,
LC.PO_NUMBER PO_NUMBER,
 LC.LC_NUMBER, 
  XX_GET_RECEIPT_NUMBER_FROM_INV (AI.INVOICE_ID) GRN_NUMBER,
  NULL TRANSACTION_ID,
  NULL CHARGE_LINE_TYPE_CODE,
  NULL COMPONENT_NAME,
  NULL TRANSACTION_ID,
  NULL EVENT_ID,
   XEH.AE_HEADER_ID,
   XEL.AE_LINE_NUM,
  XEL.CODE_COMBINATION_ID,
  (GET_GL_CODE_DESC_FROM_CCID (XEL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  XEH.DESCRIPTION,
  ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, XEH.EVENT_TYPE_CODE 
  FROM XLA_AE_LINES XEL ,
  AP_INVOICE_LINES_ALL AL,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
  GL_CODE_COMBINATIONS COM,
--  AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
  XX_LC_DETAILS LC,
  XLA.XLA_TRANSACTION_ENTITIES XTE
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
AND XEL.CODE_COMBINATION_ID= COM.CODE_COMBINATION_ID
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
AND  AI.INVOICE_ID  = AL.INVOICE_ID  
AND XTE.ENTITY_CODE      ='AP_INVOICES'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID   =XEH.ENTITY_ID
AND XTE.LEDGER_ID   =AI.SET_OF_BOOKS_ID
and XEH.PERIOD_NAME =:P_PERIOD_NAME -- 'Nov-18' 
and XEH.LEDGER_ID= '2021' 
and com.segment4=2010201
and LC.PO_HEADER_ID = AL.PO_HEADER_ID
and al.PO_HEADER_ID is not  null
 AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID)
--AND AD.ATTRIBUTE1= '10078'
--order by XEL.AE_HEADER_ID 


--======================================================================================================
select POH.SEGMENT1, LC.LC_NUMBER,rh.RECEIPT_NUM GRN_NUMBER, rt.TRANSACTION_ID,GMFV.CHARGE_LINE_TYPE_CODE,GMFV.COMPONENT_NAME, GMFV.TRANSACTION_ID,GXEH.TRANSACTION_ID,GXEH.EVENT_ID,AL.AE_HEADER_ID, AL.AE_LINE_NUM, AL.CODE_COMBINATION_ID, (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,ah.DESCRIPTION,ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, AH.EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC-- , MTL_MATERIAL_TRANSACTIONS MMT
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID
and GXEH.EVENT_ID(+)= AH.EVENT_ID
and rt.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND rt.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
and POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
and POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
--and GXEH.TRANSACTION_ID= RT.TRANSACTION_ID(+)
and GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
--and GXEH.ledger_id = AH.ledger_id
and PERIOD_NAME = 'Nov-18'
and ah.ledger_id = 2021
and com.segment4=2010201    -- 2010201 - L/C in Transit
--and AL.CODE_COMBINATION_ID = 2010201 


--==========================================================================================================





--13-JUL-2020



     SELECT    DECODE (SIGN (SUM (BASE_AMOUNT)), 1, 0, SUM (AD.BASE_AMOUNT)) DR_AMOUNT,
         DECODE (SIGN (SUM (AD.BASE_AMOUNT)), 1, 0, SUM (ad.BASE_AMOUNT)) CR_AMOUNT       
 FROM AP_INVOICE_DISTRIBUTIONS_ALL AD WHERE SET_OF_BOOKS_ID = 2021  and DIST_CODE_COMBINATION_ID = 14026 and PERIOD_NAME = 'Oct-18' and  invoice_id=512962 



SELECT DECODE(SUM(GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))) DR,
         DECODE(SUM (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0)))) CR
--          (CASE
--              WHEN (NVL (AD.BASE_AMOUNT, AD.AMOUNT)) > 0 THEN 'DR'
--              ELSE 'CR'
--           END)
            -- DRCR_FLAG
              FROM AP_INVOICE_DISTRIBUTIONS_ALL AD WHERE SET_OF_BOOKS_ID = 2021  and DIST_CODE_COMBINATION_ID = 14026 and PERIOD_NAME = 'Oct-18' and  invoice_id=512962 -- 1401583

select * from GL_CODE_COMBINATIONS where segment4=2010201 and SEGMENT1 = 101

DOC_SEQUENCE_VALUE =180004878 and SET_OF_BOOKS_ID = 2021

-- 12-JUL-2020

SELECT * FROM AP_INVOICES_ALL  WHERE DOC_SEQUENCE_VALUE  = 180000003 AND ORG_ID = 81 AND DOC_SEQUENCE_ID = 373

SELECT * FROM AP_INVOICE_LINES_ALL  WHERE  INVOICE_ID=512962  --  = 180000003 and ORG_ID = 81 and DOC_SEQUENCE_ID = 373

SELECT * FROM AP_INVOICE_DISTRIBUTIONS_ALL WHERE INVOICE_ID=512962

SELECT  * FROM XLA_AE_HEADERS WHERE DOC_SEQUENCE_VALUE  = 180000003 AND DOC_SEQUENCE_ID = 373 AND LEDGER_ID=2021  -- AE_HEADER_ID  , DOC_SEQUENCE_ID , DOC_SEQUENCE_VALUE , LEDGER_ID ,EVENT_ID ,  EVENT_TYPE_CODE

SELECT DISTINCT(PO_HEADER_ID) FROM AP_INVOICE_LINES_ALL where  PO_HEADER_ID is not null  and  INVOICE_ID=13003


SELECT  AI.* , AI.DOC_SEQUENCE_VALUE, AI.INVOICE_NUM
FROM XLA_AE_HEADERS XAH, XLA_AE_LINES XAL, GL_CODE_COMBINATIONS COM, AP_INVOICES_ALL  AI, AP_INVOICE_LINES_ALL AL  
 WHERE XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 AND AI.DOC_SEQUENCE_ID = XAH.DOC_SEQUENCE_ID 
 AND AI.DOC_SEQUENCE_VALUE = XAH.DOC_SEQUENCE_VALUE
 AND AI.INVOICE_ID= AL.INVOICE_ID
 --and  xah.doc_sequence_value  = 180000003 
 --and xah.DOC_SEQUENCE_ID = 373 
 AND XAH.LEDGER_ID=2021
 AND XAL.CODE_COMBINATION_ID=COM.CODE_COMBINATION_ID
AND COM.SEGMENT4=2010201 
 AND XAH.PERIOD_NAME = 'Oct-18' 





select * from XLA_AE_LINES     --  AE_HEADER_ID , CODE_COMBINATION_ID

select AL.* from XLA_AE_HEADERS AH, XLA_AE_LINES AL      --, GL_CODE_COMBINATIONS
where ah.ae_header_id= AL.AE_HEADER_ID
and al.ledger_id= 2021




select RECEIPT_NUMBER from AP_INVOICE_LINES_V where PO_HEADER_ID is not null








 select distinct AI.INVOICE_ID, 
 AL.PO_HEADER_ID,
 XEL.ACCOUNTED_DR,
 XEL.ACCOUNTED_CR, 
 LC.LC_NUMBER, 
 LC.PO_NUMBER,
 XX_GET_RECEIPT_NUMBER_FROM_INV (AI.INVOICE_ID) GRN_NUMBER
  FROM XLA_AE_LINES XEL ,
  AP_INVOICE_LINES_ALL AL,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
  GL_CODE_COMBINATIONS COM,
--  AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
  XX_LC_DETAILS LC,
  XLA.XLA_TRANSACTION_ENTITIES XTE
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
AND XEL.CODE_COMBINATION_ID= COM.CODE_COMBINATION_ID
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
AND  AI.INVOICE_ID  = AL.INVOICE_ID  
--AND XTE.ENTITY_CODE      ='AP_INVOICES'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID   =XEH.ENTITY_ID
AND XTE.LEDGER_ID   =AI.SET_OF_BOOKS_ID
and XEH.PERIOD_NAME = 'Oct-18' 
and XEH.LEDGER_ID= '2021' 
and com.segment4=2010201
and LC.PO_HEADER_ID= AL.PO_HEADER_ID
--and al.PO_HEADER_ID is not  null
--AND AD.ATTRIBUTE1= '10078'
--order by XEL.AE_HEADER_ID 



select PO_HEADER_ID from AP_INVOICE_DISTRIBUTIONS_ALL

select PO_HEADER_ID from AP_INVOICE_LINES_ALL  where PO_HEADER_ID is not null

select * from  XLA_AE_LINES 


select * from RCV_TRANSACTIONS where TRANSACTION_TYPE = 'DELIVER'
DR                    CR
462389.75    13667.27




      -- 2010201 - L/C in Transit




select *from XLA.XLA_TRANSACTION_ENTITIES XTE

select * from PER_ALL_POSITIONS

select * from XLA_AE_HEADERS  -- EVENT_TYPE_CODE

select * from XLA_AE_LINES

  select * from GL_CODE_COMBINATIONS
  
  select * from gmf_lc_adj_transactions
  
  -- 8-JUL-2020
  select * from GMF_XLA_EXTRACT_HEADERS
  
  SELECT * FROM GMF_XLA_RCV_TXNS_V where TRANSACTION_ID =18001
  
  select * from  GMF_XLA_LC_ADJS_V where RCV_TRANSACTION_ID = 305721 and TRANSACTION_DATE  between  '01-NOV-2018' and '30-NOV-2018'  --TRANSACTION_ID =18001
  
  select * from RCV_TRANSACTIONS where TRANSACTION_ID =305721   and ORGANIZATION_ID = 166 -- TRANSACTION_ID
  
  
XLA_AE_LINES    --   CODE_COMBINATION_ID , ACCOUNTING_CLASS_CODE,CURRENCY_CODE,ACCOUNTING_DATE,LEDGER_ID,APPLICATION_ID,AE_LINE_NUM,AE_HEADER_ID
  
  select * from AP_INVOICES_ALL where PO_HEADER_ID is not null -- = 260007  --PO_HEADER_ID , DOC_SEQUENCE_ID , DOC_SEQUENCE_VALUE, ORG_ID , LEGAL_ENTITY_ID, PARTY_ID
  
  select distinct * from ap_invoice_lines_all where   PO_HEADER_ID = '260007' --where RCV_TRANSACTION_ID = 305721  -- RCV_TRANSACTION_ID , PO_HEADER_ID,
  
    select distinct INVOICE_ID from ap_invoice_lines_all where   PO_HEADER_ID = '260007' 
    -- 13-JUL-2020
    
  --12-jul-2020  

  SELECT
  AI.INVOICE_ID,
  AI.INVOICE_NUM,
  POH.SEGMENT1 PO_NUMBER,
   LC.LC_NUMBER,
   rh.RECEIPT_NUM GRN_NUMBER,
    rt.TRANSACTION_ID,GMFV.CHARGE_LINE_TYPE_CODE,GMFV.COMPONENT_NAME, GMFV.TRANSACTION_ID,
GXEH.EVENT_ID,
AL.AE_HEADER_ID, 
AL.AE_LINE_NUM,
  AL.CODE_COMBINATION_ID,
   (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  ah.DESCRIPTION,ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, AH.EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, ap_invoices_all AI -- , MTL_MATERIAL_TRANSACTIONS MMT
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID
and GXEH.EVENT_ID(+)= AH.EVENT_ID
and rt.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND rt.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
--and al.RCV_TRANSACTION_ID = rt.transaction_id
and AI.PO_HEADER_ID(+) = poh.PO_HEADER_ID
and POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
and POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
--and GXEH.TRANSACTION_ID= RT.TRANSACTION_ID(+)
and GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
--and GXEH.ledger_id = AH.ledger_id
and ah.PERIOD_NAME = 'Oct-18'
and POH.PO_HEADER_ID is not null
and ah.ledger_id = 2021
and com.segment4=2010201    -- 2010201 - L/C in Transit
--AND AL.AE_HEADER_ID= 22385998   --20623414
UNION ALL 
select distinct AI.INVOICE_ID, 
 AI.INVOICE_NUM, 
   APPS.XX_GET_PO_NUMBER_FROM_INV (AI.INVOICE_ID) PO_NUMBER,
  APPS.XX_GET_LC_NUMBER_FROM_INV (AI.INVOICE_ID) LC_NUMBER,
  XX_GET_RECEIPT_NUMBER_FROM_INV (AI.INVOICE_ID) GRN_NUMBER,
  NULL TRANSACTION_ID,
  NULL CHARGE_LINE_TYPE_CODE,
  NULL COMPONENT_NAME,
  NULL TRANSACTION_ID,
  NULL EVENT_ID,
   XEH.AE_HEADER_ID,
   XEL.AE_LINE_NUM,
  XEL.CODE_COMBINATION_ID,
  (GET_GL_CODE_DESC_FROM_CCID (XEL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  XEH.DESCRIPTION,
  ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, XEH.EVENT_TYPE_CODE 
  FROM XLA_AE_LINES XEL ,
  AP_INVOICE_LINES_ALL AL,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
  GL_CODE_COMBINATIONS COM,
--  AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
 XX_LC_DETAILS LC,
  XLA.XLA_TRANSACTION_ENTITIES XTE
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
AND XEL.CODE_COMBINATION_ID= COM.CODE_COMBINATION_ID
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
AND  AI.INVOICE_ID  = AL.INVOICE_ID  
AND XTE.ENTITY_CODE      ='AP_INVOICES'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID   =XEH.ENTITY_ID
AND XTE.LEDGER_ID   =AI.SET_OF_BOOKS_ID
and XEH.PERIOD_NAME = 'Oct-18' 
and XEH.LEDGER_ID= '2021' 
and com.segment4=2010201
and LC.PO_HEADER_ID = AL.PO_HEADER_ID
and al.PO_HEADER_ID is not  null
 AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
--AND XEL.AE_HEADER_ID=20623414
--AND AD.ATTRIBUTE1= '10078'
--order by XEL.AE_HEADER_ID 







 select distinct AI.INVOICE_ID, 
 AI.INVOICE_NUM,
 --AL.PO_HEADER_ID,
--LC.PO_NUMBER PO_NUMBER,
--LC.LC_NUMBER, 
  XX_GET_RECEIPT_NUMBER_FROM_INV (AI.INVOICE_ID) GRN_NUMBER,
  NULL TRANSACTION_ID,
  NULL CHARGE_LINE_TYPE_CODE,
  NULL COMPONENT_NAME,
  NULL TRANSACTION_ID,
  NULL EVENT_ID,
   XEH.AE_HEADER_ID,
   XEL.AE_LINE_NUM,
  XEL.CODE_COMBINATION_ID,
  (GET_GL_CODE_DESC_FROM_CCID (XEL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  XEH.DESCRIPTION,
  ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, XEH.EVENT_TYPE_CODE 
  FROM XLA_AE_LINES XEL ,
  AP_INVOICE_LINES_ALL AL,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
  GL_CODE_COMBINATIONS COM,
--  AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
 XX_LC_DETAILS LC,
  XLA.XLA_TRANSACTION_ENTITIES XTE
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
AND XEL.CODE_COMBINATION_ID= COM.CODE_COMBINATION_ID
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
AND  AI.INVOICE_ID  = AL.INVOICE_ID  
AND XTE.ENTITY_CODE      ='AP_INVOICES'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID   =XEH.ENTITY_ID
AND XTE.LEDGER_ID   =AI.SET_OF_BOOKS_ID
and XEH.PERIOD_NAME = 'Oct-18' 
and XEH.LEDGER_ID= '2021' 
and com.segment4=2010201
and LC.PO_HEADER_ID = AL.PO_HEADER_ID
and al.PO_HEADER_ID is not  null
 AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
 AND XEL.AE_HEADER_ID=20623414
--AND AD.ATTRIBUTE1= '10078'
--order by XEL.AE_HEADER_ID 

   

select * from XLA_AE_HEADE WHERE AE_HEADER_ID=20623414

select * from XLA_AE_LINES WHERE AE_HEADER_ID=20623414




 
    
  --12-jul-2020  

  SELECT
  AI.INVOICE_ID,
  AI.INVOICE_NUM,
  POH.PO_HEADER_ID,
  POH.SEGMENT1 PO_NUMBER,
   LC.LC_NUMBER,rh.RECEIPT_NUM GRN_NUMBER, rt.TRANSACTION_ID,GMFV.CHARGE_LINE_TYPE_CODE,GMFV.COMPONENT_NAME, GMFV.TRANSACTION_ID,
GXEH.EVENT_ID,
AL.AE_HEADER_ID, 
AL.AE_LINE_NUM,
  AL.CODE_COMBINATION_ID,
   (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  ah.DESCRIPTION,ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, AH.EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, ap_invoices_all AI -- , MTL_MATERIAL_TRANSACTIONS MMT
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID
and GXEH.EVENT_ID(+)= AH.EVENT_ID
and rt.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND rt.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
--and al.RCV_TRANSACTION_ID = rt.transaction_id
and AI.PO_HEADER_ID(+) = poh.PO_HEADER_ID
and POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
and POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
--and GXEH.TRANSACTION_ID= RT.TRANSACTION_ID(+)
and GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
--and GXEH.ledger_id = AH.ledger_id
and ah.PERIOD_NAME = 'Nov-18'
and POH.PO_HEADER_ID is not null
and ah.ledger_id = 2021
and com.segment4=2010201    -- 2010201 - L/C in Transit
UNION ALL 
 select distinct AI.INVOICE_ID, 
 AI.INVOICE_NUM,
 AL.PO_HEADER_ID,
LC.PO_NUMBER PO_NUMBER,
 LC.LC_NUMBER, 
  XX_GET_RECEIPT_NUMBER_FROM_INV (AI.INVOICE_ID) GRN_NUMBER,
  NULL TRANSACTION_ID,
  NULL CHARGE_LINE_TYPE_CODE,
  NULL COMPONENT_NAME,
  NULL TRANSACTION_ID,
  NULL EVENT_ID,
   XEH.AE_HEADER_ID,
   XEL.AE_LINE_NUM,
  XEL.CODE_COMBINATION_ID,
  (GET_GL_CODE_DESC_FROM_CCID (XEL.CODE_COMBINATION_ID)) CODE_COMBINATION,
  XEH.DESCRIPTION,
  ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, XEH.EVENT_TYPE_CODE 
  FROM XLA_AE_LINES XEL ,
  AP_INVOICE_LINES_ALL AL,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
  GL_CODE_COMBINATIONS COM,
--  AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
  XX_LC_DETAILS LC,
  XLA.XLA_TRANSACTION_ENTITIES XTE
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
AND XEL.CODE_COMBINATION_ID= COM.CODE_COMBINATION_ID
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
AND  AI.INVOICE_ID  = AL.INVOICE_ID  
AND XTE.ENTITY_CODE      ='AP_INVOICES'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID   =XEH.ENTITY_ID
AND XTE.LEDGER_ID   =AI.SET_OF_BOOKS_ID
and XEH.PERIOD_NAME = 'Nov-18' 
and XEH.LEDGER_ID= '2021' 
and com.segment4=2010201
and LC.PO_HEADER_ID = AL.PO_HEADER_ID
and al.PO_HEADER_ID is not  null
 AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
--AND AD.ATTRIBUTE1= '10078'
--order by XEL.AE_HEADER_ID 








 
 SELECT ai.INVOICE_ID, XEL.*
 -- select distinct AI.*
  FROM XLA_AE_LINES XEL ,
  GL_CODE_COMBINATIONS COM,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
 --AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
  XLA.XLA_TRANSACTION_ENTITIES XTE
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
--and AI.INVOICE_ID = AD.INVOICE_ID
AND XEL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
--AND  AI.INVOICE_ID  = AD.INVOICE_ID  
AND XTE.ENTITY_CODE             ='AP_INVOICES'
and AI.INVOICE_TYPE_LOOKUP_CODE = 'STANDARD'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID               =XEH.ENTITY_ID
AND XTE.LEDGER_ID               =AI.SET_OF_BOOKS_ID
and XEH.PERIOD_NAME = 'Oct-18' 
and XEH.LEDGER_ID= '2021' 
and com.segment4=2010201 
 --and POH.PO_HEADER_ID is not null
 
 
 --=================================
 
 
 
 

  select AI.INVOICE_ID,POH.PO_HEADER_ID,POH.SEGMENT1 PO_NUMBER, LC.LC_NUMBER,rh.RECEIPT_NUM GRN_NUMBER, rt.TRANSACTION_ID,GMFV.CHARGE_LINE_TYPE_CODE,GMFV.COMPONENT_NAME, GMFV.TRANSACTION_ID,GXEH.TRANSACTION_ID,GXEH.EVENT_ID,AL.AE_HEADER_ID, AL.AE_LINE_NUM, AL.CODE_COMBINATION_ID, (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,ah.DESCRIPTION,ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, AH.EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, ap_invoices_all AI-- , MTL_MATERIAL_TRANSACTIONS MMT
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID
and GXEH.EVENT_ID(+)= AH.EVENT_ID
and rt.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND rt.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
--and al.RCV_TRANSACTION_ID = rt.transaction_id
and AI.PO_HEADER_ID(+) = poh.PO_HEADER_ID
and POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
and POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
--and GXEH.TRANSACTION_ID= RT.TRANSACTION_ID(+)
and GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
--and GXEH.ledger_id = AH.ledger_id
and ah.PERIOD_NAME = 'Oct-18'
and POH.PO_HEADER_ID is   null
and ah.ledger_id = 2021
and com.segment4=2010201    -- 2010201 - L/C in Transit



  -- 8-JUL-2020
   select
  AI.INVOICE_ID,POH.PO_HEADER_ID,POH.SEGMENT1 PO_NUMBER, LC.LC_NUMBER,rh.RECEIPT_NUM GRN_NUMBER, rt.TRANSACTION_ID,GMFV.CHARGE_LINE_TYPE_CODE,GMFV.COMPONENT_NAME, GMFV.TRANSACTION_ID,GXEH.TRANSACTION_ID,GXEH.EVENT_ID,AL.AE_HEADER_ID, AL.AE_LINE_NUM, AL.CODE_COMBINATION_ID, (GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,ah.DESCRIPTION,ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, AH.EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com , GMF_XLA_EXTRACT_HEADERS GXEH, 
 GMF_XLA_LC_ADJS_V GMFV, RCV_TRANSACTIONS RT, RCV_SHIPMENT_HEADERS RH,PO_HEADERS_ALL POH, XX_LC_DETAILS LC, ap_invoices_all AI-- , MTL_MATERIAL_TRANSACTIONS MMT
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID
and GXEH.EVENT_ID(+)= AH.EVENT_ID
and rt.TRANSACTION_ID(+)= GMFV.RCV_TRANSACTION_ID
AND rt.SHIPMENT_HEADER_ID= RH.SHIPMENT_HEADER_ID(+)
--and al.RCV_TRANSACTION_ID = rt.transaction_id
and AI.PO_HEADER_ID(+) = poh.PO_HEADER_ID
and POH.PO_HEADER_ID(+)= RT.PO_HEADER_ID
and POH.PO_HEADER_ID = LC.PO_HEADER_ID(+)
--and GXEH.TRANSACTION_ID= RT.TRANSACTION_ID(+)
and GXEH.TRANSACTION_ID = GMFV.TRANSACTION_ID(+)
--and GXEH.ledger_id = AH.ledger_id
and ah.PERIOD_NAME = 'Oct-18'
--and POH.PO_HEADER_ID is not null
and ah.ledger_id = 2021
and com.segment4=2010201    -- 2010201 - L/C in Transit


 
select * from RCV_TRANSACTIONS

select * from GMF_XLA_EXTRACT_HEADERS GXEH    -- EVENT_ID , EVENT_TYPE_CODE, LEDGER_ID , TRANSACTION_ID
  
select * from MTL_MATERIAL_TRANSACTIONS  -- TRANSACTION_ID  , ORGANIZATION_ID , INVENTORY_ITEM_ID, TRANSACTION_ID
  
  
  select * from 
  
  
  
  SELECT GXEH.TRANSACTION_ID, AH.EVENT_ID ,AH.AE_HEADER_ID,AH.EVENT_TYPE_CODE ,AH.LEDGER_ID,
GXEH.HEADER_ID , GXEH.EVENT_ID ,  GXEH.EVENT_CLASS_CODE , GXEH.LEDGER_ID, GXEH.OPERATING_UNIT , GXEH.TRANSACTION_QUANTITY,GXEH.ORGANIZATION_ID,GXEH.INVENTORY_ITEM_ID,
ACCOUNTED_DR, ACCOUNTED_CR
  FROM XLA_AE_HEADERS  AH,  GMF_XLA_EXTRACT_HEADERS GXEH, XLA_AE_LINES XEL, GL_CODE_COMBINATIONS GL
  where  AH.EVENT_ID = GXEH.EVENT_ID
  and AH.LEDGER_ID= GXEH.LEDGER_ID
  and AH.AE_HEADER_ID = XEL.AE_HEADER_ID
  and GL.CODE_COMBINATION_ID = XEL.CODE_COMBINATION_ID
  and AH.ledger_id= 2021
  
  
  
  select * from tab where tabtype='VIEW'
  and tname like '%GMF%'
  
  select * from GMF_LC_ADJ_DETAILS_V 

  
  
  
  
  
  
 
  
  
  
  
  
  
  
  
  -- BATEN VAI
  
 SELECT TRANSACTION_ID , COUNT(*) FROM 
(SELECT GXEH.TRANSACTION_ID, AH.EVENT_ID ,AH.AE_HEADER_ID,AH.EVENT_TYPE_CODE ,AH.LEDGER_ID,
GXEH.HEADER_ID , GXEH.EVENT_ID ,  GXEH.EVENT_CLASS_CODE , GXEH.LEDGER_ID, GXEH.OPERATING_UNIT , GXEH.TRANSACTION_QUANTITY,GXEH.ORGANIZATION_ID,GXEH.INVENTORY_ITEM_ID,
ACCOUNTED_DR, ACCOUNTED_CR
  FROM XLA_AE_HEADERS  AH,  GMF_XLA_EXTRACT_HEADERS GXEH, XLA_AE_LINES XEL, GL_CODE_COMBINATIONS GL
  where  AH.EVENT_ID = GXEH.EVENT_ID
  and AH.LEDGER_ID= GXEH.LEDGER_ID
  and AH.AE_HEADER_ID = XEL.AE_HEADER_ID
  and GL.CODE_COMBINATION_ID = XEL.CODE_COMBINATION_ID
  and AH.ledger_id= 2021
  )
  HAVING COUNT(*) >2
  GROUP BY TRANSACTION_ID
  
  
  
  order by GXEH.TRANSACTION_ID
  

select * from ap_suppliers where CREATION_DATE between '06-JUL-2020' and '08-JUL-2020' 

 select distinct(EVENT_TYPE_CODE) from GMF_XLA_EXTRACT_HEADERS   -- EVENT_ID  ,  ENTITY_CODE ,   EVENT_CLASS_CODE , LEGAL_ENTITY_ID   , LEDGER_ID

 select distinct XEH.AE_HEADER_ID,XEH.PERIOD_NAME,XTE.ENTITY_CODE ,
 GET_LC_NUMBER_FROM_ID(AD.ATTRIBUTE1) LC_NUMBER,
  XX_GET_RECEIPT_NUMBER_FROM_INV (AI.INVOICE_ID) GRN_NUMBER,
  XEH.DESCRIPTION, XEL.CODE_COMBINATION_ID,XEL.PARTY_ID, 
  (GET_GL_CODE_DESC_FROM_CCID (XEL.CODE_COMBINATION_ID)) ACCOUNT_CODE,XEL.ENTERED_DR, XEL.ENTERED_CR, XEL.ACCOUNTED_DR,XEL.ACCOUNTED_CR
  FROM XLA_AE_LINES XEL ,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
  AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
  GL_CODE_COMBINATIONS COM,
  XLA.XLA_TRANSACTION_ENTITIES XTE,
  GMF_XLA_EXTRACT_HEADERS GXH
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
and GXH.EVENT_ID = XE.EVENT_ID
and GXH.EVENT_ID = XEH.EVENT_ID
and GXH.EVENT_TYPE_CODE = XEH.EVENT_TYPE_CODE
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
AND  AI.INVOICE_ID  = AD.INVOICE_ID  
--AND XTE.ENTITY_CODE             ='AP_INVOICES'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID               =XEH.ENTITY_ID
AND XTE.LEDGER_ID               =AI.SET_OF_BOOKS_ID
AND  XEL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
--and XEH.PERIOD_NAME = 'Sep-18'
-- AND AD.ATTRIBUTE1= '10234'
--and com.segment4=2010201
--order by XEL.AE_HEADER_ID 
 
select * from XX_LC_DETAILS WHERE LC_number = '1743-18-01-0386'    --DR 
--Supplier account code 4030107



 

my_package


select PO_NUMBER FROM XX_LC_DETAILS WHERE SEGMENT

select * from   XLA.XLA_TRANSACTION_ENTITIES XTE

select *  from XLA_AE_HEADERS

select *  from XLA_AE_LINES
 
 
 --- KHALIL  VAI PROVIDED 
 
 select distinct AI.*
  FROM XLA_AE_LINES XEL ,
  XLA_AE_HEADERS XEH ,
  AP_INVOICES_ALL AI ,
--  AP_INVOICE_DISTRIBUTIONS_ALL AD,
  XLA_EVENTS XE ,
  XLA.XLA_TRANSACTION_ENTITIES XTE
WHERE XTE.APPLICATION_ID        =200
AND XEL.APPLICATION_ID          =200
AND XEH.APPLICATION_ID          =200
AND XE.APPLICATION_ID           =200
--AND AI.INVOICE_ID               =450736
AND XE.ENTITY_ID                =XTE.ENTITY_ID
AND XE.EVENT_ID                 =XEH.EVENT_ID
AND XEL.AE_HEADER_ID            =XEH.AE_HEADER_ID
--AND  AI.INVOICE_ID  = AD.INVOICE_ID  
AND XTE.ENTITY_CODE             ='AP_INVOICES'
AND NVL(XTE.SOURCE_ID_INT_1,-99)=AI.INVOICE_ID
AND XTE.ENTITY_ID               =XEH.ENTITY_ID
AND XTE.LEDGER_ID               =AI.SET_OF_BOOKS_ID
and XEH.PERIOD_NAME = 'Sep-18' 
and XEH.LEDGER_ID= '2021' 
--and com.segment4=2010201
--AND AD.ATTRIBUTE1= '10078'
--order by XEL.AE_HEADER_ID 




2010201 - L/C in Transit

SELECT * FROM XLA_LINES_DISTRIBUTIONS

select AL.AE_HEADER_ID, AL.AE_LINE_NUM, AL.CODE_COMBINATION_ID, 
(GET_GL_CODE_DESC_FROM_CCID (AL.CODE_COMBINATION_ID)) CODE_COMBINATION,
ah.DESCRIPTION,ENTERED_DR,ENTERED_CR,ACCOUNTED_DR,ACCOUNTED_CR, EVENT_TYPE_CODE
 from XLA_AE_HEADERS AH, XLA_AE_LINES AL, GL_CODE_COMBINATIONS com 
where AL.CODE_COMBINATION_ID=com.CODE_COMBINATION_ID
and ah.AE_HEADER_ID = al.AE_HEADER_ID 
and PERIOD_NAME = 'Sep-18'
and ah.ledger_id = 2021
and com.segment4=2010201    -- 2010201 - L/C in Transit
--and AL.CODE_COMBINATION_ID = 2010201  


se


select segment4, CODE_COMBINATION_ID, GET_GL_CODE_DESC_FROM_CCID (CODE_COMBINATION_ID)  from GL_CODE_COMBINATIONS 
where GET_GL_CODE_DESC_FROM_CCID (CODE_COMBINATION_ID) like '%L%C%'

select ah.PERIOD_NAME , 


select  distinct(GET_GL_CODE_DESC_FROM_CCID (CODE_COMBINATION_ID)) from XLA_AE_LINES

select CODE_COMBINATION_ID  from XLA_AE_LINES 


SELECT * FROM XX_lc_details WHERE LC_id= 10078 

select * from RCV_TRANSACTIONS where shipment_header_id = 32001

select * from RCV_SHIPMENT_LINES where shipment_header_id = 32001

select* from cat where table_name like '%XX%RCV%'

select * from XX_INV_RCV_TRANSACTIONS

select * from AP_INVOICES_ALL 
--==============================
-- LC LEDGER DETAILS REPORT


SELECT    SUM(DR_AMOUNT),
   SUM(CR_AMOUNT) FROM
(SELECT 
DISTINCT B.ORG_ID,
   XX_GET_HR_OPERATING_UNIT (B.ORG_ID) OPERATING_UNIT,
      B.BAL_SEG_NAME,
  -- A.LC_ID,
   A.LC_NUMBER,
    A.LC_TYPE,
   A.LC_OPENING_DATE,
   A.LC_STATUS,
   A.LC_VALUE,
   A.SUPPLIER_NAME LC_SUPPLIER_NAME,
   A.PO_NUMBER PO_NUMBER,
    XX_GET_RECEIPT_NUMBER_FROM_INV (INVOICE_ID) GRN_NUMBER,
  -- B.GRN_NUMBER,
 --  A.PO_HEADER_ID,
  A.CURRENCY_CODE,
  -- A.CURRENCY_CODE || '@' ||  A.EXCHANGE_RATE  LC_INVOICE_CURRENCY ,
  -- B.ORG_ID,
   B.INVOICE_ID,
      B.VOUCHER,
  B.COST_FACTOR_ID,
   --B.BAL_SEG,
   B.INVOICE_ID,
    B.PARTY_ID,
   B.PARTY_NAME,
 --  B.VENDOR_ID,
 --  B.CHECK_NUMBER,
  -- B.CHECK_DATE,
   B.GL_DATE,
   --B.CREATED_BY,
   B.CREATION_DATE,
   B.CURRENCY_CODE,
   B.EXCHANGE_RATE,
   B.GL_CODE_AND_DESC,
  (SELECT DISTINCT DESCRIPTION  FROM PON_PRICE_ELEMENT_TYPES_TL WHERE PRICE_ELEMENT_TYPE_ID = B.COST_FACTOR_ID) CHARGE_TYPEE,
   B.GL_DESC,
   B.ACCOUNT_CODE,
   B.SUB_ACCOUNT,
                     (  DECODE (B.COST_CENTER, NULL, NULL, B.COST_CENTER)
                     || DECODE (B.PROJECT_NAME, NULL, NULL, '-' || B.PROJECT_NAME)
                     || DECODE (B.INTER_COMPANY, NULL, NULL, '-' || B.INTER_COMPANY)
                    || DECODE (B.DESCRIPTION, NULL, NULL, '-' || B.DESCRIPTION))
                   -- || DECODE (B.LC_NUMBER, NULL, NULL, '-' || B.LC_NUMBER))
               ADD_DESCRIPTION,
   B.DR_AMOUNT,
   B.CR_AMOUNT
--   B.DRCR_FLAG,
--   B.PO_NUMBER,
 --  B.RECEIPT_NUMBER,
  -- B.BANK_ACCOUNT_NAME,
 --  B.ATTRIBUTE1,
 --   B.ATTRIBUTE2,
  --  B.ATTRIBUTE3,
 --   B.ATTRIBUTE4,
   --XX_INV_PKG.XXGET_ENAME(:P_USER_ID) USER_NAME
   FROM XX_LC_DETAILS  A , XX_AP_LC_DETAILS_VK B
   WHERE 1=1
    AND A.LC_ID=B.LC_ID  
   AND B.BAL_SEG=:P_COMPANY
    AND (:P_LC_ID IS NULL OR A.LC_ID=NVL(:P_LC_ID,A.LC_ID))
    AND (:P_ACCOUNT_CODE IS NULL OR B.ACCOUNT_CODE=NVL(:P_ACCOUNT_CODE,B.ACCOUNT_CODE))
 -- AND  (:P_DATE_FROM  IS NULL OR B.GL_DATE BETWEEN :P_DATE_FROM  AND :P_DATE_TO) 
  AND B.GL_DATE between '01-OCT-2018' and '31-OCT-2018')
--  and B.PARTY_NAME = 'SUND BIRSTA AB'
  --and b.voucher = 'AP INV-180004320'
--  AND B.ATTRIBUTE1 IS NOT NULL


    ORDER BY GL_DATE,VOUCHER ASC
    
    
    
    
    select sum(DR_AMOUNT) from XX_AP_LC_DETAILS_VK where  BAL_SEG = 101
    and  voucher= 'AP INV-180004320'
    
    
    select * from  GL_CODE_COMBINATIONS
    
    
    
--================================



select * from AP_INVOICE_LINES_ALL = 

SELECT * FROM AP_INVOICE_DISTRIBUTIONS_ALL WHERE RCV_TRANSACTION_ID= 

SELECT RCV_TRANSACTION_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL WHERE ATTRIBUTE1= '10078'

select * from rcv_shipment_headers where receipt_num=80000679 and  SHIP_TO_ORG_ID = 166

select * from rcv_transactions where shipment_header_id = 438251





SELECT DISTINCT RH.RECEIPT_NUM 
FROM RCV_SHIPMENT_HEADERs RH , rcv_transactions RT
WHERE RH.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
AND RT.TRANSACTION_ID = 317396
AND TRANSACTION_TYPE = 'DELIVER'
--AND RT.ORGANIZATION_ID = 166


--CREATE OR REPLACE FUNCTION  GET_RCPTNAME_FROM_ID(P_TRANSACTION_ID IN NUMBER )
--RETURN NUMBER
--IS
--V_GRN_NUM NUMBER;
--BEGIN
--SELECT DISTINCT RH.RECEIPT_NUM INTO V_GRN_NUM
--FROM RCV_SHIPMENT_HEADERS RH , RCV_TRANSACTIONS RT
--WHERE RH.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
--AND TRANSACTION_TYPE = 'DELIVER'
--AND RT.TRANSACTION_ID = P_TRANSACTION_ID;
--RETURN V_GRN_NUM;
--EXCEPTION WHEN OTHERS THEN 
--RETURN NULL;
--END;





select  RCV_TRANSACTION_ID from AP_INVOICE_DISTRIBUTIONS_ALL where  RCV_TRANSACTION_ID = 317395 -- is not null --ATTRIBUTE1= '10078'  --INVOICE_ID =450736


  and ad.ATTRIBUTE1= '10078' 
  and ad.org_id=104
  and AI.INVOICE_ID =450736

 --=================READY FOR SEND ========================
 
 
 
 
  SELECT 
          AI.ORG_ID,
          GC.SEGMENT1,
          GET_FLEX_VALUES_FROM_FLEX_ID (
             GET_SEGMENT_VALUE_FROM_CCID (AD.DIST_CODE_COMBINATION_ID, 1),
             1)
             BAL_SEG_NAME,
          GC.SEGMENT2 UNIT_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (2, GC.SEGMENT2, GC.SEGMENT1) UNIT_NAME,
          AI.INVOICE_ID,
          AIL.COST_FACTOR_ID,
          AI.PARTY_ID,
          --AI.PARTY_SITE_ID,
          NULL PARTY_CODE,                          --PARTY_ID,-- AV.SEGMENT1 PARTY_CODE,
          XX_GET_PARTY_NAME (PARTY_ID) PARTY_NAME, -- AV.VENDOR_NAME PARTY_NAME,
          AI.VENDOR_ID,
          AI.INVOICE_NUM,
          AI.INVOICE_DATE,
          AI.GL_DATE,
          AI.CREATED_BY,
          AI.CREATION_DATE,
          AI.INVOICE_CURRENCY_CODE,
          AI.EXCHANGE_RATE,
          AI.INVOICE_AMOUNT,
          'AP INV-' || AI.DOC_SEQUENCE_VALUE VOUCHER,
             GET_GL_CODE_DESC_FROM_CCID (AD.DIST_CODE_COMBINATION_ID)
          || ','
          || XX_GET_ACCT_FLEX_SEG_DESC (5, GC.SEGMENT5, GC.SEGMENT4),
          GET_GL_DESC_FROM_CCID (AD.DIST_CODE_COMBINATION_ID) GL_DESC,
          get_segment_value_from_ccid (AD.DIST_CODE_COMBINATION_ID, 4)
             ACCOUNT_CODE,
          AD.DESCRIPTION DESCRIPTION,
          NVL (NVL (XX_GET_AP_DFF_ALL_INFO (AI.INVOICE_ID,
                                            AD.INVOICE_DISTRIBUTION_ID,
                                            AD.ATTRIBUTE_CATEGORY,
                                            AD.ATTRIBUTE1),
                    XX_GET_AP_DFF_ALL_INFO (AI.INVOICE_ID,
                                            AIL.LINE_NUMBER,
                                            AIL.ATTRIBUTE_CATEGORY,
                                            AIL.ATTRIBUTE1)),
               AD.ATTRIBUTE2 || '-' || AD.ATTRIBUTE3 || '-' || AD.ATTRIBUTE4)
             DFF_INFO,
          GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0),
          (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))),
          (CASE
              WHEN (NVL (AD.BASE_AMOUNT, AD.AMOUNT)) > 0 THEN 'DR'
              ELSE 'CR'
           END)
             DRCR_FLAG,
          GC.SEGMENT3 COST_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (3, GC.SEGMENT3) COST_CENTER,
          GC.SEGMENT5 SUB_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (5, GC.SEGMENT5, GC.SEGMENT4) SUB_ACCOUNT,
          GC.SEGMENT6 PROJECT_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (6, GC.SEGMENT6) PROJECT_NAME,
          GC.SEGMENT7 INTER_COM_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (7, GC.SEGMENT7) INTER_COMPANY,
          AD.DIST_CODE_COMBINATION_ID,
          AD.ATTRIBUTE_CATEGORY,
          AD.ATTRIBUTE1,
          AD.ATTRIBUTE2,
          AD.ATTRIBUTE3,
          AD.ATTRIBUTE4,
          AD.ATTRIBUTE5,
          AD.RCV_TRANSACTION_ID,
          AIL.PO_HEADER_ID,
          LCD.LC_ID,
          LCD.LC_NUMBER,
          LCD.PO_NUMBER,
          LCD.BANK_NAME,
          LCD.SUPPLIER_NAME,
          AD.ATTRIBUTE3 GRN_NUMBER
     FROM AP_INVOICES_ALL AI,
          AP_INVOICE_DISTRIBUTIONS_ALL AD,
          GL_CODE_COMBINATIONS GC,
          AP_INVOICE_LINES_ALL AIL,
          XX_LC_DETAILS LCD
    WHERE     AI.INVOICE_ID = AD.INVOICE_ID
          AND AD.DIST_CODE_COMBINATION_ID = GC.CODE_COMBINATION_ID
          AND AD.LINE_TYPE_LOOKUP_CODE NOT IN ('PREPAY')
          AND AIL.INVOICE_ID = AD.INVOICE_ID
          AND AIL.LINE_NUMBER = AD.INVOICE_LINE_NUMBER
          AND AI.CANCELLED_DATE IS NULL
          AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
          AND NVL (AD.BASE_AMOUNT, AD.AMOUNT) <> 0
          AND XX_GET_INVOICE_STATUS (AI.INVOICE_ID) NOT IN
                 ('Needs Revalidation', 'Never Validated', 'Unpaid')
          AND AIL.PO_HEADER_ID = LCD.PO_HEADER_ID
          AND AI.ORG_ID = LCD.ORG_ID
          AND LCD.LC_ID IS NOT NULL
          AND (AD.ATTRIBUTE_CATEGORY IS NULL
               OR AD.ATTRIBUTE_CATEGORY <> 'LC Details')
              and ad.SET_OF_BOOKS_ID = 2021  
              and ad.DIST_CODE_COMBINATION_ID = 14026 
              --and ad.SET_OF_BOOKS_ID = 2021  and ad.DIST_CODE_COMBINATION_ID = 14026 and ad.PERIOD_NAME = 'Oct-18' and  ad.invoice_id=512962
              and ad.PERIOD_NAME = 'Oct-18' --and  ad.invoice_id=512962
             AND AI.ORG_ID = :P_ORG_ID
            AND LCD.LC_NUMBER = :P_LC_NUMBER   
            
                           
     UNION ALL   
   SELECT
          AI.ORG_ID,
          GC.SEGMENT1,
          GET_FLEX_VALUES_FROM_FLEX_ID (
             GET_SEGMENT_VALUE_FROM_CCID (AD.DIST_CODE_COMBINATION_ID, 1), 1)
             BAL_SEG_NAME,
          GC.SEGMENT2 UNIT_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (2, GC.SEGMENT2, GC.SEGMENT1) UNIT_NAME,
          AI.INVOICE_ID,
          NULL COST_FACTOR_ID,
          AI.PARTY_ID,
          NULL,                          --PARTY_ID,-- AV.SEGMENT1 PARTY_CODE,
          XX_GET_PARTY_NAME (PARTY_ID) PARTY_NAME, -- AV.VENDOR_NAME PARTY_NAME,
          AI.VENDOR_ID,
          AI.INVOICE_NUM,
          AI.INVOICE_DATE,
          AI.GL_DATE,
          AI.CREATED_BY,
          AI.CREATION_DATE,
          AI.INVOICE_CURRENCY_CODE,
          AI.EXCHANGE_RATE,
          AI.INVOICE_AMOUNT,
          'AP INV-' || AI.DOC_SEQUENCE_VALUE VOUCHER,
             GET_GL_CODE_DESC_FROM_CCID (AD.DIST_CODE_COMBINATION_ID)
          || ','
          || XX_GET_ACCT_FLEX_SEG_DESC (5, GC.SEGMENT5, GC.SEGMENT4),
          GET_GL_DESC_FROM_CCID (AD.DIST_CODE_COMBINATION_ID) GL_DESC,
          get_segment_value_from_ccid (AD.DIST_CODE_COMBINATION_ID, 4)
             ACCOUNT_CODE,
          AD.DESCRIPTION DESCRIPTION,
          NVL (NVL (XX_GET_AP_DFF_ALL_INFO (AI.INVOICE_ID,
                                            AD.INVOICE_DISTRIBUTION_ID,
                                            AD.ATTRIBUTE_CATEGORY,
                                            AD.ATTRIBUTE1),
                    XX_GET_AP_DFF_ALL_INFO (AI.INVOICE_ID,
                                            AIL.LINE_NUMBER,
                                            AIL.ATTRIBUTE_CATEGORY,
                                            AIL.ATTRIBUTE1)),
               AD.ATTRIBUTE2 || '-' || AD.ATTRIBUTE3 || '-' || AD.ATTRIBUTE4)
             DFF_INFO,
          GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0),
          (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))),
          (CASE
              WHEN (NVL (AD.BASE_AMOUNT, AD.AMOUNT)) > 0 THEN 'DR'
              ELSE 'CR'
           END)
             DRCR_FLAG,
          GC.SEGMENT3 COST_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (3, GC.SEGMENT3) COST_CENTER,
          GC.SEGMENT5 SUB_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (5, GC.SEGMENT5, GC.SEGMENT4) SUB_ACCOUNT,
          GC.SEGMENT6 PROJECT_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (6, GC.SEGMENT6) PROJECT_NAME,
          GC.SEGMENT7 INTER_COM_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (7, GC.SEGMENT7) INTER_COMPANY,
          AD.DIST_CODE_COMBINATION_ID,
          AD.ATTRIBUTE_CATEGORY,
          AD.ATTRIBUTE1,
          AD.ATTRIBUTE2,
          AD.ATTRIBUTE3,
          AD.ATTRIBUTE4,
          AD.ATTRIBUTE5,
          AD.RCV_TRANSACTION_ID,
          AIL.PO_HEADER_ID,
          LCD.LC_ID,
          LCD.LC_NUMBER,
          LCD.PO_NUMBER,
          LCD.BANK_NAME,
          LCD.SUPPLIER_NAME,
          AD.ATTRIBUTE3 GRN_NUMBER
     FROM AP_INVOICES_ALL AI,
          AP_INVOICE_DISTRIBUTIONS_ALL AD,
          GL_CODE_COMBINATIONS GC,
          AP_INVOICE_LINES_ALL AIL,
          XX_LC_DETAILS LCD
    WHERE     AI.INVOICE_ID = AD.INVOICE_ID
          AND AD.DIST_CODE_COMBINATION_ID = GC.CODE_COMBINATION_ID
          AND AD.LINE_TYPE_LOOKUP_CODE NOT IN ('PREPAY', 'ERV')
          AND AIL.INVOICE_ID = AD.INVOICE_ID
          AND AIL.LINE_NUMBER = AD.INVOICE_LINE_NUMBER
          AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
          AND NVL (AD.BASE_AMOUNT, AD.AMOUNT) <> 0
          AND XX_GET_INVOICE_STATUS (AI.INVOICE_ID) NOT IN
                 ('Needs Revalidation', 'Never Validated', 'Unpaid')
          AND TO_CHAR (LCD.LC_ID) = AD.ATTRIBUTE1
          AND AI.ORG_ID = LCD.ORG_ID
          AND AD.ATTRIBUTE_CATEGORY = 'LC Details'
          AND AI.INVOICE_TYPE_LOOKUP_CODE = 'PREPAYMENT'
          --and ad.SET_OF_BOOKS_ID = 2021  and ad.DIST_CODE_COMBINATION_ID = 14026 and ad.PERIOD_NAME = 'Oct-18' and  ad.invoice_id=512962
            AND AI.ORG_ID = :P_ORG_ID
            AND LCD.LC_NUMBER = :P_LC_NUMBER         
   UNION ALL
   SELECT 
          AI.ORG_ID,
          GC.SEGMENT1,
          GET_FLEX_VALUES_FROM_FLEX_ID (
             GET_SEGMENT_VALUE_FROM_CCID (AD.DIST_CODE_COMBINATION_ID, 1),
             1)
             BAL_SEG_NAME,
          GC.SEGMENT2 UNIT_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (2, GC.SEGMENT2, GC.SEGMENT1) UNIT_NAME,
          AI.INVOICE_ID,
          NULL COST_FACTOR_ID,
          AI.PARTY_ID,
          --  AI.PARTY_SITE_ID,
          AV.SEGMENT1 PARTY_CODE,
          AV.VENDOR_NAME PARTY_NAME,
          AI.VENDOR_ID,
          AI.INVOICE_NUM,
          AI.INVOICE_DATE,
          AI.GL_DATE,
          AI.CREATED_BY,
          AI.CREATION_DATE,
          AI.INVOICE_CURRENCY_CODE,
          AI.EXCHANGE_RATE,
          AI.INVOICE_AMOUNT,
          'AP INV-' || AI.DOC_SEQUENCE_VALUE VOUCHER,
             GET_GL_CODE_DESC_FROM_CCID (AD.DIST_CODE_COMBINATION_ID)
          || ','
          || XX_GET_ACCT_FLEX_SEG_DESC (5, GC.SEGMENT5, GC.SEGMENT4),
          GET_GL_DESC_FROM_CCID (AD.DIST_CODE_COMBINATION_ID) GL_DESC,
          get_segment_value_from_ccid (AD.DIST_CODE_COMBINATION_ID, 4)
             ACCOUNT_CODE,
          AI.DESCRIPTION DESCRIPTION,
          NVL (NVL (XX_GET_AP_DFF_ALL_INFO (AI.INVOICE_ID,
                                            AD.INVOICE_DISTRIBUTION_ID,
                                            AD.ATTRIBUTE_CATEGORY,
                                            AD.ATTRIBUTE1),
                    XX_GET_AP_DFF_ALL_INFO (AI.INVOICE_ID,
                                            AIL.LINE_NUMBER,
                                            AIL.ATTRIBUTE_CATEGORY,
                                            AIL.ATTRIBUTE1)),
               AD.ATTRIBUTE2 || '-' || AD.ATTRIBUTE3 || '-' || AD.ATTRIBUTE4)
             DFF_INFO,
          GREATEST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0),
          (0 - (LEAST (NVL (AD.BASE_AMOUNT, AD.AMOUNT), 0))),
          (CASE
              WHEN (NVL (AD.BASE_AMOUNT, AD.AMOUNT)) > 0 THEN 'DR'
              ELSE 'CR'
           END)
             DRCR_FLAG,
          GC.SEGMENT3 COST_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (3, GC.SEGMENT3) COST_CENTER,
          GC.SEGMENT5 SUB_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (5, GC.SEGMENT5, GC.SEGMENT4) SUB_ACCOUNT,
          GC.SEGMENT6 PROJECT_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (6, GC.SEGMENT6) PROJECT_NAME,
          GC.SEGMENT7 INTER_COM_CODE,
          XX_GET_ACCT_FLEX_SEG_DESC (7, GC.SEGMENT7) INTER_COMPANY,
          AD.DIST_CODE_COMBINATION_ID,
          AD.ATTRIBUTE_CATEGORY,
          AD.ATTRIBUTE1,
          AD.ATTRIBUTE2,
          AD.ATTRIBUTE3,
          AD.ATTRIBUTE4,
          AD.ATTRIBUTE5,
          NULL RCV_TRANSACTION_ID,
          AIL.PO_HEADER_ID,
          LCD.LC_ID,
          LCD.LC_NUMBER,
          LCD.PO_NUMBER,
          LCD.BANK_NAME,
          LCD.SUPPLIER_NAME,
          AD.ATTRIBUTE3 GRN_NUMBER
     FROM AP_INVOICES_ALL AI,
          AP_INVOICE_DISTRIBUTIONS_ALL AD,
          AP_INVOICE_LINES_ALL AIL,
          GL_CODE_COMBINATIONS GC,
          AP_SUPPLIERS AV,
          XX_LC_DETAILS LCD
    WHERE     AI.INVOICE_ID = AD.INVOICE_ID
          AND AD.DIST_CODE_COMBINATION_ID = GC.CODE_COMBINATION_ID
          AND AD.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
          AND AIL.INVOICE_ID = AD.INVOICE_ID
          AND AIL.LINE_NUMBER = AD.INVOICE_LINE_NUMBER
          AND AI.CANCELLED_DATE IS NULL
          AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
          AND NVL (AD.BASE_AMOUNT, AD.AMOUNT) <> 0
          AND XX_GET_INVOICE_STATUS (AI.INVOICE_ID) NOT IN
                 ('Needs Revalidation', 'Never Validated', 'Unpaid')
          AND AI.VENDOR_ID = AV.VENDOR_ID
          AND TO_CHAR (LCD.LC_ID) = AD.ATTRIBUTE1
          AND AI.ORG_ID = LCD.ORG_ID
          AND LCD.LC_ID IS NOT NULL
          AND AD.ATTRIBUTE_CATEGORY = 'LC Details'
        --  and ad.SET_OF_BOOKS_ID = 2021  and ad.DIST_CODE_COMBINATION_ID = 14026 and ad.PERIOD_NAME = 'Oct-18' and  ad.invoice_id=512962
          AND AI.VENDOR_ID = AV.VENDOR_ID
            AND AI.ORG_ID = :P_ORG_ID
            AND LCD.LC_NUMBER = :P_LC_NUMBER
   ORDER BY INVOICE_ID,ACCOUNT_CODE DESC;

 
 --===========================================
 
 
 


select * from xx_LC_DETAILS where LC_ID=10078




 select * from GMF_XLA_EXTRACT_HEADERS
  
  select * from XLA_AE_HEADERS
  
  SELECT * FROM XLA_AE_LINES
  
  select * from XLA_EVENTS
  
  SELECT * FROM XLA_AE_DISTRIBUTIONS_ALL
  
  SELECT * FROM AP_INVOICES_ALL where INVOICE_ID =450736
  
  
  SELECT * FROM AP_INVOICE_DISTRIBUTIONS_ALL WHERE ATTRIBUTE1= '10078' and org_id=104
  
    --v2 add  XLA_AE_LINES
    select XL.*
  from AP_INVOICES_ALL AI, AP_INVOICE_DISTRIBUTIONS_ALL AD,XLA_AE_HEADERS XH ,XLA_AE_LINES XL
  WHERE AI.INVOICE_ID=AD.INVOICE_ID
  AND XH.DOC_SEQUENCE_VALUE = AI.DOC_SEQUENCE_VALUE
  and XH.AE_HEADER_ID = XL.AE_HEADER_ID
  and ad.ATTRIBUTE1= '10078' 
  and ad.org_id=104
  and AI.INVOICE_ID =450736
  
  --v1 add  XLA_AE_HEADERS
    select AI.INVOICE_ID,AD.INVOICE_ID 
  from AP_INVOICES_ALL AI, AP_INVOICE_DISTRIBUTIONS_ALL AD,XLA_AE_HEADERS XH 
  WHERE AI.INVOICE_ID=AD.INVOICE_ID
  AND XH.DOC_SEQUENCE_VALUE = AI.DOC_SEQUENCE_VALUE
  and ad.ATTRIBUTE1= '10078' 
  and ad.org_id=104
  and AI.INVOICE_ID =450736
  
  
  
  --- MAIN
  select AI.INVOICE_ID,AD.INVOICE_ID 
  from AP_INVOICES_ALL AI, AP_INVOICE_DISTRIBUTIONS_ALL AD
  WHERE AI.INVOICE_ID=AD.INVOICE_ID
  and ad.ATTRIBUTE1= '10078' 
  and ad.org_id=104
   and AI.INVOICE_ID =450736
  
  
  SELECT * FROM XLA_AE_HEADERS
  
  SELECT * FROM XLA_AE_LINES
  
  SELECT AH.AE_HEADER_ID ,AH.ENTITY_ID,GA.EVENT_ID,GA.OPERATING_UNIT,GA.INVENTORY_ITEM_ID,GA.TRANSACTION_QUANTITY,GA.TRANSACTION_UOM , AH.DESCRIPTION, AH.DOC_SEQUENCE_VALUE,AH.PERIOD_NAME 
    FROM  XLA_AE_HEADERS AH, GMF_XLA_EXTRACT_HEADERS GA
    WHERE  AH.AE_HEADER_ID(+)= GA.EVENT_ID
    and GA.EVENT_ID=1450923
  
  
  
  
  
  14014       103.01.0000.2010201.001.0000.000.000.000.000
642555       103.01.2006.2010201.001.0000.000.000.000.000
652554      103.01.5002.2010201.001.0000.000.000.000.000




select * from  gl_code_combinations_kfv where SEGMENT4 = 2010201


select * from AP_INVOICES_ALL WHERE DOC_SEQUENCE_VALUE = 80000679

SELECT * FROM AP_INVOICE_LINES_ALL 

SELECT *  FROM AP_INVOICE_DISTRIBUTIONS_ALL

SELECT * FROM XLA_AE_HEADERS XH

SELECT * FROM XLA_AE_LINES XL

SELECT * FROM GMF_XLA_EXTRACT_HEADERS XTH

SELECT * FROM MTL_MATERIAL_TRANSACTIONS

SELECT  * from GMF_XLA_EXTRACT_HEADERS XTH 


SELECT * FROM XLA_AE_HEADERS XH, XLA_AE_LINES XL, GMF_XLA_EXTRACT_HEADERS XTH , AP_INVOICES_ALL AI, AP_INVOICE_LINES_ALL AL, XX_LC_DETAILS LC --, AP_INVOICE_DISTRIBUTIONS_ALL AD
WHERE XH.AE_HEADER_ID = XL.AE_HEADER_ID
and XTH.EVENT_ID = XH.EVENT_ID
and AI.DOC_SEQUENCE_VALUE(+)= XH.DOC_SEQUENCE_VALUE
and AI.INVOICE_ID(+)= AL.INVOICE_ID
AND LC.PO_HEADER_ID = AL.PO_HEADER_ID
--AND AI.INVOICE_ID(+)= AD.INVOICE_ID
--AND AL.INVOICE_ID(+)= AD.INVOICE_ID
and XL.CODE_COMBINATION_ID IN  (14014,642555,652554)
and XTH.EVENT_TYPE_CODE in ('LC_ADJUST_VALUATION',
'LC_ADJUST_RECEIVE','LC_ADJUST_DELIVER' )
and XH.PERIOD_NAME = 'Sep-18' 
--and XL.ENTERED_DR <> 0
and lc.lc_id= 10078
--and AD.attribute1 = '10078'



SELECT * FROM XLA_AE_HEADERS XH, XLA_AE_LINES XL, GMF_XLA_EXTRACT_HEADERS XTH , AP_INVOICES_ALL AI  --,   AP_INVOICE_DISTRIBUTIONS_ALL AD --AP_INVOICE_LINES_ALL AL
WHERE XH.AE_HEADER_ID = XL.AE_HEADER_ID
and XTH.EVENT_ID = XH.EVENT_ID
and AI.DOC_SEQUENCE_VALUE(+)= XH.DOC_SEQUENCE_VALUE
--and AI.INVOICE_ID(+)= AL.INVOICE_ID
--AND AI.INVOICE_ID(+)= AD.INVOICE_ID
--AND AL.INVOICE_ID(+)= AD.INVOICE_ID
--and XL.CODE_COMBINATION_ID IN  (14014,642555,652554)
--and XH.PERIOD_NAME = 'Sep-18'
--and AD.attribute1 = '10078'
--and AD.attribute1 is not null 
--and XH.AE_HEADER_ID  IN(23113999,
--23126884,
--23156977,
--23112551)
--AND XH.EVENT_ID IN (1450923)


--=================================

select * from GMF_XLA_EXTRACT_HEADERS where EVENT_TYPE_CODE IN ('LC_ADJUST_DELIVER',      -- HEADER_ID, EVENT_ID, TRANSACTION_ID, EVENT_TYPE_CODE , SOURCE_LINE_ID
'LC_ADJUST_VALUATION',
'LC_ADJUST_RECEIVE')
and ORGANIZATION_ID = 166
and TRANSACTION_ID = 658
--and SOURCE_DOCUMENT_ID = 670
--and transaction_id in (317395,
--317396,
--317397,
--317398,
--317399,
--317400,
--317401,
--317402
--)

select * from XLA_AE_HEADERS where EVENT_ID in (1450923)

SELECT XL.* FROM XLA_AE_HEADERS XH, XLA_AE_LINES XL
WHERE XH.AE_HEADER_ID = XL.AE_HEADER_ID
and XH.AE_HEADER_ID in(
20453342,
23113999)
AND XH.EVENT_ID IN (1450923)



select  * from rcv_transactions where PO_HEADER_ID=74145

select * from GMF_LC_ADJ_HEADERS_V where SHIP_HEADER_ID= 670 



--=================================
Select * from PO_HEADERS_ALL WHERE SEGMENT1= 40000195 and  org_id = 104    -- header_id 74145

select * from xx_lc_details where po_number = 40000195 and  org_id = 104   -- LC_NUMBER  ILC0801180212207

select * from RCV_SHIPMENT_HEADERS where SHIPMENT_HEADER_ID in (438251,
438253,
438257,
438255)

select * from RCV_SHIPMENT_LINES where PO_HEADER_ID=74145

select * from rcv_transactions where SHIPMENT_HEADER_ID in (438251,
438253,
438257,
438255)
and TRANSACTION_TYPE = 'DELIVER'


select * from mtl_material_transactions where RCV_TRANSACTION_ID IN(317396,
317398,
317402,
317400)


select distinct(EVENT_TYPE_CODE) from GMF_XLA_EXTRACT_HEADERS where transaction_id in (1456535,
1456539,
1456543,
1456547)

select * from GMF_XLA_EXTRACT_HEADERS where EVENT_TYPE_CODE IN ('LC_ADJUST_DELIVER',
'LC_ADJUST_VALUATION',
'LC_ADJUST_RECEIVE')
and ORGANIZATION_ID = 166

and SOURCE_DOCUMENT_ID = 670

select * from XLA_AE_HEADERS where EVENT_ID in (1450923,1891483,
1891386,
1891963,
1891438)


select * from XLA_AE_LINES where AE_HEADER_ID IN(23113999,
23126884,
23156977,
23112551)





select * from GMF_LC_ADJ_DETAILS_V  where SHIP_HEADER_ID= 670

select * from GMF_XLA_LC_ADJS_V  where RCV_TRANSACTION_ID IN(317396,
317398,
317402,
317400)
and lc_ship_num = 658



select * from tab
where tname like '%GMF%LC%' and tabtype = 'VIEW'

select * from GMF_LC_ADJ_HEADERS_V where SHIP_HEADER_ID= 670 and ADJUSTMENT_NUM = 3

select * from GMF_END_PHC_LCM_INT_UAC_TXNS_V  -- LC_ABSORPTION_ACCOUNT_ID


--==== INVOICE===

select * from AP_INVOICES_ALL

SELECT * FROM AP_INVOICE_LINES_ALL where PO_HEADER_ID = 74145

select * from GMF_LC_ADJ_DETAILS_V   --SHIP_HEADER_ID, SHIP_LINE_ID, MATCH_ID ,INVOICE_NUM,INVOICE_DISTRIBUTION_ID


SELECT * FROM gmf_xla_extract_headers  --HEADER_ID , EVENT_ID, LEGAL_ENTITY_ID, TRANSACTION_ID , INVENTORY_ITEM_ID, ORGANIZATION_ID

SELECT * FROM gmf_xla_extract_lines 

SELECT * FROM XLA_AE_HEADERS
WHERE ENTITY_ID=298820 --- From this table copy value Event id 1068826 and ae_header_id value 27994523

SELECT * FROM XLA_AE_LINES  


select * from xla_events
WHERE EVENT_ID=333062


SELECT * FROM INL_SHIP_HEADERS_ALL where ship_num= '658'

SELECT * FROM INL_SHIP_LINES_ALL where SHIP_HEADER_ID = 670  -- line id 837 , 4193 , MATCH_ID 5473

select * from INL_MATCHES where MATCH_ID =5473   --  SHIP_HEADER_ID 670 , MATCH_INT_ID  3379, ADJUSTMENT_NUM 3

--select * from INL_ADJUSTMENTS_ALL

SELECT * FROM INL_MATCH_AMOUNTS 

SELECT * FROM INL_ALLOCATIONS where SHIP_HEADER_ID = 670  and  SHIP_LINE_ID in (837,
4193) -- ALLOCATION_ID, SHIP_HEADER_ID, SHIP_LINE_ID, ADJUSTMENT_NUM, :FROM_PARENT_TABLE_NAME: INL_SHIP_LINES,INL_CHARGE_LINES

SELECT * FROM INL_ALLOCATIONS where SHIP_HEADER_ID = 670  and  SHIP_LINE_ID  =4193

select * from INL_CHARGE_HEADERS

select * from INL_CHARGE_LINES where ADJUSTMENT_NUM= 3 -- MATCH_ID = 5473    -- PARTY_ID, PARTY_SITE_ID

select * from INL_ASSOCIATIONS where SHIP_HEADER_ID = 670 

select * from INL_ALWD_LINE_TYPES  

--====================EBS LC Ledger Details History==========================
SELECT 
   A.LC_ID,
   A.LC_NUMBER,
   --XX_GET_HR_OPERATING_UNIT (B.ORG_ID) OPERATING_UNIT,
   A.SUPPLIER_NAME LC_SUPPLIER_NAME,
   A.PO_NUMBER LC_PO_NUMBER,
   A.PO_HEADER_ID,
   A.LC_TYPE,
   A.LC_OPENING_DATE,
   A.LC_STATUS,
   A.LC_VALUE,
  A.CURRENCY_CODE || '@' ||  A.EXCHANGE_RATE  LC_INVOICE_CURRENCY ,   
  B.INVOICE_ID,
   B.ORG_ID,
   B.BAL_SEG,
   B.BAL_SEG_NAME,
   B.INVOICE_ID,
   B.COST_FACTOR_ID,
   B.PARTY_NAME,
   B.VENDOR_ID,
   --B.CHECK_NUMBER,
  -- B.CHECK_DATE,
   B.GL_DATE,
   B.CREATED_BY,
   B.CREATION_DATE,
   B.CURRENCY_CODE,
   B.EXCHANGE_RATE,
   B.VOUCHER,
   B.GL_CODE_AND_DESC,
   B.GL_DESC,
   B.ACCOUNT_CODE,
   B.SUB_ACCOUNT,
                     (  DECODE (B.COST_CENTER, NULL, NULL, B.COST_CENTER)
                     || DECODE (B.PROJECT_NAME, NULL, NULL, '-' || B.PROJECT_NAME)
                     || DECODE (B.INTER_COMPANY, NULL, NULL, '-' || B.INTER_COMPANY)
                    || DECODE (B.DESCRIPTION, NULL, NULL, '-' || B.DESCRIPTION))
               --     || DECODE (B.LC_NUMBER, NULL, NULL, '-' || B.LC_NUMBER))
               ADD_DESCRIPTION,
   B.DR_AMOUNT,
   B.CR_AMOUNT,
   B.DRCR_FLAG,
   B.PO_NUMBER,
  --B.RECEIPT_NUMBER,
 --  B.BANK_ACCOUNT_NAME,
   B.ATTRIBUTE1,
    B.ATTRIBUTE2,
    B.ATTRIBUTE3,
    B.ATTRIBUTE4,
   XX_INV_PKG.XXGET_ENAME(:P_USER_ID) USER_NAME
   FROM XX_LC_DETAILS  A , XX_AP_LC_DETAILS_HIS_VK B
   WHERE 1=1
    AND B.LC_ID =A.LC_ID
   AND  B.BAL_SEG=:P_COMPANY
    AND A.LC_ID=NVL(:P_LC_ID,A.LC_ID)
    AND (:P_ACCOUNT_CODE IS NULL OR B.ACCOUNT_CODE=NVL(:P_ACCOUNT_CODE,B.ACCOUNT_CODE))
  AND  (:P_DATE_FROM  IS NULL OR B.GL_DATE BETWEEN :P_DATE_FROM  AND :P_DATE_TO) 
 -- AND B.ATTRIBUTE1 IS NOT NULL
    ORDER BY GL_DATE,VOUCHER ASC


 














-- =====================28-jun-2020====================================================
--LC:2355-20-02-0025 , 2355-20-02-0001   EI LC ER AGAINST A JEKHANE JEKHANE  INVOICE DISTRIBUTIONS A ATTRIBUTE1 

SELECT ad.attribute1 LC_ID, LC.LC_NUMBER,LC.PO_NUMBER,AI.ORG_ID, AI.INVOICE_ID,XXLA.ENTITY_ID, XAL.ENTERED_DR, XAL.ENTERED_CR,XAL.ACCOUNTED_DR, XAL.ACCOUNTED_CR, XAL.DESCRIPTION,
 AI.DOC_SEQUENCE_VALUE VOUCHER_NUMBER
FROM AP_INVOICES_ALL AI, AP_INVOICE_LINES_ALL AL, AP_INVOICE_DISTRIBUTIONS_ALL AD,XLA.xla_transaction_entities XXLA, XLA_AE_HEADERS XAH, XLA_AE_LINES XAL, XX_LC_DETAILS LC
WHERE 1=1
AND AI.INVOICE_ID= AL.INVOICE_ID
and AI.INVOICE_ID = ad.INVOICE_ID
and AL.INVOICE_ID = AD.INVOICE_ID
AND LC.LC_ID= AD.ATTRIBUTE1
and XXLA.source_id_int_1 = AI.INVOICE_ID
and XXLA.ENTITY_ID = XAH.ENTITY_ID
AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
and AI.DOC_SEQUENCE_VALUE = XAH.DOC_SEQUENCE_VALUE
--AND AI.INVOICE_ID='1418419'
AND AD.ATTRIBUTE1= '10078'  -- '10644'  


--================================================================



SELECT BAL_SEG_NAME OU_NAME ,  INVOICE_ID,GL_DATE "VOUCHER DATE", VOUCHER "VOUCHER NO", INVOICE_NUM "INVOICE NO" , 
ACCOUNT_CODE "ACCOUNT CODE" ,DFF_INFO||'/'||DESCRIPTION "ACCOUNT DESCRIPTION" , CURRENCY_CODE "CURRENCY",
DR_AMOUNT, CR_AMOUNT, PARTY_CODE "Invoice Party Code" , PARTY_NAME "Invoice Party Name" , LC_NUMBER "LC_NO" , PO_NUMBER "PO_NUMBER", SUPPLIER_NAME "Po Party Name"
 FROM XX_AP_LC_DETAILS_HIS_VK 
where LC_number= 'ILC0801180212207' 



--==========================================================================

--LC: 2355-20-02-0001   EI LC ER AGAINST A JEKHANE JEKHANE  INVOICE DISTRIBUTIONS A ATTRIBUTE1 


SELECT * FROM  AP_INVOICES_ALL where INVOICE_ID='1401666'

SELECT * FROM  AP_INVOICE_LINES_ALL where INVOICE_ID='1401666'

select *  from ap_invoice_distributions_all
where invoice_id=1401666;

select *  from ap_invoice_distributions_all
where ATTRIBUTE1='10078'



select * from XLA.xla_transaction_entities
where source_id_int_1=370898
and TRANSACTION_NUMBER='2355-20-02-0001'

SELECT * FROM XLA_AE_HEADERS
WHERE ENTITY_ID=904044 --- From this table copy value Event id 1068826 and ae_header_id value 27994523

select * from xla_events
WHERE EVENT_ID=1068826
--and AE_HEADER_ID = '27994523'

select * from xla_ae_lines
WHERE AE_HEADER_ID=27994523;

SELECT *
from gl_import_references gir
where gir.gl_sl_link_id in
(select gl_sl_link_id from xla_ae_lines
WHERE AE_HEADER_ID='27994523') -- from this table you will get detail for je_header_id, je_line_num, je_batch_id

--===========================================================================

select * from PO_HEADERS_ALL WHERE PO_HEADER_ID =  844444

select * from PO_LINES_ALL WHERE PO_HEADER_ID =  844444

select DISTINCT * from PO_LINE_LOCATIONS_ALL WHERE PO_HEADER_ID =  844444  

select DISTINCT SHIP_TO_ORGANIZATION_ID from PO_LINE_LOCATIONS_ALL WHERE PO_HEADER_ID =  844444  

SELECT * FROM ORG_ORGANIZATION_DEFINITIONS where ORGANIZATION_ID =  219

select * from AP_INVOICES_ALL

SELECT * FROM XX_AP_LC_DETAILS_HIS_VK 
where LC_number= '2355-20-02-0001'

select * from XX_LC_DETAILS where LC_number= 'ILC0801180212207'


--===============================================================================

select * from  GL_JE_LINES A

select * from XX_BAL_SEG_INFO B

select * from GL_CODE_COMBINATIONS C

select *from  GL_JE_HEADERS D

select * from  GL_JE_HEADERS D where  JE_SOURCE = 'Assets'


select * from XX_BAL_SEG_INFO


select  XX_GET_ACCT_FLEX_SEG_DESC(4,SEGMENT4)||'-'||SEGMENT4  ACCOUNT_DESC, 
XX_GET_ACCT_FLEX_SEG_DESC (5, SEGMENT5,SEGMENT4) SUB_ACCOUNT,CODE_COMBINATION_ID  from GL_CODE_COMBINATIONS where SEGMENT4 = 2010201


select * from FND_FLEX_VALUES_VL

  
select * from  XLA_AE_HEADERS 
where event_type_code in( 'LC_ADJUST_DELIVER',
'LC_ADJUST_RECEIVE',
'LC_ADJUST_VALUATION')
order by EVENT_TYPE_CODE
      
 select * FROM XLA_AE_LINES A
 
select * from mtl_material_transactions

select distinct(EVENT_TYPE_CODE) from gmf_xla_extract_headers order by EVENT_TYPE_CODE


select * from gmf_xla_extract_headers where event_TYPE_CODE IN('LC_ADJUST_DELIVER','LC_ADJUST_RECEIVE','LC_ADJUST_VALUATION') and OPERATING_UNIT = 104

select * from gmf_xla_extract_lines where ORGANIZATION_ID = 166 






select * from gmf_xla_extract_headers

select * from gmf_xla_extract_lines

Transaction_id=Transaction_id

SELECT   D.BAL_SEG, D.BAL_SEG_NAME,A.EVENT_TYPE_CODE,B.ENTERED_DR,B.ENTERED_CR,B.ACCOUNTED_DR,B.ACCOUNTED_CR, A.ACCOUNTING_DATE,A.GL_TRANSFER_DATE, COMPLETED_DATE,
DECODE(EVENT_TYPE_CODE,'CE_BAT_CLEARED','CM'||'-'||SUBSTR(B.DESCRIPTION,62,5),NULL)  VOUCHER_NUMBER 
 FROM  XLA_AE_HEADERS A ,  XLA_AE_LINES B,XX_BAL_SEG_INFO D
WHERE  A.AE_HEADER_ID=B.AE_HEADER_ID
AND A.EVENT_TYPE_CODE IN( 'LC_ADJUST_DELIVER',
'LC_ADJUST_RECEIVE',
'LC_ADJUST_VALUATION')
AND A.ACCOUNTING_DATE BETWEEN  '01-JAN-2019' and '01-JAN-2019' 
AND B.LEDGER_ID=D.LEDGER_ID

--opening dr + receving de = closing dr


--=================================================================================================================

--  FOR AREFIN VAI (LC _IN TRANSIT PURPOSE RECONCILITION PURPOSE)
-- SOURCE FROM EBS Accounts Wise Ledger
-- :P_ACCOUNT_CODE: 2010201
-- :P_BAL_SEG: 101

SELECT D.BAL_SEG, D.BAL_SEG_NAME,B.LEDGER_ID,A.ACCOUNTING_DATE,
--DECODE(A.APPLICATION_ID, 200,'AP-'||DOC_SEQUENCE_VALUE, 222,'AR-'||DOC_SEQUENCE_VALUE, DOC_SEQUENCE_VALUE) VOUCHER_NUMBER
 DECODE(EVENT_TYPE_CODE, 'REFUND RECORDED','AP PAY','PAYMENT CREATED','AP PAY','PAYMENT CLEARED','AP PAY','PAYMENT CANCELLED','AP PAY','REFUND CANCELLED','AP PAY',
          'PREPAYMENT APPLIED','AP INV','PREPAYMENT CANCELLED','AP INV','CREDIT MEMO VALIDATED','AP INV','INVOICE CANCELLED','AP INV',
          'PREPAYMENT UNAPPLIED','AP INV','INVOICE VALIDATED','AP INV','PREPAYMENT VALIDATED','AP INV','CREDIT MEMO CANCELLED','AP INV',
          'CM_CREATE','AR INV','DM_CREATE','AR INV','INV_CREATE','AR INV','CM_UPDATE','AR INV','RECP_CREATE','AR RCV',
          'MISC_RECP_CREATE','AR RCV','MISC_RECP_REVERSE','AR RCV','RECP_REVERSE','AR RCV','RECP_UPDATE','AR RCV')
          ||DECODE(DOC_SEQUENCE_VALUE,NULL,NULL,'-'||DOC_SEQUENCE_VALUE)
          ||DECODE(EVENT_TYPE_CODE,'CE_BAT_CLEARED','CM'||'-'||SUBSTR(B.DESCRIPTION,62,5),NULL)  VOUCHER_NUMBER 
           ,EVENT_TYPE_CODE,A.AE_HEADER_ID, A.APPLICATION_ID,XX_PARTY_VENDOR_NAME_FUNCTION(A.APPLICATION_ID, PARTY_ID) PARTY_VENDOR_NAME,B.JE_CATEGORY_NAME,
           SEGMENT4,
XX_GET_ACCT_FLEX_SEG_DESC(4,SEGMENT4) ACCOUNT_DESC, 
XX_GET_ACCT_FLEX_SEG_DESC (5, SEGMENT5,SEGMENT4) SUB_ACCOUNT,
PARTY_ID,
           XX_OPOSITE_HEAD_FUNCTION(:P_ACCOUNT_CODE, A.AE_HEADER_ID) OPOSITE_HEAD,
     DECODE( XX_AP_DFF_FUNCTION(DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID, B.EVENT_ID) ,  NULL , NULL, XX_AP_DFF_FUNCTION(DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID, B.EVENT_ID)||'.')
    ||   DECODE( XX_FIN_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID) ,  NULL , NULL, XX_FIN_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID)||'.' )
    ||   DECODE( XX_AP_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID,B.JE_CATEGORY_NAME) ,  NULL , NULL,
    XX_AP_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID,B.JE_CATEGORY_NAME)||'.' ) DFF_INFO,
        NVL(SUM(ACCOUNTED_DR),0) DR_AMT,NVL(SUM(ACCOUNTED_CR),0) CR_AMT 
           FROM XLA_AE_LINES A, XLA_AE_HEADERS B, GL_CODE_COMBINATIONS C, XX_BAL_SEG_INFO D
           WHERE C.CODE_COMBINATION_ID=A.CODE_COMBINATION_ID
           AND  A.AE_HEADER_ID=B.AE_HEADER_ID
           AND SEGMENT4=:P_ACCOUNT_CODE
           AND B.LEDGER_ID=D.LEDGER_ID
       --    AND A.ACCOUNTING_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
            and A.ACCOUNTING_DATE BETWEEN  '01-SEP-2018' and '01-SEP-2019'
           AND A.ACCOUNTING_DATE>'31-AUG-2018'
           AND BAL_SEG=:P_BAL_SEG
AND SEGMENT5=NVL(:P_SUB_ACC,SEGMENT5)
           GROUP BY 
           D.BAL_SEG, D.BAL_SEG_NAME,B.LEDGER_ID,A.ACCOUNTING_DATE,
            DECODE(EVENT_TYPE_CODE, 'REFUND RECORDED','AP PAY','PAYMENT CREATED','AP PAY','PAYMENT CLEARED','AP PAY','PAYMENT CANCELLED','AP PAY','REFUND CANCELLED','AP PAY',
          'PREPAYMENT APPLIED','AP INV','PREPAYMENT CANCELLED','AP INV','CREDIT MEMO VALIDATED','AP INV','INVOICE CANCELLED','AP INV',
          'PREPAYMENT UNAPPLIED','AP INV','INVOICE VALIDATED','AP INV','PREPAYMENT VALIDATED','AP INV','CREDIT MEMO CANCELLED','AP INV',
          'CM_CREATE','AR INV','DM_CREATE','AR INV','INV_CREATE','AR INV','CM_UPDATE','AR INV','RECP_CREATE','AR RCV',
          'MISC_RECP_CREATE','AR RCV','MISC_RECP_REVERSE','AR RCV','RECP_REVERSE','AR RCV','RECP_UPDATE','AR RCV')||'-'|| DOC_SEQUENCE_VALUE,DOC_SEQUENCE_VALUE,B.DESCRIPTION
           ,EVENT_TYPE_CODE,A.AE_HEADER_ID, A.APPLICATION_ID,XX_PARTY_VENDOR_NAME_FUNCTION(A.APPLICATION_ID, PARTY_ID) ,
          B.JE_CATEGORY_NAME,
           SEGMENT4,XX_GET_ACCT_FLEX_SEG_DESC(4,SEGMENT4) , PARTY_ID,
          XX_OPOSITE_HEAD_FUNCTION(:P_ACCOUNT_CODE, A.AE_HEADER_ID),
        DECODE( XX_AP_DFF_FUNCTION(DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID, B.EVENT_ID) ,  NULL , NULL, XX_AP_DFF_FUNCTION(DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID, B.EVENT_ID)||'.')
     ||   DECODE( XX_FIN_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID) ,  NULL , NULL, XX_FIN_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID)||'.' )
    ||   DECODE( XX_AP_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID,B.JE_CATEGORY_NAME) ,  NULL , NULL,
    XX_AP_INV_DESC_FUNCTION(B.APPLICATION_ID,B.DOC_SEQUENCE_VALUE, D.LEGAL_ENTITY_ID,B.JE_CATEGORY_NAME)||'.' ),
    XX_GET_ACCT_FLEX_SEG_DESC (5, SEGMENT5,SEGMENT4)
UNION ALL
SELECT B.BAL_SEG, BAL_SEG_NAME,A.LEDGER_ID, EFFECTIVE_DATE ACCOUNTING_DATE, TO_CHAR(DOC_SEQUENCE_VALUE) VOUCHER_NUMBER,NULL, NULL, NULL, NULL, NULL JE_CATEGORY_NAME,SEGMENT4,
XX_GET_ACCT_FLEX_SEG_DESC(4,SEGMENT4) ACCOUNT_DESC, 
XX_GET_ACCT_FLEX_SEG_DESC (5, SEGMENT5,SEGMENT4) SUB_ACCOUNT,
 NULL, NULL, A.DESCRIPTION ,
NVL(ACCOUNTED_DR,0) ACCOUNTED_DR, NVL(ACCOUNTED_CR,0) ACCOUNTED_CR
  FROM GL_JE_LINES A, XX_BAL_SEG_INFO B, GL_CODE_COMBINATIONS C, GL_JE_HEADERS D
   WHERE A.JE_HEADER_ID=D.JE_HEADER_ID
AND A.LEDGER_ID=B.LEDGER_ID
AND A.JE_HEADER_ID=D.JE_HEADER_ID
AND A.CODE_COMBINATION_ID=C.CODE_COMBINATION_ID
--AND EFFECTIVE_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
and EFFECTIVE_DATE BETWEEN  '01-SEP-2018' and '01-SEP-2019'
AND   SEGMENT4=:P_ACCOUNT_CODE                                                        
 AND BAL_SEG=:P_BAL_SEG
AND SEGMENT5=NVL(:P_SUB_ACC,SEGMENT5)
AND JE_SOURCE='Manual'                                                         
 ORDER BY ACCOUNTING_DATE,VOUCHER_NUMBER      
           
 


--==========================================================================================================================


-- EBS LC Ledger Details History---
--========================================

SELECT 
   A.LC_ID,
   A.LC_NUMBER,
   --XX_GET_HR_OPERATING_UNIT (B.ORG_ID) OPERATING_UNIT,
   A.SUPPLIER_NAME LC_SUPPLIER_NAME,
   A.PO_NUMBER LC_PO_NUMBER,
   A.PO_HEADER_ID,
   A.LC_TYPE,
   A.LC_OPENING_DATE,
   A.LC_STATUS,
   A.LC_VALUE,
  A.CURRENCY_CODE || '@' ||  A.EXCHANGE_RATE  LC_INVOICE_CURRENCY ,   
  B.INVOICE_ID,
   B.ORG_ID,
   B.BAL_SEG,
   B.BAL_SEG_NAME,
   B.INVOICE_ID,
   B.COST_FACTOR_ID,
   B.PARTY_NAME,
   B.VENDOR_ID,
   --B.CHECK_NUMBER,
  -- B.CHECK_DATE,
   B.GL_DATE,
   B.CREATED_BY,
   B.CREATION_DATE,
   B.CURRENCY_CODE,
   B.EXCHANGE_RATE,
   B.VOUCHER,
   B.GL_CODE_AND_DESC,
   B.GL_DESC,
   B.ACCOUNT_CODE,
   B.SUB_ACCOUNT,
                     (  DECODE (B.COST_CENTER, NULL, NULL, B.COST_CENTER)
                     || DECODE (B.PROJECT_NAME, NULL, NULL, '-' || B.PROJECT_NAME)
                     || DECODE (B.INTER_COMPANY, NULL, NULL, '-' || B.INTER_COMPANY)
                    || DECODE (B.DESCRIPTION, NULL, NULL, '-' || B.DESCRIPTION))
               --     || DECODE (B.LC_NUMBER, NULL, NULL, '-' || B.LC_NUMBER))
               ADD_DESCRIPTION,
   B.DR_AMOUNT,
   B.CR_AMOUNT,
   B.DRCR_FLAG,
   B.PO_NUMBER,
  --B.RECEIPT_NUMBER,
 --  B.BANK_ACCOUNT_NAME,
   B.ATTRIBUTE1,
    B.ATTRIBUTE2,
    B.ATTRIBUTE3,
    B.ATTRIBUTE4,
   XX_INV_PKG.XXGET_ENAME(:P_USER_ID) USER_NAME
   FROM XX_LC_DETAILS  A , XX_AP_LC_DETAILS_HIS_VK B
   WHERE 1=1
    AND B.LC_ID =A.LC_ID
   AND  B.BAL_SEG=:P_COMPANY
    AND A.LC_ID=NVL(:P_LC_ID,A.LC_ID)
    AND (:P_ACCOUNT_CODE IS NULL OR B.ACCOUNT_CODE=NVL(:P_ACCOUNT_CODE,B.ACCOUNT_CODE))
  AND  (:P_DATE_FROM  IS NULL OR B.GL_DATE BETWEEN :P_DATE_FROM  AND :P_DATE_TO) 
 -- AND B.ATTRIBUTE1 IS NOT NULL
    ORDER BY GL_DATE,VOUCHER ASC
