select SUM(TRANSACTION_QUANTITY) from MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID between 8985223 and 8986063 and INVENTORY_ITEM_ID = 428

select ORGANIZATION_ID, TRANSACTION_ID, a.CREATED_BY,  TO_CHAR(TRANSACTION_DATE,'DD-MON-RRRR') TRANSACTION_DATE ,TRANSACTION_QUANTITY, a.TRANSACTION_TYPE_ID, b.TRANSACTION_TYPE_NAME,a.ATTRIBUTE3 CHALLAN_NUMBER   
 from MTL_MATERIAL_TRANSACTIONS a, MTL_TRANSACTION_TYPES b
 where a.transaction_type_id=  b.transaction_type_id 
 --and INVENTORY_ITEM_ID= 428 
--and TRANSACTION_ID between 8985223 and 8986063 
and INVENTORY_ITEM_ID = 428
order by TRANSACTION_ID


select  ORGANIZATION_ID, TRANSACTION_ID, a.CREATED_BY, TRANSACTION_DATE,TRANSACTION_QUANTITY, a.TRANSACTION_TYPE_ID, b.TRANSACTION_TYPE_NAME,a.ATTRIBUTE3 CHALLAN_NUMBER 
 from MTL_MATERIAL_TRANSACTIONS a, MTL_TRANSACTION_TYPES b
 where a.transaction_type_id=  b.transaction_type_id 
 and INVENTORY_ITEM_ID= 428 
 and TRUNC(TRANSACTION_DATE) between '01-JAN-2021' and '14-OCT-2021'


select * from ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE= 'KOM'

select * FROM RCV_SHIPMENT_HEADERS WHERE RECEIPT_NUM= 80001454 and SHIP_TO_ORG_ID= 173

select * FROM RCV_SHIPMENT_LINES WHERE SHIPMENT_HEADER_ID =1050089