SELECT  QUANTITY  ,TO_CHAR(STATUS_DATE,'DD-MON-RRRR') STATUS_DATE
FROM MTL_TXN_REQUEST_LINES 
WHERE INVENTORY_ITEM_ID=180 -- 1851 --4271
AND  ORGANIZATION_ID  = 121
AND STATUS_DATE = (SELECT MAX(STATUS_DATE) STATUS_DATE FROM MTL_TXN_REQUEST_LINES WHERE  INVENTORY_ITEM_ID=180 -- 1851 --4271
AND  ORGANIZATION_ID  = 121)


SELECT RT.ORGANIZATION_ID , rl.shipment_header_id,QUANTITY ,TO_CHAR(RT.TRANSACTION_DATE,'DD-MON-RRRR')  -- INTO V_DATE
--MAX(RT.TRANSACTION_DATE) INTO V_DATE
FROM RCV_SHIPMENT_LINES RL , RCV_TRANSACTIONS RT
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id=180 --1851 -- P_ITEM_ID
AND RT.ORGANIZATION_ID = 121 -- P_INVORG_ID
and RT.TRANSACTION_TYPE = 'DELIVER'  
and  RT.TRANSACTION_DATE = (SELECT MAX(R.TRANSACTION_DATE)  FROM RCV_SHIPMENT_LINES  L, RCV_TRANSACTIONS R WHERE R.SHIPMENT_LINE_ID=L.SHIPMENT_LINE_ID and  L.ITEM_ID= 180 --1851 --4271
AND  R.ORGANIZATION_ID  = 121)
--GROUP BY QUANTITY

select * from rcv_transactions where shipment_header_Id=1018188 and TRANSACTION_TYPE = 'DELIVER' and 



select * from RCV_SHIPMENT_HEADERS WHERE  shipment_header_Id =1018188 

SELECT R.quantity,MAX(R.TRANSACTION_DATE)  FROM RCV_TRANSACTIONS R, RCV_SHIPMENT_LINES L WHERE  L.ITEM_ID= 1851 --4271
AND  R.ORGANIZATION_ID  = 121
GROUP BY  R.quantity



SELECT  QUANTITY ,TO_CHAR(TRUNC(MAX(RT.TRANSACTION_DATE)),'DD-MON-RRRR') -- INTO V_DATE
--MAX(RT.TRANSACTION_DATE) INTO V_DATE
FROM RCV_SHIPMENT_LINES RL , RCV_TRANSACTIONS RT
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id=1851 -- P_ITEM_ID
AND RT.ORGANIZATION_ID = 121 -- P_INVORG_ID
and RT.TRANSACTION_TYPE = 'DELIVER'
GROUP BY QUANTITY


SELECT  QUANTITY,  MAX(RT.TRANSACTION_DATE) --INTO V_DATE
--MAX(RT.TRANSACTION_DATE) INTO V_DATE
FROM RCV_SHIPMENT_LINES RL , RCV_TRANSACTIONS RT
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id=1851 -- P_ITEM_ID
AND RT.ORGANIZATION_ID = 121 -- P_INVORG_ID
and RT.TRANSACTION_TYPE = 'DELIVER'
GROUP BY QUANTITY

select MAx(RT.TRANSACTION_DATE) FROM 



--======================================================

--CREATE OR REPLACE FUNCTION GET_LAST_GRN_QTY_FROM_ITEM(P_TYPE IN number,P_ITEM IN number,P_ORG IN number,P_DATE IN date)
RETURN VARCHAR2
IS
V_NO VARCHAR2(240 BYTE);
BEGIN
SELECT DECODE(P_TYPE,1,ORGANIZATION_ID,2,QUANTITY,3,STATUS_DATE,NULL) LAST_INFO INTO V_NO
 FROM 
(
select   ORGANIZATION_ID , QUANTITY, TO_CHAR(TRUNC(STATUS_DATE),'DD-MON-RRRR') STATUS_DATE  
 FROM MTL_TXN_REQUEST_LINES 
where INVENTORY_ITEM_ID= P_ITEM --34333 --4271
and  ORGANIZATION_ID  = P_ORG -- 201
AND STATUS_DATE <= P_DATE
order by STATUS_DATE desc  
)
WHERE rownum <2;
RETURN V_NO;
EXCEPTION
WHEN OTHERS THEN
RETURN NULL;
END;
/
--=================== V3 READY FOR BOKTIAR SIR================
select * from rcv_shipment_headers 

select * from rcv_shipment_lines

select * from MTL_ITEM_CATEGORIES_V

select * from MTL_TXN_REQUEST_LINES where INVENTORY_ITEM_ID  = 36055 --771089 

select * from MTL_TXN_REQUEST_HEADERS WHERE HEADER_ID =1454398

--and STATUS_DATE = ''
ORDER BY STATUS_DATE desc

select QUANTITY_DELIVERED ,MAX(STATUS_DATE)
--  (SELECT SUM(QUANTITY_DELIVERED) FROM MTL_TXN_REQUEST_LINES S WHERE S.INVENTORY_ITEM_ID = INVENTORY_ITEM_ID s.organization_id = organization_id ) test
 from MTL_TXN_REQUEST_LINES where INVENTORY_ITEM_ID  = 1054  and organization_id=121 -- 163 
--and STATUS_DATE = (SELECT MAX(STATUS_DATE) FROM MTL_TXN_REQUEST_LINES)--121

SELECT  QUANTITY_DELIVERED  ,TO_CHAR(STATUS_DATE,'DD-MON-RRRR') STATUS_DATE
FROM MTL_TXN_REQUEST_LINES 
WHERE INVENTORY_ITEM_ID= 25951 --4271
AND  ORGANIZATION_ID  = 121
AND STATUS_DATE = (SELECT MAX(STATUS_DATE) STATUS_DATE FROM MTL_TXN_REQUEST_LINES WHERE  INVENTORY_ITEM_ID= 25951 --4271
AND  ORGANIZATION_ID  = 121)

SELECT SUM(rl.quantity_shipped) FROM RCV_SHIPMENT_LINES 

SELECT SUM(rl.quantity_shipped) FROM RCV_SHIPMENT_LINES rl, RCV_TRANSACTIONS rt  WHERE rl.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID and rl.SHIPMENT_LINE_ID= rt.SHIPMENT_LINE_ID AND TRANSACTION_TYPE= 'DELIVER'
and rl.ITEM_ID=1054
and rt.ORGANIZATION_ID= 121
and rt.TRANSACTION_DATE = (SELECT  MAX(rtt.TRANSACTION_DATE) FROM RCV_TRANSACTIONS rtt, RCV_SHIPMENT_LINES rll WHERE rtt.SHIPMENT_HEADER_ID = rll.SHIPMENT_HEADER_ID and rtt.SHIPMENT_LINE_ID = rll.SHIPMENT_LINE_ID
and rtt.SHIPMENT_HEADER_ID =  rl.SHIPMENT_HEADER_ID and rtt.SHIPMENT_LINE_ID = rl.SHIPMENT_LINE_ID AND rtt.TRANSACTION_TYPE= 'DELIVER' and rll.item_id= rl.item_id 
--and rtt.organigation_id= rt.organigation_id
and rtt.organization_id= 121
and rtt.organization_id=rt.organization_id
 )
 

 
 select max(TRANSACTION_DATE) FROM FROM RCV_TRANSACTIONS where TRANSACTION_TYPE= 'DELIVER' and organization_id= 121
 
 SELECT  QUANTITY FROM RCV_SHIPMENT_LINES rl, RCV_TRANSACTIONS rt  WHERE rl.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID and rl.SHIPMENT_LINE_ID= rt.SHIPMENT_LINE_ID AND TRANSACTION_TYPE= 'DELIVER'
and rl.ITEM_ID=1054
and rt.ORGANIZATION_ID= 121
and rt.TRANSACTION_DATE = (SELECT  MAX(rtt.TRANSACTION_DATE) FROM RCV_TRANSACTIONS rtt, RCV_SHIPMENT_LINES rll WHERE rtt.SHIPMENT_HEADER_ID = rll.SHIPMENT_HEADER_ID and rtt.SHIPMENT_LINE_ID = rll.SHIPMENT_LINE_ID
and rtt.SHIPMENT_HEADER_ID =  rl.SHIPMENT_HEADER_ID and rtt.SHIPMENT_LINE_ID = rl.SHIPMENT_LINE_ID AND rtt.TRANSACTION_TYPE= 'DELIVER' and rll.item_id= rl.item_id 
--and rtt.organigation_id= rt.organigation_id
and rtt.organization_id= 121
and rtt.organization_id=rt.organization_id
 )

GROUP BY QUANTITY
--order by rt.TRANSACTION_DATE desc

SELECT ORGANIZATION_ID, ITEM_GROUP, ITEM_CATEGORY, FINANCE_CATEGORY,ITEM_ID,LAST_DEL_DATE,DEL_QTY,RECEIVE_DAY_TILL_TODAY,LAST_CONSUMP_DATE,LAST_CONSUMP_QTY,ON_HAND_QTY FROM
(
select b.ORGANIZATION_ID, 
  (SELECT DISTINCT SEGMENT1 FROM MTL_ITEM_CATEGORIES_V WHERE     INVENTORY_ITEM_ID = a.ITEM_ID AND CATEGORY_SET_ID = 1100000041 AND ORGANIZATION_ID = b.ORGANIZATION_ID) ITEM_GROUP,
    (SELECT DISTINCT SEGMENT2 FROM MTL_ITEM_CATEGORIES_V WHERE     INVENTORY_ITEM_ID = a.ITEM_ID AND CATEGORY_SET_ID = 1100000041 AND ORGANIZATION_ID = b.ORGANIZATION_ID) ITEM_CATEGORY,
      --  (SELECT DISTINCT SEGMENT3 FROM MTL_ITEM_CATEGORIES_V WHERE     INVENTORY_ITEM_ID = a.ITEM_ID AND CATEGORY_SET_ID = 1100000041 AND ORGANIZATION_ID = b.ORGANIZATION_ID) ITEM_SUB_CATEGORY,
 (SELECT DISTINCT CATEGORY_CONCAT_SEGS FROM MTL_ITEM_CATEGORIES_V WHERE     INVENTORY_ITEM_ID = a.ITEM_ID AND CATEGORY_SET_ID = 1100000041 AND ORGANIZATION_ID = b.ORGANIZATION_ID) FINANCE_CATEGORY,
a.item_id ,TO_CHAR(TRUNC(MAX(TRANSACTION_DATE)) ,'DD-MON-RRRR') LAST_DEL_DATE ,
SUM(b.QUANTITY) DEL_QTY,
ROUND(SYSDATE -TRUNC(MAX(TRANSACTION_DATE)))  RECEIVE_DAY_TILL_TODAY,
(SELECT TO_CHAR(TRUNC(MAX(STATUS_DATE)),'DD-MON-RRRR')  FROM MTL_TXN_REQUEST_LINES WHERE INVENTORY_ITEM_ID= a.ITEM_ID AND  ORGANIZATION_ID  = b.ORGANIZATION_ID) LAST_CONSUMP_DATE,
   (SELECT  SUM(QUANTITY_DELIVERED)  FROM MTL_TXN_REQUEST_LINES WHERE INVENTORY_ITEM_ID= a.ITEM_ID AND  ORGANIZATION_ID  = b.ORGANIZATION_ID
     AND STATUS_DATE = (SELECT MAX(STATUS_DATE)  FROM MTL_TXN_REQUEST_LINES WHERE  INVENTORY_ITEM_ID= a.ITEM_ID AND  ORGANIZATION_ID  = b.ORGANIZATION_ID) 
   ) LAST_CONSUMP_QTY,
  GET_ONHAND_QTY_FROM_ITEM(SYSDATE,  b.ORGANIZATION_ID, a.item_id) ON_HAND_QTY
 from rcv_shipment_lines a, rcv_transactions b 
where a.shipment_header_id= b.shipment_header_id
and a.shipment_line_id= b.shipment_line_id
and a.item_id IN ( 1322 ,25951) -- 1054 --1054 -- 1036
and b.ORGANIZATION_ID=121
and b.TRANSACTION_TYPE = 'DELIVER'
and GET_ONHAND_QTY_FROM_ITEM(SYSDATE,  b.ORGANIZATION_ID, a.item_id) > 0
--and TRUNC(b.transaction_date) between '01-MAY2020' and '20-MAY-2020' 
and TRUNC(b.transaction_date) <='20-MAR-2021' 
GROUP BY b.ORGANIZATION_ID,a.item_id
)

select * from MTL_TXN_REQUEST_LINES   1454396

3/16/2021 9:56:06 AM



select c.ORGANIZATION_ID,
 --XXGET_OU_NAME_FROM_ID(c.OPERATING_UNIT) OU,
INVORG_NAME_FROM_ID (c.ORGANIZATION_ID) INV_ORG,
  e.SEGMENT2 item_group,
  e.SEGMENT1 ITEM_CATEGORY,
 (SELECT DISTINCT CATEGORY_CONCAT_SEGS FROM MTL_ITEM_CATEGORIES_V WHERE     INVENTORY_ITEM_ID = b.ITEM_ID AND CATEGORY_SET_ID = 1100000041 AND ORGANIZATION_ID = c.ORGANIZATION_ID) FINANCE_CATEGORY,
b.item_id, 
d.SEGMENT1||'|'||d.SEGMENT2||'|'|| d.SEGMENT3||'|'|| d.SEGMENT4 ITEM_CODE ,
d.description,
SUM(c.QUANTITY) DELIVERD_QTY,
TO_CHAR(TRUNC(TRANSACTION_DATE),'DD-MON-RRRR') DELIVERY_DATE,
       ROUND  (SYSDATE - MAX(TRANSACTION_DATE)) RECEIVE_DAY_TILL_TODAY,
  (SELECT  SUM(QUANTITY)  FROM MTL_TXN_REQUEST_LINES WHERE INVENTORY_ITEM_ID= b.ITEM_ID 
AND  ORGANIZATION_ID  = c.ORGANIZATION_ID
) LAST_CONSUMP_QTY,
  (SELECT   TO_CHAR(TRUNC(MAX(STATUS_DATE)),'DD-MON-RRRR')  FROM MTL_TXN_REQUEST_LINES WHERE INVENTORY_ITEM_ID= b.ITEM_ID AND  ORGANIZATION_ID  = c.ORGANIZATION_ID) LAST_CONSUMP_DATE,
 ROUND( SYSDATE -  (SELECT  TRUNC(MAX(STATUS_DATE))  FROM MTL_TXN_REQUEST_LINES WHERE INVENTORY_ITEM_ID= b.ITEM_ID AND  ORGANIZATION_ID  = c.ORGANIZATION_ID)) CONSUMP_DAY_TILL_TODAY,
  GET_ONHAND_QTY_FROM_ITEM(SYSDATE,  c.ORGANIZATION_ID, b.item_id) ON_HAND_QTY
 FROM rcv_shipment_lines b,rcv_transactions c, MTL_SYSTEM_ITEMS_B d, MTL_ITEM_CATEGORIES_V e
  WHERE b.SHIPMENT_HEADER_ID = c.SHIPMENT_HEADER_ID
  and b.ITEM_ID= d.INVENTORY_ITEM_ID
  and c.ORGANIZATION_ID = d.ORGANIZATION_ID
  and b.SHIPMENT_LINE_ID = c.SHIPMENT_LINE_ID
  and c.TRANSACTION_TYPE = 'DELIVER'
  and b.ITEM_ID= e.INVENTORY_ITEM_ID
     AND e.CATEGORY_SET_ID = 1
   AND c.ORGANIZATION_ID = e.ORGANIZATION_ID
 AND  e.SEGMENT2 <> 'DEFAULT'
--and  c.SEGMENT2 = NVL(:P_ITEM_GROUP,  c.SEGMENT2)
  and   GET_ONHAND_QTY_FROM_ITEM(SYSDATE,  c.ORGANIZATION_ID, b.item_id)  > 0
and TRUNC(c.TRANSACTION_DATE)  < =  NVL(:P_AS_ON_DATE, SYSDATE )  --between '01-JAN2019' and '2-JAN-2019'
and b.item_id =1036 --14 --774051
and c.ORGANIZATION_ID =121
group by c.ORGANIZATION_ID,b.item_id, d.description,   e.SEGMENT1,e.SEGMENT2, d.SEGMENT1||'|'||d.SEGMENT2||'|'|| d.SEGMENT3||'|'|| d.SEGMENT4 , TRANSACTION_DATE --, c.OPERATING_UNIT
order by TO_CHAR(TRUNC(TRANSACTION_DATE),'DD-MON-RRRR') desc

select * from MTL_SYSTEM_ITEMS_B

select * from ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_ID = 164

select 

--=================== V2 READY FOR BOKTIAR SIR================

--FOR ONHAND QTY
                 (               
                SELECT NVL(SUM(PRIMARY_QUANTITY),0)
                FROM 
                MTL_MATERIAL_TRANSACTIONS
                WHERE 
                ORGANIZATION_ID=201 --222 --MTRL.ORGANIZATION_ID
              --  AND SUBINVENTORY_CODE=NVL(MTRL.FROM_SUBINVENTORY_CODE,SUBINVENTORY_CODE)
                AND INVENTORY_ITEM_ID=12849 --MTRL.INVENTORY_ITEM_ID 
                AND  TRANSACTION_DATE <=SYSDATE --MTRL.DATE_REQUIRED
                
                ) IO_STOCK
                
select * from ORG_ORGANIZATION_DEFINITIONS

select * from rcv_shipment_headers

 SELECT WIOD.OPERATING_UNIT_ID,
  GET_ONHAND_QTY_FROM_ITEM(:P_TO_DATE,  a.ORGANIZATION_ID, a.INVENTORY_ITEM_ID) ON_HAND_QTY,
 XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) OU,
 a.ORGANIZATION_ID, INVORG_NAME_FROM_ID (a.ORGANIZATION_ID) INV_ORG,
   a.INVENTORY_ITEM_ID,
 B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4  ITEM_CODE,
B.DESCRIPTION, 
  c.SEGMENT2 item_group,
  C.SEGMENT1 ITEM_CATEGORY,
--  b.SEGMENT3 item_sub_group,
 (SELECT DISTINCT CATEGORY_CONCAT_SEGS FROM MTL_ITEM_CATEGORIES_V WHERE     INVENTORY_ITEM_ID = a.INVENTORY_ITEM_ID AND CATEGORY_SET_ID = 1100000041 AND ORGANIZATION_ID = a.ORGANIZATION_ID) FINANCE_CATEGORY,
 TO_CHAR(GET_LAST_TRANS_DATE_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID)) LAST_RECEIVE_DATE,
 (SELECT SUM(QUANTITY) FROM RCV_SHIPMENT_LINES RL , RCV_TRANSACTIONS RT WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id= a.INVENTORY_ITEM_ID AND RT.ORGANIZATION_ID = a.ORGANIZATION_ID and RT.TRANSACTION_TYPE = 'DELIVER'  
and  RT.TRANSACTION_DATE = (SELECT MAX(R.TRANSACTION_DATE)  FROM RCV_SHIPMENT_LINES  L, RCV_TRANSACTIONS R WHERE R.SHIPMENT_LINE_ID=L.SHIPMENT_LINE_ID and  L.ITEM_ID= a.INVENTORY_ITEM_ID--1851 --4271
AND  R.ORGANIZATION_ID  = a.ORGANIZATION_ID)) LAST_RECEIVE_QTY,
            ROUND  (SYSDATE -  GET_LAST_TRANS_DATE_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID)) RECEIVE_DAY_TILL_TODAY,
 TO_CHAR(TRUNC(MAX(A.STATUS_DATE)),'DD-MON-RRRR')  LAST_CONSUM_DATE,
  (SELECT  SUM(QUANTITY)  
FROM MTL_TXN_REQUEST_LINES 
WHERE INVENTORY_ITEM_ID= a.INVENTORY_ITEM_ID -- 1851 --4271
AND  ORGANIZATION_ID  = a.ORGANIZATION_ID
AND STATUS_DATE = (SELECT MAX(STATUS_DATE) STATUS_DATE FROM MTL_TXN_REQUEST_LINES WHERE  INVENTORY_ITEM_ID=  a.INVENTORY_ITEM_ID -- 1851 --4271
AND  ORGANIZATION_ID  =  a.ORGANIZATION_ID --121
)) LAST_CONSUMP_QTY,
 ROUND((SYSDATE -  MAX(A.STATUS_DATE))) CONSUMP_DAY_TILL_TODAY,
              :P_FROM_DATE DATE_FROM ,
             :P_TO_DATE DATE_TO
 FROM MTL_TXN_REQUEST_LINES a, MTL_SYSTEM_ITEMS_B b,  MTL_ITEM_CATEGORIES_V c , ORG_ORGANIZATION_DEFINITIONS ORG , WBI_INV_ORG_DETAIL WIOD --, MTL_TXN_REQUEST_HEADERS XTH
  WHERE a.INVENTORY_ITEM_ID=b.INVENTORY_ITEM_ID
  AND a.ORGANIZATION_ID = ORG.ORGANIZATION_ID
  AND WIOD.INV_ORGANIZATION_ID = ORG.ORGANIZATION_ID
  and a.ORGANIZATION_ID = WIOD.INV_ORGANIZATION_ID
  and b.INVENTORY_ITEM_ID = c.INVENTORY_ITEM_ID
   AND C.CATEGORY_SET_ID = 1
   AND B.ORGANIZATION_ID = C.ORGANIZATION_ID
 AND  c.SEGMENT2 <> 'DEFAULT'
and  c.SEGMENT2 = NVL(:P_ITEM_GROUP,  c.SEGMENT2)
 AND (A.STATUS_DATE  BETWEEN :P_FROM_DATE AND :P_TO_DATE OR :P_FROM_DATE IS NULL OR :P_TO_DATE IS NULL)
 and a.INVENTORY_ITEM_ID = NVL(:P_ITEM_ID, a.INVENTORY_ITEM_ID)
 and B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4 = NVL(:P_ITEM_CODE, B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4)
 and WIOD.OPERATING_UNIT_ID = NVL(:P_OU, WIOD.OPERATING_UNIT_ID)
 --and  GET_ONHAND_QTY_FROM_ITEM(:P_TO_DATE,  a.ORGANIZATION_ID, a.INVENTORY_ITEM_ID) > 0
--and XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) = NVL(:P_OU, XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) )
--and  a.ORGANIZATION_ID = 153
 GROUP BY a.INVENTORY_ITEM_ID,B.DESCRIPTION ,a.ORGANIZATION_ID ,  --b.SEGMENT3,
 c.SEGMENT2, B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4, C.SEGMENT1, ORG.OPERATING_UNIT, WIOD.OPERATING_UNIT_ID  --, a.header_id--, XTH.REQUEST_NUMBER --,a.QUANTITY_DELIVERED
 order by description 
  

--==================== V1 READY FOR BOKTIAR SIR===============

 select XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) OU,
 a.ORGANIZATION_ID, INVORG_NAME_FROM_ID (a.ORGANIZATION_ID) INV_ORG,
   a.INVENTORY_ITEM_ID,
 B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4  ITEM_CODE,
 DESCRIPTION, 
  c.SEGMENT2 item_group,
  C.SEGMENT1 ITEM_CATEGORY,
--  b.SEGMENT3 item_sub_group,
            (SELECT DISTINCT CATEGORY_CONCAT_SEGS
             FROM MTL_ITEM_CATEGORIES_V
            WHERE     INVENTORY_ITEM_ID = a.INVENTORY_ITEM_ID
                  AND CATEGORY_SET_ID = 1100000041
                  AND ORGANIZATION_ID = a.ORGANIZATION_ID)
             FINANCE_CATEGORY,
             TO_CHAR(GET_LAST_TRANS_DATE_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID)) LAST_RECEIVE_DATE,
             GET_LAST_TRANS_QTY_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID) RECEIVED_QTY,
            ROUND  (SYSDATE -  GET_LAST_TRANS_DATE_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID)) RECEIVE_DAY_TILL_TODAY,
 --TO_CHAR(TRUNC(MAX(A.STATUS_DATE)),'DD-MON-RRRR')  LAST_CONSUM_DATE,
 GET_LAST_GRN_QTY_FROM_ITEM(3,a.INVENTORY_ITEM_ID,a.ORGANIZATION_ID,MAX(A.STATUS_DATE))  LAST_CONSUM_DATE,
-- a.QUANTITY_DELIVERED CONSUMP_QTY,
GET_LAST_GRN_QTY_FROM_ITEM(2,  a.INVENTORY_ITEM_ID,a.ORGANIZATION_ID,TO_CHAR(TRUNC(MAX(A.STATUS_DATE)),'DD-MON-RRRR'))  CONSUMP_QTY
-- ROUND((SYSDATE -  MAX(A.STATUS_DATE))) CONSUMP_DAY_TILL_TODAY
 -- ROUND((SYSDATE -  MAX(A.STATUS_DATE)))/30  TOTAL_MONTH
-- MAX(STATUS_DATE) 
 FROM MTL_TXN_REQUEST_LINES a, MTL_SYSTEM_ITEMS_B b,  MTL_ITEM_CATEGORIES_V c , ORG_ORGANIZATION_DEFINITIONS ORG, MTL_TXN_REQUEST_LINES XTH
  WHERE a.INVENTORY_ITEM_ID=b.INVENTORY_ITEM_ID
  and a.HEADER_ID = XTH.HEADER_ID 
  and a.INVENTORY_ITEM_ID= 180 --180
  AND XTH.ORGANIZATION_ID = ORG.ORGANIZATION_ID
  and b.INVENTORY_ITEM_ID = c.INVENTORY_ITEM_ID
   AND C.CATEGORY_SET_ID = 1
   AND B.ORGANIZATION_ID = C.ORGANIZATION_ID
--            AND b.segment2 IN
--                       ('500W',
--                        'G400',
--                        'G-60',
--                        '400E',
--                        '500D',
--                        'ANGL',
--                        'SBAR')
--                AND b.segment1 IN ('FG', 'CP')
 --and a.ORGANIZATION_ID= 121
 AND  c.SEGMENT2 <> 'DEFAULT'
and  c.SEGMENT2 = NVL(:P_ITEM_GROUP,  c.SEGMENT2)
 --and a.header_id= 1650564
 AND (A.STATUS_DATE  BETWEEN :P_FROM_DATE AND :P_TO_DATE OR :P_FROM_DATE IS NULL OR :P_TO_DATE IS NULL)
and a.inventory_item_id= 180 --34333 -- 4271 --634152  --418 day
and XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) = NVL(:P_OU, XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) )
 GROUP BY a.INVENTORY_ITEM_ID,DESCRIPTION ,a.ORGANIZATION_ID ,  --b.SEGMENT3,
 c.SEGMENT2, B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4, C.SEGMENT1, ORG.OPERATING_UNIT--, A.STATUS_DATE --,a.QUANTITY_DELIVERED
 order by description 


---=============== MAIN ==========READY FOR BOKTIAR SIR=============

 select  GET_LAST_GRN_QTY_FROM_ITEM(2,a.INVENTORY_ITEM_ID,a.ORGANIZATION_ID,MAX(A.STATUS_DATE))  LAST_CONSUM_QTY,
 --GET_LAST_GRN_QTY_FROM_ITEM(3,a.INVENTORY_ITEM_ID,a.ORGANIZATION_ID,MAX(A.STATUS_DATE))  LAST_CONSUM_QTY,
 XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) OU,
 a.ORGANIZATION_ID, INVORG_NAME_FROM_ID (a.ORGANIZATION_ID) INV_ORG,
   a.INVENTORY_ITEM_ID,
 B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4  ITEM_CODE,
 DESCRIPTION, 
  c.SEGMENT2 item_group,
  C.SEGMENT1 ITEM_CATEGORY,
--  b.SEGMENT3 item_sub_group,
            (SELECT DISTINCT CATEGORY_CONCAT_SEGS
             FROM MTL_ITEM_CATEGORIES_V
            WHERE     INVENTORY_ITEM_ID = a.INVENTORY_ITEM_ID
                  AND CATEGORY_SET_ID = 1100000041
                  AND ORGANIZATION_ID = a.ORGANIZATION_ID)
             FINANCE_CATEGORY,
             TO_CHAR(GET_LAST_TRANS_DATE_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID)) LAST_RECEIVE_DATE,
             GET_LAST_TRANS_QTY_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID) RECEIVED_QTY,
            ROUND  (SYSDATE -  GET_LAST_TRANS_DATE_FRM_ITM_ID(a.ORGANIZATION_ID,  a.INVENTORY_ITEM_ID)) RECEIVE_DAY_TILL_TODAY,
 TO_CHAR(TRUNC(MAX(A.STATUS_DATE)),'DD-MON-RRRR')  LAST_CONSUM_DATE,
 --SUM(a.QUANTITY_DELIVERED)  CONSUMP_QTY,
 GET_TRANS_QUANTITY ( a.INVENTORY_ITEM_ID, a.ORGANIZATION_ID, TO_CHAR(TRUNC(MAX(A.STATUS_DATE)),'DD-MON-RRRR')) CONSUMP_QTY,
 ROUND((SYSDATE -  MAX(A.STATUS_DATE))) CONSUMP_DAY_TILL_TODAY
 -- ROUND((SYSDATE -  MAX(A.STATUS_DATE)))/30  TOTAL_MONTH
-- MAX(STATUS_DATE) 
 FROM MTL_TXN_REQUEST_LINES a, MTL_SYSTEM_ITEMS_B b,  MTL_ITEM_CATEGORIES_V c , ORG_ORGANIZATION_DEFINITIONS ORG, MTL_TXN_REQUEST_LINES XTH
  WHERE a.INVENTORY_ITEM_ID=b.INVENTORY_ITEM_ID
  and a.HEADER_ID = XTH.HEADER_ID 
  and a.INVENTORY_ITEM_ID=1851 -- 180
  AND XTH.ORGANIZATION_ID = ORG.ORGANIZATION_ID
  and b.INVENTORY_ITEM_ID = c.INVENTORY_ITEM_ID
   AND C.CATEGORY_SET_ID = 1
   AND B.ORGANIZATION_ID = C.ORGANIZATION_ID
--            AND b.segment2 IN
--                       ('500W',
--                        'G400',
--                        'G-60',
--                        '400E',
--                        '500D',
--                        'ANGL',
--                        'SBAR')
--                AND b.segment1 IN ('FG', 'CP')
 --and a.ORGANIZATION_ID= 121
 AND  c.SEGMENT2 <> 'DEFAULT'
and  c.SEGMENT2 = NVL(:P_ITEM_GROUP,  c.SEGMENT2)
 --and a.header_id= 1650564
 AND (A.STATUS_DATE  BETWEEN :P_FROM_DATE AND :P_TO_DATE OR :P_FROM_DATE IS NULL OR :P_TO_DATE IS NULL)
--and a.inventory_item_id= 34333 -- 4271 --634152  --418 day
--and XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) = NVL(:P_OU, XXGET_OU_NAME_FROM_ID(ORG.OPERATING_UNIT) )
 GROUP BY a.INVENTORY_ITEM_ID,DESCRIPTION ,a.ORGANIZATION_ID ,  --b.SEGMENT3,
 c.SEGMENT2, B.SEGMENT1||'|'||B.SEGMENT2||'|'|| B.SEGMENT3||'|'|| B.SEGMENT4, C.SEGMENT1, ORG.OPERATING_UNIT --,a.QUANTITY_DELIVERED
 order by description
 
SELECT *  FROM MTL_TXN_REQUEST_LINES  where inventory_item_id= 34333 --group by QUANTITY_DELIVERED

select *  FROM MTL_TXN_REQUEST_LINES  where inventory_item_id= 34333 --group by QUANTITY_DELIVERED




 
 
 
SELECT MAX(RT.TRANSACTION_DATE) --INTO V_DATE
FROM RCV_SHIPMENT_LINES RL , RCV_TRANSACTIONS RT
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id=34333 -- 775030 -- P_ITEM_ID
--AND RT.ORGANIZATION_ID =201 --163 -- P_INVORG_ID
--and RT.TRANSACTION_TYPE = 'DELIVER';
 

select   ORGANIZATION_ID , QUANTITY, TO_CHAR(TRUNC(STATUS_DATE),'DD-MON-RRRR') STATUS_DATE   FROM MTL_TXN_REQUEST_LINES 
where INVENTORY_ITEM_ID= 34333 --4271
and  ORGANIZATION_ID  = 201
order by STATUS_DATE desc  -- 11/12/2020 10:20:58 AM

select * from MTL_MATERIAL_TRANSACTIONS WHERE INVENTORY_ITEM_ID= 34333 --4271
and  ORGANIZATION_ID  = 201

SELECT * FROM RCV_TRANSACTIONS RT, RCV_SHIPMENT_LINES RL 
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id= 34333 --802
and RT.TRANSACTION_TYPE= 'DELIVER'
order by RT.TRANSACTION_DATE DESC



select *  FROM MTL_TXN_REQUEST_LINES 
where INVENTORY_ITEM_ID= 34333 --4271

select * from MTL_MATERIAL_TRANSACTIONS where INVENTORY_ITEM_ID= 34333 ORDER BY TRANSACTION_DATE desc
 
 SELECT * FROM RCV_SHIPMENT_LINES RL     -- ITEM_ID
 where  rl.item_id=34333 --4271 -- 180
 
  
 SELECT * FROM RCV_TRANSACTIONS RT     -- ITEM_ID
 where  rt.INVENTORY_item_id=34333 
 
 select SUM(PRIMARY_QUANTITY),MAX(TRANSACTION_DATE) , INVENTORY_ITEM_ID from MTL_MATERIAL_TRANSACTIONS 
 WHERE  INVENTORY_ITEM_ID=99 --34333 -- 99 --34333  --GROUP BY  MAX(TRANSACTION_DATE) --ORDER BY TRANSACTION_DATE DESC
 GROUP BY INVENTORY_ITEM_ID
  --HAVING MAX(TRANSACTION_DATE) = MAX(TRANSACTION_DATE) --sysdate 
  
 select TRANSACTION_DATE  , TRANSACTION_QUANTITY, PRIMARY_QUANTITY from MTL_TRANSACTION_TYPES MTT,MTL_MATERIAL_TRANSACTIONS MMT 
 WHERE MMT.INVENTORY_ITEM_ID= 34333 --4271
 and MMT.TRANSACTION_TYPE_ID = MTT.TRANSACTION_TYPE_ID
 and ORGANIZATION_ID = 201

SELECT * FROM RCV_TRANSACTIONS 

SELECT * FROM RCV_TRANSACTIONS RT, RCV_SHIPMENT_LINES RL 
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id= 34333 --802
and RT.TRANSACTION_TYPE= 'DELIVER'
order by RT.TRANSACTION_DATE DESC

CREATE OR REPLACE FUNCTION GET_LAST_TRANS_DATE_FRM_ITM_ID(P_INVORG_ID IN NUMBER, P_ITEM_ID IN NUMBER)
RETURN DATE
IS 
V_DATE DATE;
BEGIN
SELECT MAX(RT.TRANSACTION_DATE) INTO V_DATE
FROM RCV_SHIPMENT_LINES RL , RCV_TRANSACTIONS RT
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id= P_ITEM_ID
AND RT.ORGANIZATION_ID = P_INVORG_ID
and RT.TRANSACTION_TYPE = 'DELIVER';
RETURN V_DATE;
EXCEPTION WHEN OTHERS THEN 
RETURN NULL;
END;


CREATE OR REPLACE FUNCTION GET_LAST_TRANS_QTY_FRM_ITM_ID(P_INVORG_ID IN NUMBER, P_ITEM_ID IN NUMBER)
RETURN NUMBER
IS 
V_QTY NUMBER;
BEGIN
SELECT NVL(SUM(RT.QUANTITY),0) INTO V_QTY
FROM RCV_SHIPMENT_LINES RL , RCV_TRANSACTIONS RT
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id= P_ITEM_ID
AND RT.ORGANIZATION_ID = P_INVORG_ID
and RT.TRANSACTION_TYPE = 'DELIVER';
RETURN V_QTY;
EXCEPTION WHEN OTHERS THEN 
RETURN NULL;
END;


SELECT RT.ORGANIZATION_ID,MAX(RT.TRANSACTION_DATE) FROM RCV_TRANSACTIONS RT , RCV_SHIPMENT_LINES RL  
WHERE RL.SHIPMENT_LINE_ID=RT.SHIPMENT_LINE_ID
and rl.item_id= 180
AND RT.ORGANIZATION_ID = 152
group by ORGANIZATION_ID

select * from MTL_ITEM_CATEGORIES_V

select * from MTL_SYSTEM_ITEMS_B
SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4 

/*
 Which kind of  Cunsumption Date will be allowed? 
 ANS: Move order Issue , WIP Issue .......
*/

/*  XXKSRM Use Of Area Wise Consumption Report(Summary)  */ 
select    APPS.XXGET_OU_NAME_FROM_ID( ZZ.OPERATING_UNIT) OU,
XX.STATUS_DATE,
XXGET_ORG_NAME(YY.ORGANIZATION_ID) ORG_NAME ,
 COUNT (XX.REQUEST_NUMBER) TOT_MO , 
 SUM(   QUANTITY_DELIVERED * XX_GET_LIST_PRICE (INVENTORY_ITEM_ID)) TOT_VAL , 
  XX_GET_USE_AREA (XX.ATTRIBUTE2) USE_OF_AREA,
  XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME 
 FROM MTL_TXN_REQUEST_HEADERS_V YY, MTL_TXN_REQUEST_LINES_V XX, ORG_ORGANIZATION_DEFINITIONS ZZ 
WHERE 
YY.HEADER_ID = XX.HEADER_ID
         AND YY.ORGANIZATION_ID = ZZ.ORGANIZATION_ID
         AND XX.MOVE_ORDER_TYPE_NAME = 'Requisition' 
         AND XX.QUANTITY_DELIVERED <> 0
           AND (ZZ.OPERATING_UNIT =  :P_OU OR :P_OU IS NULL)
            AND (XX.ORGANIZATION_ID = :P_ORG OR :P_ORG IS NULL)
        -- and XX.CREATION_DATE between '01-jul-2019' and '10-jul-2019' 
          AND ( XX.STATUS_DATE  BETWEEN :P_FROM_DATE AND :P_TO_DATE OR :P_FROM_DATE IS NULL OR :P_TO_DATE IS NULL)
         AND (XX_GET_USE_AREA (XX.ATTRIBUTE2) = :P_U_AREA OR :P_U_AREA IS NULL)
         and ( XX.INVENTORY_ITEM_ID=:P_ITEM OR :P_ITEM IS NULL)
         GROUP BY  APPS.XXGET_OU_NAME_FROM_ID( ZZ.OPERATING_UNIT) ,
          XXGET_ORG_NAME(YY.ORGANIZATION_ID),
          XX_GET_USE_AREA (XX.ATTRIBUTE2),XX.STATUS_DATE
    

         

select * from MTL_SYSTEM_ITEMS_FVL


select * from MTL_TXN_REQUEST_HEADERS_V

SELECT * FROM MTL_TXN_REQUEST_LINES_V 


 SELECT * FROM MTL_TXN_REQUEST_LINES

SELECT Distinct  A.NAME  
FROM HR_OPERATING_UNITS A , ORG_ORGANIZATION_DEFINITIONS B

SELECT DISTINCT  SHIPMENT_NUMBER  FROM MTL_MATERIAL_TRANSACTIONS