
--============================
-- Bill BOARD REPORT FOR BRAND
---==========================

SELECT
pha.attribute4 H_DIS,
PHA.ATTRIBUTE13 project,
PHA.TYPE_LOOKUP_CODE PO_TYPE,
PLA.LINE_NUM, 
PHA.PO_HEADER_ID,
pha.segment1 PO_NUM,
TO_CHAR (pha.creation_date, 'DD-MON-YYYY') po_cr_dt,
PHA.ATTRIBUTE2 CON_PERSON,
XX_GET_ACCT_FLEX_SEG_DESC (7, PHA.ATTRIBUTE14) PROJECT_NAME,
--PHA.ATTRIBUTE10 TERM_DAYS,
TO_CHAR (pha.APPROVED_DATE, 'DD-MON-YYYY') po_APP_dt,
PHA.CURRENCY_CODE,
PHA.RATE,
ood.ORGANIZATION_CODE destinition,
pov.segment1 supplier_id,
pov.vendor_name supplier_name,
ADDRESS_LINE1||' '||
ADDRESS_LINE2 Supplier_add,
pvs.city||'-'||pvs.zip City_ZIP,
pvs.phone supp_phone,
pvs.telex,
pvs.EMAIL_ADDRESS supp_email,
XX_GET_HR_OPERATING_UNIT(:p_org_id) Org_header_name,
hrl.ADDRESS_LINE_1||' '||hrl.ADDRESS_LINE_2||' '||hrl.ADDRESS_LINE_3||', '||hrl.REGION_1||'-'||hrl.POSTAL_CODE BCL_F_ADD,
hrl.TELEPHONE_NUMBER_1 PHP_F_PHONE,
HRL.TELEPHONE_NUMBER_2 PHP_F_FAX,
HRL.LOC_INFORMATION13 PHP_F_EMAIL,
MP.ORGANIZATION_CODE IO,
XX_P2P_PKG.LC_FROM_PO(PHA.PO_HEADER_ID) LC_NO,
pra.release_num,
to_char(pra.RELEASE_DATE, 'DD-MON-RRRR') release_date, 
pha.REVISION_NUM,
hrl1.ADDRESS_LINE_1||' '||hrl1.ADDRESS_LINE_2||' '||hrl1.ADDRESS_LINE_3||', '||hrl1.REGION_1||'-'||hrl1.POSTAL_CODE BCL_bill_ADD,
TO_CHAR (pll.PROMISED_DATE, 'DD-MON-RRRR') PROMISED_DATE,
TO_CHAR (pll.NEED_BY_DATE, 'DD-MON-RRRR') NEED_BY_DATE,
DECODE (pda.req_header_reference_num,
               NULL,XX_P2P_PKG.XX_FND_REQUISITION_INFO(PLL.ATTRIBUTE1,:P_ORG_ID,PLL.ATTRIBUTE2,'RNUM'),
               pda.req_header_reference_num) requisition_no ,
'' css_no,
'' css_date,
pla.attribute1 brand,
pla.attribute2 origin,               
mst.item_code,
PHA.ATTRIBUTE11 BRND_TYPE,
PHA.ATTRIBUTE3 PER_RATE,
PHA.ATTRIBUTE7 TOTAL_SIZE,
PHA.ATTRIBUTE2 SIZEE,
PHA.ATTRIBUTE6 SUPPLIER_PERSON,
PHA.COMMENTS AREA,
PLA.ATTRIBUTE3 Item_Specification,
PLA.ATTRIBUTE6 BILL_BOARD_Q1,
PLA.ATTRIBUTE7 BILL_BOARD_Q2,
PLA.ATTRIBUTE8 BILL_BOARD_Q3,
TO_CHAR(TO_DATE(PHA.ATTRIBUTE9,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YYYY') PERIOD_FROM,
PHA.ATTRIBUTE4 DIS_AMT,
PHA.ATTRIBUTE5 DIS_PER,
PLA.NOTE_TO_VENDOR ,
pla.item_description,MUOM.UOM_CODE,
Sum(pll.quantity) po_qty,
PLA.UNIT_PRICE PRICE,
NVL((NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE),0)+NVL(PLA.ATTRIBUTE5,0) DISCOUNT_PRICE,
Sum(pll.quantity)*PLA.UNIT_PRICE CF_NET_VALUE_SUM,
PHA.ATTRIBUTE10 CARRYING_COST,
(NVL((NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE),0)+NVL(PLA.ATTRIBUTE5,0))*SUM(pll.quantity) DISCOUNT_PRICE_SUM,
--PLA.UNIT_PRICE-NVL((NVL(NVL(to_number(PLA.ATTRIBUTE11),0)/100*NVL(PLA.UNIT_PRICE,0),0)+PLA.ATTRIBUTE5),0) UNIT_PRICE,
pla.ATTRIBUTE5 line_dis,
--PLA.ATTRIBUTE11 LINE_DIS_PER,
XX_P2P_EMP_INFO.XX_P2P_GET_EMPNP_MAIL(pha.creation_date,pha.created_by) creator_details,
NVL(pha1.segment1,'...............') quote_no,
NVL(pha1.QUOTE_VENDOR_QUOTE_NUMBER,'...............') supplier_quote,
NVL(TO_CHAR (pha1.REPLY_DATE, 'DD-MON-RRRR'),'...............')  REPLY_DATE,
 '(For '||pov.vendor_name||')' SUPP_ALIAS,
NVL(PHA.ATTRIBUTE15,0) VAT
--  case  when PHA.ATTRIBUTE15 is null then  'VAT Included' else PHA.ATTRIBUTE15  end vat
  FROM po_headers_all pha,
       po_headers_all pha1,
       po_lines_all pla,
       mtl_units_of_measure_tl muom,
       po_line_locations_all pll,
       ap_suppliers pov,
       ap_supplier_sites_all pvs,
       hr_locations_all hrl,
       hr_locations_all hrl1,
       org_organization_definitions ood,
       po_releases_all pra,
       (SELECT  req_header_reference_num, line_location_id
                   FROM xx_po_distributions_v
                   WHERE PO_HEADER_ID=:P_PO_NO
                   GROUP BY req_header_reference_num, line_location_id) pda,
       (SELECT ORGANIZATION_ID,inventory_item_id, description,
                        (segment1 || '-' || segment2 || '-' || segment3|| '-' || segment4
                        ) item_code
                   FROM mtl_system_items_b) mst,
                   mtl_parameters MP
 WHERE pha.po_header_id = pla.po_header_id
   AND pha.vendor_id = pov.vendor_id
   AND pha.vendor_site_id = pvs.vendor_site_id
   AND pov.vendor_id = pvs.vendor_id
   AND pha.type_lookup_code IN ('BLANKET', 'STANDARD')
   AND NVL (UPPER (pha.authorization_status), 'INCOMPLETE') = 'APPROVED'
   AND pha.approved_flag = 'Y'
   AND pla.po_header_id = pll.po_header_id
   AND pla.po_line_id = pll.po_line_id
   AND pla.item_id = mst.inventory_item_id
   AND hrl.location_id = pll.ship_to_location_id
   AND hrl1.location_id = pha.bill_to_location_id
   AND pda.line_location_id(+) = pll.line_location_id
   AND pha1.po_header_id(+) = pha.from_header_id
   AND pll.po_release_id = pra.po_release_id(+)
   AND UPPER(pll.SHIPMENT_TYPE)<>'PRICE BREAK'
   AND pla.unit_meas_lookup_code=MUOM.UNIT_OF_MEASURE(+)
   AND NVL(PHA.CANCEL_FLAG,'N')='N'
   AND NVL(PLA.CANCEL_FLAG,'N')='N' 
   AND NVL(PLL.CANCEL_FLAG,'N')='N'
   AND PLL.approved_flag = 'Y'
   AND NVL(PRA.APPROVED_FLAG,'Y')='Y'
   AND NVL(PRA.AUTHORIZATION_STATUS,'APPROVED')='APPROVED'
   AND NVL(PRA.CANCEL_FLAG,'N')='N'
   AND PLL.SHIP_TO_ORGANIZATION_ID=MST.ORGANIZATION_ID
   AND pha.org_id = :p_org_id
   AND pha.po_header_id = nvl(:p_po_no,pha.po_header_id)
   AND ood.organization_id = pll.ship_to_organization_id  
   AND MP.ORGANIZATION_ID=pll.ship_to_organization_id
   --AND DECODE (pha.type_lookup_code, 'BLANKET', pra.release_num, 900) =  NVL (:p_release, 900)
  AND UPPER(PHA.ATTRIBUTE_CATEGORY)='BRANDING_INFO'
 -- AND PHA.ATTRIBUTE11=NVL(:P_BTYPE,PHA.ATTRIBUTE11)
  AND TRUNC(PHA.APPROVED_DATE) BETWEEN NVL(:P_F_PO_DT,TRUNC(PHA.APPROVED_DATE)) AND NVL(:P_T_PO_DT,TRUNC(PHA.APPROVED_DATE))
GROUP BY
PLA.ATTRIBUTE3,
pha.attribute4,
PHA.TYPE_LOOKUP_CODE,
PLA.LINE_NUM, 
PHA.PO_HEADER_ID,
pha.segment1,
pla.ATTRIBUTE5,
PLA.ATTRIBUTE11,
TO_CHAR (pha.creation_date, 'DD-MON-YYYY'),
PHA.ATTRIBUTE2,
XX_GET_ACCT_FLEX_SEG_DESC (7, PHA.ATTRIBUTE14),
PHA.ATTRIBUTE4,
ood.ORGANIZATION_CODE,
PHA.ATTRIBUTE3,
TO_CHAR (pha.APPROVED_DATE, 'DD-MON-YYYY'),
PHA.CURRENCY_CODE,
PHA.RATE,
PHA.ATTRIBUTE10,
PHA.ATTRIBUTE12,
PHA1.ATTRIBUTE11,
pov.segment1,
pov.vendor_name,
ADDRESS_LINE1||' '||
ADDRESS_LINE2,
pvs.city||'-'||pvs.zip,
pvs.phone,
pvs.telex,
MP.ORGANIZATION_CODE,
pvs.EMAIL_ADDRESS,
--xx_com_pkg.get_hr_operating_unit(:p_org_id),
hrl.ADDRESS_LINE_1||' '||hrl.ADDRESS_LINE_2||' '||hrl.ADDRESS_LINE_3||', '||hrl.REGION_1||'-'||hrl.POSTAL_CODE,
hrl.TELEPHONE_NUMBER_1,
HRL.TELEPHONE_NUMBER_2,
HRL.LOC_INFORMATION13,
XX_P2P_PKG.LC_DT_FROM_PO(PHA.PO_HEADER_ID),
pra.release_num,
TO_CHAR (pll.PROMISED_DATE, 'DD-MON-RRRR'),
TO_CHAR (pll.NEED_BY_DATE, 'DD-MON-RRRR') ,
DECODE (pda.req_header_reference_num,
               NULL,XX_P2P_PKG.XX_FND_REQUISITION_INFO(PLL.ATTRIBUTE1,:P_ORG_ID,PLL.ATTRIBUTE2,'RNUM'),
               pda.req_header_reference_num) ,
PHA.ATTRIBUTE11,
PHA.ATTRIBUTE3,
PHA.ATTRIBUTE7,
PHA.ATTRIBUTE2,
PHA.ATTRIBUTE6,
PHA.COMMENTS,
PLA.ATTRIBUTE6,
PLA.ATTRIBUTE7,
PLA.ATTRIBUTE8,
TO_CHAR(TO_DATE(PHA.ATTRIBUTE9,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YYYY'),
mst.item_code,
pla.attribute1,
pla.attribute2,
PLA.NOTE_TO_VENDOR ,
pla.item_description,MUOM.UOM_CODE,
PLA.UNIT_PRICE,
XX_P2P_EMP_INFO.XX_P2P_GET_EMPNP_MAIL(pha.creation_date,pha.created_by),
NVL(pha1.segment1,'...............'),
NVL(pha1.QUOTE_VENDOR_QUOTE_NUMBER,'...............'),
NVL(TO_CHAR (pha1.REPLY_DATE, 'DD-MON-RRRR'),'...............'),
 '(For '||pov.vendor_name||')',
NVL(PHA.ATTRIBUTE15,0),
PHA.ATTRIBUTE13,
PHA.ATTRIBUTE4,
PHA.ATTRIBUTE5,
--PHA.ATTRIBUTE15,
to_char(pra.RELEASE_DATE, 'DD-MON-RRRR'), 
PLA.UNIT_PRICE-NVL((NVL(NVL(PLA.ATTRIBUTE11,0)/100*NVL(PLA.UNIT_PRICE,0),0)+PLA.ATTRIBUTE5),0),
NVL((NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE),0)+NVL(PLA.ATTRIBUTE5,0)*(pll.quantity),
pha.REVISION_NUM,
PLA.UNIT_PRICE,
(hrl1.ADDRESS_LINE_1||' '||hrl1.ADDRESS_LINE_2||' '||hrl1.ADDRESS_LINE_3||', '||hrl1.REGION_1||'-'||hrl1.POSTAL_CODE)
UNION ALL
SELECT
pha.attribute4 H_DIS,
PHA.ATTRIBUTE13 project,
PHA.TYPE_LOOKUP_CODE PO_TYPE, 
PLA.LINE_NUM,
PHA.PO_HEADER_ID,
pha.segment1 PO_NUM,
TO_CHAR (pha.creation_date, 'DD-MON-YYYY') po_cr_dt,
PHA.ATTRIBUTE2 CON_PERSON,
XX_GET_ACCT_FLEX_SEG_DESC (7, PHA.ATTRIBUTE14) PROJECT_NAME,
--PHA.ATTRIBUTE10 TERM_DAYS,
TO_CHAR (pha.APPROVED_DATE, 'DD-MON-YYYY') po_APP_dt,
PHA.CURRENCY_CODE,
PHA.RATE,
NULL destinition,
pov.segment1 supplier_id,
pov.vendor_name supplier_name,
ADDRESS_LINE1||' '||
ADDRESS_LINE2 Supplier_add,
pvs.city||'-'||pvs.zip City_ZIP,
pvs.phone supp_phone,
pvs.telex,
pvs.EMAIL_ADDRESS supp_email,
XX_GET_HR_OPERATING_UNIT(:p_org_id) Org_header_name,
hrl.ADDRESS_LINE_1||' '||hrl.ADDRESS_LINE_2||' '||hrl.ADDRESS_LINE_3||', '||hrl.REGION_1||'-'||hrl.POSTAL_CODE BCL_F_ADD,
hrl.TELEPHONE_NUMBER_1 PHP_F_PHONE,
HRL.TELEPHONE_NUMBER_2 PHP_F_FAX,
HRL.LOC_INFORMATION13 PHP_F_EMAIL,
MP.ORGANIZATION_CODE IO,
--(select organization_code from mtl_parameters where ORGANIZATION_ID=pll.ship_to_organization_id) IO,
TO_CHAR(NULL) LC_NO,
TO_NUMBER(NULL) release_num,
--to_char(pra.RELEASE_DATE, 'DD-MON-RRRR') rel_dt,
null release_date,
pha.REVISION_NUM,
hrl1.ADDRESS_LINE_1||' '||hrl1.ADDRESS_LINE_2||' '||hrl1.ADDRESS_LINE_3||', '||hrl1.REGION_1||'-'||hrl1.POSTAL_CODE BCL_bill_ADD,
TO_CHAR (pll.PROMISED_DATE, 'DD-MON-RRRR') PROMISED_DATE,
TO_CHAR (pll.NEED_BY_DATE, 'DD-MON-RRRR') NEED_BY_DATE,
XX_P2P_PKG.XX_FND_REQUISITION_INFO(PLL.ATTRIBUTE1,:P_ORG_ID,PLL.ATTRIBUTE2,'RNUM') requisition_no,
'' css_no,
'' css_date,
pla.attribute1 brand,
pla.attribute2 origin,
mst.item_code,
PHA.ATTRIBUTE11 BRND_TYPE,
PHA.ATTRIBUTE3 PER_RATE,
PHA.ATTRIBUTE7 TOTAL_SIZE,
PHA.ATTRIBUTE2 SIZEE,
PHA.ATTRIBUTE6 SUPPLIER_PERSON,
PHA.COMMENTS AREA,
PLA.ATTRIBUTE3 Item_Specification,
PLA.ATTRIBUTE6 BILL_BOARD_Q1,
PLA.ATTRIBUTE7 BILL_BOARD_Q2,
PLA.ATTRIBUTE8 BILL_BOARD_Q3,
TO_CHAR(TO_DATE(PHA.ATTRIBUTE9,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YYYY') PERIOD_FROM,
PHA.ATTRIBUTE4 DIS_AMT,
PHA.ATTRIBUTE5 DIS_PER,
PLA.NOTE_TO_VENDOR ,
pla.item_description,MUOM.UOM_CODE,
Sum(pll.quantity) po_qty,
PLA.UNIT_PRICE PRICE,
NVL((NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE),0)+NVL(PLA.ATTRIBUTE5,0) DISCOUNT_PRICE,
Sum(pll.quantity)*PLA.UNIT_PRICE CF_NET_VALUE_SUM,
PHA.ATTRIBUTE10 CARRYING_COST,
(NVL((NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE),0)+NVL(PLA.ATTRIBUTE5,0))*SUM(pll.quantity) DISCOUNT_PRICE_SUM,
--PLA.UNIT_PRICE-(NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE)-NVL(PLA.ATTRIBUTE5,0) UNIT_PRICE,
pla.ATTRIBUTE5 line_dis,
XX_P2P_EMP_INFO.XX_P2P_GET_EMPNP_MAIL(pha.creation_date,pha.created_by) creator_details,
NVL(pha1.segment1,'...............') quote_no,
NVL(pha1.QUOTE_VENDOR_QUOTE_NUMBER,'...............') supplier_quote,
NVL(TO_CHAR (pha1.REPLY_DATE, 'DD-MON-RRRR'),'...............')  REPLY_DATE,
 '(For '||pov.vendor_name||')' SUPP_ALIAS,
NVL(PHA.ATTRIBUTE15,0) VAT
--  case  when PHA.ATTRIBUTE15 is null then  'VAT Included' else PHA.ATTRIBUTE15  end vat
  FROM po_headers_all pha,
       po_headers_all pha1,
       po_lines_all pla,
       mtl_units_of_measure_tl muom,
       PO_LINE_LOCATIONS_ALL PLL,
       ap_suppliers pov,
       ap_supplier_sites_all pvs,
       hr_locations_all hrl,
       hr_locations_all hrl1, 
       (SELECT inventory_item_id,
                        (segment1 || '-' || segment2 || '-' || segment3|| '-' || segment4
                        ) item_code
                   FROM mtl_system_items_b
                   group by inventory_item_id,
                        (segment1 || '-' || segment2 || '-' || segment3|| '-' || segment4
                        )) mst,
                        mtl_parameters MP
 WHERE pha.po_header_id = pla.po_header_id
   AND pha.vendor_id = pov.vendor_id
   AND pha.vendor_site_id = pvs.vendor_site_id
   AND pov.vendor_id = pvs.vendor_id
   AND pha.type_lookup_code IN ('BLANKET')
   AND NVL (UPPER (pha.authorization_status), 'INCOMPLETE') = 'APPROVED'
   AND pha.approved_flag = 'Y'
   AND pla.item_id = mst.inventory_item_id
   AND hrl.location_id = pll.ship_to_location_id
   AND hrl1.location_id = pha.bill_to_location_id 
   AND pha1.po_header_id(+) = pha.from_header_id
   AND pla.unit_meas_lookup_code=MUOM.UNIT_OF_MEASURE(+)
   AND NVL(PHA.CANCEL_FLAG,'N')='N'
   AND NVL(PLA.CANCEL_FLAG,'N')='N'
   AND UPPER(pll.SHIPMENT_TYPE)='PRICE BREAK'
   AND pha.org_id = :p_org_id
  AND PLA.PO_LINE_ID=PLL.PO_LINE_ID
   AND pha.po_header_id = :p_po_no
   --AND 1=nvl2(:p_release,900,1)
   AND MP.ORGANIZATION_ID=pll.ship_to_organization_id
  -- AND :p_release IS NULL
GROUP BY
PLA.ATTRIBUTE3,
pha.attribute4,
PHA.TYPE_LOOKUP_CODE, 
PLA.LINE_NUM,
PHA.PO_HEADER_ID,
pha.segment1,
TO_CHAR (pha.creation_date, 'DD-MON-YYYY'),
PHA.ATTRIBUTE2,
XX_GET_ACCT_FLEX_SEG_DESC (7, PHA.ATTRIBUTE14),
PHA.ATTRIBUTE4,
PHA.ATTRIBUTE3,
TO_CHAR(TO_DATE(PHA.ATTRIBUTE9,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YYYY'),
PHA.CURRENCY_CODE,
PHA.RATE,
PHA.ATTRIBUTE10,
PHA.ATTRIBUTE12,
PHA.ATTRIBUTE11,
pov.segment1,
pov.vendor_name,
ADDRESS_LINE1||' '||
ADDRESS_LINE2,
pvs.city||'-'||pvs.zip,
pvs.phone,
pvs.telex,
pvs.EMAIL_ADDRESS,
XX_GET_HR_OPERATING_UNIT(:p_org_id) ,
hrl.ADDRESS_LINE_1||' '||hrl.ADDRESS_LINE_2||' '||hrl.ADDRESS_LINE_3||', '||hrl.REGION_1||'-'||hrl.POSTAL_CODE,
MP.ORGANIZATION_CODE,
hrl.TELEPHONE_NUMBER_1,
HRL.TELEPHONE_NUMBER_2,
HRL.LOC_INFORMATION13,
TO_CHAR(NULL),
pla.ATTRIBUTE5,
PLA.UNIT_PRICE,
NVL((NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE),0)+NVL(PLA.ATTRIBUTE5,0),
TO_CHAR(NULL),
TO_CHAR (pll.PROMISED_DATE, 'DD-MON-RRRR'),
TO_CHAR (pll.NEED_BY_DATE, 'DD-MON-RRRR') ,
XX_P2P_PKG.XX_FND_REQUISITION_INFO(PLL.ATTRIBUTE1,:P_ORG_ID,PLL.ATTRIBUTE2,'RNUM'),
'' ,
'' ,
mst.item_code,
PHA.ATTRIBUTE11,
PHA.ATTRIBUTE3,
PHA.ATTRIBUTE7,
PHA.ATTRIBUTE2,
PHA.ATTRIBUTE6,
PHA.COMMENTS,
PLA.ATTRIBUTE6,
PLA.ATTRIBUTE7,
PLA.ATTRIBUTE8,
TO_CHAR (pha.APPROVED_DATE, 'DD-MON-YYYY'),
PHA.ATTRIBUTE4,
PHA.ATTRIBUTE5,
pla.attribute1,
pla.attribute2,
PLA.NOTE_TO_VENDOR ,
pla.item_description,MUOM.UOM_CODE,
PLA.UNIT_PRICE-(NVL(PLA.ATTRIBUTE11,0)/100*PLA.UNIT_PRICE)-NVL(PLA.ATTRIBUTE5,0),
XX_P2P_EMP_INFO.XX_P2P_GET_EMPNP_MAIL(pha.creation_date,pha.created_by),
NVL(pha1.segment1,'...............'),
NVL(pha1.QUOTE_VENDOR_QUOTE_NUMBER,'...............'),
NVL(TO_CHAR (pha1.REPLY_DATE, 'DD-MON-RRRR'),'...............'),
 '(For '||pov.vendor_name||')',
NVL(PHA.ATTRIBUTE15,0),
PHA.ATTRIBUTE13, 
--PHA.ATTRIBUTE15,
--to_char(pra.RELEASE_DATE, 'DD-MON-RRRR'),
null, 
pha.REVISION_NUM,
(hrl1.ADDRESS_LINE_1||' '||hrl1.ADDRESS_LINE_2||' '||hrl1.ADDRESS_LINE_3||', '||hrl1.REGION_1||'-'||hrl1.POSTAL_CODE) 
 order by line_num




--============================
--QUERY FOR BRAND/SERVICE REPORT FOR MAMUN BOS V2
--============================


SELECT 
distinct aia.org_id,WXD.FINANCE_CATEGORY,WXD.ITEM_TYPE,WXD.ITEM_GROUP, WXD.ITEM_SUB_GROUP,
SUBSTR(XX_GET_HR_OPERATING_UNIT (AIA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (AIA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
 APS.VENDOR_NAME,
 APS.SEGMENT1 VENDOR_NO,
 POH.SEGMENT1 PO_NUMBER,
 POH.APPROVED_DATE  PO_APPROVED_DATE,
   (
 SELECT DESCRIPTION
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_DESCRIPTION,
    (
 SELECT SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_CODE,
 -- XXGET_ITEM_CODE(ITEM_ID) ITEM_CODE,
  POL.QUANTITY* POL.UNIT_PRICE PO_AMOUNT,
--  (
--  SELECT SUM ( (PLA.UNIT_PRICE * PLA.QUANTITY)) PRICE
--   FROM PO_LINES_ALL PLA, PO_HEADERS_ALL PHA
--   WHERE PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
--   AND PHA.ORG_ID = AIA.ORG_ID
--   AND PHA.SEGMENT1 =POH.SEGMENT1
--         ) PO_AMOUNT,
 RSH.RECEIPT_NUM GRN_NUMBER, 
RT.CREATION_DATE GRN_DATE,
--RL.QUANTITY_RECEIVED,
RT.QUANTITY  * POL.UNIT_PRICE GRN_AMOUNT,
 AIA.INVOICE_NUM,
 AIA.INVOICE_DATE,
AIA.GL_DATE ,
AIA.INVOICE_AMOUNT, 
 AIA.DOC_SEQUENCE_VALUE INV_VOUCHER_NO,
 XX_GET_EMP_NAME_FROM_USER_ID (AIA.CREATED_BY) INV_CREATED_BY,
(SELECT  distinct XX_GET_ACCT_FLEX_SEG_DESC(4,SEGMENT4)  account_name 
FROM gl_code_combinations   
 WHERE CODE_COMBINATION_ID = AIDA.DIST_CODE_COMBINATION_ID ) GL_CODE,
 ( SELECT CONCATENATED_SEGMENTS
 FROM GL_CODE_COMBINATIONS_KFV
 WHERE CODE_COMBINATION_ID = AIDA.DIST_CODE_COMBINATION_ID
 ) DIST_GL_CODE,
ACA.DOC_SEQUENCE_VALUE PAYMENT_VOUCHER,
ACA.CREATION_DATE PAY_CREATE_DATE
,ACA.DOC_CATEGORY_CODE PAYMENT_TYPE
,ACA.STATUS_LOOKUP_CODE PAYMENT_STATUS
,ACA.AMOUNT PAY_AMOUNT
,XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
FROM AP_INVOICES_ALL AIA,
 AP_INVOICE_LINES_ALL AILA,
 AP_SUPPLIERS APS,
 AP_SUPPLIER_SITES_ALL APSS,
 AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
 PO_HEADERS_ALL POH,
 PO_LINES_ALL POL,
 PO_LINE_LOCATIONS_ALL PLL,
 PO_DISTRIBUTIONS_ALL PDA,
 RCV_SHIPMENT_HEADERS RSH,
 RCV_SHIPMENT_LINES RL,
  RCV_TRANSACTIONS RT,
AP_INVOICE_PAYMENTS_ALL AIPA, 
AP_CHECKS_ALL ACA,
 WBI_XXKBGITEM_MT_D WXD
WHERE AIA.INVOICE_ID = AILA.INVOICE_ID
AND AILA.ORG_ID = AIA.ORG_ID
AND AILA.PO_HEADER_ID = POH.PO_HEADER_ID
AND AILA.PO_LINE_ID = POL.PO_LINE_ID
AND AILA.INVOICE_ID =AIDA.INVOICE_ID
AND AIA.VENDOR_ID = APS.VENDOR_ID
AND AIA.VENDOR_SITE_ID = APSS.VENDOR_SITE_ID
AND AIA.VENDOR_ID = APSS.VENDOR_ID
AND APSS.ORG_ID = AIA.ORG_ID
AND AIDA.INVOICE_LINE_NUMBER = AILA.LINE_NUMBER
AND AIDA.ORG_ID= AILA.ORG_ID
AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND PLL.PO_HEADER_ID = POH.PO_HEADER_ID
AND PLL.PO_LINE_ID = POL.PO_LINE_ID
AND PLL.LINE_LOCATION_ID = PDA.LINE_LOCATION_ID
AND PLL.PO_HEADER_ID = PDA.PO_HEADER_ID
AND PLL.PO_LINE_ID = PDA.PO_LINE_ID
AND POL.ORG_ID = PDA.ORG_ID
AND POH.ORG_ID = PLL.ORG_ID
AND AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
AND RT.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
AND RSH.SHIPMENT_HEADER_ID =RL.SHIPMENT_HEADER_ID 
AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
AND AIA.INVOICE_ID=AIPA.INVOICE_ID(+)
AND AIPA.CHECK_ID=ACA.CHECK_ID(+)
AND PDA.GL_CANCELLED_DATE is NULL
AND (:P_ORG_ID IS NULL OR AIA.ORG_ID = :P_ORG_ID) --AP org id
--AND (:P_VENDOR_NO IS NULL OR aps.segment1 = :P_VENDOR_NO) --aps.segment1 for supplier/vendor name
AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
AND (:P_PO_NO IS NULL OR poh.segment1 = :P_PO_NO) 
AND (:P_GRN_NO IS NULL OR rsh.receipt_num = :P_GRN_NO)
and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
 and AIA.VENDOR_ID = NVL(:P_VENDOR_ID, AIA.VENDOR_ID) 
   AND WXD.INVENTORY_ITEM_ID= POL.ITEM_ID 
   AND PLL.SHIP_TO_ORGANIZATION_ID= WXD.ORGANIZATION_ID
   AND WXD.FINANCE_CATEGORY =NVL(:P_FINANCE_CAT,WXD.FINANCE_CATEGORY)
   AND WXD.ITEM_TYPE = NVL(:P_ITEM_TYPE,WXD.ITEM_TYPE)
   AND WXD.ITEM_GROUP=NVL(:P_ITEM_GROUP,WXD.ITEM_GROUP)
   AND WXD.ITEM_SUB_GROUP =NVL(:P_ITEM_SUGROUP,WXD.ITEM_SUB_GROUP)    
union all
SELECT 
distinct PHA.org_id,WXD.FINANCE_CATEGORY,WXD.ITEM_TYPE,WXD.ITEM_GROUP, WXD.ITEM_SUB_GROUP,
SUBSTR(XX_GET_HR_OPERATING_UNIT (PHA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (PHA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
       ASP.VENDOR_NAME,
       ASP.SEGMENT1 VENDOR_NO,
      PHA.SEGMENT1 PO_NUMBER,
       PHA.APPROVED_DATE  PO_APPROVED_DATE,
           PLA.ITEM_DESCRIPTION,
            XXGET_ITEM_CODE(PLA.ITEM_ID) ITEM_CODE,
     (PLA.UNIT_PRICE* PLA.QUANTITY) PO_AMOUNT,
          RH.RECEIPT_NUM GRN_NUMBER, 
          RT.CREATION_DATE GRN_DATE,
--          RL.QUANTITY_RECEIVED,
            RT.QUANTITY  * PLA.UNIT_PRICE GRN_AMOUNT,
            NULL INVOICE_NUM,
            NULL INVOICE_DATE,
            NULL GL_DATE,
            NULL INVOICE_AMOUNT,
            NULL INV_VOUCHER_NO,
            NULL INV_CREATED_BY,
            NULL GL_CODE,
          NULL DIST_GL_CODE,
          NULL PAYMENT_VOUCHER,
          NULL PAY_CREATE_DATE,
          NULL PAYMENT_TYPE,
          NULL PAYMENT_STATUS,
          NULL PAY_AMOUNT,
         XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
 from PO_HEADERS_ALL PHA, PO_LINES_ALL PLA, PO_LINE_LOCATIONS_ALL PLL,PO_DISTRIBUTIONS_ALL PDA, AP_SUPPLIERS ASP,
 RCV_TRANSACTIONS RT,RCV_SHIPMENT_LINES RL, RCV_SHIPMENT_HEADERS RH,  WBI_XXKBGITEM_MT_D WXD
 WHERE PHA.PO_HEADER_ID =PLA.PO_HEADER_ID
 and PHA.po_header_id = PLA.po_header_id
 and PLA.po_line_id= pll.po_line_id
 and PHA.po_header_id= pll.po_header_id
 and PHA.PO_HEADER_ID= PLA.PO_HEADER_ID
 AND PLA.PO_LINE_ID= PDA.PO_LINE_ID
 AND PLA.QUANTITY <> 0
 AND PHA.PO_HEADER_ID= RT.PO_HEADER_ID
 AND PLA.PO_LINE_ID= RT.PO_LINE_ID
 AND PDA.GL_CANCELLED_DATE is NULL
 AND RT.TRANSACTION_TYPE= 'DELIVER'
    AND PDA.PO_DISTRIBUTION_ID NOT IN
      (SELECT PO_DISTRIBUTION_ID FROM PO_DISTRIBUTIONS_ALL PDA
       WHERE PO_DISTRIBUTION_ID IN (SELECT DISTINCT  PO_DISTRIBUTION_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL))
 AND RH.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID
 AND RH.SHIPMENT_HEADER_ID= RL.SHIPMENT_HEADER_ID
 AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
 AND ASP.VENDOR_ID= PHA.VENDOR_ID
   AND (:P_ORG_ID IS NULL OR PHA.ORG_ID = :P_ORG_ID)
  AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
  AND (:P_PO_NO IS NULL OR PHA.segment1 = :P_PO_NO) 
  AND (:P_GRN_NO IS NULL OR rh.receipt_num = :P_GRN_NO) 
  and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
   and PHA.VENDOR_ID = NVL(:P_VENDOR_ID, PHA.VENDOR_ID)
      AND WXD.INVENTORY_ITEM_ID= PLA.ITEM_ID 
   AND PLL.SHIP_TO_ORGANIZATION_ID= WXD.ORGANIZATION_ID
   AND WXD.FINANCE_CATEGORY =NVL(:P_FINANCE_CAT,WXD.FINANCE_CATEGORY)
   AND WXD.ITEM_TYPE = NVL(:P_ITEM_TYPE,WXD.ITEM_TYPE)
   AND WXD.ITEM_GROUP=NVL(:P_ITEM_GROUP,WXD.ITEM_GROUP)
   AND WXD.ITEM_SUB_GROUP =NVL(:P_ITEM_SUGROUP,WXD.ITEM_SUB_GROUP)
        


SELECT * FROM ORG_ORGANIZATION_DEFINITIONS where ORGANIZATION_CODE = 'KSH'-- RCV_TRANSACTIONS

SELECT * FROM PO_LINES_ALL

--====================
QUERY FOR REPORT FOR MAMUN BOS V1
--========================

SELECT 
distinct aia.org_id, MTC.SEGMENT1 ITEM_TYPE, MTC.SEGMENT2 ITEM_GROUP, MTC.SEGMENT3 ITEM_SUB_GROUP,
SUBSTR(XX_GET_HR_OPERATING_UNIT (AIA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (AIA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
 APS.VENDOR_NAME,
 APS.SEGMENT1 VENDOR_NO,
 POH.SEGMENT1 PO_NUMBER,
 POH.APPROVED_DATE  PO_APPROVED_DATE,
   (
 SELECT DESCRIPTION
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_DESCRIPTION,
    (
 SELECT SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_CODE,
 -- XXGET_ITEM_CODE(ITEM_ID) ITEM_CODE,
  POL.QUANTITY* POL.UNIT_PRICE PO_AMOUNT,
--  (
--  SELECT SUM ( (PLA.UNIT_PRICE * PLA.QUANTITY)) PRICE
--   FROM PO_LINES_ALL PLA, PO_HEADERS_ALL PHA
--   WHERE PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
--   AND PHA.ORG_ID = AIA.ORG_ID
--   AND PHA.SEGMENT1 =POH.SEGMENT1
--         ) PO_AMOUNT,
 RSH.RECEIPT_NUM GRN_NUMBER, 
RT.CREATION_DATE GRN_DATE,
--RL.QUANTITY_RECEIVED,
--RT.QUANTITY QUANTITY_DELIVERED,
 AIA.INVOICE_NUM,
 AIA.INVOICE_DATE,
AIA.GL_DATE ,
AIA.INVOICE_AMOUNT, 
 AIA.DOC_SEQUENCE_VALUE INV_VOUCHER_NO,
 XX_GET_EMP_NAME_FROM_USER_ID (AIA.CREATED_BY) INV_CREATED_BY,
 ( SELECT CONCATENATED_SEGMENTS
 FROM GL_CODE_COMBINATIONS_KFV
 WHERE CODE_COMBINATION_ID = AIDA.DIST_CODE_COMBINATION_ID
 ) DIST_GL_CODE,
ACA.DOC_SEQUENCE_VALUE PAYMENT_VOUCHER,
ACA.CREATION_DATE PAY_CREATE_DATE
,ACA.DOC_CATEGORY_CODE PAYMENT_TYPE
,ACA.STATUS_LOOKUP_CODE PAYMENT_STATUS
,ACA.AMOUNT PAY_AMOUNT
,XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
FROM AP_INVOICES_ALL AIA,
 AP_INVOICE_LINES_ALL AILA,
 AP_SUPPLIERS APS,
 AP_SUPPLIER_SITES_ALL APSS,
 AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
 PO_HEADERS_ALL POH,
 PO_LINES_ALL POL,
 PO_LINE_LOCATIONS_ALL PLL,
 PO_DISTRIBUTIONS_ALL PDA,
 RCV_SHIPMENT_HEADERS RSH,
 RCV_SHIPMENT_LINES RL,
  RCV_TRANSACTIONS RT,
AP_INVOICE_PAYMENTS_ALL AIPA, 
AP_CHECKS_ALL ACA,
 mtl_categories mtc
WHERE AIA.INVOICE_ID = AILA.INVOICE_ID
AND AILA.ORG_ID = AIA.ORG_ID
AND AILA.PO_HEADER_ID = POH.PO_HEADER_ID
AND AILA.PO_LINE_ID = POL.PO_LINE_ID
AND AILA.INVOICE_ID =AIDA.INVOICE_ID
AND AIA.VENDOR_ID = APS.VENDOR_ID
AND AIA.VENDOR_SITE_ID = APSS.VENDOR_SITE_ID
AND AIA.VENDOR_ID = APSS.VENDOR_ID
AND APSS.ORG_ID = AIA.ORG_ID
AND AIDA.INVOICE_LINE_NUMBER = AILA.LINE_NUMBER
AND AIDA.ORG_ID= AILA.ORG_ID
AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND PLL.PO_HEADER_ID = POH.PO_HEADER_ID
AND PLL.PO_LINE_ID = POL.PO_LINE_ID
AND PLL.LINE_LOCATION_ID = PDA.LINE_LOCATION_ID
AND PLL.PO_HEADER_ID = PDA.PO_HEADER_ID
AND PLL.PO_LINE_ID = PDA.PO_LINE_ID
AND POL.ORG_ID = PDA.ORG_ID
AND POH.ORG_ID = PLL.ORG_ID
AND AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
AND RT.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
AND RSH.SHIPMENT_HEADER_ID =RL.SHIPMENT_HEADER_ID 
AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
AND AIA.INVOICE_ID=AIPA.INVOICE_ID(+)
AND AIPA.CHECK_ID=ACA.CHECK_ID(+)
AND PDA.GL_CANCELLED_DATE is NULL
AND (:P_ORG_ID IS NULL OR AIA.ORG_ID = :P_ORG_ID) --AP org id
--AND (:P_VENDOR_NO IS NULL OR aps.segment1 = :P_VENDOR_NO) --aps.segment1 for supplier/vendor name
AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
AND (:P_PO_NO IS NULL OR poh.segment1 = :P_PO_NO) 
AND (:P_GRN_NO IS NULL OR rsh.receipt_num = :P_GRN_NO)
and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
 and AIA.VENDOR_ID = NVL(:P_VENDOR_ID, AIA.VENDOR_ID)
   AND  POL.CATEGORY_ID = MTC.CATEGORY_ID   
   AND MTC.SEGMENT1= NVL(:P_ITEM_TYPE,MTC.SEGMENT1)--'SERVICE'
   AND MTC.SEGMENT2 = NVL(:P_ITEM_GROUP,MTC.SEGMENT2) -- 'BRANDING ITEMS'
   AND MTC.SEGMENT3 =NVL(:P_ITEM_SUBGROUP,MTC.SEGMENT3) -- 'OUTDOOR BRANDING'
union all
SELECT 
distinct PHA.org_id,MTC.SEGMENT1 ITEM_TYPE, MTC.SEGMENT2 ITEM_GROUP, MTC.SEGMENT3 ITEM_SUB_GROUP,
SUBSTR(XX_GET_HR_OPERATING_UNIT (PHA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (PHA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
       ASP.VENDOR_NAME,
       ASP.SEGMENT1 VENDOR_NO,
      PHA.SEGMENT1 PO_NUMBER,
       PHA.APPROVED_DATE  PO_APPROVED_DATE,
           PLA.ITEM_DESCRIPTION,
            XXGET_ITEM_CODE(PLA.ITEM_ID) ITEM_CODE,
     (PLA.UNIT_PRICE* PLA.QUANTITY) PO_AMOUNT,
          RH.RECEIPT_NUM GRN_NUMBER, 
          RT.CREATION_DATE GRN_DATE,
--          RL.QUANTITY_RECEIVED,
--         RT.QUANTITY QUANTITY_DELIVERED,
            NULL INVOICE_NUM,
            NULL INVOICE_DATE,
            NULL GL_DATE,
            NULL INVOICE_AMOUNT,
            NULL INV_VOUCHER_NO,
            NULL INV_CREATED_BY,
          NULL DIST_GL_CODE,
          NULL PAYMENT_VOUCHER,
          NULL PAY_CREATE_DATE,
          NULL PAYMENT_TYPE,
          NULL PAYMENT_STATUS,
          NULL PAY_AMOUNT,
         XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
 from PO_HEADERS_ALL PHA, PO_LINES_ALL PLA, PO_LINE_LOCATIONS_ALL PLL,PO_DISTRIBUTIONS_ALL PDA, AP_SUPPLIERS ASP,
 RCV_TRANSACTIONS RT,RCV_SHIPMENT_LINES RL, RCV_SHIPMENT_HEADERS RH, mtl_categories mtc
 WHERE PHA.PO_HEADER_ID =PLA.PO_HEADER_ID
 and PHA.po_header_id = PLA.po_header_id
 and PLA.po_line_id= pll.po_line_id
 and PHA.po_header_id= pll.po_header_id
 and PHA.PO_HEADER_ID= PLA.PO_HEADER_ID
 AND PLA.PO_LINE_ID= PDA.PO_LINE_ID
 AND PLA.QUANTITY <> 0
 AND PHA.PO_HEADER_ID= RT.PO_HEADER_ID
 AND PLA.PO_LINE_ID= RT.PO_LINE_ID
 AND PDA.GL_CANCELLED_DATE is NULL
 AND RT.TRANSACTION_TYPE= 'DELIVER'
    AND PDA.PO_DISTRIBUTION_ID NOT IN
      (SELECT PO_DISTRIBUTION_ID FROM PO_DISTRIBUTIONS_ALL PDA
       WHERE PO_DISTRIBUTION_ID IN (SELECT DISTINCT  PO_DISTRIBUTION_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL))
 AND RH.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID
 AND RH.SHIPMENT_HEADER_ID= RL.SHIPMENT_HEADER_ID
 AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
 AND ASP.VENDOR_ID= PHA.VENDOR_ID
   AND (:P_ORG_ID IS NULL OR PHA.ORG_ID = :P_ORG_ID)
  AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
  AND (:P_PO_NO IS NULL OR PHA.segment1 = :P_PO_NO) 
  AND (:P_GRN_NO IS NULL OR rh.receipt_num = :P_GRN_NO) 
  and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
   and PHA.VENDOR_ID = NVL(:P_VENDOR_ID, PHA.VENDOR_ID)
   AND  PLA.CATEGORY_ID = MTC.CATEGORY_ID
   AND MTC.SEGMENT1= NVL(:P_ITEM_TYPE,MTC.SEGMENT1)--'SERVICE'
   AND MTC.SEGMENT2 = NVL(:P_ITEM_GROUP,MTC.SEGMENT2) -- 'BRANDING ITEMS'
   AND MTC.SEGMENT3 =NVL(:P_ITEM_SUBGROUP,MTC.SEGMENT3) 
        
  
  select DISTINCT SEGMENT1  from mtl_categories  where SEGMENT1='SERVICE'
  
  select * from MTL_ITEM_CATEGORIES_V where CATEGORY_SET_ID = 1100000041
  
            SELECT DISTINCT CATEGORY_CONCAT_SEGS
             FROM MTL_ITEM_CATEGORIES_V
            WHERE     INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
                 -- AND CATEGORY_SET_ID = 1100000041
                --  AND ORGANIZATION_ID = MSIB.ORGANIZATION_ID

--====================
QUERY FOR REPORT FOR MAMUN BOS
--========================
SELECT 
SUBSTR(XX_GET_HR_OPERATING_UNIT (PHA.ORG_ID),5) OPERATING_UNIT,
MTC.SEGMENT1 ITEM_TYPE, MTC.SEGMENT2 ITEM_GROUP, MTC.SEGMENT3 ITEM_SUB_GROUP,
XX_INV_PKG.XXGET_ORG_LOCATION (PHA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
       ASP.VENDOR_NAME,
       ASP.SEGMENT1 VENDOR_NO,
      PHA.SEGMENT1 PO_NUMBER,
       PHA.APPROVED_DATE  PO_APPROVED_DATE,
           PLA.ITEM_DESCRIPTION,
          SUM(PLA.UNIT_PRICE* PLA.QUANTITY) PO_AMOUNT,
          RH.RECEIPT_NUM GRN_NUMBER, 
          RT.CREATION_DATE GRN_DATE
--          RL.QUANTITY_RECEIVED,
--         RT.QUANTITY QUANTITY_DELIVERED,
        -- XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
  FROM PO_DISTRIBUTIONS_ALL PDA
      ,PO_HEADERS_ALL PHA
      ,RCV_SHIPMENT_LINES RSL
      ,AP_SUPPLIERS ASP
      ,PO_LINES_ALL PLA
     , mtl_categories mtc
      ,RCV_SHIPMENT_LINES RL
      ,RCV_SHIPMENT_HEADERS RH
      ,RCV_TRANSACTIONS RT
 WHERE 1=1
   AND PDA.PO_HEADER_ID=PHA.PO_HEADER_ID
   AND RH.SHIPMENT_HEADER_ID = RL.SHIPMENT_HEADER_ID
   AND RH.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
   AND RL.SHIPMENT_LINE_ID = RT.SHIPMENT_LINE_ID
   AND TRANSACTION_TYPE = 'DELIVER'
   AND PDA.PO_DISTRIBUTION_ID NOT IN
      (SELECT PO_DISTRIBUTION_ID FROM PO_DISTRIBUTIONS_ALL PDA
       WHERE PO_DISTRIBUTION_ID IN (SELECT DISTINCT  PO_DISTRIBUTION_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL))
   AND RSL.PO_HEADER_ID=PHA.PO_HEADER_ID  
   AND ASP.VENDOR_ID=PHA.VENDOR_ID
   AND PHA.PO_HEADER_ID=PLA.PO_HEADER_ID
   AND PLA.PO_LINE_ID=PDA.PO_LINE_ID
   AND RL.PO_HEADER_ID= PHA.PO_HEADER_ID
   AND PLA.CANCEL_FLAG <> 'Y'
   AND PLA.QUANTITY <> 0
 --  AND (:P_ORG_ID IS NULL OR PHA.ORG_ID = :P_ORG_ID)
  AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.CREATION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
  AND (:P_PO_NO IS NULL OR PHA.segment1 = :P_PO_NO) 
  AND  PLA.CATEGORY_ID = MTC.CATEGORY_ID
 -- AND (:P_GRN_NO IS NULL OR rh.receipt_num = :P_GRN_NO) 
GROUP BY ASP.VENDOR_NAME,PHA.SEGMENT1,PHA.CREATION_DATE,PHA.TYPE_LOOKUP_CODE ,PHA.PO_HEADER_ID, RH.RECEIPT_NUM,PHA.ORG_ID, ASP.SEGMENT1, 
RT.ORGANIZATION_ID, PLA.ITEM_DESCRIPTION, PHA.APPROVED_DATE, RT.CREATION_DATE, MTC.SEGMENT1, MTC.SEGMENT2, MTC.SEGMENT3
ORDER BY  PO_NUMBER
 --RL.QUANTITY_RECEIVED,RT.QUANTITY 





--==================================
--BRAND ITEM ISSUES DATE : 13-DEC-2022
--===============================

SELECT * FROM mtl_categories mc where CATEGORY_ID = 5304


SELECT * FROM mtl_item_categories_v where CATEGORY_ID = 5304  -- SEGMENT1 ITEM_TYPE, SEGMENT2 ITEM_GROUP, SEGMENT3 ITEM_SUB_GROUP

 AND POL.CATEGORY_ID = MC.CATEGORY_ID
 
SELECT * FROM PO_LINES_ALL

SELECT * FROM PO_REQUISITION_HEADERS_ALL WHERE REQUISITION

SELECT * FROM PO_REQUISITION_LINES_ALL where ITEM_DESCRIPTION = 'TRAIN BRANDING'

SELECT * FROM PO_HEADERS_ALL WHERE PO_HEADER_ID=904894

SELECT CATEGORY_ID  FROM PO_LINES_ALL where ITEM_DESCRIPTION = 'TRAIN BRANDING'

SELECT * FROM XXKBG_BI_PO_GRN where PO_HEADER_ID=904894


SELECT  GET_ORG_CODE_FROM_ID(a.ORGANIZATION_ID) ORG_CODE , B.TRANSACTION_TYPE_NAME,TO_CHAR(A.
TRANSACTION_DATE,'MON-YY') TRANS_DATE, 
 XXGET_ITEM_DESCRIPTION(A.INVENTORY_ITEM_ID, A.ORGANIZATION_ID) ITEM_DESC, A.*
  FROM MTL_MATERIAL_TRANSACTIONS A, MTL_TRANSACTION_TYPES B, ORG_ORGANIZATION_DEFINITIONS O
 WHERE A.TRANSACTION_TYPE_ID = B.TRANSACTION_TYPE_ID 
 AND A.ORGANIZATION_ID = O.ORGANIZATION_ID
  and  INVENTORY_ITEM_ID IN (885082)
   --AND  TRUNC(TRANSACTION_DATE)  BETWEEN '01-OCT-2018' AND '31-OCT-2018'   -- 2,353
  --AND O.LEGAL_ENTITY = 26280






select * from MTL_TXN_REQUEST_LINES_V where header_id=1803281

select * from MTL_TXN_REQUEST_LINES_V where header_id=1762447

select ATTRIBUTE1 COUNTRY, ATTRIBUTE11 Zone, ATTRIBUTE12 REZION, ATTRIBUTE14 AREA,  ATTRIBUTE15,ATTRIBUTE1,ATTRIBUTE2 SALES_PERSON_NAME ,ATTRIBUTE3  TERIRITORY, ATTRIBUTE4,ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7  from MTL_TXN_REQUEST_HEADERS_V where header_id=1803281

select ATTRIBUTE1 COUNTRY, ATTRIBUTE11 Zone, ATTRIBUTE12 REZION, ATTRIBUTE14 AREA,  ATTRIBUTE15 TERIRITORY, ATTRIBUTE2 SALES_PERSON_NAME  from MTL_TXN_REQUEST_HEADERS_V where header_id=1762447

--================================================================================================================

--XXKSRM MOVE ORDER FOR SALES AND MARKETING(Brand)
-- Date  2-JAN-2022

SELECT    
                 MTRL.ORGANIZATION_ID
                ,NVL((SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') ORG_NAME
                ,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY) DEPARTMENT
                ,MTHL.ATTRIBUTE_CATEGORY
               ,(SELECT DISTINCT  OTM.TRIPSYS_NO FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) TRIP_NO
              ,(SELECT DISTINCT DECODE(OTM.EMPLOYEE_ID,NULL,UNLISTED_DRIVER,(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = OTM.EMPLOYEE_ID)) DRIVER_NAME FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) DRIVER_NAME
                ,MTRL.ATTRIBUTE15 GATE_PASS_NO
                ,XX_INV_PKG.XXGET_CUSTOMER_NAME((SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) ) CUSTOMER_NAME           
             ---- ,(SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) CUSTOMER_NAME
               ,(SELECT ATTRIBUTE1 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Move Order Issue' AND HEADER_ID=MTHL.HEADER_ID) WORK_ORDER_NO
                ,MTRL.REQUEST_NUMBER MOVE_ORDER_NUMBER
                 , MTHL.attribute10 Event_Type
               -- ,MTHL.attribute1 Management
                ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute1 else null end) Management
                ,   (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute2 else null end) Govt_NON_GOVT_Office
              --  ,MTHL.attribute2 Govt_NON_GOVT_Office
                ,MTHL.attribute3 Media
                , MTHL.attribute4  KSRM_Office
                ,MTHL.attribute5 DESIGNATION
                , MTHL.attribute13 Destination_and_through_by
              --  , MTHL.attribute14 GIFT_TO 
                , (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute14 else null end) GIFT_TO
              ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT  NULL THEN  MTHL.attribute1 else null end) COUNTRY
               --  , MTHL.ATTRIBUTE1 COUNTRY
                  , MTHL.ATTRIBUTE11 DEPARTMENT
                 ,  MTHL.ATTRIBUTE12 REZION
                 --  ,MTHL.ATTRIBUTE14 AREA
                      ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute14 else null end) AREA
                  ,MTHL.ATTRIBUTE15 TERITORY
                   --,MTHL.ATTRIBUTE2 SALES_PERSON_NAME   
                      ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute2 else null end) SALES_PERSON_NAME      
                ,MTRL.DATE_REQUIRED  MOVE_ORDER_DATE
                ,MTRL.TRANSACTION_TYPE_NAME MOVE_ORDER_TYPE
                ,ML.MEANING MO_STATUS_LINE
                ,MTHL.HEADER_STATUS_NAME  MO_STATUS
                ,(SELECT ATTRIBUTE9 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Issue to Project' AND HEADER_ID=MTHL.HEADER_ID) PROJECT_NAME
                ,MTRL.LINE_NUMBER
                , (MSI.SEGMENT1 || '|' || MSI.SEGMENT2 || '|' || MSI.SEGMENT3||'|' || MSI.SEGMENT4)    ITEM_CODE
                ,MSI.DESCRIPTION
                ,MTRL.UOM_CODE 
                ---=========================================
                ,MTRL.FROM_SUBINVENTORY_CODE
                ,MTRL.INVENTORY_ITEM_ID
                -----------------------------------------------------
                , (SELECT NVL(SUM(PRIMARY_QUANTITY),0)
                FROM 
                MTL_MATERIAL_TRANSACTIONS
                WHERE 
                ORGANIZATION_ID=MTRL.ORGANIZATION_ID
                AND SUBINVENTORY_CODE=NVL(MTRL.FROM_SUBINVENTORY_CODE,SUBINVENTORY_CODE)
                AND INVENTORY_ITEM_ID=MTRL.INVENTORY_ITEM_ID 
                AND  TRANSACTION_DATE <MTRL.DATE_REQUIRED) IO_STOCK
                ---=========================================
                ,MTRL.QUANTITY  MO_QTY
                ,XX.QTY_ISSUED MO_ISSUE_QTY
                ,CASE WHEN MTRL.LINE_STATUS <>5 THEN 0   ELSE (MTRL.QUANTITY-MTRL.QUANTITY_DELIVERED)  END  CANCEL_QTY
                ,XX.SUBINVENTORY_CODE
                , (SELECT SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4||'|'||SEGMENT5 LOCATOR_DESC FROM MTL_ITEM_LOCATIONS WHERE INVENTORY_LOCATION_ID=XX.LOCATOR_ID AND ORGANIZATION_ID=MTRL.ORGANIZATION_ID) LOCATOR
                ,XX.LOT_NUMBER
                ,XX_INV_PKG.XXGET_SERIAL_NUMBER(XX.TRANSACTION_ID) SERIAL_NUMBER
               ----,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 AND OU_ID=(SELECT OPERATING_UNIT_ID FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MTRL.ORGANIZATION_ID)) USEOFAREA
               ,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 ) USEOFAREA
                ,MTRL.REFERENCE REASON
                ---===================================================
                ,MTHL.DESCRIPTION PURPOSE
                ,XX.TRACKING_REMARKS
                ,MTHL.CREATED_BY PREPARED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(MTHL.CREATED_BY )  PREPARED_BY
                ,XX.TAKEN_BY
                ----===========HOD===========================
                ,(XX_INV_PKG.XXGET_ENAME ((SELECT USER_ID FROM FND_USER 
                WHERE USER_NAME =(SELECT APPROVED_BY FROM XXKSRM_MOAPPROVAL_STATUS
                WHERE HEADER_ID=MTHL.HEADER_ID AND WF_STATUS='Approved')))) HOD
                ----===========HOD===========================
                --,DECODE(MTHL.HEADER_STATUS,
                --3,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --7,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --8,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --NULL
                --) HOD
               ---- ,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)) HOD
                ----===========HOD=====================
                ,XX.ISSUED_STORE STORE_IN_CHARGE_ID
                , XX_INV_PKG.XXGET_ENAME(XX.ISSUED_STORE) STORE_IN_CHARGE
                ,XX.CREATED_BY ISSUED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.CREATED_BY) ISSUED_BY
                ,XX.RECEIVED_STORE  RECEIVED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.RECEIVED_STORE)  RECEIVED_BY
                ,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
                ,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') PORG_NAME
                ,NVL((SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORG),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
                ,:P_FROM_DATE P_FROM_DATE
               ,:P_TO_DATE P_TO_DATE
        FROM   MTL_TXN_REQUEST_HEADERS_V MTHL
          ,MTL_TXN_REQUEST_LINES_V MTRL
          ,MTL_SYSTEM_ITEMS_B MSI
          ,MFG_LOOKUPS ML
          , (  SELECT   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.ATTRIBUTE1 TAKEN_BY
                       ,MMT.ATTRIBUTE11 TRACKING_REMARKS 
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MAX (MMT.CREATED_BY) CREATED_BY
                       ,MMT.TRANSACTION_ID
                       , (MMT.TRANSACTION_DATE) TRANSACTION_DATE
                       ,SUM (ABS (MMT.PRIMARY_QUANTITY)) QTY_ISSUED
                       ,MTLN.LOT_NUMBER
                      ,MMT.ATTRIBUTE1 ISSUED_STORE
                       ,MMT.ATTRIBUTE2 RECEIVED_STORE
                 FROM   MTL_MATERIAL_TRANSACTIONS MMT
                       ,MTL_TRANSACTION_LOT_NUMBERS MTLN
                WHERE   MMT.PRIMARY_QUANTITY < 0
                    AND MMT.ORGANIZATION_ID = :P_ORG
                    AND MMT.TRANSACTION_SOURCE_TYPE_ID = 4
                    AND MTLN.TRANSACTION_ID(+)=MMT.TRANSACTION_ID
             GROUP BY   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.ATTRIBUTE1
                       ,MMT.ATTRIBUTE11
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MTLN.LOT_NUMBER
                       ,MMT.ATTRIBUTE1 
                       ,MMT.ATTRIBUTE2 
                       ,(MMT.TRANSACTION_DATE)
                       ,MMT.TRANSACTION_ID) XX
   WHERE   MTRL.REQUEST_NUMBER = MTHL.REQUEST_NUMBER
       AND MTRL.HEADER_ID = MTHL.HEADER_ID
       AND MTRL.ORGANIZATION_ID = MTHL.ORGANIZATION_ID
       --TRANSACTION_TYPE_ID
       AND MTRL.LINE_STATUS = ML.LOOKUP_CODE
       AND ML.LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
          and  MTHL.ATTRIBUTE_CATEGORY IN ('General',  'Marketing and  Sales')
         --and  MTHL.ATTRIBUTE_CATEGORY = 'Marketing and  Sales'
      -- MO-KSH-0030479
       --AND UPPER(MTRL.transaction_type_name)='MOVE ORDER ISSUE'
       AND MTRL.ORGANIZATION_ID = NVL (:P_ORG, MTRL.ORGANIZATION_ID)
       AND MTRL.REQUEST_NUMBER = NVL (:P_FROM_MO, MTRL.REQUEST_NUMBER)
      AND TRUNC(MTHL.DATE_REQUIRED) BETWEEN NVL(:P_FROM_DATE,TRUNC(MTHL.DATE_REQUIRED))  AND  NVL(:P_TO_DATE,TRUNC(MTHL.DATE_REQUIRED))
       AND MTRL.INVENTORY_ITEM_ID =NVL(:P_ITEM_ID,MTRL.INVENTORY_ITEM_ID)
      AND MTHL.HEADER_STATUS_NAME =NVL(:P_MO_STATUS,HEADER_STATUS_NAME)
    --   AND MTRL.transaction_source_type_id = 4
       AND MTRL.ORGANIZATION_ID = XX.ORGANIZATION_ID(+)
       AND MTRL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MTRL.INVENTORY_ITEM_ID = XX.INVENTORY_ITEM_ID(+)
       AND MTRL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MTRL.LINE_ID = XX.MOVE_ORDER_LINE_ID(+)
       AND MTRL.HEADER_ID = XX.TRANSACTION_SOURCE_ID(+)
       and MTHL.ATTRIBUTE_CATEGORY ='General' 





--=============================================================================================================

-- XXKSRM MOVE ORDER (Brand)  FOR SALES AND MERKITING ------------------ V1
-- Date  29-MAY-2021

SELECT    
                 MTRL.ORGANIZATION_ID
                ,NVL((SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') ORG_NAME
                ,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY) DEPARTMENT
                ,MTHL.ATTRIBUTE_CATEGORY
               ,(SELECT DISTINCT  OTM.TRIPSYS_NO FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) TRIP_NO
              ,(SELECT DISTINCT DECODE(OTM.EMPLOYEE_ID,NULL,UNLISTED_DRIVER,(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = OTM.EMPLOYEE_ID)) DRIVER_NAME FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) DRIVER_NAME
                ,MTRL.ATTRIBUTE15 GATE_PASS_NO
                ,XX_INV_PKG.XXGET_CUSTOMER_NAME((SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) ) CUSTOMER_NAME           
             ---- ,(SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) CUSTOMER_NAME
               ,(SELECT ATTRIBUTE1 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Move Order Issue' AND HEADER_ID=MTHL.HEADER_ID) WORK_ORDER_NO
                ,MTRL.REQUEST_NUMBER MOVE_ORDER_NUMBER
                 , MTHL.attribute10 Event_Type
               -- ,MTHL.attribute1 Management
                ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute1 else null end) Management
                ,   (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute2 else null end) Govt_NON_GOVT_Office
              --  ,MTHL.attribute2 Govt_NON_GOVT_Office
                ,MTHL.attribute3 Media
                , MTHL.attribute4  KSRM_Office
                ,MTHL.attribute5 DESIGNATION
                , MTHL.attribute13 Destination_and_through_by
              --  , MTHL.attribute14 GIFT_TO 
                , (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute14 else null end) GIFT_TO
              ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT  NULL THEN  MTHL.attribute1 else null end) COUNTRY
               --  , MTHL.ATTRIBUTE1 COUNTRY
                  , MTHL.ATTRIBUTE11 Zone
                 ,  MTHL.ATTRIBUTE12 REZION
                 --  ,MTHL.ATTRIBUTE14 AREA
                      ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute14 else null end) AREA
                  ,MTHL.ATTRIBUTE15 TERITORY
                   --,MTHL.ATTRIBUTE2 SALES_PERSON_NAME   
                      ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute2 else null end) SALES_PERSON_NAME      
                ,MTRL.DATE_REQUIRED  MOVE_ORDER_DATE
                ,MTRL.TRANSACTION_TYPE_NAME MOVE_ORDER_TYPE
                ,ML.MEANING MO_STATUS_LINE
                ,MTHL.HEADER_STATUS_NAME  MO_STATUS
                ,(SELECT ATTRIBUTE9 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Issue to Project' AND HEADER_ID=MTHL.HEADER_ID) PROJECT_NAME
                ,MTRL.LINE_NUMBER
                , (MSI.SEGMENT1 || '|' || MSI.SEGMENT2 || '|' || MSI.SEGMENT3||'|' || MSI.SEGMENT4)    ITEM_CODE
                ,MSI.DESCRIPTION
                ,MTRL.UOM_CODE 
                ---=========================================
                ,MTRL.FROM_SUBINVENTORY_CODE
                ,MTRL.INVENTORY_ITEM_ID
                -----------------------------------------------------
                , (SELECT NVL(SUM(PRIMARY_QUANTITY),0)
                FROM 
                MTL_MATERIAL_TRANSACTIONS
                WHERE 
                ORGANIZATION_ID=MTRL.ORGANIZATION_ID
                AND SUBINVENTORY_CODE=NVL(MTRL.FROM_SUBINVENTORY_CODE,SUBINVENTORY_CODE)
                AND INVENTORY_ITEM_ID=MTRL.INVENTORY_ITEM_ID 
                AND  TRANSACTION_DATE <MTRL.DATE_REQUIRED) IO_STOCK
                ---=========================================
                ,MTRL.QUANTITY  MO_QTY
                ,XX.QTY_ISSUED MO_ISSUE_QTY
                ,CASE WHEN MTRL.LINE_STATUS <>5 THEN 0   ELSE (MTRL.QUANTITY-MTRL.QUANTITY_DELIVERED)  END  CANCEL_QTY
                ,XX.SUBINVENTORY_CODE
                , (SELECT SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4||'|'||SEGMENT5 LOCATOR_DESC FROM MTL_ITEM_LOCATIONS WHERE INVENTORY_LOCATION_ID=XX.LOCATOR_ID AND ORGANIZATION_ID=MTRL.ORGANIZATION_ID) LOCATOR
                ,XX.LOT_NUMBER
                ,XX_INV_PKG.XXGET_SERIAL_NUMBER(XX.TRANSACTION_ID) SERIAL_NUMBER
               ----,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 AND OU_ID=(SELECT OPERATING_UNIT_ID FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MTRL.ORGANIZATION_ID)) USEOFAREA
               ,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 ) USEOFAREA
                ,MTRL.REFERENCE REASON
                ---===================================================
                ,MTHL.DESCRIPTION PURPOSE
                ,XX.TRACKING_REMARKS
                ,MTHL.CREATED_BY PREPARED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(MTHL.CREATED_BY )  PREPARED_BY
                ,XX.TAKEN_BY
                ----===========HOD===========================
                ,(XX_INV_PKG.XXGET_ENAME ((SELECT USER_ID FROM FND_USER 
                WHERE USER_NAME =(SELECT APPROVED_BY FROM XXKSRM_MOAPPROVAL_STATUS
                WHERE HEADER_ID=MTHL.HEADER_ID AND WF_STATUS='Approved')))) HOD
                ----===========HOD===========================
                --,DECODE(MTHL.HEADER_STATUS,
                --3,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --7,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --8,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --NULL
                --) HOD
               ---- ,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)) HOD
                ----===========HOD=====================
                ,XX.ISSUED_STORE STORE_IN_CHARGE_ID
                , XX_INV_PKG.XXGET_ENAME(XX.ISSUED_STORE) STORE_IN_CHARGE
                ,XX.CREATED_BY ISSUED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.CREATED_BY) ISSUED_BY
                ,XX.RECEIVED_STORE  RECEIVED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.RECEIVED_STORE)  RECEIVED_BY
                ,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
                ,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') PORG_NAME
                ,NVL((SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORG),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
                ,:P_FROM_DATE P_FROM_DATE
               ,:P_TO_DATE P_TO_DATE
        FROM   MTL_TXN_REQUEST_HEADERS_V MTHL
          ,MTL_TXN_REQUEST_LINES_V MTRL
          ,MTL_SYSTEM_ITEMS_B MSI
          ,MFG_LOOKUPS ML
          , (  SELECT   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.ATTRIBUTE1 TAKEN_BY
                       ,MMT.ATTRIBUTE11 TRACKING_REMARKS 
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MAX (MMT.CREATED_BY) CREATED_BY
                       ,MMT.TRANSACTION_ID
                       , (MMT.TRANSACTION_DATE) TRANSACTION_DATE
                       ,SUM (ABS (MMT.PRIMARY_QUANTITY)) QTY_ISSUED
                       ,MTLN.LOT_NUMBER
                      ,MMT.ATTRIBUTE1 ISSUED_STORE
                       ,MMT.ATTRIBUTE2 RECEIVED_STORE
                 FROM   MTL_MATERIAL_TRANSACTIONS MMT
                       ,MTL_TRANSACTION_LOT_NUMBERS MTLN
                WHERE   MMT.PRIMARY_QUANTITY < 0
                    AND MMT.ORGANIZATION_ID = :P_ORG
                    AND MMT.TRANSACTION_SOURCE_TYPE_ID = 4
                    AND MTLN.TRANSACTION_ID(+)=MMT.TRANSACTION_ID
             GROUP BY   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.ATTRIBUTE1
                       ,MMT.ATTRIBUTE11
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MTLN.LOT_NUMBER
                       ,MMT.ATTRIBUTE1 
                       ,MMT.ATTRIBUTE2 
                       ,(MMT.TRANSACTION_DATE)
                       ,MMT.TRANSACTION_ID) XX
   WHERE   MTRL.REQUEST_NUMBER = MTHL.REQUEST_NUMBER
       AND MTRL.HEADER_ID = MTHL.HEADER_ID
       AND MTRL.ORGANIZATION_ID = MTHL.ORGANIZATION_ID
       --TRANSACTION_TYPE_ID
       AND MTRL.LINE_STATUS = ML.LOOKUP_CODE
       AND ML.LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
          and  MTHL.ATTRIBUTE_CATEGORY IN ('General',  'Marketing and  Sales')
         --and  MTHL.ATTRIBUTE_CATEGORY = 'Marketing and  Sales'
      -- MO-KSH-0030479
       --AND UPPER(MTRL.transaction_type_name)='MOVE ORDER ISSUE'
       AND MTRL.ORGANIZATION_ID = NVL (:P_ORG, MTRL.ORGANIZATION_ID)
       AND MTRL.REQUEST_NUMBER = NVL (:P_FROM_MO, MTRL.REQUEST_NUMBER)
      AND TRUNC(MTHL.DATE_REQUIRED) BETWEEN NVL(:P_FROM_DATE,TRUNC(MTHL.DATE_REQUIRED))  AND  NVL(:P_TO_DATE,TRUNC(MTHL.DATE_REQUIRED))
       AND MTRL.INVENTORY_ITEM_ID =NVL(:P_ITEM_ID,MTRL.INVENTORY_ITEM_ID)
      AND MTHL.HEADER_STATUS_NAME =NVL(:P_MO_STATUS,HEADER_STATUS_NAME)
    --   AND MTRL.transaction_source_type_id = 4
       AND MTRL.ORGANIZATION_ID = XX.ORGANIZATION_ID(+)
       AND MTRL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MTRL.INVENTORY_ITEM_ID = XX.INVENTORY_ITEM_ID(+)
       AND MTRL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MTRL.LINE_ID = XX.MOVE_ORDER_LINE_ID(+)
       AND MTRL.HEADER_ID = XX.TRANSACTION_SOURCE_ID(+)
       and MTHL.ATTRIBUTE_CATEGORY = 'Marketing and  Sales' -- NVL(:P_EVENT_CATEGORY,MTHL.ATTRIBUTE_CATEGORY)
       AND MTHL.ATTRIBUTE11=NVL(:P_ZONE,MTHL.ATTRIBUTE11)
       AND MTHL.ATTRIBUTE12  = NVL(:P_REZION,MTHL.ATTRIBUTE12)
       AND (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute14 else null end) = NVL(:P_AREA,(CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute14 else null end) )
       AND MTHL.ATTRIBUTE15 = NVL(:P_TERITORY, MTHL.ATTRIBUTE15)
       AND  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute2 else null end) = NVL(:P_SALES_PERSON, (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute2 else null end))
      ORDER BY  MTRL.DATE_REQUIRED, MTRL.REQUEST_NUMBER,MTRL.LINE_NUMBER   -- XX.TAKEN_BY



--================================================================================================================

-- XXKSRM MOVE ORDER (Brand)
-- Date  29-MAY-2021

SELECT    
                 MTRL.ORGANIZATION_ID
                ,NVL((SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') ORG_NAME
                ,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY) DEPARTMENT
                ,MTHL.ATTRIBUTE_CATEGORY
               ,(SELECT DISTINCT  OTM.TRIPSYS_NO FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) TRIP_NO
              ,(SELECT DISTINCT DECODE(OTM.EMPLOYEE_ID,NULL,UNLISTED_DRIVER,(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = OTM.EMPLOYEE_ID)) DRIVER_NAME FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) DRIVER_NAME
                ,MTRL.ATTRIBUTE15 GATE_PASS_NO
                ,XX_INV_PKG.XXGET_CUSTOMER_NAME((SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) ) CUSTOMER_NAME           
             ---- ,(SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) CUSTOMER_NAME
               ,(SELECT ATTRIBUTE1 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Move Order Issue' AND HEADER_ID=MTHL.HEADER_ID) WORK_ORDER_NO
                ,MTRL.REQUEST_NUMBER MOVE_ORDER_NUMBER
                 , MTHL.attribute10 Event_Type
               -- ,MTHL.attribute1 Management
                ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute1 else null end) Management
                ,   (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute2 else null end) Govt_NON_GOVT_Office
              --  ,MTHL.attribute2 Govt_NON_GOVT_Office
                ,MTHL.attribute3 Media
                , MTHL.attribute4  KSRM_Office
                ,MTHL.attribute5 DESIGNATION
                , MTHL.attribute13 Destination_and_through_by
              --  , MTHL.attribute14 GIFT_TO 
                , (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='General' AND MTHL.ATTRIBUTE11 IS NULL THEN  MTHL.attribute14 else null end) GIFT_TO
              ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT  NULL THEN  MTHL.attribute1 else null end) COUNTRY
               --  , MTHL.ATTRIBUTE1 COUNTRY
                  , MTHL.ATTRIBUTE11 Zone
                 ,  MTHL.ATTRIBUTE12 REZION
                 --  ,MTHL.ATTRIBUTE14 AREA
                      ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute14 else null end) AREA
                  ,MTHL.ATTRIBUTE15 TERITORY
                   --,MTHL.ATTRIBUTE2 SALES_PERSON_NAME   
                      ,  (CASE WHEN MTHL.ATTRIBUTE_CATEGORY  ='Marketing and  Sales' AND MTHL.ATTRIBUTE11 IS NOT NULL THEN  MTHL.attribute2 else null end) SALES_PERSON_NAME      
                ,MTRL.DATE_REQUIRED  MOVE_ORDER_DATE
                ,MTRL.TRANSACTION_TYPE_NAME MOVE_ORDER_TYPE
                ,ML.MEANING MO_STATUS_LINE
                ,MTHL.HEADER_STATUS_NAME  MO_STATUS
                ,(SELECT ATTRIBUTE9 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Issue to Project' AND HEADER_ID=MTHL.HEADER_ID) PROJECT_NAME
                ,MTRL.LINE_NUMBER
                , (MSI.SEGMENT1 || '|' || MSI.SEGMENT2 || '|' || MSI.SEGMENT3||'|' || MSI.SEGMENT4)    ITEM_CODE
                ,MSI.DESCRIPTION
                ,MTRL.UOM_CODE 
                ---=========================================
                ,MTRL.FROM_SUBINVENTORY_CODE
                ,MTRL.INVENTORY_ITEM_ID
                -----------------------------------------------------
                , (SELECT NVL(SUM(PRIMARY_QUANTITY),0)
                FROM 
                MTL_MATERIAL_TRANSACTIONS
                WHERE 
                ORGANIZATION_ID=MTRL.ORGANIZATION_ID
                AND SUBINVENTORY_CODE=NVL(MTRL.FROM_SUBINVENTORY_CODE,SUBINVENTORY_CODE)
                AND INVENTORY_ITEM_ID=MTRL.INVENTORY_ITEM_ID 
                AND  TRANSACTION_DATE <MTRL.DATE_REQUIRED) IO_STOCK
                ---=========================================
                ,MTRL.QUANTITY  MO_QTY
                ,XX.QTY_ISSUED MO_ISSUE_QTY
                ,CASE WHEN MTRL.LINE_STATUS <>5 THEN 0   ELSE (MTRL.QUANTITY-MTRL.QUANTITY_DELIVERED)  END  CANCEL_QTY
                ,XX.SUBINVENTORY_CODE
                , (SELECT SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4||'|'||SEGMENT5 LOCATOR_DESC FROM MTL_ITEM_LOCATIONS WHERE INVENTORY_LOCATION_ID=XX.LOCATOR_ID AND ORGANIZATION_ID=MTRL.ORGANIZATION_ID) LOCATOR
                ,XX.LOT_NUMBER
                ,XX_INV_PKG.XXGET_SERIAL_NUMBER(XX.TRANSACTION_ID) SERIAL_NUMBER
               ----,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 AND OU_ID=(SELECT OPERATING_UNIT_ID FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MTRL.ORGANIZATION_ID)) USEOFAREA
               ,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 ) USEOFAREA
                ,MTRL.REFERENCE REASON
                ---===================================================
                ,MTHL.DESCRIPTION PURPOSE
                ,XX.TRACKING_REMARKS
                ,MTHL.CREATED_BY PREPARED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(MTHL.CREATED_BY )  PREPARED_BY
                ,XX.TAKEN_BY
                ----===========HOD=====================
                ,(XX_INV_PKG.XXGET_ENAME ((SELECT USER_ID FROM FND_USER 
                WHERE USER_NAME =(SELECT APPROVED_BY FROM XXKSRM_MOAPPROVAL_STATUS
                WHERE HEADER_ID=MTHL.HEADER_ID AND WF_STATUS='Approved')))) HOD
                ----===========HOD=====================
                --,DECODE(MTHL.HEADER_STATUS,
                --3,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --7,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --8,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --NULL
                --) HOD
               ---- ,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)) HOD
                ----===========HOD=====================
                ----===========HOD=====================
                ,XX.ISSUED_STORE STORE_IN_CHARGE_ID
                , XX_INV_PKG.XXGET_ENAME(XX.ISSUED_STORE) STORE_IN_CHARGE
                ,XX.CREATED_BY ISSUED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.CREATED_BY) ISSUED_BY
                ,XX.RECEIVED_STORE  RECEIVED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.RECEIVED_STORE)  RECEIVED_BY
                ,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
                ,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') PORG_NAME
                ,NVL((SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORG),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
                ,:P_FROM_DATE P_FROM_DATE
               ,:P_TO_DATE P_TO_DATE
        FROM   MTL_TXN_REQUEST_HEADERS_V MTHL
          ,MTL_TXN_REQUEST_LINES_V MTRL
          ,MTL_SYSTEM_ITEMS_B MSI
          ,MFG_LOOKUPS ML
          , (  SELECT   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.ATTRIBUTE1 TAKEN_BY
                       ,MMT.ATTRIBUTE11 TRACKING_REMARKS 
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MAX (MMT.CREATED_BY) CREATED_BY
                       ,MMT.TRANSACTION_ID
                       , (MMT.TRANSACTION_DATE) TRANSACTION_DATE
                       ,SUM (ABS (MMT.PRIMARY_QUANTITY)) QTY_ISSUED
                       ,MTLN.LOT_NUMBER
                      ,MMT.ATTRIBUTE1 ISSUED_STORE
                       ,MMT.ATTRIBUTE2 RECEIVED_STORE
                 FROM   MTL_MATERIAL_TRANSACTIONS MMT
                       ,MTL_TRANSACTION_LOT_NUMBERS MTLN
                WHERE   MMT.PRIMARY_QUANTITY < 0
                    AND MMT.ORGANIZATION_ID = :P_ORG
                    AND MMT.TRANSACTION_SOURCE_TYPE_ID = 4
                    AND MTLN.TRANSACTION_ID(+)=MMT.TRANSACTION_ID
             GROUP BY   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.ATTRIBUTE1
                       ,MMT.ATTRIBUTE11
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MTLN.LOT_NUMBER
                       ,MMT.ATTRIBUTE1 
                       ,MMT.ATTRIBUTE2 
                       ,(MMT.TRANSACTION_DATE)
                       ,MMT.TRANSACTION_ID) XX
   WHERE   MTRL.REQUEST_NUMBER = MTHL.REQUEST_NUMBER
       AND MTRL.HEADER_ID = MTHL.HEADER_ID
       AND MTRL.ORGANIZATION_ID = MTHL.ORGANIZATION_ID
       --TRANSACTION_TYPE_ID
       AND MTRL.LINE_STATUS = ML.LOOKUP_CODE
       AND ML.LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
          and  MTHL.ATTRIBUTE_CATEGORY IN ( 'General',  'Marketing and  Sales')
         --and  MTHL.ATTRIBUTE_CATEGORY = 'Marketing and  Sales'
      -- MO-KSH-0030479
       --AND UPPER(MTRL.transaction_type_name)='MOVE ORDER ISSUE'
       AND MTRL.ORGANIZATION_ID = NVL (:P_ORG, MTRL.ORGANIZATION_ID)
       AND MTRL.REQUEST_NUMBER = NVL (:P_FROM_MO, MTRL.REQUEST_NUMBER)
      AND TRUNC(MTHL.DATE_REQUIRED) BETWEEN NVL(:P_FROM_DATE,TRUNC(MTHL.DATE_REQUIRED))  AND  NVL(:P_TO_DATE,TRUNC(MTHL.DATE_REQUIRED))
       AND MTRL.INVENTORY_ITEM_ID =NVL(:P_ITEM_ID,MTRL.INVENTORY_ITEM_ID)
      AND MTHL.HEADER_STATUS_NAME =NVL(:P_MO_STATUS,HEADER_STATUS_NAME)
    --   AND MTRL.transaction_source_type_id = 4
       AND MTRL.ORGANIZATION_ID = XX.ORGANIZATION_ID(+)
       AND MTRL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MTRL.INVENTORY_ITEM_ID = XX.INVENTORY_ITEM_ID(+)
       AND MTRL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MTRL.LINE_ID = XX.MOVE_ORDER_LINE_ID(+)
       AND MTRL.HEADER_ID = XX.TRANSACTION_SOURCE_ID(+)
       and MTHL.ATTRIBUTE_CATEGORY = NVL(:P_EVENT_CATEGORY,MTHL.ATTRIBUTE_CATEGORY)
     --  AND MTRL.transaction_type_id = XX.transaction_type_id
       --AND MTRL.request_number='2002'
ORDER BY  MTRL.DATE_REQUIRED, MTRL.REQUEST_NUMBER,MTRL.LINE_NUMBER   ---- XX.TAKEN_BY

--MO-KSH-0030473

select * from XX_DEPT_V


select * from  MTL_TXN_REQUEST_HEADERS_V where REQUEST_NUMBER ='MO-KSH-0030479' -- 'MO-KSH-0030186' -- 'MO-KSH-0030479'

select * from  MTL_TXN_REQUEST_HEADERS_V where created_BY=1243  --ATTRIBUTE10 is not null ---


select * from MTL_TXN_REQUEST_LINES_V where header_id=1803281

select * from MTL_TXN_REQUEST_LINES_V where header_id=1762447

select ATTRIBUTE1 COUNTRY, ATTRIBUTE11 Zone, ATTRIBUTE12 REZION, ATTRIBUTE14 AREA,  ATTRIBUTE15,ATTRIBUTE1,ATTRIBUTE2 SALES_PERSON_NAME ,ATTRIBUTE3  TERIRITORY, ATTRIBUTE4,ATTRIBUTE5, ATTRIBUTE6,ATTRIBUTE7  from MTL_TXN_REQUEST_HEADERS_V where header_id=1803281

select ATTRIBUTE1 COUNTRY, ATTRIBUTE11 Zone, ATTRIBUTE12 REZION, ATTRIBUTE14 AREA,  ATTRIBUTE15 TERIRITORY, ATTRIBUTE2 SALES_PERSON_NAME  from MTL_TXN_REQUEST_HEADERS_V where header_id=1762447