--- XXKSRM Consumption Report Date: 27- OCT-2021


SELECT X.PERIOD_CODE,X.LEDGER_ID, X.COMPANY_NAME, X.COMPANY,X.OPERATING_UNIT,OPERATING_UNIT||'-'||SUBSTR(GET_OU_NAME_FROM_ID(X.OPERATING_UNIT),5,70),  X.COST_CENTER, 
X.ORGANIZATION_CODE,X.MEJOR_FIN_CAT,X.FIN_CAT,X.ORGANIZATION_ID,--X.TRANSACTION_ID,
X.INVENTORY_ITEM_ID,X.ITEM_CODE,X.ITEM_DESC, X.UOM, X.EVENT_TYPE_CODE,X.TRANSACTION_TYPE_ID,
X.TRANSACTION_TYPE_NAME,X.ACCOUNT_NAME,X.SUB_ACCOUNT,X.OP_QTY, X.OP_VAL,
SUM(X.RCV_QTY) RCV_QTY, SUM(X.RCV_VAL) RCV_VAL, (SUM(X.ISSUE_QTY))*-1 ISSUE_QTY, (SUM(X.ISSUE_VAL))* -1 ISSUE_VAL, (SUM(X.TRANS_QTY))*-1  TRANS_QTY,
ABS( (SUM(X.TRANS_VAL))*-1 / NULLIF( (SUM(X.ISSUE_QTY)),0)) RATE,
CASE WHEN TRANSACTION_TYPE_NAME = 'HMS Issue Against By Product (KBIL)'   then  SUM(X.CR) - SUM(X.DR)  ELSE    (SUM(X.TRANS_VAL))*-1  END  TRANS_VAL ,
X.JE_CATEGORY_NAME,X.ACCOUNTING_CLASS_CODE, SUM(X.DR) DR, SUM(X.CR) CR ,X.ACCOUNTING_CODE
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.LEDGER_ID, INV_TRANS.COMPANY_NAME, INV_TRANS.COMPANY, INV_TRANS.OPERATING_UNIT, INV_TRANS.COST_CENTER, 
INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,--INV_TRANS.TRANSACTION_ID,
INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,INV_TRANS.ITEM_DESC, INV_TRANS.UOM, INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,
INV_TRANS.ACCOUNT_NAME,INV_TRANS.SUB_ACCOUNT,
0 OP_QTY, 0 OP_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12,17,18,44,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12,17,18,44,61,1002,1003) THEN INV_TRANS.ACCOUNTED_DR - INV_TRANS.ACCOUNTED_CR--INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.ACCOUNTED_DR - INV_TRANS.ACCOUNTED_CR--INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.ACCOUNTED_DR - INV_TRANS.ACCOUNTED_CR--INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.ACCOUNTED_DR - INV_TRANS.ACCOUNTED_CR--  INV_TRANS.TRANSACTION_VALUE
 ELSE 0 END) RCV_VAL,
(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (106,63,200,261,101,103,104,107,111,120,140,240,32,221,1) THEN 
(SELECT  (A.TRANSACTION_QUANTITY)  FROM GMF_XLA_EXTRACT_HEADERS A  WHERE A.EVENT_ID=INV_TRANS.EVENT_ID AND  A.LEDGER_ID=INV_TRANS.LEDGER_ID 
AND A.TRANSACTION_ID=INV_TRANS.TRANSACTION_ID) ELSE 0 END) ISSUE_QTY,---Ibrahim  /2  ELSE 0 END)
(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (106,63,200,261,101,103,104,107,111,120,140,240,32,221,1) THEN 
(SELECT NVL(SUM(A.TRANSACTION_VALUE),0)  FROM GMF_XLA_EXTRACT_HEADERS A  WHERE A.EVENT_ID=INV_TRANS.EVENT_ID AND  A.LEDGER_ID=INV_TRANS.LEDGER_ID 
AND A.TRANSACTION_ID=INV_TRANS.TRANSACTION_ID)  ELSE 0 END) ISSUE_VAL,---ibrahim
(SELECT SUM(A.TRANSACTION_QUANTITY)  FROM GMF_XLA_EXTRACT_HEADERS A  WHERE A.EVENT_ID=INV_TRANS.EVENT_ID AND  A.LEDGER_ID=INV_TRANS.LEDGER_ID 
AND A.TRANSACTION_ID=INV_TRANS.TRANSACTION_ID) TRANS_QTY,---ibrahim
(SELECT NVL(SUM(A.TRANSACTION_VALUE),0)  FROM GMF_XLA_EXTRACT_HEADERS A  WHERE A.EVENT_ID=INV_TRANS.EVENT_ID AND  A.LEDGER_ID=INV_TRANS.LEDGER_ID 
AND A.TRANSACTION_ID=INV_TRANS.TRANSACTION_ID) TRANS_VAL,---ibrahim
INV_TRANS.JE_CATEGORY_NAME,INV_TRANS.ACCOUNTING_CLASS_CODE,
NVL(SUM(INV_TRANS.ACCOUNTED_DR),0) DR,NVL(SUM(INV_TRANS.ACCOUNTED_CR),0) CR ,INV_TRANS.ACCOUNTING_CODE
FROM
(
SELECT A.EVENT_ID,A.TRANSACTION_ID,TO_CHAR(TRANSACTION_DATE,'MON-YY') PERIOD_CODE, A.LEDGER_ID, (SELECT DISTINCT BAL_SEG_NAME FROM XX_INV_ORG_VW WHERE LEDGER_ID=A.LEDGER_ID) COMPANY_NAME,
C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.OPERATING_UNIT,
XX_GET_ACCT_FLEX_SEG_DESC (1, F.SEGMENT1) COMPANY,
XX_GET_ACCT_FLEX_SEG_DESC (3, F.SEGMENT3) COST_CENTER,
A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,
(SELECT DESCRIPTION FROM MTL_SYSTEM_ITEMS_B WHERE INVENTORY_ITEM_ID=A.INVENTORY_ITEM_ID AND ORGANIZATION_ID=A.ORGANIZATION_ID) ITEM_DESC,
(SELECT PRIMARY_UOM_CODE FROM MTL_SYSTEM_ITEMS_B WHERE INVENTORY_ITEM_ID=A.INVENTORY_ITEM_ID AND ORGANIZATION_ID=A.ORGANIZATION_ID) UOM,
A.EVENT_CLASS_CODE,A.EVENT_TYPE_CODE, --a.transaction_id,
G.TRANSACTION_TYPE_ID,G.TRANSACTION_TYPE_NAME,
D.JE_CATEGORY_NAME,E.ACCOUNTING_CLASS_CODE,D.AE_HEADER_ID,XX_AP_PKG.GET_ACCOUNT_DESC_FROM_CCID (E.CODE_COMBINATION_ID) ACCOUNT_NAME,
XX_AP_PKG.GET_SUB_ACCOUNT_DESC_FROM_CCID(TO_NUMBER(E.CODE_COMBINATION_ID)) SUB_ACCOUNT,
TRANSACTION_QUANTITY,TRANSACTION_VALUE,
E.ACCOUNTED_DR,E.ACCOUNTED_CR,F.CONCATENATED_SEGMENTS ACCOUNTING_CODE
FROM GMF_XLA_EXTRACT_HEADERS A,MTL_SYSTEM_ITEMS_B B,ORG_ORGANIZATION_DEFINITIONS C,XLA_AE_HEADERS D,XLA_AE_LINES E,GL_CODE_COMBINATIONS_KFV F,MTL_TRANSACTION_TYPES G
WHERE A.INVENTORY_ITEM_ID=B.INVENTORY_ITEM_ID(+) AND A.ORGANIZATION_ID=B.ORGANIZATION_ID(+) AND A.ORGANIZATION_ID=C.ORGANIZATION_ID AND A.TRANSACTION_TYPE_ID=G.TRANSACTION_TYPE_ID(+)
AND (NVL (e.ACCOUNTED_DR, 0)>0.49 or NVL (ACCOUNTED_CR, 0)>0.49 ) 
AND A.EVENT_ID=D.EVENT_ID AND D.AE_HEADER_ID=E.AE_HEADER_ID AND E.CODE_COMBINATION_ID=F.CODE_COMBINATION_ID
AND TO_CHAR(TRANSACTION_DATE,'MON-YY')=:P_PERIOD_CODE
--and A.TRANSACTION_ID=11049266--1631266
and A.OPERATING_UNIT= NVL(:P_OPERATING_UNIT,A.OPERATING_UNIT)
AND A.LEDGER_ID=:P_LEDGER_ID AND A.ORGANIZATION_ID=NVL(:P_ORGANIZATION_ID,A.ORGANIZATION_ID) AND A.INVENTORY_ITEM_ID=NVL(:P_INVENTORY_ITEM_ID,A.INVENTORY_ITEM_ID)
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID AND FIN_CAT.MEJOR_FIN_CAT= NVL(:P_MEJOR_FIN_CAT,FIN_CAT.MEJOR_FIN_CAT)
GROUP BY PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.LEDGER_ID, INV_TRANS.COMPANY_NAME,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,--INV_TRANS.TRANSACTION_ID,
INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,INV_TRANS.ITEM_DESC, INV_TRANS.UOM,
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.ACCOUNT_NAME,INV_TRANS.SUB_ACCOUNT,INV_TRANS.ACCOUNTING_CODE,INV_TRANS.EVENT_ID,INV_TRANS.TRANSACTION_ID,
INV_TRANS.TRANSACTION_TYPE_ID,INV_TRANS.JE_CATEGORY_NAME,INV_TRANS.ACCOUNTING_CLASS_CODE, COMPANY, OPERATING_UNIT, COST_CENTER
ORDER BY ORGANIZATION_ID,INVENTORY_ITEM_ID
) X
WHERE (ACCOUNT_NAME IN ('Finished Goods','Raw Materials')
OR ACCOUNT_NAME LIKE ('Stores%Spares')
OR ACCOUNT_NAME LIKE ('Fuel%Lubricants')
OR ACCOUNT_NAME LIKE ('Bi Product%Wastage'))
AND ACCOUNTING_CLASS_CODE  IN ('INVENTORY_VALUATION')
AND EVENT_TYPE_CODE IN ('MOVE_ORDER_ISSUE','MISC_RECEIPT','MISC_ISSUE','ACCT_ISSUE')
AND X.COST_CENTER = NVL(:P_COST_CENTER, X.COST_CENTER)
AND X.TRANSACTION_TYPE_ID NOT IN (42)
GROUP BY X.PERIOD_CODE,X.LEDGER_ID, X.COMPANY_NAME, X.ORGANIZATION_CODE,X.MEJOR_FIN_CAT,X.FIN_CAT,X.ORGANIZATION_ID,--X.TRANSACTION_ID,
X.INVENTORY_ITEM_ID,X.ITEM_CODE,X.ITEM_DESC, X.UOM, X.EVENT_TYPE_CODE,X.TRANSACTION_TYPE_ID,
X.TRANSACTION_TYPE_NAME,X.ACCOUNT_NAME,X.SUB_ACCOUNT,X.OP_QTY, X.OP_VAL,
X.JE_CATEGORY_NAME,X.ACCOUNTING_CLASS_CODE, X.ACCOUNTING_CODE,X.COMPANY, X.OPERATING_UNIT, X.COST_CENTER