CREATE OR REPLACE FUNCTION  GET_MTL_TRANSACTION_QTY ( P_ID IN NUMBER )
   RETURN NUMBER
IS
   CNUMBER NUMBER;
   CURSOR C1
   IS
             SELECT SUM (TRANSACTION_QUANTITY)
             FROM MTL_MATERIAL_TRANSACTIONS
            WHERE  1=1
            AND    TRANSACTION_TYPE_ID IN (42, 163, 129) 
            AND TRANSACTION_ID = P_ID ;-- IN( 8026865, 8026864) 
--     SELECT course_number
--     FROM courses_tbl
--     WHERE course_name = name_in;
BEGIN
   OPEN C1;
   FETCH C1 INTO CNUMBER;
   IF C1%NOTFOUND THEN
      CNUMBER := 9999;
   END IF;

   CLOSE C1;

RETURN CNUMBER;

END;

