-- XXKSRM Customer Wise Cylinder Stock
SELECT 
(SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=XKCV.ORGANIZATION_ID) COMPANY_NAME,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=XKCV.ORGANIZATION_ID) IO_ADDRESS,
XKCV.ORGANIZATION_ID,
XKCV.ITEMCODE,
XKCV.ITEM_DESCRIPTION,
XKCV.CHALLAN_QTY,
XKCV.CHALLAN_NO,
XKCV.CHALLAN_DATE,
XKCV.CUSTOMER_ID,
(SELECT  DISTINCT  PARTY.PARTY_NAME CUSTOMER_NAME  FROM  HZ_PARTIES PARTY, HZ_CUST_ACCOUNTS CUST_ACT WHERE PARTY.PARTY_ID = CUST_ACT.PARTY_ID AND CUST_ACT.CUST_ACCOUNT_ID=XKCV.CUSTOMER_ID ) CUSTOMER_NAME,
NVL(XKCV.RECEIPT_QTY,0)  RETURN_QTY,
XKCV.PARTY_BALANCE CUSTOMER_BALANCE,
--XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
  XX_INV_PKG.XXGET_EMP_DEPT(XKCV.CREATED_BY) DEPARTMENT,
:P_CHALLAN_DATE_FROM PDATE_FROM,
:P_CHALLAN_DATE_TO PDATE_TO
FROM 
XXKSRM_KOL_CHALLAN_V XKCV
WHERE
XKCV.PARTY_BALANCE>0
--AND XKCV.ORGANIZATION_ID=NVL(:P_ORG_ID,XKCV.ORGANIZATION_ID)
AND XKCV.CUSTOMER_ID=NVL(:P_CUSTOMER_ID,XKCV.CUSTOMER_ID)
AND TO_DATE(XKCV.CHALLAN_DATE) BETWEEN NVL(:P_CHALLAN_DATE_FROM,TO_DATE(XKCV.CHALLAN_DATE))  AND NVL(:P_CHALLAN_DATE_TO,TO_DATE(XKCV.CHALLAN_DATE))
AND XKCV.CHALLAN_NO=NVL(:P_CHALLAN_NO,XKCV.CHALLAN_NO) 

--====================================================================================================



-- XXKSRM Cylinder Stock All
SELECT DISTINCT
WXMD.ORGANIZATION_NAME,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MOQ.ORGANIZATION_ID) ORG_ADD,
WXMD.ORGANIZATION_code,
MOQ.ORGANIZATION_ID,
MOQ.SUBINVENTORY_CODE,
WXMD.ITEM_CODE,
WXMD.ITEM_DESC,
WXMD.UOM1 UOM,
NVL (XX_INV_PKG.XXGET_INV_OPENING_STOCK (MOQ.INVENTORY_ITEM_ID, MOQ.ORGANIZATION_ID, MOQ.SUBINVENTORY_CODE, MOQ.LOCATOR_ID, :P_DATE),0) OPENING_QTY ,
--NVL (XX_INV_PKG.XXGET_INV_OPENING_STOCK (MOQ.INVENTORY_ITEM_ID,MOQ.ORGANIZATION_ID,NULL, NULL, :P_DATE),0) GLOBAL_STOCK,
---NULL GLOBAL_STOCK,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
:P_DATE PDATE
FROM WBI_XXKBGITEM_MT_D WXMD,
MTL_ONHAND_QUANTITIES MOQ
WHERE     WXMD.INVENTORY_ITEM_ID = MOQ.INVENTORY_ITEM_ID
AND TRUNC(MOQ.DATE_RECEIVED) <=:P_DATE
AND WXMD.INVENTORY_ITEM_ID IN (76,77,66,102,75,118,448,428,23079,23078,23077,23076)           ---- IN (76,77,66,102,75,118,448,428)
AND WXMD.ORGANIZATION_ID = MOQ.ORGANIZATION_ID     
AND WXMD.ORGANIZATION_ID=173
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE)
UNION 
SELECT 
DISTINCT 
(SELECT INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL  WHERE INV_ORGANIZATION_ID=KCV.ORGANIZATION_ID) ORGANIZATION_NAME,
(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=KCV.ORGANIZATION_ID) ORG_ADD,
(SELECT INV_ORGANIZATION_CODE FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=KCV.ORGANIZATION_ID) ORGANIZATION_CODE,
KCV.ORGANIZATION_ID  ORGANIZATION_ID,
'PARTY'  SUBINVENTORY_CODE,
KCV.ITEMCODE ITEM_CODE,
KCV.ITEM_DESCRIPTION ITEM_DESC,
KCV.UOM_CODE UOM,
XX_TAB.PARTY_BALANCE OPENING_QTY ,
----NULL GLOBAL_STOCK,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME,
:P_DATE PDATE
FROM XXKSRM_KOL_CHALLAN_V KCV,
 (SELECT ORGANIZATION_ID,ITEMCODE,
            SUM(PARTY_BALANCE)  PARTY_BALANCE
            FROM XXKSRM_KOL_CHALLAN_V
            WHERE TO_DATE(CHALLAN_DATE)<=(:P_DATE)
            GROUP BY ORGANIZATION_ID,ITEMCODE) 
            XX_TAB
WHERE KCV.ORGANIZATION_ID=XX_TAB.ORGANIZATION_ID
AND KCV.ITEMCODE=XX_TAB.ITEMCODE
AND  KCV.ITEMCODE=NVL(:P_ITEM_CODE,KCV.ITEMCODE)



