--==============================
--GET USE OF AREA WITH DEPARTMENT
--==============================

SELECT DISTINCT UPPER(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1),'.',1)-1))  DEPT FROM PER_ALL_POSITIONS PAP
order by UPPER(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1),'.',1)-1))

--==============================
--GET USE OF AREA WITH DEPARTMENT WITH USER ID
--==============================

select * from PER_PEOPLE_V 

select * from PER_ASSIGNMENTS_v 

select * from PER_ALL_PEOPLE_F

SELECT * FROM PER_ALL_POSITIONS

select MIN(SEQUENCE_NUM), XX_P2P_EMP_INFO.GET_EMPNP_EMP_ID(ACTION_DATE,EMPLOYEE_ID)||chr(10)||'Date: '||TO_CHAR(MIN(ACTION_DATE),'DD-MON-RRRR') NAME_POS
from PO_ACTION_HISTORY PA
WHERE PA.ACTION_CODE IS NOT NULL
AND OBJECT_TYPE_CODE='REQUISITION'
AND UPPER(ACTION_CODE) IN ('SUBMIT','APPROVE','FORWARD')
--AND OBJECT_ID=467016
GROUP BY EMPLOYEE_ID,OBJECT_ID,XX_P2P_EMP_INFO.GET_EMPNP_EMP_ID(ACTION_DATE,EMPLOYEE_ID)
ORDER BY MIN(SEQUENCE_NUM) ASC



select MIN(SEQUENCE_NUM),OBJECT_ID, XX_P2P_EMP_INFO.GET_EMPNP_EMP_ID(ACTION_DATE,EMPLOYEE_ID)||chr(10)||'Date: '||TO_CHAR(MIN(ACTION_DATE),'DD-MON-RRRR') NAME_POS
from PO_ACTION_HISTORY PA
WHERE PA.ACTION_CODE IS NOT NULL
AND OBJECT_TYPE_CODE='REQUISITION'
AND UPPER(ACTION_CODE) IN ('SUBMIT','APPROVE','FORWARD')
--AND OBJECT_ID=467016
GROUP BY EMPLOYEE_ID,OBJECT_ID,XX_P2P_EMP_INFO.GET_EMPNP_EMP_ID(ACTION_DATE,EMPLOYEE_ID)
ORDER BY MIN(SEQUENCE_NUM) ASC







select * from PER_ALL_POSITIONS

--=====================================
-- TO GET ALL DEPARTMENTS
--=====================================
select * from XX_DEPT_V



CREATE OR REPLACE VIEW  XX_DEPT_V
(DEPT_NAME)
AS 
SELECT DISTINCT (CASE WHEN ATTRIBUTE5 in ('production', 'Production/ERP', 'Production') THEN 'Production' ELSE ATTRIBUTE5 END) DEPT_NAME
FROM MTL_TXN_REQUEST_LINES_V
WHERE ATTRIBUTE5 is not null
ORDER BY DEPT_NAME
;


--FUNCTION XXGET_DEPARTMENT(P_PO_HEADER_ID IN NUMBER)
RETURN CHAR
IS
V_DEPARTMENT VARCHAR2(500);
BEGIN
SELECT LISTAGG(DEPARTMENT_NAME,',') WITHIN GROUP (ORDER BY DEPARTMENT_NAME) DEPARTMENT INTO V_DEPARTMENT
FROM
(SELECT DISTINCT DEPARTMENT_NAME
FROM WBI_HR_EMPLOYEE_DETAILS_D
WHERE PERSON_ID IN (SELECT DISTINCT TO_PERSON_ID 
                                FROM PO_HEADERS_ALL PH,
                                PO_DISTRIBUTIONS_ALL D,
                                PO_REQ_DISTRIBUTIONS_ALL RD,
                                PO_REQUISITION_LINES_ALL RL,
                                PO_REQUISITION_HEADERS_ALL R
                                WHERE PH.PO_HEADER_ID = D.PO_HEADER_ID
                                AND D.REQ_DISTRIBUTION_ID = RD.DISTRIBUTION_ID
                                AND RD.REQUISITION_LINE_ID = RL.REQUISITION_LINE_ID
                                AND RL.REQUISITION_HEADER_ID = R.REQUISITION_HEADER_ID
                                AND D.PO_HEADER_ID=P_PO_HEADER_ID)
AND DEPARTMENT_NAME IS NOT NULL 
AND TRUNC(SYSDATE) BETWEEN TRUNC(EFFECTIVE_START_DATE) AND NVL(TRUNC(EFFECTIVE_END_DATE),TRUNC(SYSDATE)));