--DEPARTMENT_GET_QUERY
--=======================

SELECT  DISTINCT FULL_NAME, SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1),'.',1)-1) DEPT--, PAPF.START_DATE,END_DATE
----SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1),'.',1)-1)  DEPT
--INTO V_DEPT     
FROM PER_ALL_PEOPLE_F      PAPF
,PER_ALL_ASSIGNMENTS_F PAAF
,PER_ALL_POSITIONS     PAP
,FND_USER   FU 
WHERE PAPF.PERSON_ID=PAAF.PERSON_ID
AND PAPF.CURRENT_EMPLOYEE_FLAG='Y'
AND PAAF.PRIMARY_FLAG='Y'
AND PAAF.POSITION_ID=PAP.POSITION_ID
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAPF.EFFECTIVE_END_DATE)   
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAAF.EFFECTIVE_END_DATE)
--AND END_DATE is not null
--AND PAPF.PERSON_ID=225 --FU.EMPLOYEE_ID
--AND FU.USER_NAME= 'KG-4079' --225 P_PERSON_ID

select * from  PER_ALL_PEOPLE_F   


select * from FND_USER

--============================ FUNCTION  FOR DEPARTMENT GET===============================

 CREATE OR REPLACE FUNCTION XXGET_EMP_DEPT_NO(P_PERSON_ID IN VARCHAR2)
RETURN CHAR
IS
V_DEPT VARCHAR2(200);
BEGIN
SELECT SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1),'.',1)-1) DEPT
----SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1),'.',1)-1)  DEPT
INTO V_DEPT     
FROM PER_ALL_PEOPLE_F      PAPF
,PER_ALL_ASSIGNMENTS_F PAAF
,PER_ALL_POSITIONS     PAP
,FND_USER   FU 
WHERE PAPF.PERSON_ID=PAAF.PERSON_ID
AND PAPF.CURRENT_EMPLOYEE_FLAG='Y'
AND PAAF.PRIMARY_FLAG='Y'
AND PAAF.POSITION_ID=PAP.POSITION_ID
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAPF.EFFECTIVE_END_DATE)   
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAAF.EFFECTIVE_END_DATE)
AND PAPF.PERSON_ID=FU.EMPLOYEE_ID
AND FU.USER_ID=P_PERSON_ID;
RETURN(V_DEPT);
EXCEPTION WHEN OTHERS THEN
RETURN(NULL);
END;



SELECT SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1),'.',1)-1) DEPT
----SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',3,2)+1),'.',1)-1)  DEPT
--INTO V_DEPT     
FROM PER_ALL_PEOPLE_F      PAPF
,PER_ALL_ASSIGNMENTS_F PAAF
,PER_ALL_POSITIONS     PAP
,FND_USER   FU 
WHERE PAPF.PERSON_ID=PAAF.PERSON_ID
AND PAPF.CURRENT_EMPLOYEE_FLAG='Y'
AND PAAF.PRIMARY_FLAG='Y'
AND PAAF.POSITION_ID=PAP.POSITION_ID
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAPF.EFFECTIVE_END_DATE)   
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAAF.EFFECTIVE_END_DATE)
AND PAPF.PERSON_ID=FU.EMPLOYEE_ID
AND FU.USER_ID=1243 --'KG-4079' --P_PERSON_ID;

select * from FND_USER where user_name='KG-4079'

select * from PER_ALL_PEOPLE_F WHERE FIRST_NAME ='KG-4079'
