-- EBS Factory Overhead Report
SELECT GCC.SEGMENT1 LEGAL_ENTITY,GCC.SEGMENT2 OU, GAM.LEGAL_ENTITY_ID, GAM.ALLOC_CODE , GCC.SEGMENT1||'.'||GCC.SEGMENT2||'.'||GCC.SEGMENT3||'.'||GCC.SEGMENT4||'.'||GCC.SEGMENT5||'.'||GCC.SEGMENT6||'.'||GCC.SEGMENT7 CODE_COMBINATIONS , GCC.SEGMENT4 GL_CODE, 
XX_GET_ACCT_FLEX_SEG_DESC (1, GCC.SEGMENT1) LEGAL_ENTITY_NAME,
XX_GET_ACCT_FLEX_SEG_DESC(4,GCC.SEGMENT4) ACCOUNT_DESC, 
 :P_PERIOD_CODE,
 --(SELECT  NAME FROM GL_LEDGERS WHERE CHART_OF_ACCOUNTS_ID = GCC.SEGMENT1 ) OU,
 SUM(GAI.AMOUNT) AP_AMOUNT  
 FROM GL_ALOC_MST GAM, GL_CODE_COMBINATIONS  GCC, GL_ALOC_INP GAI, GL_ALOC_EXP GAE  
WHERE 1=1   
--AND GL.CHART_OF_ACCOUNTS_ID = GCC.SEGMENT1 
--AND GAI.CALENDAR_CODE = '19-20'
 AND  TO_CHAR(TO_DATE(GAI.PERIOD_CODE ,'MON-YY'),'MON-YY') = NVL(:P_PERIOD_CODE,  TO_CHAR(TO_DATE(GAI.PERIOD_CODE ,'MON-YY'),'MON-YY'))
--AND GAI.PERIOD_CODE = 'JUL-19'
AND GAM.ALLOC_ID = GAE.ALLOC_ID  
AND  GAE.ALLOC_ID = GAI.ALLOC_ID  
AND GAE.LINE_NO= GAI.LINE_NO   
--AND GAM.LEGAL_ENTITY_ID= 23273  -- KSRM Steel Plant Ltd (KSPL)
AND GAI.ACCOUNT_ID=GCC.CODE_COMBINATION_ID      ---
--AND GCC.SEGMENT1 = :P_LEGAL_ENTITY
  AND GCC.SEGMENT1 = NVL(:P_LEGAL_ENTITY, GCC.SEGMENT1)  --101
  AND GCC.SEGMENT2 = NVL(:P_OPERATING_UNIT, GCC.SEGMENT2) 
--and gai.AMOUNT <> 0
--and gam.alloc_code= 'GAS CONSUMED' -- like ()
GROUP BY GCC.SEGMENT1,GCC.SEGMENT2 ,GAM.LEGAL_ENTITY_ID, GAM.ALLOC_CODE,GCC.SEGMENT4,  GCC.SEGMENT1||'.'||GCC.SEGMENT2||'.'||GCC.SEGMENT3||'.'||GCC.SEGMENT4||'.'||GCC.SEGMENT5||'.'||GCC.SEGMENT6||'.'||GCC.SEGMENT7
ORDER  BY GAM.ALLOC_CODE