
/*GET PO FROM PR QUERY */

SELECT POH. PO_HEADER_ID, POH. SEGMENT1 "PO NO" , PRHA .SEGMENT1 
"REQUISTION NO" 
FROM PO_HEADERS_ALL POH, 
       PO_DISTRIBUTIONS_ALL PDA ,
       PO_REQ_DISTRIBUTIONS_ALL PRDA ,
       PO_REQUISITION_LINES_ALL PRLA ,
       PO_REQUISITION_HEADERS_ALL PRHA
WHERE POH. PO_HEADER_ID = PDA. PO_HEADER_ID 
AND    PDA. REQ_DISTRIBUTION_ID = PRDA.DISTRIBUTION_ID
AND    PRDA. REQUISITION_LINE_ID = PRLA. REQUISITION_LINE_ID
AND      PRLA. REQUISITION_HEADER_ID = PRHA. REQUISITION_HEADER_ID
--AND   POH.SEGMENT1 = '207655'  -- PO NUMBER 
AND    PRHA. SEGMENT1 = '10002561'   -- PO REQUISITION NUMBER
AND PRHA.ORG_ID = '81'