
--===========================
--Inventory BINCARD report
--=========================
SELECT 
WIOD.OPERATING_UNIT_NAME OU_NAME,
WIOD.INV_ORG_ADDRESS OU_ADD,
WIOD.INVENTORY_ORGANIZATION_NAME,
WXMD.ITEM_DESC,
WXMD.ITEM_CODE,
WXMD.UOM1 UOM,
WXMD.ITEM_TYPE,
WXMD.ITEM_GROUP,
WXMD.ITEM_SUB_GROUP,
XX_INV_PKG.XX_INV_OPEN_QTY(MMT.ORGANIZATION_ID,NULL, MMT.INVENTORY_ITEM_ID ,:P_DATE_FROM) OPEN_QTY,
----=====================================================================================
MMT.SUBINVENTORY_CODE SUBINVENTORY,
NULL LOCATION,
TO_CHAR(MMT.TRANSACTION_DATE,'DD/MM/RRRR HH24:MI:SS')  TRANSACTION_DATE,
----MMT.TRANSACTION_DATE  TRANSACTION_DATE,
MMT.TRANSACTION_TYPE_ID,
(SELECT TRANSACTION_TYPE_NAME  FROM MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_ID=MMT.TRANSACTION_TYPE_ID ) TRANSACTION_TYPE,
MMT.TRANSACTION_ID,
DECODE(MMT.TRANSACTION_TYPE_ID,
                                    21,(SELECT SHIPMENT_NUMBER FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_SOURCE_TYPE_ID=13 AND TRANSACTION_TYPE_ID=21 AND TRANSACTION_ID=MMT.TRANSACTION_ID),
                                    XX_INV_PKG.XX_INV_TRANS_NO(MMT.TRANSACTION_ID)) TRANSACTION_NO,
-----==========================================================================================================
MMT.ORGANIZATION_ID,
MMT.TRANSACTION_DATE,
MMT.INVENTORY_ITEM_ID,
---==================================CALCULATION PART ==========================================================
NVL((SELECT PRIMARY_QUANTITY FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID=MMT.TRANSACTION_ID AND PRIMARY_QUANTITY>0),0) RECEIVE_QTY,
NVL(ABS((SELECT PRIMARY_QUANTITY FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID=MMT.TRANSACTION_ID AND PRIMARY_QUANTITY<0)),0) ISSUE_QTY, 
(SELECT NVL(SUM(PRIMARY_QUANTITY),0)  FROM  MTL_MATERIAL_TRANSACTIONS WHERE  ORGANIZATION_ID=MMT.ORGANIZATION_ID AND INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID  AND TRANSACTION_ID <=MMT.TRANSACTION_ID) CLOSE_QTY,
----==========================================================================================================
NULL REMARKS,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME ,
TO_DATE(:P_DATE_FROM) DATE_FROM,
TO_DATE(:P_DATE_TO) DATE_TO 
FROM 
MTL_MATERIAL_TRANSACTIONS MMT, 
WBI_INV_ORG_DETAIL WIOD,
WBI_XXKBGITEM_MT_D WXMD
WHERE 
MMT.ORGANIZATION_ID=WIOD.INV_ORGANIZATION_ID
--=====================================
AND WXMD.INVENTORY_ITEM_ID =MMT.INVENTORY_ITEM_ID
AND WXMD.ORGANIZATION_ID= MMT.ORGANIZATION_ID
---=====================================
AND WIOD.INV_ORGANIZATION_ID = MMT.ORGANIZATION_ID
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE) 
AND MMT.ORGANIZATION_ID=NVL(:P_ORG_ID, MMT.ORGANIZATION_ID)
AND TRUNC( TRANSACTION_DATE) BETWEEN TO_DATE(:P_DATE_FROM) AND TO_DATE(:P_DATE_TO)
ORDER BY MMT.TRANSACTION_ID

/*

SELECT 
WIOD.OPERATING_UNIT_NAME OU_NAME,
WIOD.INV_ORG_ADDRESS OU_ADD,
WIOD.INVENTORY_ORGANIZATION_NAME,
WXMD.ITEM_DESC,
WXMD.ITEM_CODE,
WXMD.UOM1 UOM,
WXMD.ITEM_TYPE,
WXMD.ITEM_GROUP,
WXMD.ITEM_SUB_GROUP,
XX_INV_PKG.XX_INV_OPEN_QTY(MMT.ORGANIZATION_ID,NULL, MMT.INVENTORY_ITEM_ID ,:P_DATE_FROM) OPEN_QTY,
----=====================================================================================
MMT.SUBINVENTORY_CODE SUBINVENTORY,
NULL LOCATION,
TO_CHAR(MMT.TRANSACTION_DATE,'DD/MM/RRRR HH24:MI:SS')  TRANSACTION_DATE,
----MMT.TRANSACTION_DATE  TRANSACTION_DATE,
MMT.TRANSACTION_TYPE_ID,
(SELECT TRANSACTION_TYPE_NAME  FROM MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_ID=MMT.TRANSACTION_TYPE_ID ) TRANSACTION_TYPE,
----MMT.TRANSACTION_ID,
DECODE(MMT.TRANSACTION_TYPE_ID,
                                    21,(SELECT SHIPMENT_NUMBER FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_SOURCE_TYPE_ID=13 AND TRANSACTION_TYPE_ID=21 AND TRANSACTION_ID=MMT.TRANSACTION_ID),
                                    XX_INV_PKG.XX_INV_TRANS_NO(MMT.TRANSACTION_ID)) TRANSACTION_ID,
-----==========================================================================================================
MMT.ORGANIZATION_ID,
MMT.TRANSACTION_DATE,
MMT.INVENTORY_ITEM_ID,
---==================================CALCULATION PART ==========================================================
NVL((SELECT PRIMARY_QUANTITY FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID=MMT.TRANSACTION_ID AND PRIMARY_QUANTITY>0),0) RECEIVE_QTY,
NVL(ABS((SELECT PRIMARY_QUANTITY FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID=MMT.TRANSACTION_ID AND PRIMARY_QUANTITY<0)),0) ISSUE_QTY, 
(SELECT NVL(SUM(PRIMARY_QUANTITY),0)  FROM  MTL_MATERIAL_TRANSACTIONS WHERE  ORGANIZATION_ID=MMT.ORGANIZATION_ID AND INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID  AND TRANSACTION_ID <=MMT.TRANSACTION_ID) CLOSE_QTY,
----==========================================================================================================
NULL REMARKS,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME ,
TO_DATE(:P_DATE_FROM) DATE_FROM,
TO_DATE(:P_DATE_TO) DATE_TO 
FROM 
MTL_MATERIAL_TRANSACTIONS MMT, 
WBI_INV_ORG_DETAIL WIOD,
WBI_XXKBGITEM_MT_D WXMD
WHERE 
MMT.ORGANIZATION_ID=WIOD.INV_ORGANIZATION_ID
--=====================================
AND WXMD.INVENTORY_ITEM_ID =MMT.INVENTORY_ITEM_ID
AND WXMD.ORGANIZATION_ID= MMT.ORGANIZATION_ID
---=====================================
AND WIOD.INV_ORGANIZATION_ID = MMT.ORGANIZATION_ID
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE) 
AND MMT.ORGANIZATION_ID=NVL(:P_ORG_ID, MMT.ORGANIZATION_ID)
AND TRUNC( TRANSACTION_DATE) BETWEEN TO_DATE(:P_DATE_FROM) AND TO_DATE(:P_DATE_TO)
ORDER BY MMT.TRANSACTION_ID



SELECT 
WIOD.OPERATING_UNIT_NAME OU_NAME,
WIOD.INV_ORG_ADDRESS OU_ADD,
WIOD.INVENTORY_ORGANIZATION_NAME,
WXMD.ITEM_DESC,
WXMD.ITEM_CODE,
WXMD.UOM1 UOM,
WXMD.ITEM_TYPE,
WXMD.ITEM_GROUP,
WXMD.ITEM_SUB_GROUP,
XX_INV_PKG.XX_INV_OPEN_QTY(MMT.ORGANIZATION_ID,NULL, MMT.INVENTORY_ITEM_ID ,:P_DATE_FROM) OPEN_QTY,
----=====================================================================================
MMT.SUBINVENTORY_CODE SUBINVENTORY,
NULL LOCATION,
TO_CHAR(MMT.TRANSACTION_DATE,'DD/MM/RRRR HH24:MI:SS')  TRANSACTION_DATE,
----MMT.TRANSACTION_DATE  TRANSACTION_DATE,
(SELECT TRANSACTION_TYPE_NAME  FROM MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_ID=MMT.TRANSACTION_TYPE_ID ) TRANSACTION_TYPE,
MMT.TRANSACTION_ID,
-----==========================================================================================================
MMT.ORGANIZATION_ID,
MMT.TRANSACTION_DATE,
MMT.INVENTORY_ITEM_ID,
---==================================CALCULATION PART ==========================================================
NVL((SELECT PRIMARY_QUANTITY FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID=MMT.TRANSACTION_ID AND PRIMARY_QUANTITY>0),0) RECEIVE_QTY,
NVL(ABS((SELECT PRIMARY_QUANTITY FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID=MMT.TRANSACTION_ID AND PRIMARY_QUANTITY<0)),0) ISSUE_QTY, 
(SELECT NVL(SUM(PRIMARY_QUANTITY),0)  FROM  MTL_MATERIAL_TRANSACTIONS WHERE  ORGANIZATION_ID=MMT.ORGANIZATION_ID AND INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID  AND TRANSACTION_ID <=MMT.TRANSACTION_ID) CLOSE_QTY,
----==========================================================================================================
NULL REMARKS,
XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME ,
TO_DATE(:P_DATE_FROM) DATE_FROM,
TO_DATE(:P_DATE_TO) DATE_TO 
FROM 
MTL_MATERIAL_TRANSACTIONS MMT, 
WBI_INV_ORG_DETAIL WIOD,
WBI_XXKBGITEM_MT_D WXMD
WHERE 
MMT.ORGANIZATION_ID=WIOD.INV_ORGANIZATION_ID
--=====================================
AND WXMD.INVENTORY_ITEM_ID =MMT.INVENTORY_ITEM_ID
AND WXMD.ORGANIZATION_ID= MMT.ORGANIZATION_ID
---=====================================
AND WIOD.INV_ORGANIZATION_ID = MMT.ORGANIZATION_ID
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE) 
AND MMT.ORGANIZATION_ID=NVL(:P_ORG_ID, MMT.ORGANIZATION_ID)
AND TRUNC( TRANSACTION_DATE) BETWEEN TO_DATE(:P_DATE_FROM) AND TO_DATE(:P_DATE_TO)
ORDER BY MMT.TRANSACTION_ID

*/
