   --Inventory Valuation V7                         date 18-OCT-2021--Updated by Ibrahim Kholil Vhai
  --------------------------------------------------------------------------------------------------------
  
SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL 
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,44,18,61,1002,1003,36) THEN INV_TRANS.TRANSACTION_QUANTITY 
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) AND INV_TRANS.EVENT_TYPE_CODE <> 'FOB_RCPT_SENDER_RCPT_NO_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003,36) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR - INV_TRANS.ACCOUNTED_CR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE  
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261,221,132) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' 
OR INV_TRANS.EVENT_TYPE_CODE='FOB_RCPT_SENDER_SHIP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' 
THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_QUANTITY -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_QTY,
SUM( CASE WHEN  INV_TRANS.TRANSACTION_TYPE_ID =15 THEN  INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261,221,132) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_RCPT_SENDER_SHIP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_VALUE -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_VAL
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,sum(nvl(xal.accounted_dr,0)) accounted_dr,sum(nvl(xal.accounted_cr,0)) accounted_cr
--(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g,xla_ae_headers xah,xla_ae_lines xal 
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
and a.event_id=xah.event_id
        and a.ledger_id=xah.ledger_id
        and xah.ae_header_id = xal.ae_header_id
        and xah.application_id = xal.application_id
        and xal.accounting_class_code = 'INVENTORY_VALUATION'
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   555557   --5647466
group by 
to_char(transaction_date,'MON-YY') ,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID, INV_TRANS.ACCOUNTED_DR  
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
--AND MIC.INVENTORY_ITEM_ID = 319
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code




   --Inventory Valuation V6 date 010-OCT-2021--Ibrahim Vai Updated Query
  -------------------------------------------------------------------------------------------------
  
SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,44,18,61,1002,1003,36) THEN INV_TRANS.TRANSACTION_QUANTITY 
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) AND INV_TRANS.EVENT_TYPE_CODE <> 'FOB_RCPT_SENDER_RCPT_NO_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003,36) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR - INV_TRANS.ACCOUNTED_CR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE  
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261,221,132) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' 
OR INV_TRANS.EVENT_TYPE_CODE='FOB_RCPT_SENDER_SHIP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' 
THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_QUANTITY -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_QTY,
SUM(  CASE WHEN  INV_TRANS.TRANSACTION_TYPE_ID =15 THEN  INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261,221,132) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_RCPT_SENDER_SHIP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_VALUE -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_VAL
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,sum(nvl(xal.accounted_dr,0)) accounted_dr,sum(nvl(xal.accounted_cr,0)) accounted_cr
--(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g,xla_ae_headers xah,xla_ae_lines xal 
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
and a.event_id=xah.event_id
        and a.ledger_id=xah.ledger_id
        and xah.ae_header_id = xal.ae_header_id
        and xah.application_id = xal.application_id
        and xal.accounting_class_code = 'INVENTORY_VALUATION'
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   555557   --5647466
group by 
to_char(transaction_date,'MON-YY') ,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID, INV_TRANS.ACCOUNTED_DR
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
--AND MIC.INVENTORY_ITEM_ID = 319
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code




   --Inventory Valuation V5  irfan Vai update 07-09-2021
  ---------------------------------------------------------------
  
SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,44,18,61,1002,1003,36) THEN INV_TRANS.TRANSACTION_QUANTITY 
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) AND INV_TRANS.EVENT_TYPE_CODE <> 'FOB_RCPT_SENDER_RCPT_NO_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003,36) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE  
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261,221) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_RCPT_SENDER_SHIP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_QUANTITY -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_QTY,
SUM(  CASE WHEN  INV_TRANS.TRANSACTION_TYPE_ID =15 THEN  INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261,221) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_RCPT_SENDER_SHIP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_VALUE -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_VAL
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,
(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   10830031   --5647466
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID, INV_TRANS.ACCOUNTED_DR
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
--AND MIC.INVENTORY_ITEM_ID = 319
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code


 --- =========================================  IPB FINDING FOR OPENING DATA ===================================================
 
 SELECT * FROM MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_NAME = 'Wastage Tyre/Battery Receive'

 
 SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            and MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 = 'CP|500W|16MM|000004' -- in ('SP|ELEC|BATT|002631','SP|ELEC|BATT|002633', 'SP|VHCL|TYRE|026605', 'FL|F&LB|DSEL|000066', 'SP|ELEC|BATT|002633') -- 'SP|ELEC|BATT|002631' -- 'FL|F&LB|DSEL|000066' --   -- 'FG|PWER|OFPK|000051' 
 GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4
 
 
 --=================================== GET ITEM TRANSACTION IN VALUATION  FOR AREFIN VAI ================================================
 
 
 
 SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE
--(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
--AND B.INVENTORY_ITEM_ID IN (10409,802038) 
--AND B.INVENTORY_ITEM_ID IN (70)
and a.ledger_id=:P_LEDGER_ID
and a.transaction_id IN (10830084,
11079515,
11079428)
--and a.transaction_id=   5920526   --5647466




   --Inventory Valuation V4    DATE: 31-AUG-20121
  ---------------------------------------------------------------
  
SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,12,44,18,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE  
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_QUANTITY -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_QTY,
SUM(  CASE WHEN  INV_TRANS.TRANSACTION_TYPE_ID =15 THEN  INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_VALUE -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_VAL
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,
(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   5920526   --5647466
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID, INV_TRANS.ACCOUNTED_DR
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code




--============================================================

--Inventory Valuation V3    DATE: 1-JUN-20121
  ---------------------------------------------------------------
  
SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,12,44,18,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE  
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
ELSE 0 END) ISU_QTY,
SUM(  CASE WHEN  INV_TRANS.TRANSACTION_TYPE_ID =15 THEN  INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
ELSE 0 END) ISU_VAL
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,
(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   5920526   --5647466
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID, INV_TRANS.ACCOUNTED_DR
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code











SELECT TRANSACTION_VALUE  FROM  GMF_XLA_EXTRACT_HEADERS 
WHERE  TRANSACTION_VALUE = 4378334.91
AND  TRANSACTION_ID =  5532118 


UPDATE GMF_XLA_EXTRACT_HEADERS 
SET TRANSACTION_VALUE = 4378334.91
WHERE TRANSACTION_ID =  5532118 


UPDATE GMF_XLA_EXTRACT_HEADERS 
SET TRANSACTION_VALUE = 1306452.93
WHERE TRANSACTION_ID = 5205623 

 1306452.93
 
 
 SELECT b.* FROM RCV_SHIPMENT_LINES A, RCV_TRANSACTIONS B
 WHERE A.SHIPMENT_HEADER_ID= B.SHIPMENT_HEADER_ID
 AND A.ITEM_ID= 180
 AND B.TRANSACTION_DATE BETWEEN '01--2018' and '30-SEP-2018'
 -- AND B.TRANSACTION_DATE BETWEEN '01-OCT-2018' and '31-OCT-2018'
  and TRANSACTION_TYPE  IN ('DELIVER','RETURN TO VENDOR') -- between 
 
 SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE= 'TRM'
 
 SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE CREATION_DATE BETWEEN '01-SEP-2018' and '31-OCT-2018' and ORGANIZATION_ID IN (152) and inventory_item_id=180 -- 27865
 
 SELECT * FROM MTL_TXN_REQUEST_LINES WHERE INVENTORY_ITEM_ID = 4235 and STATUS_DATE BETWEEN '01-AUG-2018' and '31-OCT-2018'
 
 
 select CLOSED_CODE from PO_HEADERS_ALL  WHERE SEGMENT1 IN (40000140,40000057) and ORG_ID= 81
 
 
     select    ORGANIZATION_ID,    INVORG_NAME_FROM_ID (ORGANIZATION_ID) ORGANIZATION_CODE,CREATION_DATE,SUMMARY_FLAG,ENABLED_FLAG, XXGET_ITEM_CODE(inventory_item_id) ITEM_CODE ,DESCRIPTION, XX_GET_EMP_NAME_FROM_USER_ID (CREATED_BY) CREATED_BY,XX_GET_EMP_NAME_FROM_USER_ID (LAST_UPDATED_BY) LAST_UPDATED_BY , LAST_UPDATE_DATE, LAST_UPDATED_BY, AUTO_LOT_ALPHA_PREFIX,START_AUTO_LOT_NUMBER,LOT_CONTROL_CODE,RESTRICT_LOCATORS_CODE,LOCATION_CONTROL_CODE,ITEM_TYPE,START_AUTO_LOT_NUMBER,ALLOW_ITEM_DESC_UPDATE_FLAG
       PURCHASING_ITEM_FLAG,SHIPPABLE_ITEM_FLAG,CUSTOMER_ORDER_FLAG,INTERNAL_ORDER_FLAG,SERVICE_ITEM_FLAG,INVENTORY_ITEM_FLAG, ENG_ITEM_FLAG,INVENTORY_ASSET_FLAG,PURCHASING_ENABLED_FLAG
         CUSTOMER_ORDER_ENABLED_FLAG,SO_TRANSACTIONS_FLAG,STOCK_ENABLED_FLAG,BOM_ENABLED_FLAG,BUILD_IN_WIP_FLAG,REVISION_QTY_CONTROL_CODE,REVISION_QTY_CONTROL_CODE,CATALOG_STATUS_FLAG,RETURNABLE_FLAG,
        COLLATERAL_FLAG,QTY_RCV_EXCEPTION_CODE,PICK_COMPONENTS_FLAG, INSPECTION_REQUIRED_FLAG,RECEIPT_REQUIRED_FLAG,RFQ_REQUIRED_FLAG,LIST_PRICE_PER_UNIT,ALLOW_SUBSTITUTE_RECEIPTS_FLAG,ALLOW_UNORDERED_RECEIPTS_FLAG,EXPENSE_ACCOUNT,COST_OF_SALES_ACCOUNT,SALES_ACCOUNT,INVENTORY_ITEM_STATUS_CODE,RESTRICT_SUBINVENTORIES_CODE,INVOICEABLE_ITEM_FLAG,INVOICE_ENABLED_FLAG,PLANNING_TIME_FENCE_CODE, LEAD_TIME_LOT_SIZE,MRP_CALCULATE_ATP_FLAG,LOT_MERGE_ENABLED,LOT_TRANSLATE_ENABLED,LOT_SPLIT_ENABLED, LOT_STATUS_ENABLED,COSTING_ENABLED_FLAG,AUTO_CREATED_CONFIG_FLAG,CYCLE_COUNT_ENABLED_FLAG,LOT_TRANSLATE_ENABLED
         DEFAULT_SO_SOURCE_TYPE,CREATE_SUPPLY_FLAG,WIP_SUPPLY_TYPE, PRIMARY_UOM_CODE, PRIMARY_UNIT_OF_MEASURE, OBJECT_VERSION_NUMBER,ONT_PRICING_QTY_SOURCE,CHILD_LOT_FLAG,CHILD_LOT_VALIDATION_FLAG,COPY_LOT_ATTRIBUTE_FLAG,GRADE_CONTROL_FLAG,BOM_ITEM_TYPE,HAZARDOUS_MATERIAL_FLAG,LOT_DIVISIBLE_FLAG,PROCESS_COSTING_ENABLED_FLAG,PROCESS_EXECUTION_ENABLED_FLAG,PROCESS_QUALITY_ENABLED_FLAG,GDSN_OUTBOUND_ENABLED_FLAG 
        from MTL_SYSTEM_ITEMS_B 
      where inventory_item_id IN  (--4235,
--27865,
--3591,
--3591
27865
) 
 --and ORGANIZATION_ID NOT IN ( 152,157, 158) 
 
 
   SELECT * from MTL_SYSTEM_ITEMS_B 
      where inventory_item_id IN  (--4235,
--27865,
--3591,
--3591
27865
) 
      
      
      XXGET_ITEM_DESCRIPTION(P_ITEM_ID IN NUMBER)
XXGET_ITEM_CODE(P_ITEM_ID IN NUMBER)
 
 
 select * from ORG_ACCT_PERIODS where ACCT_PERIOD_ID IN (1,1037)
 
 
 SELECT GPB.* FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            and GPB.inventory_item_id 
            IN (4235,
4235,
27865,
3591,
3591)
            and GPB.ORGANIZATION_ID IN (157, 158)
             AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
         --   and OAP.PERIOD_NAME = 'Sep-18'
             -- LOT_DIVISIBLE_FLAG
             
             
           
           select * from RCV_TRANSACTIONS WHERE creation_date  BETWEEN '01-AUG-2018' and '30-SEP-2018' and ORGANIZATION_ID IN (157, 158) --and inventory_item_id= 4235
             
             select * from ORG_ACCT_PERIODS where acct_period_id= 13040
             
             select * from GMF_PERIOD_BALANCES where ORGANIZATION_ID  IN (158, 157) and inventory_item_id='4235' --and PERIOD_BALANCE_ID  IN ( 33733, 32295) 
             
              select * from GMF_PERIOD_BALANCES where CREATION_DATE > '10-MAY-18' -- PERIOD_BALANCE_ID = 2344967 
             
             
             SELECT * --PERIOD_NAME --*
             FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP  
             WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID
             and GPB.ORGANIZATION_ID IN( 157, 158)  and inventory_item_id='4235'
             
             
             
                       SELECT GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,PERIOD_NAME,  PERIOD_YEAR, PERIOD_NUM , PRIMARY_QUANTITY, OPEN_FLAG,PERIOD_CLOSE_DATE ,  SUMMARIZED_FLAG ,
                       MSI.ALLOW_ITEM_DESC_UPDATE_FLAG, AUTO_LOT_ALPHA_PREFIX,  LOT_DIVISIBLE_FLAG --PERIOD_NAME --*
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            and GPB.inventory_item_id IN (
4235,
4235,
27865,
3591,
3591)
  and GPB.ORGANIZATION_ID IN( 152, 157, 158)  
  --and  OPEN_FLAG = 'Y'           
 
--======================================================================================================================
 
 --Inventory Valuation V2    DATE: 17-MAR-20121

SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,12,44,18,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE  
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
ELSE 0 END) ISU_QTY,
SUM(  CASE WHEN  INV_TRANS.TRANSACTION_TYPE_ID =15 THEN  INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
ELSE 0 END) ISU_VAL
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,
(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   5920526   --5647466
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID, INV_TRANS.ACCOUNTED_DR
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code



-- --Inventory Valuation V1

SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,12,44,18,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
ELSE 0 END) ISU_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID =15 THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
ELSE 0 END) ISU_VAL
FROM
(SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,
(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id) accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID-- and a.transaction_id=6687923
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code




--Inventory Valuation 

SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,12,44,18,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,  
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
ELSE 0 END) ISU_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID =15 THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
ELSE 0 END) ISU_VAL
FROM
(SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,
(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id) accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE
and a.ledger_id=:P_LEDGER_ID
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code