DROP VIEW APPS.WBI_INV_ORG_DETAIL;

/* Formatted on 1/21/2020 12:15:14 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW APPS.WBI_INV_ORG_DETAIL
(
   OPERATING_UNIT_NAME,
   SHORT_CODE,
   OPERATING_UNIT_ID,
   OPERATING_UNIT_ADDRESS,
   SET_OF_BOOKS_ID,
   BUSINESS_GROUP_ID,
   INVENTORY_ORGANIZATION_NAME,
   INV_ORGANIZATION_CODE,
   INV_ORGANIZATION_ID,
   INV_ORG_ADDRESS,
   CHART_OF_ACCOUNTS_ID,
   LEGAL_ENTITY_ID,
   LEGAL_ENTITY_NAME
)
AS
   SELECT HOU.NAME OPERATING_UNIT_NAME,
          HOU.SHORT_CODE,
          HOU.ORGANIZATION_ID OPERATING_UNIT_ID,
          (SELECT HLV.ADDRESS_LINE_1
                  || DECODE (HLV.ADDRESS_LINE_2,
                             NULL, NULL,
                             ', ' || HLV.ADDRESS_LINE_2)
                  || DECODE (HLV.ADDRESS_LINE_3,
                             NULL, NULL,
                             ', ' || HLV.ADDRESS_LINE_3)
                  || DECODE (HLV.TOWN_OR_CITY,
                             NULL, NULL,
                             ', ' || HLV.TOWN_OR_CITY)
                  || DECODE (HLV.REGION_1, NULL, NULL, ', ' || HLV.REGION_1)
                  || DECODE (HLV.COUNTRY, NULL, NULL, ', ' || HLV.COUNTRY)
                     ADDRESS
             FROM HR_LOCATIONS_V HLV, HR_ALL_ORGANIZATION_UNITS HO
            WHERE HLV.LOCATION_ID = HO.LOCATION_ID
                  AND HO.ORGANIZATION_ID = HOU.ORGANIZATION_ID)
             OPERATING_UNIT_ADDRESS,
          HOU.SET_OF_BOOKS_ID,
          HOU.BUSINESS_GROUP_ID,
          OOD.ORGANIZATION_NAME INVENTORY_ORGANIZATION_NAME,
          OOD.ORGANIZATION_CODE INV_ORGANIZATION_CODE,
          OOD.ORGANIZATION_ID INV_ORGANIZATION_ID,
          (SELECT HLV.ADDRESS_LINE_1
                  || DECODE (HLV.ADDRESS_LINE_2,
                             NULL, NULL,
                             ', ' || HLV.ADDRESS_LINE_2)
                  || DECODE (HLV.ADDRESS_LINE_3,
                             NULL, NULL,
                             ', ' || HLV.ADDRESS_LINE_3)
                  || DECODE (HLV.TOWN_OR_CITY,
                             NULL, NULL,
                             ', ' || HLV.TOWN_OR_CITY)
                  || DECODE (HLV.COUNTRY, NULL, NULL, ', ' || HLV.COUNTRY)
                     ADDRESS
             FROM HR_LOCATIONS_V HLV, HR_ALL_ORGANIZATION_UNITS HO
            WHERE HLV.LOCATION_ID = HO.LOCATION_ID
                  AND HO.ORGANIZATION_ID = OOD.ORGANIZATION_ID)
             INV_ORG_ADDRESS,
          OOD.CHART_OF_ACCOUNTS_ID,
          OOD.LEGAL_ENTITY LEGAL_ENTITY_ID,
          XEP.NAME LEGAL_ENTITY_NAME
     FROM HR_OPERATING_UNITS HOU,
          ORG_ORGANIZATION_DEFINITIONS OOD,
          XLE_ENTITY_PROFILES XEP
    WHERE     1 = 1
          AND HOU.ORGANIZATION_ID = OOD.OPERATING_UNIT
          AND XEP.LEGAL_ENTITY_ID = OOD.LEGAL_ENTITY
          AND HOU.DEFAULT_LEGAL_CONTEXT_ID = XEP.LEGAL_ENTITY_ID
          AND HOU.DEFAULT_LEGAL_CONTEXT_ID = OOD.LEGAL_ENTITY;
          
          
          --==============================================
          
          DROP VIEW XLE.XLE_ENTITY_PROFILES#;

/* Formatted on 1/21/2020 12:18:14 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE EDITIONING VIEW XLE.XLE_ENTITY_PROFILES#
(
   LEGAL_ENTITY_ID,
   PARTY_ID,
   LEGAL_ENTITY_IDENTIFIER,
   NAME,
   GEOGRAPHY_ID,
   TRANSACTING_ENTITY_FLAG,
   EFFECTIVE_FROM,
   EFFECTIVE_TO,
   LE_INFORMATION_CONTEXT,
   LE_INFORMATION1,
   LE_INFORMATION2,
   LE_INFORMATION3,
   LE_INFORMATION4,
   LE_INFORMATION5,
   LE_INFORMATION6,
   LE_INFORMATION7,
   LE_INFORMATION8,
   LE_INFORMATION9,
   LE_INFORMATION10,
   LE_INFORMATION11,
   LE_INFORMATION12,
   LE_INFORMATION13,
   LE_INFORMATION14,
   LE_INFORMATION15,
   LE_INFORMATION16,
   LE_INFORMATION17,
   LE_INFORMATION18,
   LE_INFORMATION19,
   LE_INFORMATION20,
   LAST_UPDATED_BY,
   CREATION_DATE,
   LAST_UPDATE_LOGIN,
   LAST_UPDATE_DATE,
   CREATED_BY,
   OBJECT_VERSION_NUMBER,
   ATTRIBUTE_CATEGORY,
   ATTRIBUTE1,
   ATTRIBUTE2,
   ATTRIBUTE3,
   ATTRIBUTE4,
   ATTRIBUTE5,
   ATTRIBUTE6,
   ATTRIBUTE7,
   ATTRIBUTE8,
   ATTRIBUTE9,
   ATTRIBUTE10,
   ATTRIBUTE11,
   ATTRIBUTE12,
   ATTRIBUTE13,
   ATTRIBUTE14,
   ATTRIBUTE15,
   ATTRIBUTE16,
   ATTRIBUTE17,
   ATTRIBUTE18,
   ATTRIBUTE19,
   ATTRIBUTE20,
   ACTIVITY_CODE,
   SUB_ACTIVITY_CODE,
   TYPE_OF_COMPANY
)
AS
   SELECT LEGAL_ENTITY_ID LEGAL_ENTITY_ID,
          PARTY_ID PARTY_ID,
          LEGAL_ENTITY_IDENTIFIER LEGAL_ENTITY_IDENTIFIER,
          NAME NAME,
          GEOGRAPHY_ID GEOGRAPHY_ID,
          TRANSACTING_ENTITY_FLAG TRANSACTING_ENTITY_FLAG,
          EFFECTIVE_FROM EFFECTIVE_FROM,
          EFFECTIVE_TO EFFECTIVE_TO,
          LE_INFORMATION_CONTEXT LE_INFORMATION_CONTEXT,
          LE_INFORMATION1 LE_INFORMATION1,
          LE_INFORMATION2 LE_INFORMATION2,
          LE_INFORMATION3 LE_INFORMATION3,
          LE_INFORMATION4 LE_INFORMATION4,
          LE_INFORMATION5 LE_INFORMATION5,
          LE_INFORMATION6 LE_INFORMATION6,
          LE_INFORMATION7 LE_INFORMATION7,
          LE_INFORMATION8 LE_INFORMATION8,
          LE_INFORMATION9 LE_INFORMATION9,
          LE_INFORMATION10 LE_INFORMATION10,
          LE_INFORMATION11 LE_INFORMATION11,
          LE_INFORMATION12 LE_INFORMATION12,
          LE_INFORMATION13 LE_INFORMATION13,
          LE_INFORMATION14 LE_INFORMATION14,
          LE_INFORMATION15 LE_INFORMATION15,
          LE_INFORMATION16 LE_INFORMATION16,
          LE_INFORMATION17 LE_INFORMATION17,
          LE_INFORMATION18 LE_INFORMATION18,
          LE_INFORMATION19 LE_INFORMATION19,
          LE_INFORMATION20 LE_INFORMATION20,
          LAST_UPDATED_BY LAST_UPDATED_BY,
          CREATION_DATE CREATION_DATE,
          LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
          LAST_UPDATE_DATE LAST_UPDATE_DATE,
          CREATED_BY CREATED_BY,
          OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER,
          ATTRIBUTE_CATEGORY ATTRIBUTE_CATEGORY,
          ATTRIBUTE1 ATTRIBUTE1,
          ATTRIBUTE2 ATTRIBUTE2,
          ATTRIBUTE3 ATTRIBUTE3,
          ATTRIBUTE4 ATTRIBUTE4,
          ATTRIBUTE5 ATTRIBUTE5,
          ATTRIBUTE6 ATTRIBUTE6,
          ATTRIBUTE7 ATTRIBUTE7,
          ATTRIBUTE8 ATTRIBUTE8,
          ATTRIBUTE9 ATTRIBUTE9,
          ATTRIBUTE10 ATTRIBUTE10,
          ATTRIBUTE11 ATTRIBUTE11,
          ATTRIBUTE12 ATTRIBUTE12,
          ATTRIBUTE13 ATTRIBUTE13,
          ATTRIBUTE14 ATTRIBUTE14,
          ATTRIBUTE15 ATTRIBUTE15,
          ATTRIBUTE16 ATTRIBUTE16,
          ATTRIBUTE17 ATTRIBUTE17,
          ATTRIBUTE18 ATTRIBUTE18,
          ATTRIBUTE19 ATTRIBUTE19,
          ATTRIBUTE20 ATTRIBUTE20,
          ACTIVITY_CODE ACTIVITY_CODE,
          SUB_ACTIVITY_CODE SUB_ACTIVITY_CODE,
          TYPE_OF_COMPANY TYPE_OF_COMPANY
     FROM "XLE"."XLE_ENTITY_PROFILES";


DROP SYNONYM APPS.XLE_ENTITY_PROFILES;

CREATE OR REPLACE SYNONYM APPS.XLE_ENTITY_PROFILES FOR XLE.XLE_ENTITY_PROFILES#;


GRANT DELETE, INSERT, SELECT, UPDATE, DEBUG ON XLE.XLE_ENTITY_PROFILES# TO APPS WITH GRANT OPTION;



--========================================================================
