
--GET ITEM CATEGORY NAME
--===========================
SELECT distinct CATEGORY_SET_NAME from mtl_item_categories_v

select * from mtl_material_transactions where inventory_item_id=75


SELECT * FROM mtl_item_categories_v

SELECT * FROm WBI_XXKBGITEM_MT_D

SELECT DISTINCT ITEM_TYPE  FROm WBI_XXKBGITEM_MT_D


SELECT DISTINCT ITEM_GROUP  FROm WBI_XXKBGITEM_MT_D

SELECT DISTINCT ITEM_SUB_GROUP  FROm WBI_XXKBGITEM_MT_D

select * from per_all_people_f where first_name='KG-5890'

--===============================
--GET ALL ACTIVE  ITEM LIST
--===============================
select ORGANIZATION_CODE,ITEM_TYPE,  FINANCE_CATEGORY, ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,ITEM_CODE,ITEM_DESC,UOM1,UOM2,STATUS
 from WBI_XXKBGITEM_MT_D
 --where ITEM_CODE = 'SP|GENE|SHOE|003136'
--where ORGANIZATION_CODE = 'KPM'

SELECT DISTINCT FINANCE_CATEGORY  FROM WBI_XXKBGITEM_MT_D 


--==============================
-- GET CODE COMBINATION
---==============================

SELECT *  FROM GL_CODE_COMBINATIONS

SELECT  DISTINCT CODE_COMBINATION_ID, XX_AP_PKG.GET_ACCOUNT_DESC_FROM_CCID (CODE_COMBINATION_ID)  ACCOUNT_NAME  FROM GL_CODE_COMBINATIONS

XXGET_ITEM_DESCRIPTION(P_ITEM_ID IN NUMBER)

XXGET_ITEM_CODE(P_ITEM_ID IN NUMBER)



select *  from mtl_system_ITEMS_KFV  --where QTY_RCV_TOLERANCE is not null  --> QTY_RCV_EXCEPTION_CODE

SELECT * FROM ORG_ORGANIZATION_DEFINITIONS where organization_code like'%BL%'


--=====================================
--GET ALL TRANSACTION DATA AGAINST A ITEM
--=====================================

SELECT  GET_ORG_CODE_FROM_ID(a.ORGANIZATION_ID) ORG_CODE , B.TRANSACTION_TYPE_NAME,TO_CHAR(A.
TRANSACTION_DATE,'MON-YY') TRANS_DATE, 
 XXGET_ITEM_DESCRIPTION(A.INVENTORY_ITEM_ID, A.ORGANIZATION_ID) ITEM_DESC, A.*
  FROM MTL_MATERIAL_TRANSACTIONS A, MTL_TRANSACTION_TYPES B, ORG_ORGANIZATION_DEFINITIONS O
 WHERE A.TRANSACTION_TYPE_ID = B.TRANSACTION_TYPE_ID 
 AND A.ORGANIZATION_ID = O.ORGANIZATION_ID
  and  INVENTORY_ITEM_ID IN (243,244)
   AND  TRUNC(TRANSACTION_DATE)  BETWEEN '01-OCT-2018' AND '31-OCT-2018'   -- 2,353
  AND O.LEGAL_ENTITY = 26280

12,21,53,62,98

select *  from MTL_SYSTEM_ITEMS_KFV where inventory_item_id=3196 and ORGANIZATION_ID =121  --and ATTRIBUTE not like '0'

select distinct INVENTORY_ITEM_ID,SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4 ITEM_CODE, DESCRIPTION
 from MTL_SYSTEM_ITEMS_B where SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4 LIKE '%FG|CYLN|CO2|000053%' --'SF|BILT|A706|000012'
 
 
 SF|BILT|500|000011
 SF|BILT|G-80|000011
 
 SP|MECH|BRNG|018780
 SP|MECH|BRNG|01878
 
 SELECT  distinct CONCATENATED_SEGMENTS , XX_GET_ACCT_FLEX_SEG_DESC(4,SEGMENT4)  FROM GL_CODE_COMBINATIONS_KFV
 
 XX_KSRM_SLA_INV_CAT
 
  XX_KSRM_LC_VAL_CAT
 
 select  XX_GET_EMP_NAME_FROM_USER_ID (CREATED_BY) from MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID = 4619753
 
 select DISTINCT INVENTORY_ITEM_ID,SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4 ITEM_CODE, DESCRIPTION
 from MTL_SYSTEM_ITEMS_B where DESCRIPTION LIKE  '%FILLED%CYLINDER%'  --'%VIETNAM%'
--and SEGMENT1 IN ('FG', 'FA') 
 --AND  DESCRIPTION LIKE '%FILLED%'
--AND  DESCRIPTION LIKE '%EMPTY%'
 
  select DISTINCT INVENTORY_ITEM_ID,SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4 ITEM_CODE, DESCRIPTION
 from MTL_SYSTEM_ITEMS_B where INVENTORY_ITEM_ID IN (
817306)

--'FL|F&LB|HOIL|000083' -- 'RM|SCRP|ROLL|000005' -- 'CP|400E|10MM|000052'


select * from ra_interface_lines_all 

/**************************************************************
GET ITEM OPENING STOCK DATA 
***************************************************************/

SELECT B.TRANSACTION_TYPE_NAME , A.* FROM MTL_MATERIAL_TRANSACTIONS A, mtl_transaction_types B
WHERE A.TRANSACTION_TYPE_ID = B.TRANSACTION_TYPE_ID
AND TRUNC(A.TRANSACTION_DATE)  between '31-JAN-2022' and '31-JAN-2022'
AND A.ORGANIZATION_ID=176

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE ORGANIZATION_ID=176 AND TRUNC(TRANSACTION_DATE)  between '31-JAN-2022' and '31-JAN-2022'

select * from mtl_transaction_types where TRANSACTION_TYPE_ID= 161







 --=================================== GET ITEM TRANSACTION  IN VALUATION ================================== 
  
  SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE
--(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
 --AND B.INVENTORY_ITEM_ID IN (243,244)
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   5920526   --5647466


--====================================
-- ITEM NOT TRANSACTED IN A SPECIFIC PERIOD   
--====================================

SELECT DISTINCT MSI.SEGMENT1, MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE
    ,msi.inventory_item_id
    ,Q.ORGANIZATION_ID
    ,Q.QUANTITY
FROM MTL_SYSTEM_ITEMS_B MSI
    JOIN (SELECT INVENTORY_ITEM_ID, ORGANIZATION_ID, SUM(TRANSACTION_QUANTITY) QUANTITY
          FROM MTL_ONHAND_QUANTITIES
          GROUP BY INVENTORY_ITEM_ID, ORGANIZATION_ID) Q ON MSI.INVENTORY_ITEM_ID = Q.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=Q.ORGANIZATION_ID   
WHERE NOT EXISTS (SELECT *
                  FROM MTL_MATERIAL_TRANSACTIONS MMT
                  WHERE MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
                      AND MSI.ORGANIZATION_ID = MMT.ORGANIZATION_ID
                      AND TRUNC(MMT.TRANSACTION_DATE) > SYSDATE - 180)
ORDER BY Q.ORGANIZATION_ID,MSI.SEGMENT1;

--=============================================
-- ALL ITEM LIST FOR MAMUN BOS V2 date: 4-jan-2023
--=============================================

SELECT --B.OPERATING_UNIT,
(SELECT NAME  FROM XLE_ENTITY_PROFILES where LEGAL_ENTITY_ID= b.LEGAL_ENTITY) LE,
GET_OU_NAME_FROM_ID(B.OPERATING_UNIT) OPERATING_UNIT,
A.ORGANIZATION_CODE,ITEM_TYPE, 
 a.INVENTORY_ITEM_ID,FINANCE_CATEGORY,
 (SELECT MAX(TRANSACTION_DATE) FROM MTL_MATERIAL_TRANSACTIONS WHERE INVENTORY_ITEM_ID=a.INVENTORY_ITEM_ID and ORGANIZATION_ID=a.ORGANIZATION_ID ) LAST_TRANS_DATE,
-- ITEM_SEGMENT_1,ITEM_SEGMENT_2,ITEM_SEGMENT_3,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D A, ORG_ORGANIZATION_DEFINITIONS b  -- , MTL_MATERIAL_TRANSACTIONS B
 WHERE 1=1
 --AND a.INVENTORY_ITEM_ID=b.INVENTORY_ITEM_ID
 AND A.ORGANIZATION_ID=b.ORGANIZATION_ID
 and A.ORGANIZATION_CODE NOT IN 'KIM'
-- and  INVENTORY_ITEM_ID = 1036
-- and  ITEM_TYPE = 'REFRACTORY ITEMS' -- LIKE '%REFRACTORY%'
 --AND A.ORGANIZATION_CODE = 'KSM'
 --and  ITEM_DESC = 'SLIDE GATE CUP' 
-- AND  B.OPERATING_UNIT=81
 AND LEGAL_ENTITY=23273
 AND a.STATUS = 'Active'
 


select * from  WBI_XXKBGITEM_MT_D WHERE 

--==================================
-- KOL TRANSACTION ITEM DATA V2 FOR MAMUN BOS
--==================================
SELECT b.transaction_type_name, c.ITEM_TYPE,c.ITEM_GROUP,c.ITEM_SUB_GROUP,c.ITEM_CODE,c.ITEM_DESCRIPTION,a.* FROM MTL_MATERIAL_TRANSACTIONS a , MTL_TRANSACTION_TYPES B, WBI_XXKBGITEM_MT_D c
 WHERE a.transaction_type_id=b.Transaction_type_id
 AND a.INVENTORY_ITEM_ID=c.INVENTORY_ITEM_ID
AND a.ORGANIZATION_ID=c.ORGANIZATION_ID
 AND a.ORGANIZATION_ID= 173  --and  INVENTORY_ITEM_ID =9639  110,701
 AND TRUNC(a.TRANSACTION_DATE)  BETWEEN '01-AUG-2018' and '5-DEC-2023' 

-- KOL TRANSACTION DATA V1
SELECT b.transaction_type_name, a.* FROM MTL_MATERIAL_TRANSACTIONS a , MTL_TRANSACTION_TYPES B
 WHERE a.transaction_type_id=b.Transaction_type_id
 AND a.ORGANIZATION_ID= 173  --and  INVENTORY_ITEM_ID =9639  110,701

select * from ORG_ORGANIZATION_DEFINITIONS where  ORGANIZATION_ID= 173

--=============================================
-- ALL ITEM LIST FOR MAMUN BOS V1 date: 4-jan-2023
--=============================================

SELECT ORGANIZATION_CODE,ITEM_TYPE, 
 INVENTORY_ITEM_ID,FINANCE_CATEGORY,
-- ITEM_SEGMENT_1,ITEM_SEGMENT_2,ITEM_SEGMENT_3,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE 1=1
 and ORGANIZATION_CODE NOT IN 'KIM'
-- and  INVENTORY_ITEM_ID = 1036
 and  ITEM_TYPE LIKE '%REFRACTORY%'
 AND ORGANIZATION_CODE = 'KSM'
 and  ITEM_DESC = 'SLIDE GATE CUP' 



--=============================================
-- ALL ITEM LIST FOR ROBIUL VAI V1 date: 23-jan-2023
--=============================================

SELECT ORGANIZATION_CODE,ITEM_TYPE "Inventory Type", ITEM_GROUP "Inventory Group", ITEM_SUB_GROUP "Inventory Sub Group", 0  "Natural sequence",
 ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0  "Inventory Category-Combine",
 --INVENTORY_ITEM_ID,
 FINANCE_CATEGORY "Fin_Category-Combine",
-- ITEM_SEGMENT_1,ITEM_SEGMENT_2,ITEM_SEGMENT_3,
 -- ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE 1=1
and ORGANIZATION_CODE  IN 'KSM'
 --WHERE  INVENTORY_ITEM_ID = 1036

--=============================================
-- ALL ITEM LIST FOR ROBIUL VAI V1 date: 1-jan-2023
--=============================================

SELECT ORGANIZATION_CODE,ITEM_TYPE , 
 INVENTORY_ITEM_ID,FINANCE_CATEGORY,
-- ITEM_SEGMENT_1,ITEM_SEGMENT_2,ITEM_SEGMENT_3,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE 1=1
and ORGANIZATION_CODE  IN 'KIM'
 --WHERE  INVENTORY_ITEM_ID = 1036
 
 SELECT * FROM WBI_XXKBGITEM_MT_D WHERE ORGANIZATION_CODE  IN 'KIM'


 select * from WBI_XXKBGITEM_MT_D 
 
 
 SELECT * FROM MTL_ITEM_CATEGORIES_V
 
 
 SELECT * FROM  MTL_SYSTEM_ITEMS_FVL  


--=============================================
-- ALL ITEM LIST FOR ROBIUL VAI
--===============================================

SELECT ORGANIZATION_CODE,ITEM_TYPE, 
 INVENTORY_ITEM_ID,FINANCE_CATEGORY,
-- ITEM_SEGMENT_1,ITEM_SEGMENT_2,ITEM_SEGMENT_3,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE 1=1
 --and ORGANIZATION_CODE NOT IN 'KIM'
 --WHERE  INVENTORY_ITEM_ID = 1036
 
 select * from WBI_XXKBGITEM_MT_D  where  INVENTORY_ITEM_ID like'%CYLINDER%'
 
 
 SELECT * FROM MTL_ITEM_CATEGORIES_V
 
 
 SELECT * FROM  MTL_SYSTEM_ITEMS_FVL   -- INVENTORY_ITEM_ID,ORGANIZATION_ID, COST_OF_SALES_ACCOUNT, EXPENSE_ACCOUNT, SALES_ACCOUNT, PRIMARY_UOM_CODE ,SECONDARY_UOM_CODE
 
--=============================================
-- ALL ITEM LIST FOR MD IBRAHIM VAI
--===============================================

SELECT distinct  INVENTORY_ITEM_ID, ORGANIZATION_CODE,ITEM_TYPE, 
 INVENTORY_ITEM_ID,FINANCE_CATEGORY,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE ITEM_DESC LIKE '%CYLINDER%'
 AND ORGANIZATION_CODE = 'KOM'
 ORDER BY ITEM_DESC
 --WHERE  INVENTORY_ITEM_ID = 1036
 
 
 
--=============================================
-- ITEM LIST FOR MAMUN BOS --> FG AND BP ITEM OF KSPL
--===============================================

SELECT ORGANIZATION_CODE,ITEM_TYPE, 
 INVENTORY_ITEM_ID,FINANCE_CATEGORY,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE 1=1
 --and  INVENTORY_ITEM_ID = 1036
-- AND FINANCE_CATEGORY LIKE '%FINISHED GOODS|FINISHED GOODS%'
--  AND FINANCE_CATEGORY LIKE '%BY PRODUCT%WASTAGE|BP SCRAP%'
    AND FINANCE_CATEGORY LIKE '%BY PRODUCT%WASTAGE|BY PRODUCT%WASTAGE%'
     AND ORGANIZATION_CODE = 'KSM'
    UNION ALL    
    SELECT ORGANIZATION_CODE,ITEM_TYPE, 
 INVENTORY_ITEM_ID,FINANCE_CATEGORY,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE 1=1
 --and  INVENTORY_ITEM_ID = 1036
-- AND FINANCE_CATEGORY LIKE '%FINISHED GOODS|FINISHED GOODS%'
  AND FINANCE_CATEGORY LIKE '%BY PRODUCT%WASTAGE|BP SCRAP%'
    --AND FINANCE_CATEGORY LIKE '%BY PRODUCT%WASTAGE|BY PRODUCT%WASTAGE%'
    AND ORGANIZATION_CODE = 'KSM'    
    UNION ALL  
  SELECT ORGANIZATION_CODE,ITEM_TYPE, 
 INVENTORY_ITEM_ID,FINANCE_CATEGORY,
  ITEM_TYPE||'|'||ITEM_GROUP||'|'||ITEM_SUB_GROUP||'|'||0 INVENTORY_CATEGORY,
  ITEM_CODE,
  ITEM_DESC,
  UOM1,UOM2,
  STATUS
 FROM WBI_XXKBGITEM_MT_D 
 WHERE 1=1
 --and  INVENTORY_ITEM_ID = 1036
 AND FINANCE_CATEGORY LIKE '%FINISHED GOODS|FINISHED GOODS%'
  --AND FINANCE_CATEGORY LIKE '%BY PRODUCT%WASTAGE|BP SCRAP%'
    --AND FINANCE_CATEGORY LIKE '%BY PRODUCT%WASTAGE|BY PRODUCT%WASTAGE%'
    AND ORGANIZATION_CODE = 'KPM'
  
 
 
 
 --=====================================================
 --ALL BRANDING ITEMS FOR MAMUN BOS
 --=====================================================
 
 select  DISTINCT INVENTORY_ITEM_ID,  ITEM_TYPE, ITEM_GROUP,FINANCE_CATEGORY,ITEM_CODE,ITEM_DESC,UOM1,STATUS
   FROM WBI_XXKBGITEM_MT_D WHERE ITEM_GROUP = 'BRANDING ITEMS'   
 
 
 --===========================================
 --TO GET ALL ATTRIBUTES OF A SPECIFIC ITEM
 --===============================================
 SELECT 
ROW_ID, INVENTORY_ITEM_ID, ORGANIZATION_ID, CONCATENATED_SEGMENTS, PADDED_CONCATENATED_SEGMENTS, EXCLUDE_FROM_BUDGET_FLAG, DRP_PLANNED_FLAG, CRITICAL_COMPONENT_FLAG,
 CONTINOUS_TRANSFER, CONVERGENCE, DIVERGENCE, CHILD_LOT_FLAG, CHILD_LOT_VALIDATION_FLAG, COPY_LOT_ATTRIBUTE_FLAG, GRADE_CONTROL_FLAG, HAZARDOUS_MATERIAL_FLAG, LOT_DIVISIBLE_FLAG,
  PROCESS_COSTING_ENABLED_FLAG, PROCESS_EXECUTION_ENABLED_FLAG, PROCESS_QUALITY_ENABLED_FLAG, RECIPE_ENABLED_FLAG, PREPOSITION_POINT, REPAIR_PROGRAM, OUTSOURCED_ASSEMBLY, 
  GDSN_OUTBOUND_ENABLED_FLAG, SERIAL_TAGGING_FLAG, IB_ITEM_TRACKING_LEVEL, LAST_UPDATE_DATE, LAST_UPDATED_BY, CREATION_DATE, CREATED_BY, LAST_UPDATE_LOGIN, SUMMARY_FLAG, 
  ENABLED_FLAG, DESCRIPTION, SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, PURCHASING_ITEM_FLAG, SHIPPABLE_ITEM_FLAG, CUSTOMER_ORDER_FLAG, INTERNAL_ORDER_FLAG, SERVICE_ITEM_FLAG, 
  INVENTORY_ITEM_FLAG, ENG_ITEM_FLAG, INVENTORY_ASSET_FLAG, PURCHASING_ENABLED_FLAG, CUSTOMER_ORDER_ENABLED_FLAG, INTERNAL_ORDER_ENABLED_FLAG, SO_TRANSACTIONS_FLAG,
   MTL_TRANSACTIONS_ENABLED_FLAG, STOCK_ENABLED_FLAG, BOM_ENABLED_FLAG, BUILD_IN_WIP_FLAG, REVISION_QTY_CONTROL_CODE, CATALOG_STATUS_FLAG, RETURNABLE_FLAG, 
   COLLATERAL_FLAG, QTY_RCV_EXCEPTION_CODE, ALLOW_ITEM_DESC_UPDATE_FLAG, INSPECTION_REQUIRED_FLAG, RECEIPT_REQUIRED_FLAG, RFQ_REQUIRED_FLAG, LIST_PRICE_PER_UNIT,
    ALLOW_SUBSTITUTE_RECEIPTS_FLAG, ALLOW_UNORDERED_RECEIPTS_FLAG, RECEIVING_ROUTING_ID, LOT_CONTROL_CODE, SHELF_LIFE_CODE, SHELF_LIFE_DAYS, SERIAL_NUMBER_CONTROL_CODE, 
    EXPENSE_ACCOUNT, RESTRICT_SUBINVENTORIES_CODE, RESTRICT_LOCATORS_CODE, LOCATION_CONTROL_CODE, PLANNING_TIME_FENCE_CODE, LEAD_TIME_LOT_SIZE, MRP_CALCULATE_ATP_FLAG,
     ACCEPTABLE_RATE_INCREASE, ACCEPTABLE_RATE_DECREASE, PLANNING_TIME_FENCE_DAYS, REPETITIVE_PLANNING_FLAG, BOM_ITEM_TYPE, PICK_COMPONENTS_FLAG, REPLENISH_TO_ORDER_FLAG,
      ATP_COMPONENTS_FLAG, ATP_FLAG, WIP_SUPPLY_TYPE, PRIMARY_UOM_CODE, PRIMARY_UNIT_OF_MEASURE, ALLOWED_UNITS_LOOKUP_CODE, COST_OF_SALES_ACCOUNT, SALES_ACCOUNT, 
      DEFAULT_INCLUDE_IN_ROLLUP_FLAG, INVENTORY_ITEM_STATUS_CODE, INVENTORY_PLANNING_CODE, PLANNING_MAKE_BUY_CODE, ROUNDING_CONTROL_TYPE, POSTPROCESSING_LEAD_TIME,
       MRP_SAFETY_STOCK_CODE, RESERVABLE_TYPE, VENDOR_WARRANTY_FLAG, SERVICEABLE_COMPONENT_FLAG, SERVICEABLE_PRODUCT_FLAG, PREVENTIVE_MAINTENANCE_FLAG, PRORATE_SERVICE_FLAG,
        INVOICEABLE_ITEM_FLAG, INVOICE_ENABLED_FLAG, MUST_USE_APPROVED_VENDOR_FLAG, REQUEST_ID, PROGRAM_APPLICATION_ID, PROGRAM_ID, PROGRAM_UPDATE_DATE, OUTSIDE_OPERATION_FLAG, 
        COSTING_ENABLED_FLAG, AUTO_CREATED_CONFIG_FLAG, CYCLE_COUNT_ENABLED_FLAG, ITEM_TYPE, SHIP_MODEL_COMPLETE_FLAG, MRP_PLANNING_CODE, RETURN_INSPECTION_REQUIREMENT, 
        ATO_FORECAST_CONTROL, CONTAINER_ITEM_FLAG, VEHICLE_ITEM_FLAG, EFFECTIVITY_CONTROL, CHECK_SHORTAGES_FLAG, EQUIPMENT_TYPE, EVENT_FLAG, ELECTRONIC_FLAG, DOWNLOADABLE_FLAG, 
        WEB_STATUS, INDIVISIBLE_FLAG, BULK_PICKED_FLAG, LOT_STATUS_ENABLED, SERIAL_STATUS_ENABLED, LOT_SPLIT_ENABLED, LOT_MERGE_ENABLED, DUAL_UOM_CONTROL, DUAL_UOM_DEVIATION_HIGH, 
        DUAL_UOM_DEVIATION_LOW, SERV_BILLING_ENABLED_FLAG, LOT_TRANSLATE_ENABLED, DEFAULT_SO_SOURCE_TYPE, CREATE_SUPPLY_FLAG, OBJECT_VERSION_NUMBER, TRACKING_QUANTITY_IND, 
        ONT_PRICING_QTY_SOURCE, CONSIGNED_FLAG, ASN_AUTOEXPIRE_FLAG, VMI_FORECAST_TYPE
FROM MTL_SYSTEM_ITEMS_KFV 
where inventory_item_id=604 
--and ORGANIZATION_ID =121


--=======================================
-- GET DUPLICATE ITEM CATEGORY CODE
--========================================

SELECT category_set_name, category_concat_segments, COUNT (*)
FROM mtl_category_set_valid_cats_v
WHERE (category_set_id = 1)
GROUP BY category_set_name, category_concat_segments
HAVING COUNT (*) > 1
ORDER BY category_concat_segments




--==============================================================
--DISPLAY ALL CATEGORIES THAT THE ITEM BELONGS
--===============================================================


SELECT micv.CATEGORY_SET_NAME "Category Set",
micv.CATEGORY_SET_ID "Category Set ID",
decode( micv.CONTROL_LEVEL,
1, 'Master',
2, 'Org',
'Other') "Control Level",
micv.CATEGORY_ID "Category ID",
micv.CATEGORY_CONCAT_SEGS "Category"
FROM
MTL_ITEM_CATEGORIES_V micv

--======================================
--GET ONHAND QTY WITH ORANIZATION ID, ITEM CODE, QUANTITY 
--FOR ROBIUL VAI 23-JAN-223
--======================================
SELECT moq.organization_id,INVORG_NAME_FROM_ID (moq.organization_id) org_code,
(SELECT ( msib.segment1|| '|'|| msib.segment2|| '|'|| msib.segment3|| '|'|| msib.segment4)
FROM mtl_system_items_b msib
WHERE msib.inventory_item_id = moq.inventory_item_id
AND msib.organization_id = moq.organization_id) "Item Code",
(SELECT description
FROM mtl_system_items_b msib
WHERE msib.inventory_item_id =
moq.inventory_item_id
AND msib.organization_id = moq.organization_id)
"item Description",
SUM (moq.transaction_quantity) onhandqty,
b.PRIMARY_UOM_CODE
FROM mtl_onhand_quantities moq , mtl_system_items_b b
where moq.ORGANIZATION_ID=b.ORGANIZATION_ID
AND moq.inventory_item_id = b.inventory_item_id
and 1=1 --INVORG_NAME_FROM_ID (organization_id) like '%D'
AND moq.ORGANIZATION_ID IN(
281,
402,
144,
172,
159,
162,
166,
175,
178,
180,
182,
464
)
GROUP BY moq.organization_id, (moq.inventory_item_id),b.PRIMARY_UOM_CODE


SELECT * FROm mtl_onhand_quantities


SELECT * FROM mtl_system_items_b where organization_id= 176

SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_NAME like '%Deep Sea%'

--================
-- Onhand Quantity For Rabiul Vai 
--===============

SELECT * FROm MTL_ONHAND_QUANTITIES

--===================
-- ITEM STOCK ALL IO WISE
--FOR RABIUL VAI
-----------------------------------------

SELECT DISTINCT
WXMD.ITEM_TYPE,
--MOQ.ORGANIZATION_ID INV_ORGS,
----XXGET_OU_NAME_FROM_ID(MOQ.ORGANIZATION_ID) OU,
XXGET_OU_NAME_FROM_INV_ID(WXMD.ORGANIZATION_code) OU,
WXMD.ITEM_GROUP,
WXMD.ITEM_SUB_GROUP,
WXMD.FINANCE_CATEGORY,
NVL((SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG_ID),'KABIR GROUP') ORGANIZATION_NAME,
NVL((SELECT OPERATING_UNIT_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORG_ID),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') ORG_ADD,
---WXMD.ORGANIZATION_NAME,
---(SELECT address_line_1||','|| address_line_2||','|| address_line_3||','|| town_or_city||','|| country  FROM hr_locations  HL ,hr_all_organization_units HOU
----WHERE HL.location_id = HOU.location_id AND HOU.organization_id =MOQ.ORGANIZATION_ID) ORG_ADD,
WXMD.ORGANIZATION_code,
MOQ.ORGANIZATION_ID,
WXMD.ITEM_CODE,
WXMD.ITEM_DESC,
WXMD.UOM1 UOM,
NVL (XX_INV_PKG.XXGET_INV_OPENING_STOCK (MOQ.INVENTORY_ITEM_ID,NVL(:P_ORG_ID,MOQ.ORGANIZATION_ID), NULL, NULL, :P_DATE),0) OPENING_QTY ,
---NVL (XXGET_INV_OPENING_STOCK (MOQ.INVENTORY_ITEM_ID,MOQ.ORGANIZATION_ID,NULL, NULL, :P_DATE),0) GLOBAL_STOCK,
NVL (XX_INV_PKG.XXGET_INV_OPENING_STOCK (MOQ.INVENTORY_ITEM_ID,NULL,NULL, NULL, :P_DATE),0) GLOBAL_STOCK,
:P_ITEM_TYPE  PITEM_TYPE,
:P_ITEM_GROU PITEM_GROUP,
:P_ITEM_SUB_GROUP PITEM_SUB_GROUP,
:P_FINANCE_CATEGORY PFINANCE_CATEGORY
FROM WBI_XXKBGITEM_MT_D WXMD,
MTL_ONHAND_QUANTITIES MOQ
WHERE     WXMD.INVENTORY_ITEM_ID= MOQ.INVENTORY_ITEM_ID(+) 
AND WXMD.ORGANIZATION_ID= MOQ.ORGANIZATION_ID (+)     
---AND   WXMD.ORGANIZATION_ID=:P_ORG_ID 
--AND   WXMD.ORGANIZATION_ID=NVL(:P_ORG_ID,WXMD.ORGANIZATION_ID)
AND WXMD.ORGANIZATION_code LIKE '%Deep%Sea%'
--AND WXMD.ITEM_TYPE=NVL(:P_ITEM_TYPE,WXMD.ITEM_TYPE)
--AND  WXMD.ITEM_GROUP=NVL(:P_ITEM_GROU,WXMD.ITEM_GROUP)
--AND  WXMD.ITEM_SUB_GROUP=NVL(:P_ITEM_SUB_GROUP,WXMD.ITEM_SUB_GROUP)
AND  WXMD.INVENTORY_ITEM_ID NOT IN(19851,19536,2479,17544)
--AND NVL(WXMD.FINANCE_CATEGORY,'XX')=NVL(:P_FINANCE_CATEGORY,NVL(WXMD.FINANCE_CATEGORY,'XX'))
--AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE)


select * from ORG_ORGANIZATION_DEFINITIONS