-- PARAMETER: :P_PERIOD_CODE= JUL-19
-- :P_OU= 104
-- :P_ORG= KBD
--===================================

SELECT 
      A.OU,
       A.ORGANIZATION_CODE,
       A.VENDOR_NAME,
        A.PO_NUMBER,
        AI.INVOICE_NUM,
        DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
         (SELECT DISTINCT CONCATENATED_SEGMENTS
           FROM MTL_SYSTEM_ITEMS_KFV
           WHERE INVENTORY_ITEM_ID = AIL.INVENTORY_ITEM_ID)
           ITEM_CODE,
         AD.ACCOUNTING_DATE GL_DATE,
      AI.DESCRIPTION,
       AD.LINE_TYPE_LOOKUP_CODE,
       RECEIPT_NUMBER,
        RECEIPT_DATE,
       TRUNC (A.CREATION_DATE) RECEIPT_CREATION_DATE,
           PO_NUMBER,
        LC_NUMBER,
       (CASE WHEN AD.LINE_TYPE_LOOKUP_CODE IN ('ACCRUAL','ERV') THEN 
       (SELECT DISTINCT CONCATENATED_SEGMENTS
        FROM MTL_SYSTEM_ITEMS_KFV
         WHERE INVENTORY_ITEM_ID = AIL.INVENTORY_ITEM_ID)
        ELSE        
       DECODE (PE.NAME, NULL, '', PE.NAME) END) LC_CHARGE_TYPE,
       NVL (AD.BASE_AMOUNT, AD.AMOUNT) AMOUNT, :P_PERIOD_CODE
  FROM XX_PO_RECEIPT A,
       AP_INVOICE_LINES_ALL AIL,
       AP_INVOICES_ALL AI,
       AP_INVOICE_DISTRIBUTIONS_ALL AD,
       PON_PRICE_ELEMENT_TYPES_TL PE
 WHERE     A.PO_HEADER_ID = AIL.PO_HEADER_ID
       AND A.TRANSACTION_ID = AIL.RCV_TRANSACTION_ID
       AND AI.INVOICE_ID = AIL.INVOICE_ID
       AND A.ORG_ID = AI.ORG_ID
       AND AI.INVOICE_ID = AD.INVOICE_ID
       ---AND NVL (AD.REVERSAL_FLAG, 'N') <> 'Y'
       AND AI.CANCELLED_DATE IS NULL
       AND UPPER(A.RECEIPT_DATE)=:P_PERIOD_CODE
       --=:P_PERIOD-- ('Sep-18','Oct-18')
       AND ai.org_id =:P_OU
       AND AD.INVOICE_LINE_NUMBER = LINE_NUMBER
       AND AIL.COST_FACTOR_ID = PE.PRICE_ELEMENT_TYPE_ID(+)
       AND A.ORGANIZATION_CODE=:P_ORG
     --  AND A.ORGANIZATION_ID=:P_ORG
       --AND B.ACCOUNTING_DATE NOT BETWEEN :P_DATE_FROM AND :P_DATE_TO_ONE
       --AND AD.ACCOUNTING_DATE NOT BETWEEN '01-Oct-2018' and '31-Oct-2018'
       --and GET_GL_CODE_FROM_CCID (AD.DIST_CODE_COMBINATION_ID)='2010201'
       --AND B.LINE_TYPE_LOOKUP_CODE='MISCELLANEOUS'
       --AND INVOICE_NUM='KBD-80000489'
       --and DOC_SEQUENCE_VALUE='190001534'
     --  AND RECEIPT_NUMBER = 80000240
ORDER BY A.PO_HEADER_ID, AI.INVOICE_ID, AIL.LINE_NUMBER


