
-- INV_TRANS FOR CONSUMPTION REPORT

--(

SELECT CASE WHEN TRANSACTION_TYPE_NAME = 'HMS Issue Against By Product (KBIL)' and DISPLAYED_LINE_NUMBER >2  then A.TRANSACTION_VALUE/2 ELSE  A.TRANSACTION_VALUE END TRANSACTION_VALUE,
 E.AE_LINE_NUM, DISPLAYED_LINE_NUMBER ,TO_CHAR(TRANSACTION_DATE,'MON-YY') PERIOD_CODE, A.LEDGER_ID, (SELECT DISTINCT BAL_SEG_NAME FROM XX_INV_ORG_VW WHERE LEDGER_ID=A.LEDGER_ID) COMPANY_NAME,
C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.OPERATING_UNIT, 
XX_GET_ACCT_FLEX_SEG_DESC (1, F.SEGMENT1) COMPANY,
--XX_GET_ACCT_FLEX_SEG_DESC (2, F.SEGMENT2) OPERATING_UNIT,
XX_GET_ACCT_FLEX_SEG_DESC (3, F.SEGMENT3) COST_CENTER, 
--(SELECT DISTINCT XX_GET_ACCT_FLEX_SEG_DESC (3, SEGMENT3) COST_CENTER FROM GL_CODE_COMBINATIONS_KFV WHERE CODE_COMBINATION_ID=E.CODE_COMBINATION_ID) COST_CENTER,
A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,
(SELECT DESCRIPTION FROM MTL_SYSTEM_ITEMS_B WHERE INVENTORY_ITEM_ID=A.INVENTORY_ITEM_ID AND ORGANIZATION_ID=A.ORGANIZATION_ID) ITEM_DESC,
(SELECT PRIMARY_UOM_CODE FROM MTL_SYSTEM_ITEMS_B WHERE INVENTORY_ITEM_ID=A.INVENTORY_ITEM_ID AND ORGANIZATION_ID=A.ORGANIZATION_ID) UOM,
 A.EVENT_TYPE_CODE
, a.transaction_id,
G.TRANSACTION_TYPE_ID,
G.TRANSACTION_TYPE_NAME,
--DECODE (G.TRANSACTION_TYPE_NAME , 'HMS Issue Against By Product (KBIL)' ,  E.AE_LINE_NUM , G.TRANSACTION_TYPE_NAME) TRANSACTION_TYPE_NAME ,
--CASE WHEN TRANSACTION_TYPE_NAME = 'HMS Issue Against By Product (KBIL)' and AE_LINE_NUM  >2  THEN  E.DISPLAYED_LINE_NUMBER   ELSE G.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,
--CASE WHEN G.TRANSACTION_TYPE_NAME = 'HMS Issue Against By Product (KBIL)'  THEN  E.AE_LINE_NUM  ELSE G.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,
D.JE_CATEGORY_NAME,E.ACCOUNTING_CLASS_CODE,D.AE_HEADER_ID,XX_AP_PKG.GET_ACCOUNT_DESC_FROM_CCID (E.CODE_COMBINATION_ID) ACCOUNT_NAME,
XX_AP_PKG.GET_SUB_ACCOUNT_DESC_FROM_CCID(TO_NUMBER(E.CODE_COMBINATION_ID)) SUB_ACCOUNT,
TRANSACTION_QUANTITY,
--CASE WHEN TRANSACTION_TYPE_NAME = 'HMS Issue Against By Product (KBIL)' then A.TRANSACTION_VALUE END  TRANSACTION_VALUE,
A.TRANSACTION_VALUE,
E.ACCOUNTED_DR,E.ACCOUNTED_CR,F.CONCATENATED_SEGMENTS ACCOUNTING_CODE
FROM GMF_XLA_EXTRACT_HEADERS A,MTL_SYSTEM_ITEMS_B B,ORG_ORGANIZATION_DEFINITIONS C,XLA_AE_HEADERS D,XLA_AE_LINES E,GL_CODE_COMBINATIONS_KFV F,MTL_TRANSACTION_TYPES G
WHERE A.INVENTORY_ITEM_ID=B.INVENTORY_ITEM_ID(+)
AND A.ORGANIZATION_ID=B.ORGANIZATION_ID(+) 
AND A.ORGANIZATION_ID=C.ORGANIZATION_ID 
AND A.TRANSACTION_TYPE_ID=G.TRANSACTION_TYPE_ID(+)
AND (NVL (e.ACCOUNTED_DR, 0)>0.49 or NVL (ACCOUNTED_CR, 0)>0.49 ) 
AND A.EVENT_ID=D.EVENT_ID 
AND D.AE_HEADER_ID=E.AE_HEADER_ID (+)
AND E.CODE_COMBINATION_ID=F.CODE_COMBINATION_ID(+) 
AND TO_CHAR(TRANSACTION_DATE,'MON-YY')=:P_PERIOD_CODE
and A.OPERATING_UNIT= NVL(:P_OPERATING_UNIT,A.OPERATING_UNIT)
AND A.LEDGER_ID=:P_LEDGER_ID AND A.ORGANIZATION_ID=NVL(:P_ORGANIZATION_ID,A.ORGANIZATION_ID)
 AND A.INVENTORY_ITEM_ID=NVL(:P_INVENTORY_ITEM_ID,A.INVENTORY_ITEM_ID)
 --AND  CASE  WHEN E.DISPLAYED_LINE_NUMBER >2 THEN E.DISPLAYED_LINE_NUMBER   ELSE   E.DISPLAYED_LINE_NUMBER END
-- AND (SELECT AE_LINE_NUM  FROM XLA_AE_LINES WHERE AE_LINE_NUM >=2 ) 
 --AND (CASE WHEN DISPLAYED_LINE_NUMBER > 2 THEN DISPLAYED_LINE_NUMBER  ELSE  0   END )
and a.transaction_id in (1631266)   --,1631266, 1631270,1631220)
--) INV_TRANS



select * from GMF_XLA_EXTRACT_HEADERS A , MTL_SYSTEM_ITEMS_B B,ORG_ORGANIZATION_DEFINITIONS C, XLA_AE_HEADERS D, XLA_AE_LINES E, GL_CODE_COMBINATIONS_KFV F, MTL_TRANSACTION_TYPES G
WHERE 1=1
AND A.INVENTORY_ITEM_ID=B.INVENTORY_ITEM_ID(+)
AND A.ORGANIZATION_ID=B.ORGANIZATION_ID(+) 
AND A.ORGANIZATION_ID=C.ORGANIZATION_ID 
AND A.EVENT_ID=D.EVENT_ID 
AND D.AE_HEADER_ID=E.AE_HEADER_ID(+)
AND E.CODE_COMBINATION_ID=F.CODE_COMBINATION_ID(+)
AND A.TRANSACTION_TYPE_ID=G.TRANSACTION_TYPE_ID(+)
and a.transaction_id in (1631266, 1631270,1631220)
OR DISPLAYED_LINE_NUMBER IN (4,3)
AND TO_CHAR(TRANSACTION_DATE,'MON-YY')=:P_PERIOD_CODE
--AND A.LEDGER_ID=:P_LEDGER_ID AND A.ORGANIZATION_ID=NVL(:P_ORGANIZATION_ID,A.ORGANIZATION_ID)


select * from ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE = 'KBA'


select * from GMF_XLA_EXTRACT_HEADERS WHERE TRANSACTION_ID IN (
1631266,
1631270,
1631220
)


select * from XLA_AE_HEADERS WHERE EVENT_ID IN (
5518492,
5517930,
5518556
)



select * from XLA_AE_LINES WHERE AE_HEADER_ID IN (
47884911,
47890274,
47890280
)


SELECT * FROM XLA_DISTRIBUTION_LINKS WHERE AE_HEADER_ID IN (
47842064,
47847424,
47847430
)

select * from GMF_XLA_EXTRACT_HEADERS WHERE TRANSACTION_ID = 862490 

select * from XLA_AE_HEADERS WHERE EVENT_ID IN (
5732654,
5520469,
5520859
)

select * from XLA_AE_LINES WHERE AE_HEADER_ID IN (
47836418,
47847171,
47815423
)