--=================================================
--DRAFT ACCOUNTING V2.1 -- REARRENGE COLUNMN HEADING   
--=================================================

SELECT INV_TRANS.ORGANIZATION_CODE ORG, INV_TRANS.GRN,INV_TRANS.TXN_ID,INV_TRANS.XLA_HEADER_ID,FIN_CAT.MEJOR_FIN_CAT,INV_TRANS.ITEM_CODE,INV_TRANS.EVENT_TYPE_CODE, 
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END  TRX_TYPE_NAME,
0 OP_QTY, 0 OP_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,12,44,18,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003) THEN INV_TRANS.TRANSACTION_VALUE 
                 WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) THEN INV_TRANS.TRANSACTION_VALUE -----INV_TRANS.ACCOUNTED_DR 
                 WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61)  THEN INV_TRANS.ACCOUNTED_DR
                 WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12)  THEN INV_TRANS.ACCOUNTED_DR 
                  WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111  AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE    
                  WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222  AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE  
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
                  SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,35,36,42,43,15,21,63,101,103,104,106,107,111,120,10008,140,71,200,240,241,260,261,52) THEN INV_TRANS.TRANSACTION_QUANTITY 
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (33) AND NVL(INV_TRANS.ACCOUNTED_DR,1) > 0 THEN 0 
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (33) AND NVL(INV_TRANS.ACCOUNTED_DR,1) =  0 THEN 0 
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (62) AND NVL(INV_TRANS.ACCOUNTED_DR,0) >  0 THEN INV_TRANS.TRANSACTION_QUANTITY
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (62) AND NVL(INV_TRANS.ACCOUNTED_CR,0) > 0 THEN INV_TRANS.TRANSACTION_QUANTITY
                  ELSE 0 END) ISSUE_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,35,36,42,43,21,63,101,103,104,106,107,111,120,10008,140,71,200,240,241,260,261,52) THEN INV_TRANS.TRANSACTION_VALUE 
                 WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (15) THEN INV_TRANS.ACCOUNTED_DR   
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (33) AND NVL(INV_TRANS.ACCOUNTED_DR,0) > 0 THEN INV_TRANS.ACCOUNTED_DR
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (33) AND NVL(INV_TRANS.ACCOUNTED_DR,0) =  0 THEN INV_TRANS.TRANSACTION_VALUE 
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (62) AND NVL(INV_TRANS.ACCOUNTED_DR,0) >  0 THEN INV_TRANS.TRANSACTION_VALUE
                  WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (62) AND NVL(INV_TRANS.ACCOUNTED_CR,0) > 0 THEN INV_TRANS.TRANSACTION_VALUE
                  ELSE 0 END) ISSUE_VAL,
                  SUM(nvl(INV_TRANS.TRANSACTION_QUANTITY,0)) TRANS_QTY, 
INV_TRANS.PRIMARY_UOM_CODE UOM, 
SUM(nvl(INV_TRANS.TRANSACTION_VALUE,0)) TRANS_VAL,
INV_TRANS.ACCOUNT_NAME,
INV_TRANS.SUB_ACCOUNT,
INV_TRANS.je_category_name,
INV_TRANS.accounting_class_code,
SUM(INV_TRANS.ACCOUNTED_DR) DR,SUM(INV_TRANS.ACCOUNTED_CR) CR ,
INV_TRANS.ACCOUNTING_CODE,
FIN_CAT.FIN_CAT,
INV_TRANS.ORGANIZATION_ID ORG_ID,INV_TRANS.LEDGER_ID LE_ID, INV_TRANS.OPERATING_UNIT OU, INV_TRANS.INVENTORY_ITEM_ID ITEM_ID,
INV_TRANS.TRANSACTION_TYPE_ID TRX_TYPE_ID
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,
(CASE when a.transaction_type_id IN (18,36) then NVL(( Select rsh.RECEIPT_NUM  from rcv_shipment_headers rsh , rcv_shipment_lines rsl,rcv_transactions rt,mtl_material_transactions mmt
where rsh.shipment_header_id=rsl.shipment_header_id
and rsl.shipment_header_id=rt.shipment_header_id
and rsl.SHIPMENT_LINE_ID=rt.SHIPMENT_LINE_ID
and rt.transaction_id=mmt.RCV_TRANSACTION_ID
--and rt.transaction_type='DELIVER'
and mmt.transaction_Id=a.transaction_Id
),0)
when a.transaction_type_id=33 then 
NVL(( Select SHIPMENT_NUMBER  from mtl_material_transactions where 
transaction_Id=a.transaction_Id
),0)
when a.transaction_type_id in (63,103,104,107,120,200,106) then 
NVL(( select MTRH.REQUEST_NUMBER from MTL_TXN_REQUEST_HEADERS MTRH,MTL_TXN_REQUEST_LINES MTRL,MTL_MATERIAL_TRANSACTIONS MMT
where MTRH.header_id=MTRL.header_id
and MTRL.LINE_ID=MMT.TRX_SOURCE_LINE_ID
and MMT.transaction_id=a.transaction_id
),0)
when a.transaction_type_id=62 and a.event_type_code='FOB_SHIP_SENDER_SHIP_NO_TP' then 
NVL(( Select SHIPMENT_NUMBER  from mtl_material_transactions where 
transaction_Id=a.transaction_Id
),0)
when a.transaction_type_id=62 and a.event_type_code='FOB_SHIP_RECIPIENT_SHIP_NO_TP' then 
NVL(( Select rmv.RECEIPT_NUM  from rcv_msh_v rmv ,mtl_material_transactions mmt
where rmv.SHIPMENT_NUM=mmt.SHIPMENT_NUMBER
and mmt.transaction_Id=a.transaction_Id
),0)
when a.transaction_type_id=21 and a.event_type_code='FOB_SHIP_SENDER_SHIP_NO_TP' then 
NVL(( Select SHIPMENT_NUMBER  from mtl_material_transactions where 
transaction_Id=a.transaction_Id
),0)
when a.transaction_type_id=21 and a.event_type_code='FOB_SHIP_RECIPIENT_SHIP_NO_TP' then 
NVL(( Select rmv.RECEIPT_NUM  from rcv_msh_v rmv ,mtl_material_transactions mmt
where rmv.SHIPMENT_NUM=mmt.SHIPMENT_NUMBER
and mmt.transaction_Id=a.transaction_Id
),0)
when a.transaction_type_id=62 and a.event_type_code='FOB_SHIP_RECIPIENT_SHIP_TP' then 
NVL(( Select rmv.RECEIPT_NUM  from rcv_msh_v rmv ,mtl_material_transactions mmt
where rmv.SHIPMENT_NUM=mmt.SHIPMENT_NUMBER
and mmt.transaction_Id=a.transaction_Id),0)
when a.transaction_type_id in (21,62) and a.event_type_code='FOB_SHIP_SENDER_SHIP_TP' then 
NVL(( Select SHIPMENT_NUMBER  from mtl_material_transactions where 
transaction_Id=a.transaction_Id
),0)
when a.transaction_type_id in (61,12) and a.event_type_code='FOB_SHIP_RECIPIENT_RCPT' then 
NVL(( Select rmv.RECEIPT_NUM  from rcv_msh_v rmv ,mtl_material_transactions mmt
where rmv.SHIPMENT_NUM=mmt.SHIPMENT_NUMBER
and mmt.transaction_Id=a.transaction_Id),0)
when a.transaction_type_id=10008 and a.event_type_code='COGS_RECOGNITION' then 
NVL(( Select TRANSACTION_SOURCE_NAME  from mtl_material_transactions where 
transaction_Id=a.transaction_Id
),0)
when  a.event_type_code IN ('RECEIVE','DELIVER_EXPENSE','RET_TO_VENDOR','LC_ADJUST_DELIVER','LC_ADJUST_RECEIVE','LC_ADJUST_VALUATION') then 
NVL((Select rsh.RECEIPT_NUM  from rcv_shipment_headers rsh , rcv_shipment_lines rsl,rcv_transactions rt
where rsh.shipment_header_id=rsl.shipment_header_id
and rsl.shipment_header_id=rt.shipment_header_id
and rsl.SHIPMENT_LINE_ID=rt.SHIPMENT_LINE_ID
--and rt.transaction_type='RECEIVE'
and a.SOURCE_LINE_ID=rt.transaction_Id
and a.ENTITY_CODE='PURCHASING'),0)
when a.transaction_type_id in(44,35,1002,1003,17,43) then 
NVL(( Select gbh.batch_no  from gme_batch_header gbh ,mtl_material_transactions mmt
where gbh.BATCH_ID=mmt.TRANSACTION_SOURCE_ID
and gbh.organization_id=mmt.organization_id
and mmt.transaction_Id=a.transaction_Id),0)
else NULL
end ) GRN, C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.LEDGER_ID, A.OPERATING_UNIT,a.TRANSACTION_ID TXN_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,
d.je_category_name,d.AE_HEADER_ID XLA_HEADER_ID,e.accounting_class_code,d.ae_header_id,XX_AP_PKG.GET_ACCOUNT_DESC_FROM_CCID (e.CODE_COMBINATION_ID) ACCOUNT_NAME,XX_AP_PKG.GET_SUB_ACCOUNT_DESC_FROM_CCID(TO_NUMBER(e.CODE_COMBINATION_ID)) SUB_ACCOUNT,
TRANSACTION_QUANTITY, PRIMARY_UOM_CODE, TRANSACTION_VALUE,SUM(NVL(e.accounted_dr,0))accounted_dr ,SUM(NVL(e.accounted_cr,0))accounted_cr ,f.concatenated_segments accounting_code
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,xla_ae_headers d,xla_ae_lines e,gl_code_combinations_kfv f,mtl_transaction_types g
WHERE 1= 1 --a.transaction_id=
--and a.transaction_id IN (1717278)  -- 5759855 -- 5647504
and a.inventory_item_id=b.inventory_item_id(+) and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id  and a.transaction_type_id=g.transaction_type_id(+)
and a.event_id=d.event_id and d.ae_header_id=e.ae_header_id and e.code_combination_id=f.code_combination_id
AND (NVL (e.ACCOUNTED_DR, 0)>0.49 or NVL (e.ACCOUNTED_CR, 0)>0.49 )   -- Added  for Transaction id  4911717,4911442,4911409,4911720 , 4878396,4906916  qty shows double
and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE and a.ledger_id=:P_LEDGER_ID
group by 
--------------- 
transaction_date,
a.event_type_code , C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.LEDGER_ID, A.OPERATING_UNIT,a.TRANSACTION_ID ,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ,a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,a.transaction_type_id,
d.je_category_name,d.AE_HEADER_ID ,e.accounting_class_code,d.ae_header_id,XX_AP_PKG.GET_ACCOUNT_DESC_FROM_CCID (e.CODE_COMBINATION_ID) ,XX_AP_PKG.GET_SUB_ACCOUNT_DESC_FROM_CCID(TO_NUMBER(e.CODE_COMBINATION_ID)) ,
TRANSACTION_QUANTITY, PRIMARY_UOM_CODE, TRANSACTION_VALUE ,f.concatenated_segments , a.SOURCE_LINE_ID, a.ENTITY_CODE
) INV_TRANS 
LEFT OUTER JOIN  (SELECT  MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT 
                                       FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE  MIC.CATEGORY_ID=MC.CATEGORY_ID  AND STRUCTURE_ID=50408) FIN_CAT 
                                                ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND  FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PRIMARY_UOM_CODE,GRN,INV_TRANS.TXN_ID,INV_TRANS.XLA_HEADER_ID,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.LEDGER_ID, INV_TRANS.OPERATING_UNIT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.ACCOUNT_NAME,INV_TRANS.SUB_ACCOUNT,INV_TRANS.ACCOUNTING_CODE,INV_TRANS.TRANSACTION_TYPE_ID,INV_TRANS.je_category_name,INV_TRANS.accounting_class_code


--==========================================================================================


  --Inventory Valuation V4    DATE: 31-AUG-20121
  ---------------------------------------------------------------
  
SELECT MEJOR_FIN_CAT,PERIOD_CODE,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE,
 SUM(NVL(OPN_QTY,0)) OPN_QTY, SUM(NVL(OPN_VAL,0)) OPN_VAL, SUM(NVL(RCV_QTY,0)) RCV_QTY, SUM(NVL(RCV_VAL,0)) RCV_VAL,
SUM(NVL(ISU_QTY,0)) ISU_QTY, SUM(NVL(ISU_VAL,0)) ISU_VAL, SUM(NVL(CLS_QTY,0)) CLS_QTY, SUM(NVL(CLS_VAL,0)) CLS_VAL
FROM
(SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE,
----SUM(TRANS_VAL),SUM(TRANS_QTY),
SUM(OPN_QTY) OPN_QTY,SUM(OPN_VAL) OPN_VAL,
SUM(RCV_QTY) RCV_QTY,SUM(RCV_VAL) RCV_VAL,SUM(ISU_QTY) ISU_QTY,SUM(ISU_VAL) ISU_VAL ,SUM(CLS_QTY) CLS_QTY,SUM(CLS_VAL) CLS_VAL FROM
(
SELECT PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE
-----,SUM(nvl(TRANS_VAL,0)) TRANS_VAL,SUM(nvl(TRANS_QTY,0)) TRANS_QTY
,SUM(NVL(OPN_QTY,0)) OPN_QTY,SUM(NVL(OPN_VAL,0)) OPN_VAL,SUM(NVL(RCV_QTY,0)) RCV_QTY,SUM(NVL(RCV_VAL,0)) RCV_VAL,SUM(NVL(ISU_QTY,0)) ISU_QTY,SUM(NVL(ISU_VAL,0)) ISU_VAL
,(SUM(NVL(OPN_QTY,0)) + SUM(NVL(RCV_QTY,0))) + SUM(NVL(ISU_QTY,0)) CLS_QTY,(SUM(NVL(OPN_VAL,0)) + SUM(NVL(RCV_VAL,0))) + SUM(NVL(ISU_VAL,0)) CLS_VAL
FROM
(
SELECT INV_TRANS.PERIOD_CODE,INV_TRANS.ORGANIZATION_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE, INV_TRANS.DESCRIPTION, INV_TRANS.PRIMARY_UOM_CODE, 
INV_TRANS.EVENT_TYPE_CODE,INV_TRANS.TRANSACTION_TYPE_ID,
CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.EVENT_TYPE_CODE ELSE INV_TRANS.TRANSACTION_TYPE_NAME END TRANSACTION_TYPE_NAME,0 OPN_QTY,0 OPN_VAL,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,12,44,18,61,1002,1003) THEN INV_TRANS.TRANSACTION_QUANTITY ELSE 0 END) RCV_QTY,
SUM(CASE WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (17,18,1002,1003) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID NOT IN (6687923) THEN INV_TRANS.TRANSACTION_VALUE ---- NVL(INV_TRANS.ACCOUNTED_DR,0)
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (61) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (12) THEN INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (44) and INV_TRANS.TRANSACTION_ID IN (6687923)  THEN INV_TRANS.ACCOUNTED_DR
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,11111)=11111 AND EVENT_TYPE_CODE = 'GLCOSTALOC' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,2222)=2222 AND EVENT_TYPE_CODE = 'LC_ADJUST_VALUATION' THEN INV_TRANS.TRANSACTION_VALUE
WHEN NVL(INV_TRANS.TRANSACTION_TYPE_ID,0)=0 AND EVENT_TYPE_CODE = 'ACTCOSTADJ' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=-99 THEN INV_TRANS.TRANSACTION_VALUE ELSE 0 END) RCV_VAL,
SUM(CASE  
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_QUANTITY
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_QUANTITY -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_QTY,
SUM(  CASE WHEN  INV_TRANS.TRANSACTION_TYPE_ID =15 THEN  INV_TRANS.ACCOUNTED_DR
WHEN INV_TRANS.TRANSACTION_TYPE_ID IN (32,33,35,36,42,43,15,63,101,103,104,106,107,111,120,140,71,200,240,241,260,261) THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=21 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE = 'FOB_SHIP_SENDER_SHIP_NO_TP' OR INV_TRANS.EVENT_TYPE_CODE='FOB_SHIP_SENDER_SHIP_TP' THEN INV_TRANS.TRANSACTION_VALUE
WHEN INV_TRANS.TRANSACTION_TYPE_ID=62 AND INV_TRANS.EVENT_TYPE_CODE  ='FOB_RCPT_SENDER_SHIP'  THEN INV_TRANS.TRANSACTION_VALUE -- ADDED DATE: 31-AUG-20121
ELSE 0 END) ISU_VAL
FROM
(
SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE,
(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
-------and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id=   5920526   --5647466
) INV_TRANS
LEFT OUTER JOIN (SELECT MIC.INVENTORY_ITEM_ID,MIC.ORGANIZATION_ID,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT
FROM MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID AND STRUCTURE_ID=50408) FIN_CAT
ON FIN_CAT.INVENTORY_ITEM_ID=INV_TRANS.INVENTORY_ITEM_ID AND FIN_CAT.ORGANIZATION_ID=INV_TRANS.ORGANIZATION_ID
GROUP BY INV_TRANS.PERIOD_CODE,FIN_CAT.MEJOR_FIN_CAT,FIN_CAT.FIN_CAT,INV_TRANS.ORGANIZATION_CODE,INV_TRANS.ORGANIZATION_ID,INV_TRANS.INVENTORY_ITEM_ID,INV_TRANS.ITEM_CODE,  INV_TRANS.DESCRIPTION,
INV_TRANS.PRIMARY_UOM_CODE, INV_TRANS.EVENT_TYPE_CODE,
INV_TRANS.TRANSACTION_TYPE_NAME,INV_TRANS.TRANSACTION_TYPE_ID, INV_TRANS.ACCOUNTED_DR
UNION ALL
SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OP_QTY OPN_QTY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OP_QTY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OP_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION, PRIMARY_UOM_CODE----,SYSTEM_COST
)
GROUP BY PERIOD_CODE,ORGANIZATION_CODE,MEJOR_FIN_CAT,FIN_CAT,ORGANIZATION_ID,INVENTORY_ITEM_ID,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE)
WHERE period_code = :P_PERIOD_CODE
GROUP BY mejor_fin_cat,period_code,ORGANIZATION_CODE,ITEM_CODE,DESCRIPTION,PRIMARY_UOM_CODE
order by period_code,organization_code,mejor_fin_cat,item_code

 --=================================== GET ITEM TRANSACTION IN VALUATION  FOR AREFIN VAI ================================================
 
 
 SELECT to_char(transaction_date,'MON-YY') PERIOD_CODE,C.ORGANIZATION_CODE,A.ORGANIZATION_ID,A.INVENTORY_ITEM_ID,B.SEGMENT1||'|'||B.SEGMENT2||'|'||B.SEGMENT3||'|'||B.SEGMENT4 ITEM_CODE,B.description, B.PRIMARY_UOM_CODE,
a.transaction_id,a.event_class_code,a.event_type_code,
g.transaction_type_id,g.transaction_type_name,TRANSACTION_QUANTITY,TRANSACTION_VALUE
--(select sum(nvl(accounted_dr,0)) from xla_ae_headers ah,xla_ae_lines al where ah.ae_header_id=al.ae_header_id and ah.event_id=a.event_id and ACCOUNTING_CLASS_CODE = 'INVENTORY_VALUATION') accounted_dr
FROM GMF_XLA_EXTRACT_HEADERS a,mtl_system_items_b b,org_organization_definitions c,mtl_transaction_types g
WHERE a.inventory_item_id=b.inventory_item_id(+)and a.organization_id=b.organization_id(+) and A.organization_id=c.organization_id and a.transaction_type_id=g.transaction_type_id(+)
and to_char(transaction_date,'MON-YY')=:P_PERIOD_CODE 
--AND B.INVENTORY_ITEM_ID IN (10409,802038) 
AND B.INVENTORY_ITEM_ID IN (20462)
and a.ledger_id=:P_LEDGER_ID
--and a.transaction_id IN (1717278)
--and a.transaction_id=   5920526   --5647466