
--PARAMETER FOR PERIOD 
SELECT DISTINCT period_code FROM gmf_period_statuses

SELECT * FROM gmf_period_statuses 

--PARAMETER FOR LEDGER
SELECT * FROM GL_LEDGERS WHERE LEDGER_CATEGORY_CODE='PRIMARY' and  ledger_ID= 2021  ORDER BY LEDGER_ID

--PARAMETER FOR OPERATING UNIT
select *  from XX_OPERATING_UNITS

kg-2248


audit