
-- OPENING FUNCTION
--CREATE OR REPLACE FUNCTION APPS.GET_ONHAND_QTY_FROM_ITEM(P_TRANSACTION_DATE IN DATE, P_ORG_ID IN NUMBER, P_ITEM_ID IN NUMBER)
RETURN NUMBER
IS
V_QTY NUMBER;
BEGIN
SELECT SUM (MQ.TRANSACTION_QUANTITY)   INTO  V_QTY    
FROM ORG_ORGANIZATION_DEFINITIONS OOD, 
 MTL_ONHAND_QUANTITIES MQ,
 MTL_SYSTEM_ITEMS_B MSI   
  WHERE 1 = 1      
  AND MQ.ORGANIZATION_ID = MSI.ORGANIZATION_ID
  AND OOD.ORGANIZATION_ID = MSI.ORGANIZATION_ID     
  AND MQ.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
  and MQ.INVENTORY_ITEM_ID = P_ITEM_ID -- 774051 --180   
  and MQ.ORGANIZATION_ID = P_ORG_ID 
   AND TRUNC(MQ.DATE_RECEIVED) <=P_TRANSACTION_DATE
  GROUP BY MQ.ORGANIZATION_ID,OOD.ORGANIZATION_CODE;
  RETURN V_QTY;
  EXCEPTION WHEN OTHERS THEN 
  RETURN NULL;
END;
/







-- GET OPENING QTY FOR COSTING 

SELECT IPB.PERIOD_CODE,IPB.ORGANIZATION_CODE,MC.SEGMENT1 MEJOR_FIN_CAT,MC.SEGMENT1||'|'||MC.SEGMENT2 FIN_CAT,IPB.ORGANIZATION_ID,IPB.INVENTORY_ITEM_ID,
IPB.ITEM_CODE,IPB.DESCRIPTION,IPB.PRIMARY_UOM_CODE,NULL,NULL,'OPENING VALUE' TRANSACTION_TYPE_NAME,IPB.OPENING_QUANTITY OPENING_QUANTITY,IPB.OP_VAL OPN_VAL,NULL RCV_QTY,NULL RCV_VAL,
NULL ISSUE_QTY,NULL ISSUE_VAL-----,NULL TRANS_QTY,NULL TRANS_VAL,NULL
FROM (SELECT :P_PERIOD_CODE PERIOD_CODE,OOD.ORGANIZATION_CODE,GPB.ORGANIZATION_ID,GPB.INVENTORY_ITEM_ID,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4 ITEM_CODE,MSI.DESCRIPTION,MSI.PRIMARY_UOM_CODE,
        SUM(PRIMARY_QUANTITY) OPENING_QUANTITY,
        GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0) OPENING_COST,
        SUM(PRIMARY_QUANTITY) * GMF_CMCOMMON.GET_CMPT_COST(GPB.INVENTORY_ITEM_ID,GPB.ORGANIZATION_ID, TRUNC(TO_DATE((TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY')),'MON-YY')),1000,0)  OP_VAL
            FROM GMF_PERIOD_BALANCES  GPB,ORG_ACCT_PERIODS   OAP , ORG_ORGANIZATION_DEFINITIONS OOD,MTL_SYSTEM_ITEMS_B MSI         
            WHERE  GPB.ACCT_PERIOD_ID=OAP.ACCT_PERIOD_ID  AND OAP.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND GPB.ORGANIZATION_ID=OOD.ORGANIZATION_ID
            AND MSI.INVENTORY_ITEM_ID=GPB.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID=GPB.ORGANIZATION_ID
            AND UPPER(OAP.PERIOD_NAME)= TO_CHAR((TO_DATE('01-'||:P_PERIOD_CODE))-1,'MON-YY') 
            AND GPB.ORGANIZATION_ID IN (SELECT ORGANIZATION_ID FROM  ORG_ORGANIZATION_DEFINITIONS WHERE SET_OF_BOOKS_ID=:P_LEDGER_ID)
            GROUP BY GPB.INVENTORY_ITEM_ID,MSI.DESCRIPTION, MSI.PRIMARY_UOM_CODE, GPB.ORGANIZATION_ID,OOD.ORGANIZATION_CODE,MSI.SEGMENT1||'|'||SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4) IPB,MTL_ITEM_CATEGORIES MIC,MTL_CATEGORIES MC, ORG_ORGANIZATION_DEFINITIONS OOD
WHERE MIC.CATEGORY_ID=MC.CATEGORY_ID
AND MIC.INVENTORY_ITEM_ID=IPB.INVENTORY_ITEM_ID AND MIC.ORGANIZATION_ID=IPB.ORGANIZATION_ID
AND MIC.INVENTORY_ITEM_ID=119 -- IPB.INVENTORY_ITEM_ID 
AND MIC.ORGANIZATION_ID=OOD.ORGANIZATION_ID AND STRUCTURE_ID=50408
----AND IPB.PERIOD_CODE=:P_PERIOD_CODE
AND SET_OF_BOOKS_ID=:P_LEDGER_ID
