-- GET OPERATING UNIT FORM GL_CODE_COMBINATIONS
-- --============================================
 SELECT DISTINCT SEGMENT1||'-'||XX_GET_ACCT_FLEX_SEG_DESC (1, SEGMENT1)  FROM GL_CODE_COMBINATIONS



PODATE FROM:          YYYY/MM/DD HH24:MI:SS               2021/2/1 11:04:20
PO DATE TO:           YYYY/MM/DD HH24:MI:SS               2019/04/28 11:04:20

--========================
-- GET ITEM GROUP  AS PARAMETER
--========================
(SELECT  DISTINCT ITEM_GROUP,ITEM_TYPE FROM WBI_XXKBGITEM_MT_D)

SELECT  DISTINCT ITEM_GROUP  FROM WBI_XXKBGITEM_MT_D where item_group= '500 W'

EBS Item Stock ( For Reconciliation)
XXITESTOCKMRECON


OPM GMF Request Group MIS

FINANCE_CATEGORY= FIN_CAT
ITEM_TYPE = INVENTORY_TYPE

FG|500W|20MM|000006

FG|500W|20MM|000006	    KSRM B 500 CWR 20 MM


REPORT NAME: XXKSRM Item Stock (Reconciliation)   --> DONE IN PRODUCTION    XXKSRM Item Stock (Reconciliations)
EXECUTABLE: XXITEMSTOCKRECON     --> XXITEMSTOCKRECONS
CONCURRENT PROGRAM: EBS Item Stock ( For Reconciliation)

LE Valuset:
XX_LE_NAME = ( SELECT DISTINCT SEGMENT1 LEGAL_ENTITY_CODE,SEGMENT1||'-'||XX_GET_ACCT_FLEX_SEG_DESC (1, SEGMENT1) LEGAL_ENTITY_NAME FROM GL_CODE_COMBINATIONS) 
XX_LEGAL_ENTITY_NAME = (select LEGAL_ENTITY_ID, BAL_SEG_NAME from XX_BAL_SEG_INFO)  ORDER BY LEGAL_ENTITY_ID 

LEDGER VALUSET:
XX_GL_LEDGER

OU/ OPERATING UNIT VALUSET:
XX_UNIT_NAME, XX_OU_NAME,
XX_OU_NAME_WITH_LE = (SELECT DEFAULT_LEGAL_CONTEXT_ID, NAME FROM HR_OPERATING_UNITS) ORDER BY DEFAULT_LEGAL_CONTEXT_ID

INVENTORY ORG VALUSET : 
XXKBG_MO_ORG
XXKSRM_MO_ORG
INV_ORG = (SELECT ORGANIZATION_ID , ORGANIZATION_CODE,ORGANIZATION_NAME  FROM ORG_ORGANIZATION_DEFINITIONS) X

PERIOD VALUSET:
XX_COST_PERIOD

Cost Center Valuset: 
XX_COST_CENTER

ITEM Description Valuset:
Item Description

Natural Account Valuset:
XX_NATURAL_ACCOUNT

Bank Account Name:
XX_BANK_ACCOUNT_NUMBER

Item Code:
XXKSRM_ITEM_CODE_NAME_LC
XXKBG_ITEM_CODES : (SELECT DISTINCT (MSI.SEGMENT1 || '|'||MSI.SEGMENT2 || '|'||MSI.SEGMENT3 || '|'||MSI.SEGMENT4) ITEMCODE, DESCRIPTION,ORGANIZATION_ID  FROM MTL_SYSTEM_ITEMS MSI)X
XXKBG_ITEM_CODESS: (SELECT DISTINCT (MSI.SEGMENT1 || '|'||MSI.SEGMENT2 || '|'||MSI.SEGMENT3 || '|'||MSI.SEGMENT4) ITEMCODE, DESCRIPTION FROM MTL_SYSTEM_ITEMS)X
XX_ITEMS_CODE : (SELECT DISTINCT INVENTORY_ITEM_ID ,  (SEGMENT1 || '|'||SEGMENT2 || '|'||SEGMENT3 || '|'||SEGMENT4) ITEMCODE, DESCRIPTION FROM MTL_SYSTEM_ITEMS) X
EBS_ITEM_CODE

Printed by/ USER VALUSET: 
15 Characters



Item Type: XXKSRM_ITEM_TYPE
(SELECT  DISTINCT WXMD.ITEM_TYPE FROM WBI_XXKBGITEM_MT_D WXMD)
(SELECT  DISTINCT WXMD.ITEM_TYPE FROM WBI_XXKBGITEM_MT_DMN WXMD)


Item Group : 
XXKSRM_ITEM_GROUP_D = (SELECT  DISTINCT ITEM_GROUP,ITEM_TYPE FROM WBI_XXKBGITEM_MT_D)WHERE ITEM_TYPE=:$FLEX$.XXKSRM_ITEM_TYPE 
XXKSRM_ITEM_GROUP_KBG = (SELECT  DISTINCT ITEM_GROUP,ITEM_TYPE FROM WBI_XXKBGITEM_MT_D)

Item Sub Group : 
XXKSRM_ITEM_SUB_GROUP_D = (SELECT  DISTINCT ITEM_SUB_GROUP,ITEM_GROUP,ITEM_TYPE FROM WBI_XXKBGITEM_MT_D) WHERE ITEM_TYPE=:$FLEX$.XXKSRM_ITEM_TYPE AND ITEM_GROUP=:$FLEX$.XXKSRM_ITEM_GROUP_D
XX_ITEM_SUB_GROUP_KBG = (SELECT  DISTINCT ITEM_SUB_GROUP,ITEM_GROUP,ITEM_TYPE FROM WBI_XXKBGITEM_MT_D)

Finance Category : 
XXKSRM_FINANCE_CATEGORY_D = (SELECT  DISTINCT FINANCE_CATEGORY ,ITEM_SUB_GROUP,ITEM_GROUP,ITEM_TYPE  FROM WBI_XXKBGITEM_MT_D) WHERE ITEM_TYPE=:$FLEX$.XXKSRM_ITEM_TYPE AND ITEM_GROUP=:$FLEX$.XXKSRM_ITEM_GROUP_D AND ITEM_SUB_GROUP=:$FLEX$.XXKSRM_ITEM_SUB_GROUP_D
XX_FINANCE_CATEGORY_KBG = (SELECT  DISTINCT FINANCE_CATEGORY ,ITEM_SUB_GROUP,ITEM_GROUP,ITEM_TYPE  FROM WBI_XXKBGITEM_MT_D)
XX_FIN_CAT = (SELECT  DISTINCT  FIN_CAT   FROM WBI_XXKBGITEM_MT_DMN)

--=========================================
Report Name: EBS Factory Overhead Report
--=========================================
Executable: XX_FACTORYOVERHEAD_DTL
Parameter: 
Legal Entity Name :
Valuset: XX_LE_NAME
Operating Unit: XX_UNIT_NAME

--=======================================
ReportName: XXKSRM Consumption Report
--=======================================
Company:
VAluset: XX_GL_LEDGER
Operating Unit: 
XX_KSRM_OU: (SELECT ORGANIZATION_ID, SUBSTR(NAME ,5,100) NAME FROM HR_OPERATING_UNITS)
XX_KSRM_OU_DTL= (SELECT ORGANIZATION_ID, ORGANIZATION_ID||'-'||SUBSTR(NAME ,5,100) NAME FROM HR_OPERATING_UNITS)
Cost Center: 
Valuset: XX_COST_CENTER


--===================================
NEW REPORT: 
============
 NAME: EBS Challan Wise Blanket PO GRN Details(Audit)
 EXECUTABLE: XXCHALLANWISEGRN 


VALUSET Report Parameter:
==================
OPERATING_UNIT: ---> Valiset: XX_OU_NAME
DEpARTRTMENT: Valuset:  XX_DEPT_NAME ---> table name : XX_DEPT_V
PO NUMBER: ---> Valuset: XX_BPO_F XX_BPO_TO
CHALLAN_NUMBER_RT : XXKSRM_CHALLAN_NO_INV
Challan_Number: Valuset:XXKSRM_CHALLAN :   (SELECT DISTINCT CHALLAN_NUMBER_RT ,ORGANIZATION_ID,RECEIPT_NO FROM WBI_INV_RCV_TRANSACTIONS_F) X
                                            WHERE X.CHALLAN_NUMBER_RT IS NOT NULL
                                            AND X.ORGANIZATION_ID=:$FLEX$.XXKSRM_MO_ORG
GRN_NUMBER: VALUSET: XX_GRN_NUMBER
INVENTORY_ITEM_ID: VALUSET: XXKSRM_ITEM_CODE_NAME
FROM_DATE: ---> FND_DATE_STANDARD ,  TO_DATE: FND_DATE_STANDARD
SUPPLIER: VALUSET: XX_AP_SUPPLIERS, XXKSRM_VENDOR


PARAMETER: 
==========

Item Type: XXKSRM_ITEM_TYPE
(SELECT  DISTINCT WXMD.ITEM_TYPE FROM WBI_XXKBGITEM_MT_D WXMD)

Item Group : XXKSRM_ITEM_GROUP_D
(SELECT  DISTINCT ITEM_GROUP,ITEM_TYPE FROM WBI_XXKBGITEM_MT_D)
WHERE ITEM_TYPE=:$FLEX$.XXKSRM_ITEM_TYPE 

Item Sub Group : XXKSRM_ITEM_SUB_GROUP_D
(SELECT  DISTINCT ITEM_SUB_GROUP,ITEM_GROUP,ITEM_TYPE FROM WBI_XXKBGITEM_MT_D)
    WHERE ITEM_TYPE=:$FLEX$.XXKSRM_ITEM_TYPE
    AND ITEM_GROUP=:$FLEX$.XXKSRM_ITEM_GROUP_D


Finance Category : XXKSRM_FINANCE_CATEGORY_D
(SELECT  DISTINCT FINANCE_CATEGORY ,ITEM_SUB_GROUP,ITEM_GROUP,ITEM_TYPE  FROM WBI_XXKBGITEM_MT_D)
    WHERE ITEM_TYPE=:$FLEX$.XXKSRM_ITEM_TYPE
    AND ITEM_GROUP=:$FLEX$.XXKSRM_ITEM_GROUP_D
    AND ITEM_SUB_GROUP=:$FLEX$.XXKSRM_ITEM_SUB_GROUP_D


--====================================================
-- 
--====================================================

 
Some Suggestion for OPP Issue:
 
1.       Run Create Accounting ” Cost management request for very frequently or schedule it
2.       Verify & correct Accounting setup to avoid unprocessed event errors
3.       Correct  parameters to be passed like Locator to run Pick Selection Generation ” SRS request
4.    Regenerate the Template
 











