 --=====================================REQUISITION UPDATE======================================

 
 SELECT * FROM PO_REQUISITION_HEADERS_ALL WHERE  SEGMENT1=10003748 AND ORG_ID=104  ---ORG_ID
 
 
 SELECT * FROM PO_REQUISITION_LINES_ALL WHERE  REQUISITION_HEADER_ID = 1393729

UPDATE PO_requisition_headers_all
SET LAST_UPDATE_DATE=TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'), 
CREATION_DATE=TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'), 
APPROVED_DATE = TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
WHERE 1=1
AND REQUISITION_HEADER_ID= 1393729
AND ORG_ID = 104


 select * from po_requisition_lines_all where requisition_header_id= 1393729 -- 1364128
 


UPDATE po_requisition_lines_all
SET LAST_UPDATE_DATE=TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'), 
CREATION_DATE=TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'), 
NEED_BY_DATE = TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
WHERE 1=1
AND REQUISITION_HEADER_ID=1393729 --1339634
AND ORG_ID = 104



select * from po_req_distributions_all where REQUISITION_LINE_ID IN (941861,941862,941863,942200)-- 1339634


UPDATE po_req_distributions_all
SET
CREATION_DATE=TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'), 
 LAST_UPDATE_DATE=TO_DATE('6/30/2021 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
 WHERE 1=1
and  REQUISITION_LINE_ID IN (972025)
and org_id=104
  

select * from PO_REQ_DISTRIBUTIONS_ALL WHERE  REQUISITION_LINE_ID = 945577

-- REQUISITION  INV ORG UPDATE AFTER APPROVE THE PR
--======================================

UPDATE PO_REQUISITION_LINES_ALL
SET DELIVER_TO_LOCATION_ID = 185,
DESTINATION_ORGANIZATION_ID = 144
WHERE ORG_ID= 81
AND REQUISITION_LINE_ID = 945577


POCISO





 
 --=========================================================================================
 --===================================== PO UPDATE ====================================================
 
 
 SELECT * FROM HR_OPERATING_UNITS 
 
      
/*PO PRICE UPDATE  SCRIPT*/

 SELECT * FROM PO_HEADERS_ALL WHERE SEGMENT1= 40000371 AND  ORG_ID= 102
      
  SELECT * FROM PO_LINES_ALL WHERE PO_HEADER_ID= 864066
      
      SELECT * FROM PO_LINE_LOCATIONS_ALL WHERE PO_HEADER_ID= 864066
      
      select * from MTL_SYSTEM_ITEMS
      
      UPDATE PO_LINES_ALL 
      SET LIST_PRICE_PER_UNIT =11.055128  ,
          UNIT_PRICE =11.055128  ,
          BASE_UNIT_PRICE = 11.055128 
      WHERE PO_HEADER_ID= 850760 
      AND PO_LINE_ID = 1234136
      
      
      UPDATE PO_LINES_ALL 
      SET LIST_PRICE_PER_UNIT =8.125128  ,
          UNIT_PRICE =8.125128  ,
          BASE_UNIT_PRICE =8.125128 
      WHERE PO_HEADER_ID= 850760 
      AND PO_LINE_ID = 1234137
      
            UPDATE PO_LINES_ALL 
      SET LIST_PRICE_PER_UNIT =8.125128  ,
          UNIT_PRICE =8.125128  ,
          BASE_UNIT_PRICE =8.125128 
      WHERE PO_HEADER_ID= 850760 
      AND PO_LINE_ID = 1234137
      
      
      update PO_LINE_LOCATIONS_ALL
      set PRICE_OVERRIDE = 11.055128
      where LINE_LOCATION_ID = 1236395
      and PO_HEADER_ID= 850760 
      AND PO_LINE_ID = 1234136
      
        update PO_LINE_LOCATIONS_ALL
      set PRICE_OVERRIDE = 8.125128 
      where LINE_LOCATION_ID = 1236396
      and PO_HEADER_ID= 850760 
      AND PO_LINE_ID = 1234137
      
      
      
 SELECT * FROM HR_OPERATING_UNITS
 
 SELECT PO_HEADER_ID,LAST_UPDATE_DATE , CREATION_DATE,APPROVED_DATE,PROGRAM_UPDATE_DATE,SUBMIT_DATE,CLM_EFFECTIVE_DATE FROM PO_HEADERS_ALL WHERE SEGMENT1 = 40000315 and ORG_ID= 102

/*================================PO DATE UPDATE========================================================*/
--========PO_HEADERS_ALL============

SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE= 'PWM'

select * from HR_OPERATING_UNITS


select  * from PO_HEADERS_ALL WHERE PO_HEADER_ID= 21001

select * from PO_HEADERS_ALL WHERE SEGMENT1= 40021051 and ORG_ID=103

SELECT * FROM PO_LINES_ALL WHERE PO_HEADER_ID = 21001

SELECT '12/31/2018 12:44:32 PM' new_date,
Ph.LAST_UPDATE_DATE,  ph.CREATION_DATE,ph.REVISED_DATE,ph.APPROVED_DATE,  ph.SUBMIT_DATE,
pl.LAST_UPDATE_DATE, pl.CREATION_DATE,
pll.LAST_UPDATE_DATE, pll.CREATION_DATE, pll.NEED_BY_DATE,pll.PROMISED_DATE,pll.APPROVED_DATE, pll.PROGRAM_UPDATE_DATE,
PD.LAST_UPDATE_DATE,PD.CREATION_DATE,PD.RATE_DATE,PD.PROGRAM_UPDATE_DATE
 FROM PO_HEADERS_ALL PH , PO_LINES_ALL PL, PO_LINE_LOCATIONS_ALL PLL, PO_DISTRIBUTIONS_ALL PD
 WHERE ph.po_header_id= pl.PO_HEADER_ID
 and pl.po_HEADER_ID = pll.PO_HEADER_ID
 and pl.po_line_ID= PLL.PO_LINE_ID
 and ph.po_header_id= pl.po_header_id
 and pl.po_line_id= pll.po_line_id
 and pll.po_line_id=pd.po_line_id
 and   ph.PO_HEADER_ID = 864781  



--============================ ALL PO TABLE DATE  UPDATE QUERY ======================================== 

SELECT '10/20/2020 12:44:32 PM' new_date, PH.PO_HEADER_ID,PL.ITEM_DESCRIPTION,
Ph.LAST_UPDATE_DATE,  ph.CREATION_DATE,ph.REVISED_DATE,ph.APPROVED_DATE,  ph.SUBMIT_DATE,
pl.LAST_UPDATE_DATE, pl.CREATION_DATE,
pll.LAST_UPDATE_DATE, pll.CREATION_DATE, pll.NEED_BY_DATE,pll.PROMISED_DATE,pll.APPROVED_DATE, pll.PROGRAM_UPDATE_DATE,
PD.LAST_UPDATE_DATE,PD.CREATION_DATE,PD.RATE_DATE,PD.PROGRAM_UPDATE_DATE
 FROM PO_HEADERS_ALL PH , PO_LINES_ALL PL, PO_LINE_LOCATIONS_ALL PLL, PO_DISTRIBUTIONS_ALL PD
 WHERE ph.po_header_id= pl.PO_HEADER_ID
 and pl.po_HEADER_ID = pll.PO_HEADER_ID
 and pl.po_line_ID= PLL.PO_LINE_ID
 and ph.po_header_id= pl.po_header_id
 and pl.po_line_id= pll.po_line_id
 and pll.po_line_id=pd.po_line_id
 and ph.segment1=  40021051 
 and ph.org_id= 103
-- and   ph.PO_HEADER_ID = 21001  


BEGIN
FOR i IN(
SELECT ORG_ID ,PO_HEADER_ID HEADER_ID ,LAST_UPDATE_DATE , CREATION_DATE,REVISED_DATE,APPROVED_DATE,SUBMIT_DATE, TO_DATE('3/28/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM') NEW_DATE
FROM PO_HEADERS_ALL 
WHERE PO_HEADER_ID =  864781  
and ORG_ID = 102
)
LOOP
UPDATE PO_HEADERS_ALL 
SET  LAST_UPDATE_DATE  = i.NEW_DATE,
CREATION_DATE = i.NEW_DATE,
REVISED_DATE = i.NEW_DATE,
APPROVED_DATE = i.NEW_DATE,
SUBMIT_DATE= i.NEW_DATE,
ORG_ID = i.org_id
WHERE PO_HEADER_ID= i.HEADER_ID;

 Update  PO_LINES_ALL
 SET LAST_UPDATE_DATE = i.new_date, 
 CREATION_DATE =  i.new_date,
 ORG_ID= i.ORG_ID
 WHERE PO_HEADER_ID= i.HEADER_ID;
 
 UPDATE PO_LINE_LOCATIONS_ALL
 SET LAST_UPDATE_DATE =  i.new_date, 
 CREATION_DATE =  i.new_date, 
 NEED_BY_DATE =  i.new_date, 
 PROMISED_DATE =  i.new_date, 
 APPROVED_DATE =  i.new_date, 
 PROGRAM_UPDATE_DATE =  i.new_date,
 ORG_ID= i.ORG_ID
 WHERE PO_HEADER_ID= i.HEADER_ID;
 
UPDATE PO_DISTRIBUTIONS_ALL
SET  LAST_UPDATE_DATE =  i.new_date, 
 CREATION_DATE =  i.new_date,
 RATE_DATE =  i.new_date,
 PROGRAM_UPDATE_DATE =  i.new_date,
 ORG_ID= i.ORG_ID
 WHERE PO_HEADER_ID= i.HEADER_ID;
END LOOP;
END;


--=========================================GRN QUERY ==========================================

select * from HR_OPERATING_UNITS

select * from org_organization_definitions where ORGANIZATION_CODE='PWM'

SELECT * FROM PO_HEADERS_ALL WHERE SEGMENT1='40014946'

select * from RCV_SHIPMENT_LINES WHERE SHIPMENT_HEADER_ID= 880992

select *  from PO_LINES_ALL WHERE PO_HEADER_ID= 880992 and PO_LINE_ID=1320529

XX_GET_EMP_NAME_FROM_USER_ID (CANCELLED_BY) 

select comments from RCV_TRANSACTIONS WHERE SHIPMENT_LINE_ID=1293297 --SHIPMENT_HEADER_ID= 1107737

select * from RCV_SHIPMENT_LINES where SHIPMENT_LINE_ID=1293297 --1107737

 and TRANSACTION_TYPE = 'DELIVER'  
 
 SELECT PERSON_ID,EMPLOYEE_NUMBER  FROM PER_ALL_PEOPLE_F WHERE FIRST_NAME = 'KG-7037'
 
 SELECT PERSON_ID,EMPLOYEE_NUMBER  FROM PER_ALL_PEOPLE_F WHERE EMPLOYEE_NUMBER=8936
 
  SELECT First_name, PERSON_ID,EMPLOYEE_NUMBER, FULL_NAME  FROM PER_ALL_PEOPLE_F WHERE PERSON_ID=8936




SELECT * FROm MTL_MATERIAL_TRANSACTIONS WHERE SHIPMENT_NUMBER='INT-TRM-0005977' 





SELECT a.RECEIPT_NUM, b.TRANSACTION_TYPE,B.TRANSACTION_DATE,b.QUANTITY, b.transaction_id RCV_TRANS_ID,a.SHIPMENT_HEADER_ID, b.CREATION_DATE,a.LAST_UPDATE_DATE, a.ATTRIBUTE13
 FROM RCV_SHIPMENT_HEADERS  a, RCV_TRANSACTIONS b
 where 1=1
 and a.receipt_num IN (
80030875
)
 and a.SHIPMENT_HEADER_ID = b.SHIPMENT_HEADER_ID
and b.TRANSACTION_TYPE = 'DELIVER'  
AND a.SHIP_TO_ORG_ID =163

SELECT * FROM RCV_TRANSACTIONS WHERE  SHIPMENT_HEADER_ID = 1118079

SELECT * FROM RCV_SHIPMENT_HEADERS WHERE ship_to_org_id= 170 and  receipt_num=80001135 --SHIPMENT_HEADER_ID= 1059857

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE RCV_TRANSACTION_ID IN
(
1324889,
1324890,
1324891,
1324892,
1324893,
1324894,
1324895,
1324896,
1324897,
1324898
)

--=============================================GRN UPDATE ==============================================

select RCV_TRANSACTION_ID ,  shipment_NUMBER  , TRANSACTION_SOURCE_ID from MTL_MATERIAL_TRANSACTIONS where   shipment_NUMBER = 80007541 and 

select *  from MTL_MATERIAL_TRANSACTIONS where   RCV_TRANSACTION_ID IN(
320718
)




BEGIN
FOR i IN(
SELECT a.RECEIPT_NUM, b.transaction_id TRANS_ID,b.transaction_DATE,a.SHIPMENT_HEADER_ID, b.CREATION_DATE,a.LAST_UPDATE_DATE, a.ATTRIBUTE13,  
TO_DATE('12/31/2022 11:00:30 AM', 'MM/DD/YYYY HH12:MI:SS PM') new_date
 FROM RCV_SHIPMENT_HEADERS  a, RCV_TRANSACTIONS b
 where 1=1
 and a.receipt_num IN (
80030875
 )
 and a.SHIPMENT_HEADER_ID = b.SHIPMENT_HEADER_ID
 and b.TRANSACTION_TYPE = 'DELIVER'  
AND a.SHIP_TO_ORG_ID = 163
)
LOOP
UPDATE RCV_SHIPMENT_HEADERS 
SET 
LAST_UPDATE_DATE= i.new_date, 
CREATION_DATE= i.new_date
--ATTRIBUTE13 = '2020/12/31 00:00:00'
WHERE  SHIPMENT_HEADER_ID  =i.SHIPMENT_HEADER_ID;

UPDATE  RCV_SHIPMENT_LINES
SET LAST_UPDATE_DATE= i.new_date, 
CREATION_DATE= i.new_date, 
PROGRAM_UPDATE_DATE = i.new_date
WHERE  SHIPMENT_HEADER_ID = i.SHIPMENT_HEADER_ID;

UPDATE  RCV_TRANSACTIONS
SET LAST_UPDATE_DATE= i.new_date, 
CREATION_DATE= i.new_date, 
PROGRAM_UPDATE_DATE= i.new_date, 
TRANSACTION_DATE= i.new_date, 
CURRENCY_CONVERSION_DATE = i.new_date
--ATTRIBUTE9 = '2019/12/31 00:00:00'
WHERE  SHIPMENT_HEADER_ID = i.SHIPMENT_HEADER_ID;

UPDATE MTL_MATERIAL_TRANSACTIONS
set  LAST_UPDATE_DATE = i.new_date,
CREATION_DATE = i.new_date,
PROGRAM_UPDATE_DATE= i.new_date,
TRANSACTION_DATE=i.new_date
where RCV_TRANSACTION_ID = i.TRANS_ID;

END LOOP;
END;

--============ 
--REMARKS UPDATE  IN GRN 
--============
select comments from RCV_TRANSACTIONS WHERE SHIPMENT_LINE_ID=1293297 

update RCV_TRANSACTIONS
SET comments='New yard shearing machine.'
WHERE SHIPMENT_LINE_ID=1293297 

--==================
--LC NUMBER UPDATE IN GRN 
--==================

    SELECT * FROm XX_LC_DETAILS where LC_NUMBER= '3086-22-01-0034' 
    
    SELECT *  FROM RCV_TRANSACTIONS WHERE attribute4 in ('11222') --and TRANSACTION_TYPE = 'DELIVER'

     UPDATE RCV_TRANSACTIONS 
     SET ATTRIBUTE4 = '11222' --- ATTRIBUTE4 = LC_NUMBER
     WHERE SHIPMENT_HEADER_ID =1114903 
     
     UPDATE RCV_TRANSACTIONS 
     SET ATTRIBUTE_CATEGORY='LC Item Receiving'
      WHERE SHIPMENT_HEADER_ID =1114903
     
     
     --==================
--LC DATE  UPDATE IN GRN 
--==================
     UPDATE RCV_TRANSACTIONS 
      SET ATTRIBUTE9 = '2019/12/31 00:00:00'  -- LC_DATE 
     WHERE SHIPMENT_HEADER_ID =1114903 

--==============================
-- VEHICLE DFF UPDATE ON GRN Report
--===========================
SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE='TRA'

SELECT * FROM RCV_SHIPMENT_HEADERS WHERE RECEIPT_NUM= 80000032 and SHIP_TO_ORG_ID=261

SELECT * FROM RCV_TRANSACTIONS RT WHERE SHIPMENT_HEADER_ID = 1110223

 SELECT RT.ATTRIBUTE7 VEHICLE_NUMBER_RT FROM RCV_TRANSACTIONS RT WHERE SHIPMENT_HEADER_ID = 111022

UPDATE RCV_TRANSACTIONS
SET ATTRIBUTE7 = ''
WHERE SHIPMENT_HEADER_ID = 111022


SELECT * FROM XXKSRM_INV_USE_AREA_V where use_area_id= 10263 -- USE_AREA LIKE  '%CM-TA-05-1184%'


--==================================== MOVE ORDER  QUERY ==================================================

-- FOR CHECKING 
SELECT TOL.ATTRIBUTE6,TOL.ATTRIBUTE5,TOL.ATTRIBUTE2 USE_OF_AREA_ID, MMT.TRANSACTION_ID TRANSACTION_ID, MMT.TRANSACTION_TYPE_ID,mmt.transaction_date, tol.attribute2 Use_Of_AREA,
TOH.HEADER_ID WITH_HEADER_ID,TOH.CREATION_DATE,
 XX_GET_EMP_NAME_FROM_USER_ID (TOH.CREATED_BY) CREATED_BY,
  TOL.ORGANIZATION_ID,
  GET_ORG_CODE_FROM_ID( TOL.ORGANIZATION_ID) ORG_CODE,
  TOH.REQUEST_NUMBER,
  TOH.HEADER_ID,
  TOL.LINE_NUMBER,
  TOL.LINE_ID,
  TOL.INVENTORY_ITEM_ID,
  MY_PACKAGE.XXGET_ITEM_DESCRIPTION(TOL.INVENTORY_ITEM_ID, TOL.ORGANIZATION_ID) ITEM_DESCRIPTION,
  TOH.DESCRIPTION,
  TOH.MOVE_ORDER_TYPE,
  TOL.LINE_STATUS,
  TOL.QUANTITY,
  TOL.QUANTITY_DELIVERED,
  TOL.QUANTITY_DETAILED,
  (SELECT DISTINCT USE_AREA  FROM XXKSRM_INV_USE_AREA_V where use_area_id= TOL.ATTRIBUTE2) VEHICLE
FROM MTL_TXN_REQUEST_HEADERS TOH,
  MTL_TXN_REQUEST_LINES TOL,
  MTL_MATERIAL_TRANSACTIONS MMT
WHERE TOH.HEADER_ID = TOL.HEADER_ID
 AND TOH.ORGANIZATION_ID= TOL.ORGANIZATION_ID
 AND TOL.LINE_ID = MMT.MOVE_ORDER_LINE_ID(+)
AND TOH.REQUEST_NUMBER LIKE '%MO-TRM-0102117%'
--AND TOL.INVENTORY_ITEM_ID=180
--AND TOL.INVENTORY_ITEM_ID = '771089'
--AND TOL.ATTRIBUTE5 is not null
and   TOL.QUANTITY_DELIVERED IS NOT NULL 
--AND TRUNC(mmt.transaction_date)  BETWEEN '01-NOV-2022' and '30-NOV-2022'
 --and TOH.HEADER_ID IN (1764072)
-- )


SELECT * FROM XXKSRM_INV_USE_AREA_V where use_area_id=  146 

SELECT * FROM XXKSRM_INV_USE_AREA_V where USE_AREA LIKE  '%CANTEEN%'

SELECT * FROM MTL_TXN_REQUEST_HEADERS WHERE REQUEST_NUMBER='MO-TRM-0097365'

SELECT * FROM MTL_TXN_REQUEST_LINES WHERE HEADER_ID= 2147384

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID IN (15419357)  

SELECT * FROM XXKSRM_INV_USE_AREA_V where USE_AREA LIKE  '%Barabkunda Binding%Delivery Shed%'



MO-KPM-0003270, Wrong Posting

select * from MTL_TRANSACTION_TYPES where TRANSACTION_TYPE_ID=53



SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE = 'KBM' 



--==================================== MOVE ORDER  SCRIPT FOR UPDATE ==================================================


BEGIN
FOR i IN(
SELECT MMT.TRANSACTION_ID TRANSACTION_ID, TO_DATE('6/30/2022 4:42:38 PM', 'MM/DD/YYYY HH12:MI:SS PM') NEW_DATE,
mmt.transaction_date,
TOH.HEADER_ID WITH_HEADER_ID,
  TOL.ORGANIZATION_ID,
  TOH.REQUEST_NUMBER,
  TOH.HEADER_ID,
  TOL.LINE_NUMBER,
  TOL.LINE_ID,
  TOL.INVENTORY_ITEM_ID,
  TOH.DESCRIPTION, 
  TOH.MOVE_ORDER_TYPE,
  TOL.LINE_STATUS,
  TOL.QUANTITY,
  TOL.QUANTITY_DELIVERED,
  TOL.QUANTITY_DETAILED
FROM MTL_TXN_REQUEST_HEADERS TOH,
  MTL_TXN_REQUEST_LINES TOL,
  MTL_MATERIAL_TRANSACTIONS MMT
WHERE TOH.HEADER_ID = TOL.HEADER_ID
 AND TOH.ORGANIZATION_ID= TOL.ORGANIZATION_ID
 AND TOL.LINE_ID = MMT.MOVE_ORDER_LINE_ID(+)
 AND TOH.REQUEST_NUMBER='MO-TRA-0063953'
 and TOH.ORGANIZATION_ID = 261
)
LOOP
UPDATE MTL_TXN_REQUEST_HEADERS
SET
CREATION_DATE =  i.new_date, 
LAST_UPDATE_DATE= i.new_date, 
DATE_REQUIRED= i.new_date
WHERE REQUEST_NUMBER = i.REQUEST_NUMBER;

UPDATE MTL_TXN_REQUEST_LINES
SET
CREATION_DATE=  i.new_date, 
LAST_UPDATE_DATE =  i.new_date, 
DATE_REQUIRED =  i.new_date, 
STATUS_DATE=  i.new_date
where header_id= i.WITH_HEADER_ID;

UPDATE MTL_MATERIAL_TRANSACTIONS
SET
CREATION_DATE= i.new_date, 
LAST_UPDATE_DATE= i.new_date, 
TRANSACTION_DATE= i.new_date
where TRANSACTION_ID = i.TRANSACTION_ID;
END LOOP;
END;


--============================
--UPDATE USE OF AREA IN MOVE ORDER 
--============================

SELECT * FROM MTL_TXN_REQUEST_HEADERS where REQUEST_NUMBER='MO-KSA-0042195' 

SELECT Attribute2 Use_Of_AREA  FROM MTL_TXN_REQUEST_LINES WHERE HEADER_ID=2194228

SELECT * FROM XXKSRM_INV_USE_AREA_V where USE_AREA LIKE '%CANTEEN%' -- use_area_id= 10263 

 UPDATE MTL_TXN_REQUEST_LINES
SET Attribute2='10232'
WHERE HEADER_ID=2194228


--======================================== IOT DATE UPDATE =============================================
/***************************************************************
--- FOR CHERCKING IOT DATE ----
*****************************************************************/


SELECT c.transaction_id ,a.SHIPMENT_HEADER_ID,a.ship_to_org_id,a.shipment_num,a.CREATION_DATE,a.SHIPPED_DATE,a.EXPECTED_RECEIPT_DATE, c.ATTRIBUTE3 LC_ID,
b.LAST_UPDATE_DATE ,c.TRANSACTION_DATE MMT_TRANS_DATE,TO_DATE('12/21/2020 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM') NEW_DATE
from RCV_SHIPMENT_HEADERS a, rcv_shipment_lines b, MTL_MATERIAL_TRANSACTIONS c
where a.shipment_header_id= b.shipment_header_id
and a.ship_to_org_id =  b.TO_ORGANIZATION_ID
and b.TO_ORGANIZATION_ID   = c.TRANSFER_ORGANIZATION_ID
and a.shipment_num = c.SHIPMENT_NUMBER
and a.ORGANIZATION_ID = c.ORGANIZATION_ID
and b.MMT_TRANSACTION_ID = c.TRANSACTION_ID
and a.shipment_num LIKE  '%INT-KBD%' 
ORDER BY c.TRANSACTION_DATE DESC
--and a.ship_to_org_id= 201

SELECT SHIPMENT_NUMBER  from MTL_MATERIAL_TRANSACTIONS  where inventory_item_ID=24476 and trunc(transaction_DATE) between '1-JUN-2022' and '2-JUN-2022' -- and  SHIPMENT_NUMBER 

--***************************************************************************
--- FOR  UPDATE  IOT DATE
--************************************************************************
--BEGIN
FOR i IN(
SELECT a.SHIPMENT_HEADER_ID,a.ship_to_org_id,a.shipment_num,a.CREATION_DATE,a.SHIPPED_DATE,a.EXPECTED_RECEIPT_DATE,
b.LAST_UPDATE_DATE ,TO_DATE('3/11/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM') NEW_DATE
from RCV_SHIPMENT_HEADERS a, rcv_shipment_lines b, MTL_MATERIAL_TRANSACTIONS c
where a.shipment_header_id= b.shipment_header_id
and a.ship_to_org_id =  b.TO_ORGANIZATION_ID
and b.TO_ORGANIZATION_ID   = c.TRANSFER_ORGANIZATION_ID
and a.shipment_num = c.SHIPMENT_NUMBER
and a.ORGANIZATION_ID = c.ORGANIZATION_ID
and b.MMT_TRANSACTION_ID = c.TRANSACTION_ID
and a.shipment_num= 'INT-KLO-0000808' 
and a.ship_to_org_id= 201
)
LOOP
update RCV_SHIPMENT_HEADERS 
 SET 
SHIPPED_DATE= i.new_date, 
CREATION_DATE= i.new_date
WHERE  SHIPMENT_HEADER_ID  =i.SHIPMENT_HEADER_ID;

UPDATE  RCV_SHIPMENT_LINES
SET LAST_UPDATE_DATE= i.new_date, 
CREATION_DATE= i.new_date, 
PROGRAM_UPDATE_DATE = i.new_date
WHERE  SHIPMENT_HEADER_ID = i.SHIPMENT_HEADER_ID;

UPDATE MTL_MATERIAL_TRANSACTIONS
set  LAST_UPDATE_DATE = i.new_date,
CREATION_DATE = i.new_date,
PROGRAM_UPDATE_DATE= i.new_date,
TRANSACTION_DATE=i.new_date
where SHIPMENT_NUMBER  = i.SHIPMENT_NUM
and TRANSFER_ORGANIZATION_ID = i.SHIP_TO_ORG_ID;

END LOOP;
END;

--=======================================
--Case: Some transaction does not create IOT number but transaction completed 
Solusion: 1. find the last iot number of this org 
               2. capture that IOT on the blank transaction 
--======================================

select * from ORG_ORGANIZATION_DEFINITIONS 
WHERE ORGANIZATION_CODE='PWD'

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE ORGANIZATION_ID=162
AND TRANSACTION_TYPE_ID = 21
--ORDER BY TRANSACTION_DATE DESC
AND TRANSACTION_ID IN(
1915452,
16793045,
16793046,
16793047,
16793048)





SELECT * FROM RCV_SHIPMENT_HEADERS WHERE SHIPMENT_NUM='INT-PWD-0000903'


INT-PWD-0000753

INT-PWD-0000903

--================================================CHALLAN  DATE , QTY UPDATE ==========================================


--CHALLAN DATE OR QTY UPDATE 
--============================

SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE = 'TRM'

SELECT * FROM RCV_SHIPMENT_HEADERS WHERE  RECEIPT_NUM= 80004933  and SHIP_TO_ORG_ID=152

select * from RCV_TRANSACTIONS WHERE SHIPMENT_HEADER_ID= 1114786  --and SHIPMENT_LINE_ID = 1283524 --and TRANSACTION_TYPE = 'DELIVER'  

select *   from RCV_TRANSACTIONS WHERE SHIPMENT_HEADER_ID= 1114786 -- and TRANSACTION_TYPE = 'DELIVER'  

select  TRANSACTION_ID, SHIPMENT_HEADER_ID ,SHIPMENT_LINE_ID , ATTRIBUTE5 CHALLAN_NO,ATTRIBUTE6 CHALLAN_QTY, ATTRIBUTE9 CHALLAN_DATE, ATTRIBUTE7 Vehicle_NO 
from RCV_TRANSACTIONS WHERE SHIPMENT_HEADER_ID= 1111381  --and SHIPMENT_LINE_ID = 1283524

--------- Challan Date  Update---------
UPDATE RCV_TRANSACTIONS
SET ATTRIBUTE9 = '2019/12/31 00:00:00'  --CHALLAN DATE
WHERE  TRANSACTION_ID=1222740
and TRANSACTION_TYPE = 'DELIVER'

--------- Challan Qty Update---------
UPDATE RCV_TRANSACTIONS
SET ATTRIBUTE6= '4500.000' --- CHALLAN QTY
WHERE  TRANSACTION_ID=1310019
--and TRANSACTION_TYPE = 'DELIVER'


--------- Challan NO Update---------
UPDATE RCV_TRANSACTIONS
SET  ATTRIBUTE5= 77 --- CHALLAN NO
--ATTRIBUTE7 = NULL
 WHERE SHIPMENT_HEADER_ID= 1111381 

--======= LC NUMBER  Correction process ===============
--*****************************************************
-- QUERY TO GET LC NUMBER AND TRANSACTION NUMBER
--****************************************************

SELECT c.transaction_id ,a.SHIPMENT_HEADER_ID,a.ship_to_org_id,a.shipment_num,a.CREATION_DATE,a.SHIPPED_DATE,a.EXPECTED_RECEIPT_DATE, c.ATTRIBUTE3 LC_ID,
b.LAST_UPDATE_DATE ,c.TRANSACTION_DATE MMT_TRANS_DATE,TO_DATE('12/21/2020 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM') NEW_DATE
from RCV_SHIPMENT_HEADERS a, rcv_shipment_lines b, MTL_MATERIAL_TRANSACTIONS c
where a.shipment_header_id= b.shipment_header_id
and a.ship_to_org_id =  b.TO_ORGANIZATION_ID
and b.TO_ORGANIZATION_ID   = c.TRANSFER_ORGANIZATION_ID
and a.shipment_num = c.SHIPMENT_NUMBER
and a.ORGANIZATION_ID = c.ORGANIZATION_ID
and b.MMT_TRANSACTION_ID = c.TRANSACTION_ID
and a.shipment_num= 'INT-KBD-0026464' 
--and a.ship_to_org_id= 201

SELECT * FROM XX_LC_DETAILS WHERE LC_NUMBER='1743-22-01-0356' -- 11207

SELECT LC_ID,LC_NUMBER FROM XX_LC_DETAILS WHERE LC_ID IN(11265) --='0731-22-01-0094'

SELECT ATTRIBUTE3 LC_ID, TRANSACTION_ID FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID IN( 15554457,15554458) --ATTRIBUTE3='11208' --'11207'

--UPDATE MTL_MATERIAL_TRANSACTIONS
--SET ATTRIBUTE3='11207' 
--WHERE TRANSACTION_ID = 15554457


--- Remarks Update---------

--UPDATE RCV_TRANSACTIONS
--SET COMMENTS= 'Total Challan qty 52000 kg, Excess Found 200 kg' --- CHALLAN QTY
--WHERE  TRANSACTION_ID IN (
--1240633,
--1240634,
--1240623,
--1240625,
--1240628,
--1240629
--)
--and TRANSACTION_TYPE = 'DELIVER'

Total Challan qty 52000 kg, short rcvd 700 kg


--========================================VEHICLE NUMBER UPDATE===============================

SELECT * FROM XXKSRM_INV_USE_AREA_V where USE_AREA LIKE  '%CM-TA-05-1184%'

SELECT * FROM MTL_TXN_REQUEST_HEADERS WHERE REQUEST_NUMBER='MO-TRA-0063953'

SELECT * FROM MTL_TXN_REQUEST_LINES WHERE HEADER_ID= 2214273  --and  LINE_ID=2936514

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID IN (14637930)  

SELECT * FROM XXKSRM_INV_USE_AREA_V where USE_AREA LIKE  'CRANE%65%'


UPDATE MTL_TXN_REQUEST_LINES 
SET ATTRIBUTE2 = 403
WHERE HEADER_ID= 2214273
and LINE_ID=3087991


--=====================MISCELINIUS RECEIPT ISSUE DATE UPDATE SCRIPT==================================

 select * from MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID IN ( 13252414, 13252455)
 
-- update MTL_MATERIAL_TRANSACTIONS
-- SET CREATION_DATE = TO_DATE('1/31/2022 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
-- TRANSACTION_DATE=TO_DATE('1/31/2022 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
-- LAST_UPDATE_DATE=TO_DATE('1/31/2022 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
-- WHERE TRANSACTION_ID IN ( 13252414, 13252455)







---- MTL_MATERIAL_TRANSACTION TABLE UPDATE 
--
--BEGIN
--FOR i IN(
--select a.ORGANIZATION_ID ORG_ID, a.TRANSACTION_ID TRANS_ID ,b.TRANSACTION_DATE, b.RCV_TRANSACTION_ID , TO_DATE('4/30/2020 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM') new_date
-- from RCV_TRANSACTIONS a, MTL_MATERIAL_TRANSACTIONS b
--where a.TRANSACTION_ID = b.RCV_TRANSACTION_ID
--and a.TRANSACTION_TYPE = 'DELIVER' 
--and a.ORGANIZATION_ID = b.ORGANIZATION_ID
--and a.SHIPMENT_HEADER_ID = 1006171
----and ORGANIZATION_ID = 
--)
--LOOP
--UPDATE MTL_MATERIAL_TRANSACTIONS
--set  LAST_UPDATE_DATE = i.new_date,
--CREATION_DATE = i.new_date,
--PROGRAM_UPDATE_DATE= i.new_date,
--TRANSACTION_DATE=i.new_date
--where RCV_TRANSACTION_ID = i.TRANS_ID
--and ORGANIZATION_ID = i.ORG_ID;
--END LOOP;
--END;




select * from MTL_MATERIAL_TRANSACTIONS 





--
--
--
--UPDATE RCV_SHIPMENT_HEADERS 
--SET 
--LAST_UPDATE_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
--CREATION_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
----ATTRIBUTE13 = '2020/12/31 00:00:00'
--WHERE 1=1
--AND SHIPMENT_HEADER_ID  = 1035373
--AND SHIP_TO_ORG_ID = 160
--
-- 
--SELECT * FROM RCV_SHIPMENT_LINES RSL 
--where 1=1
--and RSL.SHIPMENT_HEADER_ID = 1032311
-- AND RSL.TO_ORGANIZATION_ID = 163
--
--UPDATE  RCV_SHIPMENT_LINES
--SET LAST_UPDATE_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
--CREATION_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
--PROGRAM_UPDATE_DATE =TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
--WHERE 1=1
--AND SHIPMENT_HEADER_ID = 1035373
--AND TO_ORGANIZATION_ID = 160
--
--
--
--
--    
--SELECT * FROM  RCV_TRANSACTIONS WHERE SHIPMENT_HEADER_ID = 1032311 AND ORGANIZATION_ID = 163
--    
--UPDATE  RCV_TRANSACTIONS
--SET LAST_UPDATE_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
--CREATION_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
--PROGRAM_UPDATE_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
--TRANSACTION_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
--CURRENCY_CONVERSION_DATE =TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
----ATTRIBUTE9 = '2019/12/31 00:00:00'
--WHERE 1=1
--AND SHIPMENT_HEADER_ID =1035373 
--AND ORGANIZATION_ID = 160
--
--
---- MTL_MATERIAL_TRANSACTION TABLE UPDATE 
---------------------------
--
SELECT * FROM RCV_SHIPMENT_HEADERS RSH 
where receipt_num= 80017954  AND SHIP_TO_ORG_ID =163

SELECT * FROM  RCV_TRANSACTIONS 
WHERE 1=1
AND SHIPMENT_HEADER_ID =  1036259 
 AND ORGANIZATION_ID = 163 and TRANSACTION_TYPE = 'DELIVER'


select * from MTL_MATERIAL_TRANSACTIONS where RCV_TRANSACTION_ID IN (
937577,
937578
)
and  ORGANIZATION_ID = 163




Update MTL_MATERIAL_TRANSACTIONS
SET LAST_UPDATE_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
CREATION_DATE =TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
TRANSACTION_DATE=TO_DATE('1/31/2021 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
WHERE 1=1
and ORGANIZATION_ID = 163
AND RCV_TRANSACTION_ID IN (
937577,
937578
)



--Select  rt.transaction_DATE, MTT.*
-- from mtl_material_transactions mtt , rcv_shipment_headers rsh , rcv_shipment_lines rsl,rcv_transactions rt
--where rsh.SHIPMENT_HEADER_ID=rsl.SHIPMENT_HEADER_ID
--and rsl.SHIPMENT_HEADER_ID=rt.SHIPMENT_HEADER_ID
--and rsl.SHIPMENT_LINE_ID=rt.SHIPMENT_LINE_ID
--and rt.transaction_id=mtt.RCV_TRANSACTION_ID
----and rt.transaction_type='DELIVER'
--and RSH.RECEIPT_NUM=80000433
----and  MTT.TRANSACTION_DATE = TO_DATE('12/26/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
--AND RSH.SHIP_TO_ORG_ID = 160

SELECT * FROM RCV_SHIPMENT_HEADERS  where SHIPMENT_HEADER_ID=1031722

SELECT * FROM RCV_SHIPMENT_LINES  where SHIPMENT_HEADER_ID=1031722

select * from RCV_TRANSACTIONS where SHIPMENT_HEADER_ID=1031722


SELECT * FROM  mtl_material_transactions where SHIPMENT_NUMBER in ('4201010000220')

select * from RCV_SHIPMENT_HEADERS where receipt_num = 80000291 AND SHIP_TO_ORG_ID = 149


select * from RCV_TRANSACTIONS WHERE TRANSACTION_ID = 851249

select  * from mtl_material_transactions where RCV_TRANSACTION_ID= 851249


SET 

5500688
8098675



--------------------------------------------------------------------------------------------------------------------------------------------------->
---->
--         commit;
--        2020/04/01 00:00:00
--       40004070 kspl
--      3949






SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID IN (11083285,
11083284,
11083293)



--FIRST RUN THIS QUERY TO GET TRANSACTION ID THEN UPDATE 

SELECT MMT.TRANSACTION_ID,MMT.TRANSACTION_DATE,
TOH.HEADER_ID,
  TOL.ORGANIZATION_ID,
  TOH.REQUEST_NUMBER,
  TOH.HEADER_ID,
  TOL.LINE_NUMBER,
  TOL.LINE_ID,
  TOL.INVENTORY_ITEM_ID,
  TOH.DESCRIPTION,
  TOH.MOVE_ORDER_TYPE,
  TOL.LINE_STATUS,
  TOL.QUANTITY,
  TOL.QUANTITY_DELIVERED,
  TOL.QUANTITY_DETAILED
FROM MTL_TXN_REQUEST_HEADERS TOH,
  MTL_TXN_REQUEST_LINES TOL,
  MTL_MATERIAL_TRANSACTIONS MMT
WHERE TOH.HEADER_ID = TOL.HEADER_ID
 AND TOH.ORGANIZATION_ID= TOL.ORGANIZATION_ID
 AND TOL.LINE_ID = MMT.MOVE_ORDER_LINE_ID(+)
 AND REQUEST_NUMBER='MO-KBM-0119177'
 --AND toh.request_number = '0090175'   

--============================RUN THIS QUERY TO GET HEADER ID OF MOVE ORDER ==============

select * from MTL_TXN_REQUEST_HEADERS where request_number='MO-KSO-0001478' -- 'MO-KBM-0104242'

select * from MTL_TXN_REQUEST_LINES where header_id = 1650564

--=============================================================================

UPDATE MTL_TXN_REQUEST_HEADERS
SET
CREATION_DATE = TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
LAST_UPDATE_DATE=TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
DATE_REQUIRED=TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
where header_id= 1655369


SELECT * FROM MTL_TXN_REQUEST_LINES MTRL where header_id= 1643405 

UPDATE MTL_TXN_REQUEST_LINES
SET
CREATION_DATE= TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
LAST_UPDATE_DATE = TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
DATE_REQUIRED = TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
STATUS_DATE= TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
where header_id= 1655369
--and ORGANIZATION_ID = 163



SELECT * FROM MTL_MATERIAL_TRANSACTIONS where TRANSACTION_ID  IN(9183156,
9183211)

UPDATE MTL_MATERIAL_TRANSACTIONS
SET
CREATION_DATE=TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
LAST_UPDATE_DATE=TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
TRANSACTION_DATE=TO_DATE('12/31/2019 01:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM')
where TRANSACTION_ID  IN(
9325929,
9325934,
9325936,
9325920,
9325925,
9325901,
9325902,
9325904,
9325907,
9325916,
9325917,
9325937,
9325933,
9325909,
9325923,
9325910,
9325914,
9325924,
9325927,
9325908,
9325931,
9325912,
9325919,
9325932,
9325935,
9325930,
9325926,
9325900,
9325903,
9325905,
9325906,
9325915,
9325918,
9325922,
9325911,
9325921,
9325913,
9325928)









--=========================================================================================================
--RUN THIS MOVE ORDER REPORT TO GET TRANSACTION ID FROM MTL MATERIAL TRANSACTIONS TABLE, THEN UPDATE ACCORDING TO TRANSACTION_ID
--=========================================================================================================

SELECT    xx.TRANSACTION_ID
                , MTRL.ORGANIZATION_ID
                ,NVL((SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') ORG_NAME
                ,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY) DEPARTMENT
               ,(SELECT DISTINCT  OTM.TRIPSYS_NO FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) TRIP_NO
              ,(SELECT DISTINCT DECODE(OTM.EMPLOYEE_ID,NULL,UNLISTED_DRIVER,(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = OTM.EMPLOYEE_ID)) DRIVER_NAME FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) DRIVER_NAME
                ,MTRL.ATTRIBUTE15 GATE_PASS_NO
                ,XX_INV_PKG.XXGET_CUSTOMER_NAME((SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) ) CUSTOMER_NAME           
             ---- ,(SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) CUSTOMER_NAME
               ,(SELECT ATTRIBUTE1 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Move Order Issue' AND HEADER_ID=MTHL.HEADER_ID) WORK_ORDER_NO
                ,MTRL.REQUEST_NUMBER MOVE_ORDER_NUMBER
                ,MTRL.DATE_REQUIRED  MOVE_ORDER_DATE
                ,MTRL.TRANSACTION_TYPE_NAME MOVE_ORDER_TYPE
                ,ML.MEANING MO_STATUS_LINE
                ,MTHL.HEADER_STATUS_NAME  MO_STATUS
                ,(SELECT ATTRIBUTE9 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Issue to Project' AND HEADER_ID=MTHL.HEADER_ID) PROJECT_NAME
                ,MTRL.LINE_NUMBER
                , (MSI.SEGMENT1 || '|' || MSI.SEGMENT2 || '|' || MSI.SEGMENT3||'|' || MSI.SEGMENT4)    ITEM_CODE
                ,MSI.DESCRIPTION
                ,MTRL.UOM_CODE
                ---=========================================
                ,MTRL.FROM_SUBINVENTORY_CODE
                ,MTRL.INVENTORY_ITEM_ID
                ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
                , (SELECT NVL(SUM(PRIMARY_QUANTITY),0)
                FROM 
                MTL_MATERIAL_TRANSACTIONS
                WHERE 
                ORGANIZATION_ID=MTRL.ORGANIZATION_ID
                AND SUBINVENTORY_CODE=NVL(MTRL.FROM_SUBINVENTORY_CODE,SUBINVENTORY_CODE)
                AND INVENTORY_ITEM_ID=MTRL.INVENTORY_ITEM_ID 
                AND  TRANSACTION_DATE <MTRL.DATE_REQUIRED) IO_STOCK
                ---=========================================
                ,MTRL.QUANTITY  MO_QTY
                ,XX.QTY_ISSUED MO_ISSUE_QTY
                ,CASE WHEN MTRL.LINE_STATUS <>5 THEN 0   ELSE (MTRL.QUANTITY-MTRL.QUANTITY_DELIVERED)  END  CANCEL_QTY
                ,XX.SUBINVENTORY_CODE
                , (SELECT SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4||'|'||SEGMENT5 LOCATOR_DESC FROM MTL_ITEM_LOCATIONS WHERE INVENTORY_LOCATION_ID=XX.LOCATOR_ID AND ORGANIZATION_ID=MTRL.ORGANIZATION_ID) LOCATOR
                ,XX.LOT_NUMBER
                ,XX_INV_PKG.XXGET_SERIAL_NUMBER(XX.TRANSACTION_ID) SERIAL_NUMBER
               ----,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 AND OU_ID=(SELECT OPERATING_UNIT_ID FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MTRL.ORGANIZATION_ID)) USEOFAREA
               ,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 ) USEOFAREA
                ,MTRL.REFERENCE REASON
                ---===================================================
                ,MTHL.DESCRIPTION PURPOSE
                ,XX.TRACKING_REMARKS
                ,MTHL.CREATED_BY PREPARED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(MTHL.CREATED_BY )  PREPARED_BY
                ,XX.TAKEN_BY
                ----===========HOD=====================
                ,(XX_INV_PKG.XXGET_ENAME ((SELECT USER_ID FROM FND_USER 
                WHERE USER_NAME =(SELECT APPROVED_BY FROM XXKSRM_MOAPPROVAL_STATUS
                WHERE HEADER_ID=MTHL.HEADER_ID AND WF_STATUS='Approved')))) HOD
                ----===========HOD=====================
                --,DECODE(MTHL.HEADER_STATUS,
                --3,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --7,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --8,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --NULL
                --) HOD
               ---- ,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)) HOD
                ----===========HOD=====================
                ----===========HOD=====================
                ,XX.ISSUED_STORE STORE_IN_CHARGE_ID
                , XX_INV_PKG.XXGET_ENAME(XX.ISSUED_STORE) STORE_IN_CHARGE
                ,XX.CREATED_BY ISSUED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.CREATED_BY) ISSUED_BY
                ,XX.RECEIVED_STORE  RECEIVED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.RECEIVED_STORE)  RECEIVED_BY
                ,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
                ,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') PORG_NAME
                ,NVL((SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORG),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
                ----=====================================================
        FROM   MTL_TXN_REQUEST_HEADERS_V MTHL
          ,MTL_TXN_REQUEST_LINES_V MTRL
          ,MTL_SYSTEM_ITEMS_B MSI
          ,MFG_LOOKUPS ML
          , (  SELECT   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.ATTRIBUTE1 TAKEN_BY
                       ,MMT.ATTRIBUTE11 TRACKING_REMARKS 
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MAX (MMT.CREATED_BY) CREATED_BY
                       ,MMT.TRANSACTION_ID
                       , (MMT.TRANSACTION_DATE) TRANSACTION_DATE
                       ,SUM (ABS (MMT.PRIMARY_QUANTITY)) QTY_ISSUED
                       ,MTLN.LOT_NUMBER
                      ,MMT.ATTRIBUTE1 ISSUED_STORE
                       ,MMT.ATTRIBUTE2 RECEIVED_STORE
                 FROM   MTL_MATERIAL_TRANSACTIONS MMT
                       ,MTL_TRANSACTION_LOT_NUMBERS MTLN
                WHERE   MMT.PRIMARY_QUANTITY < 0
                    AND MMT.ORGANIZATION_ID = :P_ORG
                    AND MMT.TRANSACTION_SOURCE_TYPE_ID = 4
                    AND MTLN.TRANSACTION_ID(+)=MMT.TRANSACTION_ID
             GROUP BY   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.ATTRIBUTE1
                       ,MMT.ATTRIBUTE11
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MTLN.LOT_NUMBER
                       ,MMT.ATTRIBUTE1 
                       ,MMT.ATTRIBUTE2 
                       ,(MMT.TRANSACTION_DATE)
                       ,MMT.TRANSACTION_ID) XX
   WHERE   MTRL.REQUEST_NUMBER = MTHL.REQUEST_NUMBER
       AND MTRL.HEADER_ID = MTHL.HEADER_ID
       AND MTRL.ORGANIZATION_ID = MTHL.ORGANIZATION_ID
       --TRANSACTION_TYPE_ID
       AND MTRL.LINE_STATUS = ML.LOOKUP_CODE
       AND ML.LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
       --AND UPPER(MTRL.transaction_type_name)='MOVE ORDER ISSUE'
       AND MTRL.ORGANIZATION_ID = NVL (:P_ORG, MTRL.ORGANIZATION_ID)
       AND MTRL.REQUEST_NUMBER = NVL (:P_FROM_MO, MTRL.REQUEST_NUMBER)
       AND TRUNC(MTHL.DATE_REQUIRED) BETWEEN NVL(:P_FROM_DATE,TRUNC(MTHL.DATE_REQUIRED))  AND  NVL(:P_TO_DATE,TRUNC(MTHL.DATE_REQUIRED))
       AND MTRL.INVENTORY_ITEM_ID =NVL(:P_ITEM_ID,MTRL.INVENTORY_ITEM_ID)
       AND MTHL.HEADER_STATUS_NAME =NVL(:P_MO_STATUS,HEADER_STATUS_NAME)
    --   AND MTRL.transaction_source_type_id = 4
       AND MTRL.ORGANIZATION_ID = XX.ORGANIZATION_ID(+)
       AND MTRL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MTRL.INVENTORY_ITEM_ID = XX.INVENTORY_ITEM_ID(+)
       AND MTRL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MTRL.LINE_ID = XX.MOVE_ORDER_LINE_ID(+)
       AND MTRL.HEADER_ID = XX.TRANSACTION_SOURCE_ID(+)
     --  AND MTRL.transaction_type_id = XX.transaction_type_id
       --AND MTRL.request_number='2002'
ORDER BY  MTRL.DATE_REQUIRED, MTRL.REQUEST_NUMBER,MTRL.LINE_NUMBER ---- XX.TAKEN_BY











--================================


 
 select * from MTL_MATERIAL_TRANSACTIONS where TRANSACTION_ID IN (8280777,8280804)
 
 select * from GL_CODE_COMBINATIONS
 
 select DISTINCT(LINE_STATUS) from  MTL_TXN_REQUEST_LINES --MFG_LOOKUPS ML
 
        SELECT  *  FROM   MTL_TXN_REQUEST_HEADERS_V MTHL
        
          SELECT * FROM MTL_TXN_REQUEST_LINES_V MTRL where MOVE_ORDER_LINE_ID in()
          
          select * from  MTL_TXN_REQUEST_LINES where line_id in(1568283,1568284)
          
          
          select    LOOKUP_CODE from MFG_LOOKUPS ML
          
          
          select * from MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID IN ( 13252414, 13252455)
          
            select * from MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID= 13252455