SELECT 
distinct aia.org_id, XX_GET_REQUESTER_FROM_PR(AIA.org_id,GET_PR_NUMBER_FROM_PO(POH.org_id,POH.SEGMENT1),POL.ITEM_ID) Requester,
SUBSTR(XX_GET_HR_OPERATING_UNIT (AIA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (AIA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
 APS.VENDOR_NAME, 
 APS.SEGMENT1 VENDOR_NO,
 GET_PR_NUMBER_FROM_PO(aia.org_id,POH.SEGMENT1) REQUISITION_NUMBER,
 POH.SEGMENT1 PO_NUMBER,
 POH.APPROVED_DATE  PO_APPROVED_DATE,
  XX_GET_EMP_NAME_FROM_USER_ID (POH.CREATED_BY) BUYER,
   (
 SELECT DESCRIPTION
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_DESCRIPTION,
    (
 SELECT SEGMENT1||'|'||SEGMENT2||'|'|| SEGMENT3||'|'|| SEGMENT4
 FROM MTL_SYSTEM_ITEMS_B
 WHERE INVENTORY_ITEM_ID = POL.ITEM_ID
 AND ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
 ) ITEM_CODE,
 -- XXGET_ITEM_CODE(ITEM_ID) ITEM_CODE,
 POL.UNIT_PRICE  UNIT_PRICE,
 POH.RATE RATE ,
POL.QUANTITY PO_QUANTITY,
( POL.QUANTITY* POL.UNIT_PRICE)*NVL(POH.RATE,1) PO_AMOUNT,
RT. QUANTITY GRN_QUANTITY,
(RT. QUANTITY* POL.UNIT_PRICE)*NVL(POH.RATE,1) GRN_AMOUNT,
--  (
--  SELECT SUM ( (PLA.UNIT_PRICE * PLA.QUANTITY)) PRICE
--   FROM PO_LINES_ALL PLA, PO_HEADERS_ALL PHA
--   WHERE PLA.PO_HEADER_ID = PHA.PO_HEADER_ID
--   AND PHA.ORG_ID = AIA.ORG_ID
--   AND PHA.SEGMENT1 =POH.SEGMENT1
--         ) PO_AMOUNT,
 RSH.RECEIPT_NUM GRN_NUMBER, 
RT.CREATION_DATE GRN_DATE,
--RL.QUANTITY_RECEIVED,
--RT.QUANTITY QUANTITY_DELIVERED,
 AIA.INVOICE_NUM,
 AIA.INVOICE_DATE,
AIA.GL_DATE ,
AIA.INVOICE_AMOUNT, 
 AIA.DOC_SEQUENCE_VALUE INV_VOUCHER_NO,
 XX_GET_EMP_NAME_FROM_USER_ID (AIA.CREATED_BY) INV_CREATED_BY,
 ( SELECT CONCATENATED_SEGMENTS
 FROM GL_CODE_COMBINATIONS_KFV
 WHERE CODE_COMBINATION_ID = AIDA.DIST_CODE_COMBINATION_ID
 ) DIST_GL_CODE,
ACA.DOC_SEQUENCE_VALUE PAYMENT_VOUCHER,
ACA.CREATION_DATE PAY_CREATE_DATE
,ACA.DOC_CATEGORY_CODE PAYMENT_TYPE
,ACA.STATUS_LOOKUP_CODE PAYMENT_STATUS
,ACA.AMOUNT PAY_AMOUNT
,XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
FROM AP_INVOICES_ALL AIA,
 AP_INVOICE_LINES_ALL AILA,
 AP_SUPPLIERS APS,
 AP_SUPPLIER_SITES_ALL APSS,
 AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
 PO_HEADERS_ALL POH,
 PO_LINES_ALL POL,
 PO_LINE_LOCATIONS_ALL PLL,
 PO_DISTRIBUTIONS_ALL PDA,
 RCV_SHIPMENT_HEADERS RSH,
 RCV_SHIPMENT_LINES RL,
  RCV_TRANSACTIONS RT,
AP_INVOICE_PAYMENTS_ALL AIPA, 
AP_CHECKS_ALL ACA
WHERE AIA.INVOICE_ID = AILA.INVOICE_ID
AND AILA.ORG_ID = AIA.ORG_ID
AND AILA.PO_HEADER_ID = POH.PO_HEADER_ID
AND AILA.PO_LINE_ID = POL.PO_LINE_ID
AND AILA.INVOICE_ID =AIDA.INVOICE_ID
AND AIA.VENDOR_ID = APS.VENDOR_ID
AND AIA.VENDOR_SITE_ID = APSS.VENDOR_SITE_ID
AND AIA.VENDOR_ID = APSS.VENDOR_ID
AND APSS.ORG_ID = AIA.ORG_ID
AND AIDA.INVOICE_LINE_NUMBER = AILA.LINE_NUMBER
AND AIDA.ORG_ID= AILA.ORG_ID
AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND PLL.PO_HEADER_ID = POH.PO_HEADER_ID
AND PLL.PO_LINE_ID = POL.PO_LINE_ID
AND PLL.LINE_LOCATION_ID = PDA.LINE_LOCATION_ID
AND PLL.PO_HEADER_ID = PDA.PO_HEADER_ID
AND PLL.PO_LINE_ID = PDA.PO_LINE_ID
AND POL.ORG_ID = PDA.ORG_ID
AND POH.ORG_ID = PLL.ORG_ID
AND AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
AND RT.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
AND RSH.SHIPMENT_HEADER_ID =RL.SHIPMENT_HEADER_ID 
AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
AND AIA.INVOICE_ID=AIPA.INVOICE_ID(+)
AND AIPA.CHECK_ID=ACA.CHECK_ID(+)
AND PDA.GL_CANCELLED_DATE is NULL
AND (:P_ORG_ID IS NULL OR AIA.ORG_ID = :P_ORG_ID) --AP org id
--AND (:P_VENDOR_NO IS NULL OR aps.segment1 = :P_VENDOR_NO) --aps.segment1 for supplier/vendor name
AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
AND (:P_PO_NO IS NULL OR poh.segment1 = :P_PO_NO) 
AND (:P_GRN_NO IS NULL OR rsh.receipt_num = :P_GRN_NO)
and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
 and AIA.VENDOR_ID = NVL(:P_VENDOR_ID, AIA.VENDOR_ID)
  AND POH.ATTRIBUTE1 = 'L'
  
union all
SELECT 
distinct PHA.org_id, XX_GET_REQUESTER_FROM_PR(PHA.org_id,GET_PR_NUMBER_FROM_PO(pha.org_id,pha.SEGMENT1),PLA.ITEM_ID) Requester,
XX_GET_DEPT_FROM_REQUESTER(XX_GET_REQUESTER_FROM_PR(PHA.org_id,GET_PR_NUMBER_FROM_PO(pha.org_id,pha.SEGMENT1),PLA.ITEM_ID)) DEPT,
--GET_REQUESTER(GET_PR_REQUESTER_FROM_PR(PHA.org_id,GET_PR_NUMBER_FROM_PO(pha.org_id,pha.SEGMENT1),PLA.ITEM_ID)),
 --XX_GET_EMP_NAME_FROM_USER_ID (GET_PR_REQUESTER_FROM_PR(PHA.org_id,GET_PR_NUMBER_FROM_PO(pha.org_id,pha.SEGMENT1),PLA.ITEM_ID)) REQUESTED_BY,
SUBSTR(XX_GET_HR_OPERATING_UNIT (PHA.ORG_ID),5) OPERATING_UNIT,
XX_INV_PKG.XXGET_ORG_LOCATION (PHA.ORG_ID) ORG_ADDRESS,
RT.ORGANIZATION_ID INV_ORG,
RT.TRANSACTION_DATE,
INVORG_NAME_FROM_ID (RT.ORGANIZATION_ID) INV_ORG_NAME,
       ASP.VENDOR_NAME,
       ASP.SEGMENT1 VENDOR_NO,
      PHA.SEGMENT1 PO_NUMBER,
       GET_PR_NUMBER_FROM_PO(pha.org_id,pha.SEGMENT1) REQUISITION_NUMBER,
       PHA.APPROVED_DATE  PO_APPROVED_DATE,
         XX_GET_EMP_NAME_FROM_USER_ID (PHA.CREATED_BY) BUYER,
           PLA.ITEM_DESCRIPTION,
            XXGET_ITEM_CODE(PLA.ITEM_ID) ITEM_CODE,
             PHA.RATE RATE,
  PLA.UNIT_PRICE RATE ,
  PLA.QUANTITY PO_QUANTITY,
 (PLA.QUANTITY* PLA.UNIT_PRICE)*NVL(PHA.RATE,1) PO_AMOUNT,
  RT. QUANTITY GRN_QUANTITY,
  (RT. QUANTITY* PLA.UNIT_PRICE)* NVL(PHA.RATE,1) GRN_AMOUNT,
          RH.RECEIPT_NUM GRN_NUMBER, 
          RT.CREATION_DATE GRN_DATE,
--          RL.QUANTITY_RECEIVED,
--         RT.QUANTITY QUANTITY_DELIVERED,
            NULL INVOICE_NUM,
            NULL INVOICE_DATE,
            NULL GL_DATE,
            NULL INVOICE_AMOUNT,
            NULL INV_VOUCHER_NO,
            NULL INV_CREATED_BY,
          NULL DIST_GL_CODE,
          NULL PAYMENT_VOUCHER,
          NULL PAY_CREATE_DATE,
          NULL PAYMENT_TYPE,
          NULL PAYMENT_STATUS,
          NULL PAY_AMOUNT,
         XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
 from PO_HEADERS_ALL PHA, PO_LINES_ALL PLA, PO_LINE_LOCATIONS_ALL PLL,PO_DISTRIBUTIONS_ALL PDA, AP_SUPPLIERS ASP,
 RCV_TRANSACTIONS RT,RCV_SHIPMENT_LINES RL, RCV_SHIPMENT_HEADERS RH
 WHERE PHA.PO_HEADER_ID =PLA.PO_HEADER_ID
 and PHA.po_header_id = PLA.po_header_id
 and PLA.po_line_id= pll.po_line_id
 and PHA.po_header_id= pll.po_header_id
 and PHA.PO_HEADER_ID= PLA.PO_HEADER_ID
 AND PLA.PO_LINE_ID= PDA.PO_LINE_ID
 AND PLA.QUANTITY <> 0
 AND PHA.PO_HEADER_ID= RT.PO_HEADER_ID
 AND PLA.PO_LINE_ID= RT.PO_LINE_ID
 AND PDA.GL_CANCELLED_DATE is NULL
 AND RT.TRANSACTION_TYPE= 'DELIVER'
    AND PDA.PO_DISTRIBUTION_ID NOT IN
      (SELECT PO_DISTRIBUTION_ID FROM PO_DISTRIBUTIONS_ALL PDA
       WHERE PO_DISTRIBUTION_ID IN (SELECT DISTINCT  PO_DISTRIBUTION_ID FROM AP_INVOICE_DISTRIBUTIONS_ALL))
 AND RH.SHIPMENT_HEADER_ID= RT.SHIPMENT_HEADER_ID
 AND RH.SHIPMENT_HEADER_ID= RL.SHIPMENT_HEADER_ID
 AND RL.SHIPMENT_LINE_ID= RT.SHIPMENT_LINE_ID
 AND ASP.VENDOR_ID= PHA.VENDOR_ID
   AND (:P_ORG_ID IS NULL OR PHA.ORG_ID = :P_ORG_ID)
  AND (:P_GRN_FROM_DT IS NULL OR TRUNC(RT.TRANSACTION_DATE) BETWEEN :P_GRN_FROM_DT AND :P_GRN_TO_DT) 
  AND (:P_PO_NO IS NULL OR PHA.segment1 = :P_PO_NO) 
  AND (:P_GRN_NO IS NULL OR rh.receipt_num = :P_GRN_NO) 
  and RT.ORGANIZATION_ID = NVL(:P_INV_ORG, RT.ORGANIZATION_ID ) 
   and PHA.VENDOR_ID = NVL(:P_VENDOR_ID, PHA.VENDOR_ID)
   AND PHA.ATTRIBUTE1 = 'L'
   
   --========================For Data Checking ================================
   select DISTINCT *  from  PER_position_definitions where POSITION_DEFINITION_ID=1344

select * from PO_REQUISITION_HEADERS_ALL WHERE SEGMENT1 IN(10005294)  and org_id=81 --- 10000046

select *  from PO_REQUISITION_LINES_ALL where REQUISITION_HEADER_ID IN(1414400) --> TO_PERSON_ID

select * from PO_REQ_DISTRIBUTIONS_ALL where REQUISITION_LINE_ID=1017961  


select * from PER_ALL_POSITIONS where POSITION_ID=1157

select * from PER_ALL_PEOPLE_F WHERE FIRST_NAME LIKE '%KG-4887%' --  Md. Jalal Uddin (KG-4887)

select * from PER_ALL_PEOPLE_F WHERE PERSON_ID IN(1213)

select * from FND_USER where USER_NAME= 'KG-1503'
--====================================================================






CREATE OR REPLACE FUNCTION GET_PR_REQUESTER_FROM_PR(P_ORG_ID in number,P_PR_NUMBER IN NUMBER,P_ITEM_ID IN NUMBER)
return VARCHAR2
IS
V_REQUESTER  VARCHAR2 (50);
BEGIN
SELECT  PRL.TO_PERSON_ID INTO V_REQUESTER
  FROM PO_REQUISITION_HEADERS_ALL PRH, PO_REQUISITION_LINES_ALL PRL
WHERE PRH.REQUISITION_HEADER_ID= PRL.REQUISITION_HEADER_ID
--AND PRL.TO_PERSON_ID= 1157
AND PRH.ORG_ID=P_ORG_ID
AND PRH.SEGMENT1=P_PR_NUMBER
AND PRL.ITEM_ID= P_ITEM_ID ;
RETURN V_REQUESTER;
EXCEPTION WHEN OTHERS THEN
RETURN NULL;
END;

--====================

CREATE OR REPLACE FUNCTION XX_GET_REQUESTER_FROM_PR(P_ORG_ID in number,P_PR_NUMBER IN NUMBER,P_ITEM_ID IN NUMBER)
return VARCHAR2
IS
V_REQUESTER  VARCHAR2 (100);
BEGIN
SELECT  PAF.FULL_NAME INTO V_REQUESTER
  FROM PO_REQUISITION_HEADERS_ALL PRH, PO_REQUISITION_LINES_ALL PRL, PER_ALL_PEOPLE_F PAF
WHERE PRH.REQUISITION_HEADER_ID= PRL.REQUISITION_HEADER_ID
AND PAF.PERSON_ID=PRL.TO_PERSON_ID
--AND PRL.TO_PERSON_ID= 1157
AND PRH.ORG_ID= P_ORG_ID
AND PRH.SEGMENT1=P_PR_NUMBER
AND PRL.ITEM_ID= P_ITEM_ID ;
RETURN V_REQUESTER;
EXCEPTION WHEN OTHERS THEN
RETURN NULL;
END;


CREATE OR REPLACE FUNCTION XX_GET_DEPT_FROM_REQUESTER(P_FULL_NAME IN VARCHAR2)
return VARCHAR2
IS
V_DEPT  VARCHAR2 (100);
BEGIN
SELECT DISTINCT SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1,INSTR(SUBSTR(PAP.NAME,INSTR(PAP.NAME,'.',2,1)+1),'.',1)-1) INTO V_DEPT    
FROM PER_ALL_PEOPLE_F      PAPF
,PER_ALL_ASSIGNMENTS_F PAAF
,PER_ALL_POSITIONS     PAP
,FND_USER   FU 
WHERE PAPF.PERSON_ID=PAAF.PERSON_ID
AND PAPF.CURRENT_EMPLOYEE_FLAG='Y'
AND PAAF.PRIMARY_FLAG='Y'
AND PAAF.POSITION_ID=PAP.POSITION_ID
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAPF.EFFECTIVE_END_DATE)   
AND TRUNC(SYSDATE) BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) 
AND   TRUNC(PAAF.EFFECTIVE_END_DATE)
AND   PAPF.FULL_NAME=P_FULL_NAME;
RETURN V_DEPT;
EXCEPTION WHEN OTHERS THEN
RETURN NULL;
END;





--======================================================

SELECT DISTINCT FULL_NAME 
FROM FND_USER A, PER_ALL_PEOPLE_F B 
WHERE A.USER_NAME= B.FIRST_NAME
--AND A.USER_NAME= 'KG-1503'
AND A.USER_ID=P_USER_ID




XXKBG_BI_PO_GRN WHERE APPROVED_DATE BETWEEN '01-JAN-2022' and '2-JAN-2022'



SELECT * FROM XXKBG_BI_PO_GRN  WHERE OU_ID=81 and  APPROVED_DATE BETWEEN '01-JAN-2022' and '2-JAN-2022'
