--=============================================V1==========================================

-- XXKSRM Item Stock All  V1

SELECT
DISTINCT 
WXMD.ORGANIZATION_ID
,WXMD.ORGANIZATION_CODE
,WXMD.ORGANIZATION_CODE||'-'||WXMD.ORGANIZATION_NAME ORGANIZATION_NAME
,NVL((SELECT OPERATING_UNIT_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORGANIZATION_ID),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') ORGANIZATION_ADDRESS
,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORGANIZATION_ID),'KABIR GROUP') ORG_NAME
,WXMD.INVENTORY_ITEM_ID
,WXMD.ITEM_TYPE
,WXMD.ITEM_GROUP
,WXMD.ITEM_SUB_GROUP
,WXMD.ITEM_CODE
,WXMD.ITEM_DESC
,WXMD.UOM1 UOM
, :P_TRANSACTION_DATE_FROM DATE_FROM 
, :P_TRANSACTION_DATE_TO DATE_TO
, WXMD.FINANCE_CATEGORY FINANCE_CATEGORY
,XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) OPENING_STOCK_NEW
,XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) RECEIVED_QTY_NEW
,XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) ISSUED_QTY_NEW
---------------------------------
,(XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) 
+XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) 
-XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) ) CLOSING_STOCK
-------------------------------------
,(SELECT NVL(MIN_MINMAX_QUANTITY,0) FROM MTL_SYSTEM_ITEMS_B WHERE ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID) SAFETY_STOCK
,MMT.SUBINVENTORY_CODE
,XX_INV_PKG.XX_INV_ITEM_LOCATOR(MMT.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, MMT.INVENTORY_ITEM_ID ) LOCATOR_INFO
----=====================================================
,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
---===============================================================
FROM 
WBI_XXKBGITEM_MT_D WXMD, 
MTL_MATERIAL_TRANSACTIONS MMT
WHERE WXMD.ORGANIZATION_ID=MMT.ORGANIZATION_ID(+)
AND WXMD.INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID(+)
----AND TO_DATE(MMT.TRANSACTION_DATE) BETWEEN TO_DATE(:P_TRANSACTION_DATE_FROM) AND TO_DATE(:P_TRANSACTION_DATE_TO)
AND WXMD.ORGANIZATION_ID=:P_ORGANIZATION_ID
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE)
AND WXMD.ITEM_TYPE=NVL(:P_ITEM_TYPE,WXMD.ITEM_TYPE)
AND WXMD.ITEM_GROUP=NVL(:P_ITEM_GROUP,WXMD.ITEM_GROUP)
AND WXMD.ITEM_SUB_GROUP=NVL(:P_ITEM_SUB_GROUP,WXMD.ITEM_SUB_GROUP)
AND NVL(WXMD.FINANCE_CATEGORY,'XXXX')=NVL(:P_FINANCE_CATEGORY,NVL(WXMD.FINANCE_CATEGORY,'XXXX'))
AND NVL(MMT.SUBINVENTORY_CODE,'XX')=NVL(:P_SUBINVENTORY_CODE,NVL(MMT.SUBINVENTORY_CODE,'XX'))
AND (XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) 
+XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) 
-XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO))>0
ORDER BY 19

--============================================================================================
--XXKSRM Store Ledger Group Wise v1


SELECT
DISTINCT WXMD.ORGANIZATION_ID
,WXMD.ORGANIZATION_CODE
,WXMD.ORGANIZATION_NAME
, (SELECT OPERATING_UNIT_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WXMD.ORGANIZATION_ID)  ORGANIZATION_ADDRESS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
,NVL((SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORGANIZATION_ID),'KABIR GROUP') PORG_NAME
,NVL((SELECT OPERATING_UNIT_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORGANIZATION_ID),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
,WXMD.INVENTORY_ITEM_ID
,WXMD.ITEM_TYPE
,WXMD.ITEM_GROUP
,WXMD.ITEM_SUB_GROUP
,WXMD.FINANCE_CATEGORY
,WXMD.ITEM_CODE
,WXMD.ITEM_DESC
,WXMD.UOM1 UOM
, :P_TRANSACTION_DATE_FROM DATE_FROM 
, :P_TRANSACTION_DATE_TO DATE_TO
,XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) OPENING_STOCK
----===============================================================================================================
,NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (12,61) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0) RECEIVED_QTY_INT_COM
--,NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID  NOT IN (12,61,2,10008,52,59,53) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY>0),0)
---ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (36,71,17,1003) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0 ),0)) RECEIVED_QTY_PO_OTH

,(XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO)
-NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (12,61,2,52,53,43,111,15) AND  TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY>0),0)
-ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (36,71,17,1003) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0 ),0))
) RECEIVED_QTY_PO_OTH
-----===============================================================================================================
,ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN  (35) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0))
-(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID=43 AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0)) ISSUED_QTY_PROD
--,ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID NOT IN  (35,2,52,53) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0),0))ISSUED_QTY_TRA_SAL_OTH
,(XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO)
-ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN  (35,1003,17,71,36,2,52,53) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0),0))
-(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (15,111) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0))
) ISSUED_QTY_TRA_SAL_OTH
----================================================================================================================
,(XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) 
+XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO)
-XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) ) CLOSING_STOCK
----================================================================================================================
,XX_INV_PKG.XXGET_ENAME(:P_USER) USER_NAME
FROM WBI_XXKBGITEM_MT_D WXMD---, MTL_MATERIAL_TRANSACTIONS MMT
WHERE 
--WXMD.ORGANIZATION_ID=MMT.ORGANIZATION_ID
--AND WXMD.INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID
----AND MMT.TRANSACTION_DATE BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO
WXMD.ORGANIZATION_ID=NVL(:P_ORGANIZATION_ID,WXMD.ORGANIZATION_ID)
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE)
AND WXMD.ITEM_TYPE=NVL(:P_ITEM_TYPE,WXMD.ITEM_TYPE)
AND WXMD.ITEM_GROUP=NVL(:P_ITEM_GROUP,WXMD.ITEM_GROUP)
AND WXMD.ITEM_SUB_GROUP=NVL(:P_ITEM_SUB_GROUP,WXMD.ITEM_SUB_GROUP)
AND NVL(WXMD.FINANCE_CATEGORY,'ASDF')=NVL(:P_FINANCE_CATEGORY,NVL(WXMD.FINANCE_CATEGORY,'ASDF'))




--=========================================== MAIN =========================================
-- XXKSRM Item Stock All

SELECT
DISTINCT 
WXMD.ORGANIZATION_ID
,WXMD.ORGANIZATION_CODE
,WXMD.ORGANIZATION_CODE||'-'||WXMD.ORGANIZATION_NAME ORGANIZATION_NAME
,NVL((SELECT OPERATING_UNIT_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORGANIZATION_ID),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') ORGANIZATION_ADDRESS
,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORGANIZATION_ID),'KABIR GROUP') ORG_NAME
,WXMD.INVENTORY_ITEM_ID
,WXMD.ITEM_TYPE
,WXMD.ITEM_GROUP
,WXMD.ITEM_SUB_GROUP
,WXMD.ITEM_CODE
,WXMD.ITEM_DESC
,WXMD.UOM1 UOM
, :P_TRANSACTION_DATE_FROM DATE_FROM 
, :P_TRANSACTION_DATE_TO DATE_TO
, WXMD.FINANCE_CATEGORY FINANCE_CATEGORY
,XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) OPENING_STOCK_NEW
,XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) RECEIVED_QTY_NEW
,XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) ISSUED_QTY_NEW
---------------------------------
,(XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) 
+XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) 
-XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) ) CLOSING_STOCK
-------------------------------------
,(SELECT NVL(MIN_MINMAX_QUANTITY,0) FROM MTL_SYSTEM_ITEMS_B WHERE ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID) SAFETY_STOCK
,MMT.SUBINVENTORY_CODE
,XX_INV_PKG.XX_INV_ITEM_LOCATOR(MMT.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, MMT.INVENTORY_ITEM_ID ) LOCATOR_INFO
----=====================================================
,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
---===============================================================
FROM 
WBI_XXKBGITEM_MT_D WXMD, 
MTL_MATERIAL_TRANSACTIONS MMT
WHERE WXMD.ORGANIZATION_ID=MMT.ORGANIZATION_ID(+)
AND WXMD.INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID(+)
----AND TO_DATE(MMT.TRANSACTION_DATE) BETWEEN TO_DATE(:P_TRANSACTION_DATE_FROM) AND TO_DATE(:P_TRANSACTION_DATE_TO)
AND WXMD.ORGANIZATION_ID=:P_ORGANIZATION_ID
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE)
AND WXMD.ITEM_TYPE=NVL(:P_ITEM_TYPE,WXMD.ITEM_TYPE)
AND WXMD.ITEM_GROUP=NVL(:P_ITEM_GROUP,WXMD.ITEM_GROUP)
AND WXMD.ITEM_SUB_GROUP=NVL(:P_ITEM_SUB_GROUP,WXMD.ITEM_SUB_GROUP)
AND NVL(WXMD.FINANCE_CATEGORY,'XXXX')=NVL(:P_FINANCE_CATEGORY,NVL(WXMD.FINANCE_CATEGORY,'XXXX'))
AND NVL(MMT.SUBINVENTORY_CODE,'XX')=NVL(:P_SUBINVENTORY_CODE,NVL(MMT.SUBINVENTORY_CODE,'XX'))
AND (XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) 
+XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) 
-XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,MMT.SUBINVENTORY_CODE, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO))>0
ORDER BY 19

--============================================================================================
--XXKSRM Store Ledger Group Wise


SELECT
DISTINCT WXMD.ORGANIZATION_ID
,WXMD.ORGANIZATION_CODE
,WXMD.ORGANIZATION_NAME
, (SELECT OPERATING_UNIT_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WXMD.ORGANIZATION_ID)  ORGANIZATION_ADDRESS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
,NVL((SELECT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORGANIZATION_ID),'KABIR GROUP') PORG_NAME
,NVL((SELECT OPERATING_UNIT_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORGANIZATION_ID),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
,WXMD.INVENTORY_ITEM_ID
,WXMD.ITEM_TYPE
,WXMD.ITEM_GROUP
,WXMD.ITEM_SUB_GROUP
,WXMD.FINANCE_CATEGORY
,WXMD.ITEM_CODE
,WXMD.ITEM_DESC
,WXMD.UOM1 UOM
, :P_TRANSACTION_DATE_FROM DATE_FROM 
, :P_TRANSACTION_DATE_TO DATE_TO
,XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) OPENING_STOCK
----===============================================================================================================
,NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (12,61) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0) RECEIVED_QTY_INT_COM
--,NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID  NOT IN (12,61,2,10008,52,59,53) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY>0),0)
---ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (36,71,17,1003) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0 ),0)) RECEIVED_QTY_PO_OTH

,(XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO)
-NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (12,61,2,52,53,43,111,15) AND  TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY>0),0)
-ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (36,71,17,1003) AND    TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0 ),0))
) RECEIVED_QTY_PO_OTH
-----===============================================================================================================
,ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN  (35) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0))
-(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID=43 AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0)) ISSUED_QTY_PROD
--,ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID NOT IN  (35,2,52,53) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0),0))ISSUED_QTY_TRA_SAL_OTH
,(XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO)
-ABS(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN  (35,1003,17,71,36,2,52,53) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO AND PRIMARY_QUANTITY<0),0))
-(NVL((SELECT SUM(PRIMARY_QUANTITY) FROM MTL_MATERIAL_TRANSACTIONS  WHERE INVENTORY_ITEM_ID=WXMD.INVENTORY_ITEM_ID  AND ORGANIZATION_ID=WXMD.ORGANIZATION_ID AND TRANSACTION_TYPE_ID IN (15,111) AND   TRUNC( TRANSACTION_DATE) BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO),0))
) ISSUED_QTY_TRA_SAL_OTH
----================================================================================================================
,(XX_INV_PKG.XX_INV_OPEN_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM) 
+XX_INV_PKG.XX_INV_RECV_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO)
-XX_INV_PKG.XX_INV_ISSU_QTY(WXMD.ORGANIZATION_ID,NULL, WXMD.INVENTORY_ITEM_ID,:P_TRANSACTION_DATE_FROM,:P_TRANSACTION_DATE_TO) ) CLOSING_STOCK
----================================================================================================================
,XX_INV_PKG.XXGET_ENAME(:P_USER) USER_NAME
FROM WBI_XXKBGITEM_MT_D WXMD---, MTL_MATERIAL_TRANSACTIONS MMT
WHERE 
--WXMD.ORGANIZATION_ID=MMT.ORGANIZATION_ID
--AND WXMD.INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID
----AND MMT.TRANSACTION_DATE BETWEEN :P_TRANSACTION_DATE_FROM AND :P_TRANSACTION_DATE_TO
WXMD.ORGANIZATION_ID=NVL(:P_ORGANIZATION_ID,WXMD.ORGANIZATION_ID)
AND WXMD.ITEM_CODE=NVL(:P_ITEM_CODE,WXMD.ITEM_CODE)
AND WXMD.ITEM_TYPE=NVL(:P_ITEM_TYPE,WXMD.ITEM_TYPE)
AND WXMD.ITEM_GROUP=NVL(:P_ITEM_GROUP,WXMD.ITEM_GROUP)
AND WXMD.ITEM_SUB_GROUP=NVL(:P_ITEM_SUB_GROUP,WXMD.ITEM_SUB_GROUP)
AND NVL(WXMD.FINANCE_CATEGORY,'ASDF')=NVL(:P_FINANCE_CATEGORY,NVL(WXMD.FINANCE_CATEGORY,'ASDF'))

--=================================================================================================

