Select *  from FND_CONC_REQ_SUMMARY_V
where USER_CONCURRENT_PROGRAM_NAME like '%SMS%'
order by ACTUAL_COMPLETION_DATE desc 

--- SMS PROCESS 

--XX_SMS_PKG.OD_SMS_GEN

-- XX_SMS_PKG.CHALLAN_SMS_GEN

--=============================================================



--CREATE OR REPLACE PACKAGE BODY APPS.XX_SMS_PKG AS

-------------Start CHALLAN_SMS_GEN ------------------------------------------------
--PROCEDURE CHALLAN_SMS_GEN (ERRORBUF VARCHAR2,RETCODE VARCHAR2,P_ORG_ID NUMBER) IS
V_MSG VARCHAR2(4000);
V_PHONE VARCHAR2(200);
V_SP_PHONE1 VARCHAR2(50);
V_SP_PHONE2 VARCHAR2(50);
V_SP_PHONE3 VARCHAR2(50);
V_SP_PHONE4 VARCHAR2(50);
V_CUST_PHONE VARCHAR2(50);
CURSOR C1 IS
SELECT * FROM XX_ONT_SMS_DELIVERY_V
WHERE CHALLAN_DATE >= SYSDATE-(3/24)
AND ORG_ID = P_ORG_ID
AND DELIVERY_ID NOT IN (SELECT SOURCE_DOC_ID FROM XX_SMS_GEN WHERE PURPOSE = 'CHALLAN')
ORDER BY CHALLAN_DATE;

BEGIN
    
    FOR I IN C1 LOOP
    /* V_MSG := 'Dear Customer ('||I.ACCOUNT_NUMBER||'), Goods delivered '|| I.TOTAL_CHALLAN_QTY||' '|| I.UOM||' ('||I.ALL_ITEMS||'), Dated on '||INITCAP (TRUNC(I.CHALLAN_DATE))||
                    '. Vehicle: '|| I.REG_NO||', Driver Cell No: '||I.DRIVER_CONTACT||', Del. Site: '||INITCAP(I.DELIVERY_ADDRESS) ||chr(10)|| 'Complements of KSRM';  */
    V_MSG := 'Dear '||INITCAP(I.CUSTOMER_NAME)||' ('||I.ACCOUNT_NUMBER||'), Goods delivered '|| I.TOTAL_CHALLAN_QTY||' '|| I.UOM||' ('||I.ALL_ITEMS||'), Dated on '||INITCAP (TRUNC(I.CHALLAN_DATE))||
                    '. Vehicle: '|| I.REG_NO||', Driver Cell No: '||I.DRIVER_CONTACT||', Del. Site: '||INITCAP(I.DELIVERY_ADDRESS) ||chr(10)|| 'Complements of KSRM';                    
    
    V_PHONE        := NULL;
    V_SP_PHONE1 := NULL;
    V_SP_PHONE2 := NULL;
    V_SP_PHONE3 := NULL;
    V_SP_PHONE4 := NULL;
    V_CUST_PHONE := NULL;

    BEGIN
    
        BEGIN
            SELECT DECODE(ATTRIBUTE12,NULL,NULL,',')||ATTRIBUTE12 INTO V_CUST_PHONE
            FROM HZ_CUST_ACCOUNTS 
            WHERE CUST_ACCOUNT_ID = I.CUSTOMER_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    
   
        BEGIN                     
            SELECT DISTINCT S.ATTRIBUTE2 INTO V_SP_PHONE1  
            FROM JTF_RS_DEFRESOURCES_V S, JTF_RS_SALESREPS SR
            WHERE S.RESOURCE_ID = SR.RESOURCE_ID
            AND SR.SALESREP_ID = I.SALESREP_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
        
        BEGIN
        
            IF V_SP_PHONE1 IS NULL THEN
                ---- Fetching Data for lead territoty phone          
                SELECT S.ATTRIBUTE2 INTO V_SP_PHONE2
                FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
                WHERE A.SALESREP_ID = SR.SALESREP_ID
                AND S.RESOURCE_ID = SR.RESOURCE_ID   
                AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
                AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
                FROM XX_ROLE_TERRITORY_V A, 
                (SELECT COUNTRY, ZONE, REGION,AREA AREA, LEAD_TERRITORY TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
                WHERE A.COUNTRY = B.COUNTRY 
                AND A.ZONE = B.ZONE 
                AND A.REGION = B.REGION
                AND A.AREA = B.AREA
                AND A.TERRITORY = B.TERRITORY);
            END IF;

        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
        

        BEGIN
        
            IF V_SP_PHONE1 IS NULL AND V_SP_PHONE2 IS NULL THEN
                ---- Fetching Data for Area Phone          
                SELECT S.ATTRIBUTE2 INTO V_SP_PHONE3
                --into v_people_id  
                FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
                WHERE A.SALESREP_ID = SR.SALESREP_ID
                AND S.RESOURCE_ID = SR.RESOURCE_ID   
                AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
                AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
                FROM XX_ROLE_TERRITORY_V A, 
                (SELECT COUNTRY, ZONE, REGION,AREA AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
                WHERE A.COUNTRY = B.COUNTRY 
                AND A.ZONE = B.ZONE 
                AND A.REGION = B.REGION
                AND A.AREA = B.AREA
                AND A.TERRITORY = B.TERRITORY);
            END IF;
            
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
        
        BEGIN
        
            IF V_SP_PHONE1 IS NULL AND V_SP_PHONE2 IS NULL AND V_SP_PHONE3 IS NULL THEN
                ---- FETCHING DATA FOR REGION PHONE          
                SELECT S.ATTRIBUTE2 INTO V_SP_PHONE4
                FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
                WHERE A.SALESREP_ID = SR.SALESREP_ID
                AND S.RESOURCE_ID = SR.RESOURCE_ID   
                AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
                AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
                FROM XX_ROLE_TERRITORY_V A, 
                (SELECT COUNTRY, ZONE, REGION, 'NA' AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
                WHERE A.COUNTRY = B.COUNTRY 
                AND A.ZONE = B.ZONE 
                AND A.REGION = B.REGION
                AND A.AREA = B.AREA
                AND A.TERRITORY = B.TERRITORY);
            END IF;          
        
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
    
    EXCEPTION
        WHEN OTHERS THEN
        NULL;
    END;    
    
    ----V_PHONE := '+01929921300';  --+01917044104   
    V_PHONE  :=  NVL(NVL(NVL(V_SP_PHONE1,V_SP_PHONE2),V_SP_PHONE3),V_SP_PHONE4)||V_CUST_PHONE; --||',+01929921300'; --||',+01917044104';              
    
    --- INSERTING DATA INTO MASSAGE GERNATION TABLE
    INSERT INTO XX_SMS_GEN (MODULE_CODE,PURPOSE,ORG_ID,SOURCE_DOC_ID, MESSAGE,PHONE,ATTRIBUTE1)
    VALUES('ONT','CHALLAN',I.ORG_ID, I.DELIVERY_ID,V_MSG,V_PHONE,NULL);
    
    END LOOP;
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
    NULL;
END; 
-------------End CHALLAN_SMS_GEN ------------------------------------------------

-------------Start OD_SMS_GEN ------------------------------------------------
PROCEDURE OD_SMS_GEN (ERRORBUF VARCHAR2,RETCODE VARCHAR2,P_ORG_ID NUMBER) IS
V_MSG VARCHAR2(4000);
V_PHONE VARCHAR2(200);
V_SP_PHONE1 VARCHAR2(200);
V_SP_PHONE2 VARCHAR2(200);
V_SP_PHONE3 VARCHAR2(200);
V_SP_PHONE4 VARCHAR2(200);

CURSOR C1 IS
SELECT * FROM XX_ONT_SMS_OD_V
WHERE OD_DATE >= SYSDATE-1
AND ORG_ID = P_ORG_ID
AND OD_NUMBER NOT IN (SELECT SOURCE_DOC_ID FROM XX_SMS_GEN WHERE PURPOSE = 'OD')
ORDER BY OD_DATE;

BEGIN
    
    FOR I IN C1 LOOP
    
    V_MSG := 'Dear '||INITCAP(I.CUSTOMER_NAME)||' ('||I.ACCOUNT_NUMBER||'), Delivery Order Placed '|| I.TOTAL_OD_QTY||' '|| I.UOM||' ('||I.ALL_ITEMS||'), Dated on '||INITCAP (TRUNC(I.OD_DATE))||
                    '. DO No.- '|| I.OD_NUMBER||'. Del. Site: '||INITCAP(I.DELIVERY_ADDRESS) ||chr(10)|| 'Complements of KSRM';                    
    
    V_PHONE        := NULL; 
    V_SP_PHONE1 := NULL;  --SALESREP
    V_SP_PHONE2 := NULL;  --LEAD TERR
    V_SP_PHONE3 := NULL;  --AREA
    V_SP_PHONE4 := NULL;

    BEGIN
    
        BEGIN                        
            SELECT DISTINCT S.ATTRIBUTE2 || ',' --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
            INTO V_SP_PHONE1  
            FROM JTF_RS_DEFRESOURCES_V S, JTF_RS_SALESREPS SR
            WHERE S.RESOURCE_ID = SR.RESOURCE_ID
            AND SR.SALESREP_ID = I.SALESREP_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    
    
        ---- Fetching Data for lead territoty phone
       BEGIN           
            SELECT S.ATTRIBUTE2 || ','  --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
            INTO V_SP_PHONE2
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, LEAD_TERRITORY TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
    
        ---- Fetching Data for Area Phone          
        BEGIN
            SELECT S.ATTRIBUTE2
                INTO V_SP_PHONE3
            --into v_people_id  
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
    
    EXCEPTION
        WHEN OTHERS THEN
        NULL;
    END;    
    
    ----V_PHONE := '+01929921300';  --+01917044104   
    --V_PHONE  := '+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||DECODE(V_SP_PHONE1,NULL,NULL,',')||V_SP_PHONE2||DECODE(V_SP_PHONE2,NULL,NULL,',')||DECODE(V_SP_PHONE2,NULL,NULL,',')||V_SP_PHONE3||'+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||','||V_SP_PHONE2||','||V_SP_PHONE3||',+01929921300,+01929921477';              
    --V_PHONE  := V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3||'+01929921300,+01929921477';
    V_PHONE  := V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3;
    
    --- INSERTING DATA INTO MASSAGE GERNATION TABLE
    INSERT INTO XX_SMS_GEN (MODULE_CODE,PURPOSE,ORG_ID,SOURCE_DOC_ID, MESSAGE,PHONE)
    VALUES('ONT','OD',I.ORG_ID, I.OD_NUMBER,V_MSG,V_PHONE);
    
    END LOOP;
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
    NULL;
END; 
-------------End OD_SMS_GEN ------------------------------------------------

-------------Start OD_CANCEL_SMS_GEN  ------------------------------------------------
PROCEDURE OD_CANCEL_SMS_GEN (ERRORBUF VARCHAR2,RETCODE VARCHAR2,P_ORG_ID NUMBER) IS
V_MSG VARCHAR2(4000);
V_PHONE VARCHAR2(200);
V_SP_PHONE1 VARCHAR2(50);
V_SP_PHONE2 VARCHAR2(50);
V_SP_PHONE3 VARCHAR2(50);
V_SP_PHONE4 VARCHAR2(50);

CURSOR C1 IS
SELECT * FROM XX_ONT_SMS_OD_CANCEL_V
WHERE CANCEL_OD_DATE >= SYSDATE-1  --(1/48)
AND ORG_ID = P_ORG_ID
AND OD_NUMBER NOT IN (SELECT SOURCE_DOC_ID FROM XX_SMS_GEN WHERE PURPOSE = 'OD_CANCEL')
ORDER BY OD_DATE;

BEGIN
    
    FOR I IN C1 LOOP
    /* V_MSG := 'Dear Customer ('||I.ACCOUNT_NUMBER||'), Goods delivered '|| I.TOTAL_CHALLAN_QTY||' '|| I.UOM||' ('||I.ALL_ITEMS||'), Dated on '||INITCAP (TRUNC(I.CHALLAN_DATE))||
                    '. Vehicle: '|| I.REG_NO||', Driver Cell No: '||I.DRIVER_CONTACT||', Del. Site: '||INITCAP(I.DELIVERY_ADDRESS) ||chr(10)|| 'Complements of KSRM';  */
        --Dear Rupali Trading (70133), Delivery order placed 10.00 MT (08MM, 10MM, 12MM, 20MM, 25MM) on 20-May-19. DO No-19147005862.Del.site: BESIDE RAHMAN NAGAR SCHOOL. HAMZARBAG MURADOUR, CTG.||Compliments of KSRM.
    V_MSG := 'Dear '||INITCAP(I.CUSTOMER_NAME)||' ('||I.ACCOUNT_NUMBER||'), Delivery order cancelled '|| I.TOTAL_OD_QTY||' '|| I.UOM||' ('||I.ALL_ITEMS||'), on '||INITCAP (TRUNC(I.CANCEL_OD_DATE))||
                    '. DO No.- '|| I.OD_NUMBER||'. Del. Site: '||INITCAP(I.DELIVERY_ADDRESS) ||chr(10)|| 'Complements of KSRM';                    
    
    V_PHONE        := NULL; 
    V_SP_PHONE1 := NULL;  --SALESREP
    V_SP_PHONE2 := NULL;  --LEAD TERR
    V_SP_PHONE3 := NULL;  --AREA
    V_SP_PHONE4 := NULL;

    BEGIN
        
        BEGIN                            
            SELECT DISTINCT S.ATTRIBUTE2 || ',' --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
            INTO V_SP_PHONE1  
            FROM JTF_RS_DEFRESOURCES_V S, JTF_RS_SALESREPS SR
            WHERE S.RESOURCE_ID = SR.RESOURCE_ID
            AND SR.SALESREP_ID = I.SALESREP_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
    
        ---- Fetching Data for lead territoty phone          
        BEGIN
            SELECT S.ATTRIBUTE2 || ','  --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
                INTO V_SP_PHONE2
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, LEAD_TERRITORY TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
    
        ---- Fetching Data for Area Phone
        BEGIN          
            SELECT S.ATTRIBUTE2|| ','
                INTO V_SP_PHONE3
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
    
    EXCEPTION
        WHEN OTHERS THEN
        NULL;
    END;    
    
    --V_PHONE := '+01917044104,+01929921300' ;
    --V_PHONE  := '+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||DECODE(V_SP_PHONE1,NULL,NULL,',')||V_SP_PHONE2||DECODE(V_SP_PHONE2,NULL,NULL,',')||DECODE(V_SP_PHONE2,NULL,NULL,',')||V_SP_PHONE3||'+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||','||V_SP_PHONE2||','||V_SP_PHONE3||',+01929921300,+01929921477';              
    V_PHONE  := V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3||'+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3;
    
    --- INSERTING DATA INTO MASSAGE GERNATION TABLE
    INSERT INTO XX_SMS_GEN (MODULE_CODE,PURPOSE,ORG_ID,SOURCE_DOC_ID, MESSAGE,PHONE)
    VALUES('ONT','OD_CANCEL',I.ORG_ID, I.OD_NUMBER,V_MSG,V_PHONE);
    
    END LOOP;
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
    NULL;
END; 
-------------End OD_CANCEL_SMS_GEN ------------------------------------------------

-------------- Start BG Notification 1 ---------------------------------
PROCEDURE BG_SMS_GEN_N1 (ERRORBUF VARCHAR2,RETCODE VARCHAR2,P_ORG_ID NUMBER) IS
V_MSG VARCHAR2(4000);
V_PHONE VARCHAR2(200);
V_SP_PHONE1 VARCHAR2(200);
V_SP_PHONE2 VARCHAR2(200);
V_SP_PHONE3 VARCHAR2(200);
V_SP_PHONE4 VARCHAR2(200);
V_CUST_PHONE VARCHAR2(200);

CURSOR C1 IS

SELECT * FROM XX_ONT_BG_SMS_V
WHERE SYSDATE > EXPIRE_DATE - NOTIFY_DAYS_1
AND SYSDATE <= EXPIRE_DATE
AND ORG_ID = P_ORG_ID
AND (BG_SYSNO, BG_VERSION) NOT IN (SELECT SOURCE_DOC_ID, ATTRIBUTE1 FROM XX_SMS_GEN WHERE PURPOSE = 'BG-N1')
AND STATUS IN ('V','H','N')
--AND BG_SYSNO = 'BG-18-00061'
ORDER BY BG_SYSNO;

BEGIN
    
    FOR I IN C1 LOOP
    
    V_MSG := 'REMINDER:'||chr(10)||
                    'Dear '||INITCAP(I.CUSTOMER_NAME)||' ('||I.ACCOUNT_NUMBER||'), Please be informed that your BG no-'|| I.BG_NO||' at '|| I.BANK_NAME||', BDT '||TO_CHAR(I.BG_AMT, '99G99G99G999', 'NLS_NUMERIC_CHARACTERS=",."')
                    ||'/- will be expired on '||INITCAP (TRUNC(I.EXPIRE_DATE))||'.'
                    ||chr(10)|| 'Complements of KSRM';                    
    
    V_PHONE        := NULL; 
    V_SP_PHONE1 := NULL;  --SALESREP
    V_SP_PHONE2 := NULL;  --LEAD TERR
    V_SP_PHONE3 := NULL;  --AREA
    V_SP_PHONE4 := NULL;   --REGION PHONE
    V_CUST_PHONE := NULL; 

    BEGIN

        BEGIN                            
            SELECT DISTINCT S.ATTRIBUTE2 || ',' --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
            INTO V_SP_PHONE1  
            FROM JTF_RS_DEFRESOURCES_V S, JTF_RS_SALESREPS SR
            WHERE S.RESOURCE_ID = SR.RESOURCE_ID
            AND SR.SALESREP_ID = I.SALESREP_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;        
    
        
        ---- Fetching Data for lead territoty phone
        BEGIN          
            SELECT S.ATTRIBUTE2 || ','  --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
                INTO V_SP_PHONE2
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, LEAD_TERRITORY TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    

    
        ---- Fetching Data for Area Phone
        BEGIN          
            SELECT S.ATTRIBUTE2|| ',' 
                INTO V_SP_PHONE3
            --into v_people_id  
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    
        
        
        ---- Fetching Data for Region Phone      
        BEGIN    
            SELECT S.ATTRIBUTE2|| ',' 
                INTO V_SP_PHONE4
            --into v_people_id  
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,'NA' AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    
        
        BEGIN
            SELECT ATTRIBUTE12 || ',' 
                INTO V_CUST_PHONE
            FROM HZ_CUST_ACCOUNTS 
            WHERE CUST_ACCOUNT_ID = I.CUSTOMER_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    

    
    
    EXCEPTION
        WHEN OTHERS THEN
        NULL;
    END;    
    
    ----V_PHONE := '+01929921300';  --+01917044104   
    --V_PHONE  := '+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||DECODE(V_SP_PHONE1,NULL,NULL,',')||V_SP_PHONE2||DECODE(V_SP_PHONE2,NULL,NULL,',')||DECODE(V_SP_PHONE2,NULL,NULL,',')||V_SP_PHONE3||'+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||','||V_SP_PHONE2||','||V_SP_PHONE3||',+01929921300,+01929921477';              
    --V_PHONE  := V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3||'+01929921300,+01929921477';
    V_PHONE  := V_CUST_PHONE||V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3||V_SP_PHONE4||'+01929921300,+01929921452,+01929921713';
    --V_PHONE  := '+01929921300,+01917044104,+01929921456,+01929921713';
    
    --- INSERTING DATA INTO MASSAGE GERNATION TABLE
    INSERT INTO XX_SMS_GEN (MODULE_CODE,PURPOSE,ORG_ID,SOURCE_DOC_ID, MESSAGE,PHONE,ATTRIBUTE1)
    VALUES('ONT','BG-N1',I.ORG_ID, I.BG_SYSNO,V_MSG,V_PHONE,I.BG_VERSION);
    
    END LOOP;
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
    NULL;
END;

------------- End BG Notification 1 --------------

-------------- Start BG Notification 2 ---------------------------------
PROCEDURE BG_SMS_GEN_N2 (ERRORBUF VARCHAR2,RETCODE VARCHAR2,P_ORG_ID NUMBER) IS
V_MSG VARCHAR2(4000);
V_PHONE VARCHAR2(200);
V_SP_PHONE1 VARCHAR2(200);
V_SP_PHONE2 VARCHAR2(200);
V_SP_PHONE3 VARCHAR2(200);
V_SP_PHONE4 VARCHAR2(200);
V_CUST_PHONE VARCHAR2(200);

CURSOR C1 IS

SELECT * FROM XX_ONT_BG_SMS_V
WHERE SYSDATE > EXPIRE_DATE - NOTIFY_DAYS_2
AND SYSDATE <= EXPIRE_DATE
AND ORG_ID = P_ORG_ID
AND (BG_SYSNO, BG_VERSION) NOT IN (SELECT SOURCE_DOC_ID, ATTRIBUTE1 FROM XX_SMS_GEN WHERE PURPOSE = 'BG-N2')
AND STATUS IN ('V','H','N')
--AND BG_SYSNO = 'BG-18-00061'
ORDER BY BG_SYSNO;

BEGIN
    
    FOR I IN C1 LOOP
    
    V_MSG := 'REMINDER:'||chr(10)||
                    'Dear '||INITCAP(I.CUSTOMER_NAME)||' ('||I.ACCOUNT_NUMBER||'), Please be informed that your BG no-'|| I.BG_NO||' at '|| I.BANK_NAME||', BDT '||TO_CHAR(I.BG_AMT, '99G99G99G999', 'NLS_NUMERIC_CHARACTERS=",."')
                    ||'/- will be expired on '||INITCAP (TRUNC(I.EXPIRE_DATE))||'.'
                    ||chr(10)|| 'Complements of KSRM';                    
    
    V_PHONE        := NULL; 
    V_SP_PHONE1 := NULL;  --SALESREP
    V_SP_PHONE2 := NULL;  --LEAD TERR
    V_SP_PHONE3 := NULL;  --AREA
    V_SP_PHONE4 := NULL;   --REGION PHONE
    V_CUST_PHONE := NULL; 

    BEGIN

        BEGIN                            
            SELECT DISTINCT S.ATTRIBUTE2 || ',' --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
            INTO V_SP_PHONE1  
            FROM JTF_RS_DEFRESOURCES_V S, JTF_RS_SALESREPS SR
            WHERE S.RESOURCE_ID = SR.RESOURCE_ID
            AND SR.SALESREP_ID = I.SALESREP_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;        
    
        
        ---- Fetching Data for lead territoty phone
        BEGIN          
            SELECT S.ATTRIBUTE2 || ','  --DECODE(S.ATTRIBUTE2,NULL,NULL,',') 
                INTO V_SP_PHONE2
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, LEAD_TERRITORY TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    

    
        ---- Fetching Data for Area Phone
        BEGIN          
            SELECT S.ATTRIBUTE2|| ',' 
                INTO V_SP_PHONE3
            --into v_people_id  
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,AREA AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    
        
        
        ---- Fetching Data for Region Phone      
        BEGIN    
            SELECT S.ATTRIBUTE2|| ',' 
                INTO V_SP_PHONE4
            --into v_people_id  
            FROM RA_SALESREP_TERRITORIES A, JTF_RS_DEFRESOURCES_VL S, JTF_RS_SALESREPS SR
            WHERE A.SALESREP_ID = SR.SALESREP_ID
            AND S.RESOURCE_ID = SR.RESOURCE_ID   
            AND TRUNC(SYSDATE) BETWEEN TRUNC(A.START_DATE_ACTIVE) AND NVL(TRUNC(A.END_DATE_ACTIVE),TRUNC(SYSDATE))
            AND A.TERRITORY_ID =  (SELECT DISTINCT TERRITORY_ID 
            FROM XX_ROLE_TERRITORY_V A, 
            (SELECT COUNTRY, ZONE, REGION,'NA' AREA, 'NA' TERRITORY  FROM XX_ROLE_TERRITORY_V WHERE TERRITORY_ID = I.TERRITORY_ID) B
            WHERE A.COUNTRY = B.COUNTRY 
            AND A.ZONE = B.ZONE 
            AND A.REGION = B.REGION
            AND A.AREA = B.AREA
            AND A.TERRITORY = B.TERRITORY);
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;
        
        
        BEGIN
            SELECT ATTRIBUTE12 || ',' INTO V_CUST_PHONE
            FROM HZ_CUST_ACCOUNTS 
            WHERE CUST_ACCOUNT_ID = I.CUSTOMER_ID;
        EXCEPTION
            WHEN OTHERS THEN
            NULL;
        END;    
    
    
    EXCEPTION
        WHEN OTHERS THEN
        NULL;
    END;    
    
    ----V_PHONE := '+01929921300';  --+01917044104   
    --V_PHONE  := '+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||DECODE(V_SP_PHONE1,NULL,NULL,',')||V_SP_PHONE2||DECODE(V_SP_PHONE2,NULL,NULL,',')||DECODE(V_SP_PHONE2,NULL,NULL,',')||V_SP_PHONE3||'+01929921300,+01929921477';
    --V_PHONE  := V_SP_PHONE1 ||','||V_SP_PHONE2||','||V_SP_PHONE3||',+01929921300,+01929921477';              
    --V_PHONE  := V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3||'+01929921300,+01929921477';
    V_PHONE  := V_CUST_PHONE||V_SP_PHONE1 ||V_SP_PHONE2||V_SP_PHONE3||V_SP_PHONE4||'+01929921300,+01929921452,+01929921713';
    --V_PHONE  := '+01929921300,+01917044104,+01929921456,+01929921713';
    
    --- INSERTING DATA INTO MASSAGE GERNATION TABLE
    INSERT INTO XX_SMS_GEN (MODULE_CODE,PURPOSE,ORG_ID,SOURCE_DOC_ID, MESSAGE,PHONE,ATTRIBUTE1)
    VALUES('ONT','BG-N2',I.ORG_ID, I.BG_SYSNO,V_MSG,V_PHONE,I.BG_VERSION);
    
    END LOOP;
    
    COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
    NULL;
END;

------------- End BG Notification 2 --------------

END XX_SMS_PKG;
/
