 SELECT * FROM PO_HEADERS_ALL WHERE  ORG_ID= 103 AND SEGMENT1=  '40004647'         --  ACTUAL CODE 1117 INSTATED OF 3279    
 
   
  --=================== For checking before upddate===================

  
  select * from ap_suppliers where segment1= 1117
  
  SELECT * FROM AP_SUPPLIER_SITES_ALL WHERE VENDOR_ID= 7493
  
    SELECT VENDOR_ID,VENDOR_SITE_ID, ORG_ID  FROM AP_SUPPLIER_SITES_ALL WHERE VENDOR_ID=7493 AND ORG_ID = 103
    
      SELECT VENDOR_ID,VENDOR_SITE_ID, ORG_ID  FROM AP_SUPPLIER_SITES_ALL WHERE VENDOR_ID=117 AND ORG_ID = 103
  
   SELECT * FROM AP_SUPPLIERS WHERE SEGMENT1= 3279 
   
   SELECT * FROM HR_OPERATING_UNITS 
   
          

 PO_PORTION
 -- ==============
  
  UPDATE PO_HEADERS_ALL
  SET VENDOR_ID = 117
  WHERE   ORG_ID= 103
  AND SEGMENT1 = '40004647'
  
  UPDATE PO_HEADERS_ALL
  SET VENDOR_SITE_ID = 65013
  WHERE VENDOR_ID = 117
  AND  ORG_ID= 103
  AND SEGMENT1 = '40004647'
  
  GRN PORTION
  --=============
  
   SELECT * FROM RCV_TRANSACTIONS WHERE PO_HEADER_ID = 844486
  
  UPDATE RCV_TRANSACTIONS
  SET  VENDOR_ID = 117
  WHERE PO_HEADER_ID = 844486
  
  UPDATE RCV_TRANSACTIONS
  SET VENDOR_SITE_ID = 65013
  WHERE VENDOR_ID = 117
  AND PO_HEADER_ID = 844486
  
 

