
SELECT * FROM XX_ONT_TRIP_MT where TRIPSYS_NO =  349302


SELECT  TO_CHAR(STATUS_DATE,'DD-MON-RRRR HH12:MI:SS PM')   FROM MTL_TXN_REQUEST_LINES_V WHERE REQUEST_NUMBER = 'MO-TRM-0101963'

select * FROM  MTL_TXN_REQUEST_HEADERS WHERE REQUEST_NUMBER =  'MO-TRM-0101963'

SELECT STATUS_DATE, TO_CHAR(STATUS_DATE,'DD-MON-RRRR HH12:MI:SS PM')   FROM MTL_TXN_REQUEST_LINES WHERE HEADER_ID=2257428  -- WHERE REQUEST_NUMBER = 'MO-TRM-0101963'

 
--==================================
--REPORT FOR RAIHAN FOR MONITORING TRIP STATUS
--==================================

--V1
SELECT  A.CREATED_BY, FUEL_INV_ORG_ID,GET_ORG_CODE_FROM_ID(FUEL_INV_ORG_ID) ORG_CODE,
(SELECT DISTINCT VEHICLE_TYPE  FROM xx_ont_vehicle_v WHERE REG_NO=A.REG_NO) VEHICLE_TYPE,
TRIPSYS_NO, TRIP_DATE,TRANSPORT_TYPE,REG_NO,TRIP_TYPE,PURPOSE,TRIP_STATUS,MOVE_ORDER_NUMBER,
FUEL_ISSUED,B.TRANSACTION_QUANTITY FUEL_TRANSACT,B.TRANSACTION_DATE,
  XX_GET_EMP_NAME_FROM_USER_ID (A.CREATED_BY) TRIP_CREATED_BY,GATE_IN_1,GATE_OUT,GATE_IN_2,REMARKS,IC_VERIFIED_FLAG,
  :P_FROM_DATE, :P_TO_DATE
 FROM XX_ONT_TRIP_MT A, MTL_MATERIAL_TRANSACTIONS B --, MTL_TXN_REQUEST_HEADERS C
--  MTL_TXN_REQUEST_LINES D
 WHERE  A.TRIPSYS_NO=B.TRANSACTION_REFERENCE(+)
-- AND B.TRANSACTION_DATE BETWEEN NVL(:P_FROM_DATE,B.TRANSACTION_DATE) AND NVL(:P_TO_DATE,B.TRANSACTION_DATE)  --- MO Transaction Date
  AND A.CREATION_DATE BETWEEN NVL(:P_FROM_DATE,A.CREATION_DATE) AND NVL(:P_TO_DATE,A.CREATION_DATE)
AND A.CREATED_BY = NVL(:P_TRIP_CREATED_BY,A.CREATED_BY)
AND (SELECT DISTINCT VEHICLE_TYPE  FROM xx_ont_vehicle_v WHERE REG_NO=A.REG_NO) = NVL(:P_VEHICLE_TYPE, (SELECT DISTINCT VEHICLE_TYPE  FROM xx_ont_vehicle_v WHERE REG_NO=A.REG_NO))


DUMP TRUCK
 
 SELECT * FROM MTL_MATERIAL_TRANSACTIONS
 
 
 SELECT * FROM   XX_ONT_TRIP_MT A where  A.CREATION_DATE BETWEEN '01-DEC-2022' AND '15-DEC-2022'

--MAIN
SELECT  FUEL_INV_ORG_ID,GET_ORG_CODE_FROM_ID(FUEL_INV_ORG_ID) ORG_CODE,TRIPSYS_NO, TRIP_DATE,TRANSPORT_TYPE,REG_NO,TRIP_TYPE,PURPOSE,TRIP_STATUS,MOVE_ORDER_NUMBER,FUEL_ISSUED,
  XX_GET_EMP_NAME_FROM_USER_ID (CREATED_BY) CREATED_BY,GATE_IN_1,GATE_OUT,GATE_IN_2,REMARKS,IC_VERIFIED_FLAG
 FROM XX_ONT_TRIP_MT
--  326,083

SELECT TRIP_STATUS   FROM XX_ONT_TRIP_MT 


SELECT * FROM XXTRIPDTLS_ALL where TRIPSYS_NO= '327083'



--======================
GET TRIP STATUS
--======================

SELECT  XX_GET_EMP_NAME_FROM_USER_ID (A.CREATED_BY) CREATED_BY,A.* FROM XX_ONT_TRIP_MT A WHERE TRUNC(CREATION_date)  BETWEEN '19-DEC-2022' and  '19-DEC-2022' and TRIP_STATUS = 'CL'


--================================
--GET TODAY's ALL TRIP INFO
--============================

SELECT * FROM XX_ONT_TRIP_MT WHERE TRUNC(CREATION_date)  BETWEEN '1-NOV-2022' and  '12-NOV-2022'





-- MANUAL MOVE ORDER FOR VEHICLE AND TRIP  For Raihan  Date: 11-DEC-2022 
--============================================================

-- FOR CHECKING 
SELECT   GET_ORG_CODE_FROM_ID(MMT.ORGANIZATION_ID) ORG_CODE ,TOL.ATTRIBUTE5,TOL.ATTRIBUTE2 USE_OF_AREA_ID, MMT.TRANSACTION_ID TRANSACTION_ID, 
MMT.TRANSACTION_TYPE_ID,
(SELECT TRANSACTION_TYPE_NAME FROM MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_ID=MMT.TRANSACTION_TYPE_ID ) TRANSACTION_TYPE_NAME,
mmt.transaction_date, tol.attribute2 Use_Of_AREA,
TOH.HEADER_ID WITH_HEADER_ID,TOH.CREATION_DATE,
 XX_GET_EMP_NAME_FROM_USER_ID (TOH.CREATED_BY) CREATED_BY,
  TOL.ORGANIZATION_ID,
  TOH.REQUEST_NUMBER,
  TOH.HEADER_ID,
  TOL.LINE_NUMBER,
  TOL.LINE_ID,
  TOL.INVENTORY_ITEM_ID,
  MY_PACKAGE.XXGET_ITEM_DESCRIPTION(TOL.INVENTORY_ITEM_ID, TOL.ORGANIZATION_ID) ITEM_DESCRIPTION,
  TOH.DESCRIPTION,
  TOH.MOVE_ORDER_TYPE,
  TOL.LINE_STATUS,
  TOL.QUANTITY,
  TOL.QUANTITY_DELIVERED,
  TOL.QUANTITY_DETAILED,
  (SELECT DISTINCT USE_AREA  FROM XXKSRM_INV_USE_AREA_V where use_area_id= TOL.ATTRIBUTE2) VEHICLE
FROM MTL_TXN_REQUEST_HEADERS TOH,
  MTL_TXN_REQUEST_LINES TOL,
  MTL_MATERIAL_TRANSACTIONS MMT
WHERE TOH.HEADER_ID = TOL.HEADER_ID
 AND TOH.ORGANIZATION_ID= TOL.ORGANIZATION_ID
 AND TOL.LINE_ID = MMT.MOVE_ORDER_LINE_ID(+)
--AND TOH.REQUEST_NUMBER LIKE '%1615955%' -- 1618008
AND TOL.INVENTORY_ITEM_ID=180
--AND TOL.ATTRIBUTE5 is not null
and   TOL.QUANTITY_DELIVERED IS NOT NULL 
--AND GET_ORG_CODE_FROM_ID(MMT.ORGANIZATION_ID) <> 'TRM'
AND TRUNC(mmt.transaction_date)  BETWEEN '01-DEC-2022' and '30-DEC-2022'  
 --and TOH.HEADER_ID IN (1764072)
-- )

select * from   MTL_TXN_REQUEST_HEADERS where REQUEST_NUMBER = '1615955' -- INVENTORY_ITEM_ID=180 and QUANTITY_DELIVERED IS NOT NULL 

 SELECT * FROM XXTRIPDTLS_ALL where MO_NUMBER_ADD is not null


SELECT DISTINCT  REQUEST_NUMBER  FROM MTL_TXN_REQUEST_HEADERS a , MTL_TXN_REQUEST_LINES b WHERE a.header_id=b.HEADER_ID --AND B.LINE_ID = C.MOVE_ORDER_LINE_ID

SELECT --a.TRIPSYS_NO, a.MOVE_ORDER_NUMBER TRIP_MO_NO, b.MO_NUMBER BILL_MO_NO,C.TRANSACTION_SOURCE_ID, A.IC_VERIFIED_FLAG , 
A.*  , C.TRANSACTION_ID,A.fuel_issued,ABS(c.transaction_quantity) transaction_quantity, a.MOVE_ORDER_NUMBER TRIP_MO_NO, b.MO_NUMBER BILL_MO_NO,
 XX_GET_EMP_NAME_FROM_USER_ID (A.CREATED_BY) CREATED_BY ,
(SELECT DISTINCT  REQUEST_NUMBER  FROM MTL_TXN_REQUEST_HEADERS a , MTL_TXN_REQUEST_LINES b WHERE a.header_id=b.HEADER_ID  AND B.LINE_ID = C.MOVE_ORDER_LINE_ID ) MO_NUM,
(SELECT DISTINCT USE_AREA  FROM XXKSRM_INV_USE_AREA_V where use_area_id= TOL.ATTRIBUTE2) VEHICLE,
(SELECT DISTINCT REQUEST_NUMBER FROM MTL_TXN_REQUEST_HEADERS WHERE HEADER_ID=TOL.HEADER_ID) MO
 FROM XX_ONT_TRIP_MT A,  XXTRIPDTLS_ALL B, MTL_MATERIAL_TRANSACTIONS C ,  MTL_TXN_REQUEST_LINES TOL
WHERE a.TRIPSYS_NO=b.TRIPSYS_NO(+)
 and A.TRIPSYS_NO=C.TRANSACTION_REFERENCE(+)
 AND  A.MOVE_ORDER_NUMBER=C.TRANSACTION_SOURCE_ID(+)
--and A.TRIP_TYPE = 'Inter Company'
--AND FUEL_INV_ORG_ID=152 -- TRM
--AND  A.TRIP_STATUS NOT IN ('CL', 'D', 'I') 
AND TOL.LINE_ID = C.MOVE_ORDER_LINE_ID
AND TOL.ORGANIZATION_ID= C.ORGANIZATION_ID
--AND  A.IC_VERIFIED_FLAG IS  NULL 
AND a.TRIPSYS_NO='1004'


--==================================== MOVE ORDER  QUERY  FOR TRIP ==================================================

select reference from MTL_TXN_REQUEST_LINES where line_id= 3104511

--UPDATE MTL_TXN_REQUEST_LINES
--SET reference='339867'
---where line_id= 3104511



SELECT  
                 MTRL.ORGANIZATION_ID, MTRL.LINE_ID
                ,NVL((SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') ORG_NAME
                ,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY) DEPARTMENT
               ,(SELECT DISTINCT  OTM.TRIPSYS_NO FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) TRIP_NO
              ,NVL((SELECT DISTINCT DECODE(OTM.EMPLOYEE_ID,NULL,UNLISTED_DRIVER,(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = OTM.EMPLOYEE_ID)) DRIVER_NAME FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL),mtrl.attribute1) DRIVER_NAME
                ,MTRL.ATTRIBUTE15 GATE_PASS_NO
                ,XX_INV_PKG.XXGET_CUSTOMER_NAME((SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) ) CUSTOMER_NAME           
             ---- ,(SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) CUSTOMER_NAME
               ,(SELECT ATTRIBUTE1 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Move Order Issue' AND HEADER_ID=MTHL.HEADER_ID) WORK_ORDER_NO
                ,MTRL.REQUEST_NUMBER MOVE_ORDER_NUMBER
                ,MTRL.DATE_REQUIRED  MOVE_ORDER_DATE
                ,MTRL.TRANSACTION_TYPE_NAME MOVE_ORDER_TYPE
                ,ML.MEANING MO_STATUS_LINE
                ,MTHL.HEADER_STATUS_NAME  MO_STATUS
                ,(SELECT ATTRIBUTE9 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Issue to Project' AND HEADER_ID=MTHL.HEADER_ID) PROJECT_NAME
                ,MTRL.LINE_NUMBER
                , (MSI.SEGMENT1 || '|' || MSI.SEGMENT2 || '|' || MSI.SEGMENT3||'|' || MSI.SEGMENT4)    ITEM_CODE
                ,MSI.DESCRIPTION
                ,MTRL.UOM_CODE
                ---=========================================
                ,MTRL.FROM_SUBINVENTORY_CODE
                ,MTRL.INVENTORY_ITEM_ID
                -----------------------------------------------------
                , (SELECT NVL(SUM(PRIMARY_QUANTITY),0)
                FROM 
                MTL_MATERIAL_TRANSACTIONS
                WHERE 
                ORGANIZATION_ID=MTRL.ORGANIZATION_ID
                AND SUBINVENTORY_CODE=NVL(MTRL.FROM_SUBINVENTORY_CODE,SUBINVENTORY_CODE)
                AND INVENTORY_ITEM_ID=MTRL.INVENTORY_ITEM_ID 
                AND  TRANSACTION_DATE <MTRL.DATE_REQUIRED) IO_STOCK
                ---=========================================
                ,MTRL.QUANTITY  MO_QTY
                ,XX.QTY_ISSUED MO_ISSUE_QTY
                ,CASE WHEN MTRL.LINE_STATUS <>5 THEN 0   ELSE (MTRL.QUANTITY-MTRL.QUANTITY_DELIVERED)  END  CANCEL_QTY
                ,XX.SUBINVENTORY_CODE
                , (SELECT SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4||'|'||SEGMENT5 LOCATOR_DESC FROM MTL_ITEM_LOCATIONS WHERE INVENTORY_LOCATION_ID=XX.LOCATOR_ID AND ORGANIZATION_ID=MTRL.ORGANIZATION_ID) LOCATOR
                ,XX.LOT_NUMBER
                ,XX_INV_PKG.XXGET_SERIAL_NUMBER(XX.TRANSACTION_ID) SERIAL_NUMBER
               ----,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 AND OU_ID=(SELECT OPERATING_UNIT_ID FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MTRL.ORGANIZATION_ID)) USEOFAREA
               ,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 ) USEOFAREA
                ,MTRL.REFERENCE REASON
                ---===================================================
                ,MTHL.DESCRIPTION PURPOSE
                ,XX.TRACKING_REMARKS
                ,MTHL.CREATED_BY PREPARED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(MTHL.CREATED_BY )  PREPARED_BY
                ,XX.TAKEN_BY
                ----===========HOD=====================
                ,(XX_INV_PKG.XXGET_ENAME ((SELECT USER_ID FROM FND_USER 
                WHERE USER_NAME =(SELECT APPROVED_BY FROM XXKSRM_MOAPPROVAL_STATUS
                WHERE HEADER_ID=MTHL.HEADER_ID AND WF_STATUS='Approved')))) HOD
                ----===========HOD=====================
                --,DECODE(MTHL.HEADER_STATUS,
                --3,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --7,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --8,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --NULL
                --) HOD
               ---- ,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)) HOD
                ----===========HOD=====================
                ----===========HOD=====================
                ,XX.ISSUED_STORE STORE_IN_CHARGE_ID
                , XX_INV_PKG.XXGET_ENAME(XX.ISSUED_STORE) STORE_IN_CHARGE
                ,XX.CREATED_BY ISSUED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.CREATED_BY) ISSUED_BY
                ,XX.RECEIVED_STORE  RECEIVED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.RECEIVED_STORE)  RECEIVED_BY
                ,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
                ,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') PORG_NAME
                ,NVL((SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORG),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
                ----=====================================================
        FROM   MTL_TXN_REQUEST_HEADERS_V MTHL
          ,MTL_TXN_REQUEST_LINES_V MTRL
          ,MTL_SYSTEM_ITEMS_B MSI
          ,MFG_LOOKUPS ML
          , (  SELECT   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.ATTRIBUTE1 TAKEN_BY
                       ,MMT.ATTRIBUTE11 TRACKING_REMARKS 
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MAX (MMT.CREATED_BY) CREATED_BY
                       ,MMT.TRANSACTION_ID
                       , (MMT.TRANSACTION_DATE) TRANSACTION_DATE
                       ,SUM (ABS (MMT.PRIMARY_QUANTITY)) QTY_ISSUED
                       ,MTLN.LOT_NUMBER
                      ,MMT.ATTRIBUTE1 ISSUED_STORE
                       ,MMT.ATTRIBUTE2 RECEIVED_STORE
                 FROM   MTL_MATERIAL_TRANSACTIONS MMT
                       ,MTL_TRANSACTION_LOT_NUMBERS MTLN
                WHERE   MMT.PRIMARY_QUANTITY < 0
                    AND MMT.ORGANIZATION_ID = :P_ORG
                    AND MMT.TRANSACTION_SOURCE_TYPE_ID = 4
                    AND MTLN.TRANSACTION_ID(+)=MMT.TRANSACTION_ID
             GROUP BY   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.ATTRIBUTE1
                       ,MMT.ATTRIBUTE11
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MTLN.LOT_NUMBER
                       ,MMT.ATTRIBUTE1 
                       ,MMT.ATTRIBUTE2 
                       ,(MMT.TRANSACTION_DATE)
                       ,MMT.TRANSACTION_ID) XX
   WHERE   MTRL.REQUEST_NUMBER = MTHL.REQUEST_NUMBER
       AND MTRL.HEADER_ID = MTHL.HEADER_ID
       AND MTRL.ORGANIZATION_ID = MTHL.ORGANIZATION_ID
       --TRANSACTION_TYPE_ID
       AND MTRL.LINE_STATUS = ML.LOOKUP_CODE
       AND ML.LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
       --AND UPPER(MTRL.transaction_type_name)='MOVE ORDER ISSUE'
       AND MTRL.ORGANIZATION_ID = NVL (:P_ORG, MTRL.ORGANIZATION_ID)
       AND MTRL.REQUEST_NUMBER = NVL (:P_FROM_MO, MTRL.REQUEST_NUMBER)
       AND TRUNC(MTHL.DATE_REQUIRED) BETWEEN NVL(:P_FROM_DATE,TRUNC(MTHL.DATE_REQUIRED))  AND  NVL(:P_TO_DATE,TRUNC(MTHL.DATE_REQUIRED))
       AND MTRL.INVENTORY_ITEM_ID =NVL(:P_ITEM_ID,MTRL.INVENTORY_ITEM_ID)
       AND MTHL.HEADER_STATUS_NAME =NVL(:P_MO_STATUS,HEADER_STATUS_NAME)
    --   AND MTRL.transaction_source_type_id = 4
       AND MTRL.ORGANIZATION_ID = XX.ORGANIZATION_ID(+)
       AND MTRL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MTRL.INVENTORY_ITEM_ID = XX.INVENTORY_ITEM_ID(+)
       AND MTRL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MTRL.LINE_ID = XX.MOVE_ORDER_LINE_ID(+)
       AND MTRL.HEADER_ID = XX.TRANSACTION_SOURCE_ID(+)
       AND MTHL.REQUEST_NUMBER LIKE '%2221479%'
     --  AND MTRL.transaction_type_id = XX.transaction_type_id
       --AND MTRL.request_number='2002'
ORDER BY  MTRL.DATE_REQUIRED, MTRL.REQUEST_NUMBER,MTRL.LINE_NUMBER---- XX.TAKEN_BY




--TRIP COMPLETE BUT NOT BILL V1 (With Transaction Move Order) For Mamun Bos Date: 12-NOV-2022
--=========================================

SELECT --a.TRIPSYS_NO, a.MOVE_ORDER_NUMBER TRIP_MO_NO, b.MO_NUMBER BILL_MO_NO,C.TRANSACTION_SOURCE_ID, A.IC_VERIFIED_FLAG , 
A.*  , C.TRANSACTION_ID,A.fuel_issued,ABS(c.transaction_quantity) transaction_quantity, a.MOVE_ORDER_NUMBER TRIP_MO_NO, b.MO_NUMBER BILL_MO_NO,
 XX_GET_EMP_NAME_FROM_USER_ID (A.CREATED_BY) CREATED_BY 
 FROM xx_ont_trip_mt A,  XXTRIPDTLS_ALL B, MTL_MATERIAL_TRANSACTIONS C 
WHERE a.TRIPSYS_NO=b.TRIPSYS_NO(+)
 and A.TRIPSYS_NO=C.TRANSACTION_REFERENCE(+)
 AND  A.MOVE_ORDER_NUMBER=C.TRANSACTION_SOURCE_ID(+)
and A.TRIP_TYPE = 'Inter Company'
AND FUEL_INV_ORG_ID=152 -- TRM
AND  A.TRIP_STATUS NOT IN ('CL', 'D', 'I') 
AND  A.IC_VERIFIED_FLAG IS  NULL 
--AND MOVE_ORDER_NUMBER = '121095'
--and a.TRIPSYS_NO IN(
--'80273',
--'82537'
--)
--AND a.MOVE_ORDER_NUMBER is not null
--and C.TRANSACTION_ID IS not NULL
--AND TRUNC(C.TRANSACTION_DATE) BETWEEN '01-AUG-2018' and '31-OCT-2022'
--AND TRUNC(A.TRIP_DATE) BETWEEN '01-AUG-2018' and '31-OCT-2022'
--AND A.TRIPSYS_NO='339867'

8,675

SELECT * FROM MTL_MATERIAL_TRANSACTIONS where transaction_id=16138533

--=====================================
ALL TEIP STATUS FOR A MONTH
--=====================================

SELECT  A.*, XX_GET_EMP_NAME_FROM_USER_ID (A.CREATED_BY) CREATED_BY   
FROM XX_ONT_TRIP_MT A 
where 1=1 
-AND  TRUNC(CREATION_DATE) between '1-NOV-2022' and '30-NOV-2022' 
and MOVE_ORDER_NUMBER is not null
--and TRIPSYS_NO='331312'
AND A.IC_VERIFIED_FLAG  IS NULL

SELECT DISTINCT IC_VERIFIED_FLAG FROM XX_ONT_TRIP_MT

--******************************************
--FOR RAIHAN SB
--*****************************************

SELECT * FROM XX_ONT_TRIP_MT where TRUNC(CREATION_DATE) between '1-NOV-2022' and '30-NOV-2022' and TRIP_STATUS = 'CL' and MOVE_ORDER_NUMBER is not null


SELECT * FROM  XX_TRIP_FUEL_ADJ_UNADJ where CREATION_DATE between '01-JAN-2021' and '31-JAN-2021' and TRIP_NO IN
(
'180593'
,'181116'
,'181780'
,'182249'
,'183213'
,'184067'
,'184601'
,'185108'
,'185386'
,'185705'
,'185901'
,'186629'
,'186834'
,'187027'
)
AND DRIVER_NAME = 'NURUL HUDA-(TP-149)'

select  distinct SUBSTR(XX_GET_VENDOR_NAME_WITH_NUMBER (OTM.EMPLOYEE_ID),8) DRIVER_NAME, otm.org_id from XX_ONT_TRIP_MT OTM

(select  distinct SUBSTR(XX_GET_VENDOR_NAME_WITH_NUMBER (OTM.EMPLOYEE_ID),8) DRIVER_NAME, otm.org_id from XX_ONT_TRIP_MT OTM) XXDVR

(select  distinct VENDOR_NAME  FROM AP_SUPPLIERS where VENDOR_TYPE_LOOKUP_CODE = 'DRIVER'  and END_DATE_ACTIVE is null) XXDRIV

 SELECT * FROM XXTRIPDTLS_ALL where TRIPSYS_NO='339867' --TRUNC(CREATION_DATE) between '01-JAN-2022' and '31-JAN-2022'
 
 select * from HR_OPERATING_UNITS 339567

--/*********************************
-- Captured TRIP NO IN PAYABLE DFF
/*********************************/
 SELECT * FROM AP_INVOICES_ALL where ATTRIBUTE2='339867';
 
 

--==================================
select * from  XX_ONT_TRIP_MT  where CREATION_DATE  between '01-JAN-2022' and '31-JAN-2022'

SELECT * FROM XX_ONT_TRIP_MT where CREATION_DATE between '8-NOV-2022' and '11-NOV-2022'


SELECT * FROM  XX_TRIP_FUEL_ADJ_UNADJ where CREATION_DATE between '01-JAN-2021' and '31-JAN-2021' --and TRIP_NO= '180593'
AND DRIVER_NAME = 'NURUL HUDA-(TP-149)'

 SELECT * FROM XXTRIPDTLS_ALL where TRUNC(CREATION_DATE) between '01-JAN-2022' and '31-JAN-2022'


SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE LEGAL_ENTITY = 26286

XLA_00222_AAD_C_011141_PKG


INV_MGD_PERIOD_CONTROL_CP.Run_Period_Control


SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID=11956869

SELECT * FROM MTL_MATERIAL_TRANSACTIONS_TEMP WHERE TRANSACTION_TEMP_ID=11956869



select * from AR_CASH_RECEIPTS_V 


select * from ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE='TRM'



select * from  XX_ONT_TRIP_MT where TRIPSYS_NO = '1018'


SELECT * FROm XX_ONT_TRIP_MT_TEST

 CREATE TABLE XX_ONT_TRIP_MT_TEST AS
 select * from  XX_ONT_TRIP_MT where TRIPSYS_NO = '1018'
 
 --========================== TRIP DETAILS ===========================================
 


 
 
 
 
 
 --===================== UPDATE std.Consumpton Quantity=====================
 
-- SELECT * FROM XXTRIPDTLS_ALL where TRIPSYS_NO = '331274'
-- 
-- UPDATE XXTRIPDTLS_ALL
-- SET STD_CONSMPTION = 132.73
-- WHERE TRIPSYS_NO='331274'
 
 /*****************************************************************************
 EBS Driver Wise Fuel Issue Consumption Details (ALL)
 ******************************************************************************/

SELECT DISTINCT ORG_ID
,SUBSTR(XX_GET_HR_OPERATING_UNIT (ORG_ID),5) OPERATING_UNIT     
,XX_INV_PKG.XXGET_ORG_LOCATION (ORG_ID) ORG_ADDRESS  
,SOURCE          
,TRIP_NO                                                         
,REG_NO   
,DRIVER_NAME                                                                
,MOVE_ORDER_NUMBER ||' '|| MOVE_ORDER_NO_ADD MOVE_ORDER_NUMBER
,ROUND(NVL(ISSUED_QTY,0),2) ISSUED_QTY
,ROUND(NVL(BILL_FUEL_ISSUE,0),2) BILL_FUEL_ISSUE
,ROUND(NVL(PURCHASE_QTY,0),2) PURCHASE_QTY
,ROUND(NVL(ADJUSTED_QTY,0),2) ADJUSTED_QTY
,ROUND(NVL(CONSUMPTION_QTY,0),2) CONSUMPTION_QTY
,ROUND((NVL(BILL_FUEL_ISSUE,0)+NVL(PURCHASE_QTY,0)+NVL(ADJUSTED_QTY,0)-NVL(CONSUMPTION_QTY,0)),2) FUEL_BLNC
--,ROUND(( NVL((SUM(NVL(ISSUED_QTY,0))+SUM(NVL(PURCHASE_QTY,0))+SUM(NVL(ADJUSTED_QTY,0))-SUM(NVL(CONSUMPTION_QTY,0))),0)),2) CLOSING_BLNC
,DESCRIPTION
, XX_ONT_GET_ENAME(:P_USER) PRINTED_BY 
,CREATION_DATE
,XX_GET_EMP_NAME_FROM_USER_ID (CREATED_BY) CREATED_BY
,XX_GET_EMP_NAME_FROM_USER_ID (LAST_UPDATED_BY) UPDATED_BY
FROM XX_TRIP_FUEL_ADJ_UNADJ                                                    
WHERE 1 = 1                                
AND (:P_ORG_ID IS NULL OR ORG_ID = :P_ORG_ID)
AND (:P_VEH_TYPE IS NULL OR VEHICLE_TYPE = :P_VEH_TYPE)
--AND (:P_REG_NO IS NULL OR REG_NO = :P_REG_NO) 
AND (:P_DRIVER IS NULL OR DRIVER_NAME = :P_DRIVER) 
--AND (:P_DATE IS NULL OR CREATION_DATE <= :P_DATE+1)
--AND (:P_FROM_DT IS NULL OR TRUNC(CREATION_DATE) BETWEEN :P_FROM_DT AND :P_TO_DT)
AND   CREATION_DATE BETWEEN :P_FROM_DT AND :P_TO_DT
AND TRIP_NO    = :P_TRIP_NO --'182249'
ORDER BY REG_NO, CREATION_DATE
 
select * from XX_TRIP_FUEL_ADJ_UNADJ where  TRIP_NO    = '182249'

 
 -- =======================TABLE SCRIPT=============
 
 
 DROP TABLE APPS.XXTRIPDTLS_ALL CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXTRIPDTLS_ALL
(
  ORG_ID               NUMBER(22)               NOT NULL,
  OPERATING_UNIT       VARCHAR2(240 BYTE),
  TRIPSYS_NO           VARCHAR2(15 BYTE)        NOT NULL,
  TRIP_FROM            VARCHAR2(240 BYTE),
  TRIP_TO              VARCHAR2(240 BYTE),
  TRIP_KM              NUMBER,
  DTRIP_FROM           VARCHAR2(240 BYTE),
  DTRIP_TO             VARCHAR2(240 BYTE),
  DTRIP_KM             NUMBER,
  TRIP_DATE_FROM       DATE,
  KM_TYPE              VARCHAR2(10 BYTE),
  F_KM_LTR             NUMBER,
  OPN_BLNC             NUMBER,
  FUEL_ISSUE           NUMBER,
  FUEL_PUR             NUMBER,
  STD_CONSMPTION       NUMBER,
  EXEC_OR_SHORT        NUMBER,
  ADJ_Y_N              VARCHAR2(10 BYTE),
  ADJ_LTR              NUMBER,
  FUEL_BLNC            NUMBER,
  FUEL_RATE            NUMBER,
  AMT                  NUMBER,
  REMARKS              VARCHAR2(240 BYTE),
  TRIP_DATE_TO         DATE,
  REG_NO               VARCHAR2(50 BYTE),
  TOT_KM               NUMBER(30),
  MO_NUMBER            NUMBER,
  FUEL_PUR_AMT         NUMBER(15,3),
  TRIP_ALLOWANCE       NUMBER(15,3),
  FOODING_ALLOWANCE    NUMBER(15,3),
  OVER_LOAD_CHARGE     NUMBER(15,3),
  TOLL_CHARGE          NUMBER(15,3),
  LABOUR_EXPENSES      NUMBER(15,3),
  PAY_AGAINST_FUEL     NUMBER(15,3),
  POLICE_EXPENSES      NUMBER(15,3),
  REPAIR_EXPENSES      NUMBER(15,3),
  OTHER_EXPENSES       NUMBER(15,3),
  REC_AGT_FUEL_CONS    NUMBER(15,3),
  DOWN_TRIP_FARE       NUMBER(15,3),
  TRIP_ALLOWANCE_D     NUMBER(15,3),
  FOODING_ALLOWANCE_D  NUMBER(15,3),
  OVER_LOAD_CHARGE_D   NUMBER(15,3),
  TOLL_CHARGE_D        NUMBER(15,3),
  LABOUR_EXPENSES_D    NUMBER(15,3),
  PAY_AGAINST_FUEL_D   NUMBER(15,3),
  POLICE_EXPENSES_D    NUMBER(15,3),
  REPAIR_EXPENSES_D    NUMBER(15,3),
  OTHER_EXPENSES_D     NUMBER(15,3),
  DOWN_TRIP_COMM       NUMBER(15,3),
  CREATION_DATE        DATE,
  CREATED_BY           NUMBER(15),
  LAST_UPDATE_DATE     DATE,
  LAST_UPDATED_BY      NUMBER(15),
  LAST_UPDATE_LOGIN    NUMBER(15),
  TRIP_TOTAL_HOURS     VARCHAR2(50 BYTE),
  MEMO_NUMBER          NUMBER,
  MO_NUMBER_ADD        NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

 
 --===========================================================================
--EBS Transport Intercompany Income Expenses Verify Date  Wise

select legal_entity_name,org_name,org_address,trip_no,trip_date,customer_name,reg_no,vehicle_type,purpose,loading_wh,number_trip,dlv_qty,dlv_qty_uom,issued_fuel,fuel_cost,trip_fare,printed_by,
sum(trip_expense) trip_expense,remarks, trunc(:p_date_from) p_date_from, trunc(:p_date_to) p_date_to from(
select distinct a.org_id, b.operating_unit_name org_name, b.operating_unit_address org_address, b.legal_entity_name,
a.issued_org_id customer_id,decode(c.known_as,null,c.customer_name,c.known_as) customer_name , a.tripsys_no trip_no,
trunc(a.trip_date) trip_date , a.number_trip, a.transport_type, null payment_voucher, null payment_date, decode(a.vehicle_id,null,a.reg_no,d.reg_no) reg_no, d.vehicle_type, 
e.organization_code loading_wh, f.organization_code unloading_wh, a.purpose, a.fuel_issued, a.trip_fare, NVL (CASE WHEN a.move_order_number IS NULL THEN 0 ELSE a.fuel_issued END , 0) issued_fuel, NVL (a.fuel_issued * XX_FUAL_RATE_FUNC(mol.INVENTORY_ITEM_ID,TO_DATE(moh.CREATION_DATE,'DD-MON-RR')), 0) fuel_cost, NVL (ai.invoice_amount, 0) trip_expense,ai.invoice_id,
 a.remarks,decode(nvl(a.ic_verified_flag,'N'),'N','No','Y','Yes') ic_verified_desc ,ic_verified_date,
 (select distinct nvl(challan_no,0)   from XX_ONT_TRIP_ICPAY_SUM_V where tripsys_no =a.tripsys_no) challan_no,
(select distinct nvl(challan_date,0)   from XX_ONT_TRIP_ICPAY_SUM_V where tripsys_no =a.tripsys_no) challan_date,
(select distinct nvl(dlv_qty,0)   from XX_ONT_TRIP_ICPAY_SUM_V where tripsys_no =a.tripsys_no) dlv_qty,
(select distinct nvl(dlv_qty_uom,0)   from XX_ONT_TRIP_ICPAY_SUM_V where tripsys_no =a.tripsys_no) dlv_qty_uom,
(select distinct nvl(dlv_loc,0)   from XX_ONT_TRIP_ICPAY_SUM_V where tripsys_no =a.tripsys_no) dlv_loc,
--g.challan_no, g.challan_date, g.dlv_qty, g.dlv_qty_uom, g.dlv_loc,
XX_INV_PKG.XXGET_ENAME(:P_USER) printed_by
from xx_ont_trip_mt a, wbi_inv_org_detail b, xx_ar_customer_site_v c, xx_ont_vehicle_v d, org_organization_definitions e, org_organization_definitions f
--, xx_ont_trip_icpay_sum_v g
,ap_invoices_all ai
,mtl_txn_request_headers moh
,mtl_txn_request_lines mol
where 1=1
and a.org_id = b.operating_unit_id
and a.org_id = c.org_id(+)
and a.issued_org_id = c.customer_id(+)
and a.vehicle_id= d.vehicle_id(+)
and a.beneficiary_org_id = e.organization_id(+)
and a.unload_organization_id = f.organization_id(+)
and a.move_order_number = moh.header_id(+)
and moh.HEADER_ID = mol.header_id(+)
--and a.tripsys_no = g.tripsys_no(+)
AND a.tripsys_no = ai.attribute2(+)
AND AI.CANCELLED_DATE IS NULL
and a.trip_type = 'Inter Company' 
and nvl(ic_verified_flag,'N') = 'Y'
and trip_status = 'C'
--and a.close_flag = 'Y'
and a.trip_fare is not null
and ( :p_date_from is null or  trunc(ic_verified_date) between to_date(:p_date_from) and to_date(:p_date_to))
--and a.org_id = :p_org_id
--and a.issued_org_id = nvl(:p_customer_id,a.issued_org_id)
--and  nvl(g.tripsys_no,a.tripsys_no) = nvl(:p_trip_no,nvl(g.tripsys_no,a.tripsys_no))
 )
group by legal_entity_name,org_name,org_address,trip_no,trip_date,customer_name,reg_no,vehicle_type,purpose,loading_wh,number_trip,dlv_qty,dlv_qty_uom,issued_fuel,fuel_cost,trip_fare,printed_by,remarks
order by customer_name,trip_no


select * from ORG_ORGANIZATION_DEFINITIONS

select distinct *  from xx_ont_trip_mt 

TRIP STATUS
============= 
CL= Cancel
D= Discard
C= Complete
I= Initiate





SELECT * FROM  XXTRIPDTLS_ALL where TRIPSYS_NO IN(
'36339'
)


SELECT TRANSACTION_DATE , TRANSACTION_SOURCE_ID MOVE_ORDER,TRANSACTION_REFERENCE TRIP_NO,TRX_SOURCE_LINE_ID,MOVE_ORDER_LINE_ID FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_SOURCE_ID =2184830--TRANSACTION_ID=15732040 

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_SOURCE_ID =2184830

SELECT * FROM xx_ont_trip_mt  WHERE 1=1 and TRIP_TYPE = 'Inter Company' and TRIP_STATUS NOT IN ( 'CL', 'D', 'I')  and IC_VERIFIED_FLAG IS NULL and TRIPSYS_NO ='327067' --and NVL(CLOSE_FLAG,'N')='Y'


SELECT * FROM xx_ont_trip_mt where TRIPSYS_NO= '1054'

SELECT * FROm XXTRIPDTLS_ALL where TRIPSYS_NO= '1054'


SELECT * FROM XX_ONT_TRIP_DT where TRIPSYS_NO='1054'



SELECT * FROM xx_ont_trip_mt A , MTL_MATERIAL_TRANSACTIONS B 
WHERE A.TRIPSYS_NO=B.TRANSACTION_REFERENCE 
--AND A.MOVE_ORDER_NUMBER='2184830'
--AND A.TRIPSYS_NO='1024'
AND FUEL_INV_ORG_ID=152
and TRIP_TYPE = 'Inter Company' and TRIP_STATUS NOT IN ( 'CL', 'D', 'I') 
and TRIPSYS_NO IN(
'309402',
'308021'
)
AND A.MOVE_ORDER_NUMBER=B.TRANSACTION_SOURCE_ID



--TRIP COMPLETE BUT NOT BILL
--====================

SELECT a.* FROM xx_ont_trip_mt A,  XXTRIPDTLS_ALL B WHERE a.TRIPSYS_NO=b.TRIPSYS_NO
and A.TRIP_TYPE = 'Inter Company'
AND  A.TRIP_STATUS NOT IN ( 'CL', 'D', 'I') 
--AND  A.IC_VERIFIED_FLAG IS NULL 
--AND MOVE_ORDER_NUMBER = '2184830'
and A.TRIPSYS_NO IN(
'309402',
'308021'
)

SELECT * FROM xx_ont_trip_mt  WHERE 1=1 and TRIP_TYPE = 'Inter Company' and TRIP_STATUS NOT IN ( 'CL', 'D', 'I')  and IC_VERIFIED_FLAG IS NULL and TRIPSYS_NO ='327067'--and NVL(CLOSE_FLAG,'N')='Y'

SELECT * FROM XX_ONT_TRIP_DT where TRIP_STATUS NOT IN ( 'CL', 'D', 'I') and TRIPSYS_NO=1069

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID= 12261738

------------------------------------------------------
--FOR ISSUE RETURN DESEAL ITEM:
-----------------------------------------------------

 SELECT TRANSACTION_SOURCE_NAME, TRANSACTION_REFERENCE  FROM MTL_MATERIAL_TRANSACTIONS WHERE TRANSACTION_ID= 12261738

select * from ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE='TRM'

SELECT A.* FROM xx_ont_trip_mt A,  XXTRIPDTLS_ALL B WHERE a.TRIPSYS_NO=b.TRIPSYS_NO
and A.TRIP_TYPE = 'Inter Company'
AND  A.TRIP_STATUS NOT IN ( 'CL', 'D', 'I') 
AND  A.IC_VERIFIED_FLAG IS NULL 
--and a.TRIPSYS_NO ='2499'

SELECT * FROM XXTRIPDTLS_ALL where TRIPSYS_NO ='327067'


SELECT * FROM XXTRIPDTLS_ALL where TRIPSYS_NO ='2499'

VALUSET:
=======

XX_OPERATING_UNIT_FOR

RECORD GROUP QUERY FROM FORM
=======================

SELECT DISTINCT CUSTOMER_ID, CUSTOMER_TYPE,CUSTOMER_NAME CUSTOMER_NAME
FROM WBI_ONT_CUSTOMER_D 
WHERE 1=1
AND CUSTOMER_TYPE= 'I'
--ORG_ID = :XX_ONT_TRIP_MT.ORG_ID
AND DECODE(CUSTOMER_TYPE,'I','INTERNAL', 'EXTERNAL')  = DECODE(UPPER(:XX_ONT_TRIP_MT.TRIP_TYPE),'INTER COMPANY','INTERNAL','OUTSIDE','EXTERNAL')
AND STATUS='A'
AND SITE_USE_CODE = 'BILL_TO'
AND PRIMARY_FLAG = 'Y'
ORDER BY CUSTOMER_NAME

--=============================
--MOVE ORDER REPORT 
--=======================



SELECT  
                 MTRL.ORGANIZATION_ID, TRANSACTION_ID
                ,NVL((SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') ORG_NAME
                ,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY) DEPARTMENT
               ,(SELECT DISTINCT  OTM.TRIPSYS_NO FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) TRIP_NO
              ,(SELECT DISTINCT DECODE(OTM.EMPLOYEE_ID,NULL,UNLISTED_ c 
              ],(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = OTM.EMPLOYEE_ID)) DRIVER_NAME FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(MTRL.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) DRIVER_NAME
                ,MTRL.ATTRIBUTE15 GATE_PASS_NO
                ,XX_INV_PKG.XXGET_CUSTOMER_NAME((SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) ) CUSTOMER_NAME           
             ---- ,(SELECT ATTRIBUTE11 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Sample Issue to Customer/Test' AND HEADER_ID=MTHL.HEADER_ID) CUSTOMER_NAME
               ,(SELECT ATTRIBUTE1 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Move Order Issue' AND HEADER_ID=MTHL.HEADER_ID) WORK_ORDER_NO
                ,MTRL.REQUEST_NUMBER MOVE_ORDER_NUMBER
                ,MTRL.DATE_REQUIRED  MOVE_ORDER_DATE
                ,MTRL.TRANSACTION_TYPE_NAME MOVE_ORDER_TYPE
                ,ML.MEANING MO_STATUS_LINE
                ,MTHL.HEADER_STATUS_NAME  MO_STATUS
                ,(SELECT ATTRIBUTE9 FROM MTL_TXN_REQUEST_HEADERS_V WHERE ATTRIBUTE_CATEGORY='Issue to Project' AND HEADER_ID=MTHL.HEADER_ID) PROJECT_NAME
                ,MTRL.LINE_NUMBER
                , (MSI.SEGMENT1 || '|' || MSI.SEGMENT2 || '|' || MSI.SEGMENT3||'|' || MSI.SEGMENT4)    ITEM_CODE
                ,MSI.DESCRIPTION
                ,MTRL.UOM_CODE
                ---=========================================
                ,MTRL.FROM_SUBINVENTORY_CODE
                ,MTRL.INVENTORY_ITEM_ID
                -----------------------------------------------------
                , (SELECT NVL(SUM(PRIMARY_QUANTITY),0)
                FROM 
                MTL_MATERIAL_TRANSACTIONS
                WHERE 
                ORGANIZATION_ID=MTRL.ORGANIZATION_ID
                AND SUBINVENTORY_CODE=NVL(MTRL.FROM_SUBINVENTORY_CODE,SUBINVENTORY_CODE)
                AND INVENTORY_ITEM_ID=MTRL.INVENTORY_ITEM_ID 
                AND  TRANSACTION_DATE <MTRL.DATE_REQUIRED) IO_STOCK
                ---=========================================
                ,MTRL.QUANTITY  MO_QTY
                ,XX.QTY_ISSUED MO_ISSUE_QTY
                ,CASE WHEN MTRL.LINE_STATUS <>5 THEN 0   ELSE (MTRL.QUANTITY-MTRL.QUANTITY_DELIVERED)  END  CANCEL_QTY
                ,XX.SUBINVENTORY_CODE
                , (SELECT SEGMENT2||'|'||SEGMENT3||'|'||SEGMENT4||'|'||SEGMENT5 LOCATOR_DESC FROM MTL_ITEM_LOCATIONS WHERE INVENTORY_LOCATION_ID=XX.LOCATOR_ID AND ORGANIZATION_ID=MTRL.ORGANIZATION_ID) LOCATOR
                ,XX.LOT_NUMBER
                ,XX_INV_PKG.XXGET_SERIAL_NUMBER(XX.TRANSACTION_ID) SERIAL_NUMBER
               ----,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 AND OU_ID=(SELECT OPERATING_UNIT_ID FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=MTRL.ORGANIZATION_ID)) USEOFAREA
               ,(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= MTRL.ATTRIBUTE2 ) USEOFAREA
                ,MTRL.REFERENCE REASON
                ---===================================================
                ,MTHL.DESCRIPTION PURPOSE
                ,XX.TRACKING_REMARKS
                ,MTHL.CREATED_BY PREPARED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(MTHL.CREATED_BY )  PREPARED_BY
                ,XX.TAKEN_BY
                ----===========HOD=====================
                ,(XX_INV_PKG.XXGET_ENAME ((SELECT USER_ID FROM FND_USER 
                WHERE USER_NAME =(SELECT APPROVED_BY FROM XXKSRM_MOAPPROVAL_STATUS
                WHERE HEADER_ID=MTHL.HEADER_ID AND WF_STATUS='Approved')))) HOD
                ----===========HOD=====================
                --,DECODE(MTHL.HEADER_STATUS,
                --3,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --7,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --8,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)),
                --NULL
                --) HOD
               ---- ,XX_INV_PKG.XX_INV_HOD(MTRL.ORGANIZATION_ID,XX_INV_PKG.XXGET_EMP_DEPT(MTHL.CREATED_BY)) HOD
                ----===========HOD=====================
                ----===========HOD=====================
                ,XX.ISSUED_STORE STORE_IN_CHARGE_ID
                , XX_INV_PKG.XXGET_ENAME(XX.ISSUED_STORE) STORE_IN_CHARGE
                ,XX.CREATED_BY ISSUED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.CREATED_BY) ISSUED_BY
                ,XX.RECEIVED_STORE  RECEIVED_BY_ID
                , XX_INV_PKG.XXGET_ENAME(XX.RECEIVED_STORE)  RECEIVED_BY
                ,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
                ,NVL((SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=:P_ORG),'KABIR GROUP') PORG_NAME
                ,NVL((SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORG),'Kabir Manzil,SK, Mujib Road,Agrabad,Chittagong,BD') PORG_ADDRESS
                ----=====================================================
        FROM   MTL_TXN_REQUEST_HEADERS_V MTHL
          ,MTL_TXN_REQUEST_LINES_V MTRL
          ,MTL_SYSTEM_ITEMS_B MSI
          ,MFG_LOOKUPS ML
          , (  SELECT   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.ATTRIBUTE1 TAKEN_BY
                       ,MMT.ATTRIBUTE11 TRACKING_REMARKS 
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MAX (MMT.CREATED_BY) CREATED_BY
                       ,MMT.TRANSACTION_ID
                       , (MMT.TRANSACTION_DATE) TRANSACTION_DATE
                       ,SUM (ABS (MMT.PRIMARY_QUANTITY)) QTY_ISSUED
                       ,MTLN.LOT_NUMBER
                      ,MMT.ATTRIBUTE1 ISSUED_STORE
                       ,MMT.ATTRIBUTE2 RECEIVED_STORE
                 FROM   MTL_MATERIAL_TRANSACTIONS MMT
                       ,MTL_TRANSACTION_LOT_NUMBERS MTLN
                WHERE   MMT.PRIMARY_QUANTITY < 0
                    AND MMT.ORGANIZATION_ID = :P_ORG
                    AND MMT.TRANSACTION_SOURCE_TYPE_ID = 4
                    AND MTLN.TRANSACTION_ID(+)=MMT.TRANSACTION_ID
             GROUP BY   MMT.ORGANIZATION_ID
                       ,MMT.INVENTORY_ITEM_ID
                       ,MMT.TRANSACTION_TYPE_ID
                       ,MMT.ATTRIBUTE1
                       ,MMT.ATTRIBUTE11
                       ,MMT.MOVE_ORDER_LINE_ID
                       ,MMT.SUBINVENTORY_CODE
                       ,MMT.LOCATOR_ID
                       ,MMT.TRANSACTION_SOURCE_ID
                       ,MMT.REASON_ID
                       ,MTLN.LOT_NUMBER
                       ,MMT.ATTRIBUTE1 
                       ,MMT.ATTRIBUTE2 
                       ,(MMT.TRANSACTION_DATE)
                       ,MMT.TRANSACTION_ID) XX
   WHERE   MTRL.REQUEST_NUMBER = MTHL.REQUEST_NUMBER
       AND MTRL.HEADER_ID = MTHL.HEADER_ID
       AND MTRL.ORGANIZATION_ID = MTHL.ORGANIZATION_ID
       --TRANSACTION_TYPE_ID
       AND MTRL.LINE_STATUS = ML.LOOKUP_CODE
       AND ML.LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
       --AND UPPER(MTRL.transaction_type_name)='MOVE ORDER ISSUE'
       AND MTRL.ORGANIZATION_ID = NVL (:P_ORG, MTRL.ORGANIZATION_ID)
       AND MTRL.REQUEST_NUMBER = NVL (:P_FROM_MO, MTRL.REQUEST_NUMBER)
       AND TRUNC(MTHL.DATE_REQUIRED) BETWEEN NVL(:P_FROM_DATE,TRUNC(MTHL.DATE_REQUIRED))  AND  NVL(:P_TO_DATE,TRUNC(MTHL.DATE_REQUIRED))
       AND MTRL.INVENTORY_ITEM_ID =NVL(:P_ITEM_ID,MTRL.INVENTORY_ITEM_ID)
       AND MTHL.HEADER_STATUS_NAME =NVL(:P_MO_STATUS,HEADER_STATUS_NAME)
    --   AND MTRL.transaction_source_type_id = 4
       AND MTRL.ORGANIZATION_ID = XX.ORGANIZATION_ID(+)
       AND MTRL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MTRL.INVENTORY_ITEM_ID = XX.INVENTORY_ITEM_ID(+)
       AND MTRL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MTRL.LINE_ID = XX.MOVE_ORDER_LINE_ID(+)
       AND MTRL.HEADER_ID = XX.TRANSACTION_SOURCE_ID(+)
       --AND TRANSACTION_ID IS NULL
     --  AND MTRL.transaction_type_id = XX.transaction_type_id
       --AND MTRL.request_number='2002'
ORDER BY  MTRL.DATE_REQUIRED, MTRL.REQUEST_NUMBER,MTRL.LINE_NUMBER---- XX.TAKEN_BY


select * from MTL_MATERIAL_TRANSACTIONS where transaction_ID=15732040  -- TRANSACTION_SOURCE_ID,TRANSACTION_REFERENCE,TRX_SOURCE_LINE_ID,MOVE_ORDER_LINE_ID,

select TRANSACTION_SOURCE_ID MOVE_ORDER,TRANSACTION_REFERENCE TRIP_NO,TRX_SOURCE_LINE_ID,MOVE_ORDER_LINE_ID from MTL_MATERIAL_TRANSACTIONS where transaction_ID=15732040  -- ,

/***********************************************
UPDATE MOVE ORDER NO and QTY
****************************************************/

SELECT * FROM XXTRIPDTLS_ALL where TRIPSYS_NO IN( '338548','1024')

Update XXTRIPDTLS_ALL
SET FUEL_ISSUE = 49,
MO_NUMBER =2217130
WHERE TRIPSYS_NO =  '338548'




SELECT * FROM XX_ONT_TRIP_MT WHERE TRIPSYS_NO IN ('327078','327079')


SELECT * FROM XXTRIPDTLS_ALL where TRIPSYS_NO IN ('327074','327075')


XX_ONT_TRIP_MT 

update XX_ONT_TRIP_MT 
SET MOVE_ORDER_NUMBER=2200832,
FUEL_ISSUED=10,
GATE_IN_1 = TO_DATE('12/12/2022 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'), 
GATE_OUT= TO_DATE('12/12/2022 06:18:34 PM', 'MM/DD/YYYY HH12:MI:SS PM'),
FUEL_INV_ORG_ID = 152,
GATE_IN_1_ORGANIZATION_ID=121
where TRIPSYS_NO ='327079'







update XX_ONT_TRIP_MT 
SET MOVE_ORDER_NUMBER=NULL,
FUEL_ISSUED=NULL
where TRIPSYS_NO ='327074'


DELETE MOVE_ORDER_NUMBER FROM  XX_ONT_TRIP_MT 
where TRIPSYS_NO ='327078'

--FUEL_ISSUED=NULL

-- XXKSRM Monthly DIESEL Movement Report Details

SELECT
A.STATUS_DATE STATUS_DATE, MMT.TRANSACTION_DATE,
(SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL  IOD WHERE IOD.INV_ORGANIZATION_ID=A.ORGANIZATION_ID) ORG_NAME,
(SELECT  DISTINCT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL IOD WHERE IOD.INV_ORGANIZATION_ID=A.ORGANIZATION_ID) ORG_ADDRESS,
GET_ORG_CODE_FROM_ID(A.ORGANIZATION_ID) ORG_CODE,
XXGET_ITEM_DESCRIPTION(A.INVENTORY_ITEM_ID, A.ORGANIZATION_ID) ITEM_DESC,
A.REQUEST_NUMBER MO_NUMBER,
--WIRTF.ORGANIZATION_NAME,
A.ORGANIZATION_ID, A.INVENTORY_ITEM_ID,A.MOVE_ORDER_TYPE_NAME,A.TRANSACTION_TYPE_NAME,  REFERENCE TRIP_NUMBER, 
A.QUANTITY REQUESTED_QTY,
 QUANTITY_DELIVERED,
(SELECT DISTINCT  USE_AREA FROM XXKSRM_INV_USE_AREA_V WHERE USE_AREA_ID= A.ATTRIBUTE2 ) USEOFAREA ,
  (SELECT DISTINCT DECODE(OTM.EMPLOYEE_ID,NULL,UNLISTED_DRIVER,(SELECT DISTINCT VENDOR_NAME  FROM AP_SUPPLIERS  WHERE VENDOR_ID = OTM.EMPLOYEE_ID)) DRIVER_NAME FROM  XX_ONT_TRIP_MT OTM WHERE TO_CHAR(OTM.MOVE_ORDER_NUMBER)=TO_CHAR(A.REQUEST_NUMBER) AND OTM.MOVE_ORDER_NUMBER IS NOT NULL) DRIVER_NAME,
  (case when A.LINE_STATUS =3 then 'Partially Approved'
when A.LINE_STATUS =5 then 'Closed' 
when A.LINE_STATUS =6 then 'Canceled' 
 when A.LINE_STATUS =7 then 'Pre Approved'
  when A.LINE_STATUS =8 then 'Others'
end) MO_STATUS,
A.LINE_STATUS,
:P_TRANSACT_DT_FROM,
:P_TRANSACT_DT_TO
FROM MTL_TXN_REQUEST_LINES_V A,  MTL_TXN_REQUEST_HEADERS_V  B, MTL_MATERIAL_TRANSACTIONS MMT
WHERE A.HEADER_ID=B.HEADER_ID
and A.TRANSACTION_TYPE_NAME not in ('Sales Order Pick', 'Internal Order Pick')
AND A.INVENTORY_ITEM_ID = 180
AND (SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL  IOD WHERE IOD.INV_ORGANIZATION_ID=A.ORGANIZATION_ID) = NVL(:P_OU,(SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL  IOD WHERE IOD.INV_ORGANIZATION_ID=A.ORGANIZATION_ID) )
AND TRUNC(A.STATUS_DATE) BETWEEN NVL(:P_TRANSACT_DT_FROM, A.STATUS_DATE) and   NVL(:P_TRANSACT_DT_TO, A.STATUS_DATE)
AND A.ORGANIZATION_ID = NVL(:P_ORG_ID,A.ORGANIZATION_ID)
AND HEADER_STATUS_NAME NOT IN  'Incomplete'
 AND A.LINE_ID = MMT.MOVE_ORDER_LINE_ID(+)
--and A.REQUEST_NUMBER =NVL(:P_MO_NUMBER, A.REQUEST_NUMBER)
 and a.request_number= 'MO-TRM-0102013' -- 'MO-TRA-0049296'
-- AND A.LINE_STATUS =6 
 

 
 
 SELECT GET_ORG_CODE_FROM_ID(MMT.ORGANIZATION_ID) ORG_CODE ,MMT.TRANSACTION_ID , MMT.CREATION_DATE,MMT.INVENTORY_ITEM_ID, XX_GET_EMP_NAME_FROM_USER_ID (MMT.CREATED_BY) CREATED_BY,
  (SELECT TRANSACTION_TYPE_NAME FROM MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_ID=MMT.TRANSACTION_TYPE_ID) TRANSACTION_TYPE,
 MMT.TRANSACTION_TYPE_ID,MMT.TRANSACTION_QUANTITY,MMT.TRANSACTION_DATE , MMT.TRANSACTION_REFERENCE
 FROM MTL_MATERIAL_TRANSACTIONS MMT WHERE TRUNC(TRANSACTION_DATE)  BETWEEN '01-NOV-2022' and '30-NOV-2022' AND INVENTORY_ITEM_ID = 180
 and MMT.TRANSACTION_TYPE_ID not in (52,53)



SELECT * FROM MTL_TRANSACTION_TYPES WHERE TRANSACTION_TYPE_NAME in ('Sales Order Pick', 'Internal Order Pick')

--==============================
TRIP NUMBER UPDATE IN INVOICE SCREEN
--==============================

SELECT * FROM AP_INVOICES_ALL WHERE INVOICE_NUM='339567'

 

SELECT * FROM AP_INVOICES_ALL WHERE INVOICE_ID=1778002
ATTRIBUTE2 -- TRIP_NUMBER
339867

--UPDATE AP_INVOICES_ALL
--SET ATTRIBUTE2='339567'
--WHERE INVOICE_ID=1778002

----==================================
--UPDATE MOVEORDER
--REASON: User Has created a trip and generate move order but another user cancel that move order , when user tring to transact thje move order , he sow that it is canceled.
--Then user create a maual move order and we captured that manual  move order in the trip from backend  
----==================================

SELECT * FROM XX_ONT_TRIP_MT where TRIPSYS_NO =  349302


--=============================== TRIP DETAILS FORM ER CALCULATION==============================

--OPENING BALANCE ERR CALCULATION:
BEGIN
  SELECT NVL((SUM(NVL(ISSUED_QTY,0))+SUM(NVL(PURCHASE_QTY,0))+SUM(NVL(ADJUSTED_QTY,0))-SUM(NVL(CONSUMPTION_QTY,0))),0)
  INTO :XXTRIPDTLS_ALL.OPN_BLNC  
  FROM XX_TRIP_FUEL_ADJ_UNADJ 
  WHERE ORG_ID=:XXTRIPDTLS_ALL.ORG_ID
  AND REG_NO=:XXTRIPDTLS_ALL.REG_NO  
  AND CREATION_DATE <SYSDATE;
EXCEPTION 
WHEN OTHERS THEN  
NULL ;
END;


  SELECT NVL((SUM(NVL(ISSUED_QTY,0))+SUM(NVL(PURCHASE_QTY,0))+SUM(NVL(ADJUSTED_QTY,0))-SUM(NVL(CONSUMPTION_QTY,0))),0)
  --INTO :XXTRIPDTLS_ALL.OPN_BLNC  
  FROM XX_TRIP_FUEL_ADJ_UNADJ 
  WHERE ORG_ID=:XXTRIPDTLS_ALL.ORG_ID
  AND REG_NO=:XXTRIPDTLS_ALL.REG_NO  
  AND CREATION_DATE <SYSDATE;
  
   SELECT * FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_CODE='TRM'