
 
 
-----list all Purchase Requisition without a Purchase Order that means  a PR has not been autocreated to PO.  
  select   
  prh.segment1 "PR NUM",   
  trunc(prh.creation_date) "CREATED ON",   
  trunc(prl.creation_date) "Line Creation Date" ,  
  prl.line_num "Seq #",   
  msi.segment1 "Item Num",   
  prl.item_description "Description",   
  prl.quantity "Qty",   
  trunc(prl.need_by_date) "Required By",   
  ppf1.full_name "REQUESTOR",   
  ppf2.agent_name "BUYER"   
  from   
  po.po_requisition_headers_all prh,  
  po.po_requisition_lines_all prl,   
  apps.per_people_f ppf1,   
  (select distinct agent_id,agent_name from apps.po_agents_v ) ppf2,   
  po.po_req_distributions_all prd,   
  inv.mtl_system_items_b msi,   
  po.po_line_locations_all pll,   
  po.po_lines_all pl,   
  po.po_headers_all ph  
  WHERE   
  prh.requisition_header_id = prl.requisition_header_id   
  and prl.requisition_line_id = prd.requisition_line_id   
  and ppf1.person_id = prh.preparer_id   
  and prh.creation_date between ppf1.effective_start_date and ppf1.effective_end_date   
  and ppf2.agent_id(+) = msi.buyer_id   
  and msi.inventory_item_id = prl.item_id   
  and msi.organization_id = prl.destination_organization_id   
  and pll.line_location_id(+) = prl.line_location_id   
  and pll.po_header_id = ph.po_header_id(+)   
  AND PLL.PO_LINE_ID = PL.PO_LINE_ID(+)   
  AND PRH.AUTHORIZATION_STATUS = 'APPROVED'   
  AND PLL.LINE_LOCATION_ID IS NULL   
  AND PRL.CLOSED_CODE IS NULL   
  AND NVL(PRL.CANCEL_FLAG,'N') <> 'Y'  
  ORDER BY 1,2  
  
  
  
  --==================5-FEB-2018============================
  
  select * FROM WBI_XXKBGITEM_MT_D

SELECT ITEM_GROUP,ITEM_SUB_GROUP,ITEM_CODE,ITEM_DESC FROM WBI_XXKBGITEM_MT_D
WHERE  ITEM_GROUP = 'ELECTRICAL';        



select distinct ITEM_GROUP from  WBI_XXKBGITEM_MT_D



select * from  MTL_ITEM_CATEGORIES_V

select distinct segment2 from  MTL_ITEM_CATEGORIES_V --- Group and sub group can take from here


select * from mtl_system_items_b

select * from  WBI_INV_RCV_TRANSACTIONS_F

select distinct ORGANIZATION_ID from WBI_INV_RCV_TRANSACTIONS_F

SELECT * FROM PO_HEADERS_ALL WHERE SEGMENT1='40000007'

--===================5-FEB-2018 GRN LOCAL REPORT=========================

SELECT 
DISTINCT WIRTF.ORGANIZATION_ID
,SEGMENT1 ITEM_GROUP
,SEGMENT2 ITEM_SUBGROUP
,WIRTF.RECEIPT_NO GRN_NO
,WIRTF.RECEIPT_DATE GRN_DATE
,DECODE(WIRTF.GRN_SOURCE,'VENDOR',WIRTF.PO_NO,'INTERNAL ORDER',WIRTF.SHIPMENT_NUM,'INVENTORY',WIRTF.SHIPMENT_NUM,'CUSTOMER',WIRTF.CUSTOMER_ORDER_NO)  PO_NO
,WIRTF.PO_APPROVED_DATE
,DECODE(WIRTF.GRN_SOURCE,'VENDOR',WIRTF.SUPPLIER,
                                              'INTERNAL ORDER',(SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WIRTF.IOT_IR_FROM_ORG),
                                              'INVENTORY',(SELECT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WIRTF.IOT_IR_FROM_ORG),
                                              'CUSTOMER',XX_INV_PKG.XXGET_CUSTOMER_NAME(WIRTF.GRN_CUS_ID)) SUPPLIER
,WIRTF.VENDOR_ID SUPPLIER_ID
,DECODE(WIRTF.GRN_SOURCE,'VENDOR',WIRTF.SUPPLIER_ADDRESS,
                                              'INTERNAL ORDER',(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WIRTF.IOT_IR_FROM_ORG),
                                              'INVENTORY',(SELECT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WIRTF.IOT_IR_FROM_ORG),
                                              'CUSTOMER',(SELECT ADDRESS1||', '||ADDRESS2||', '||ADDRESS3||', '||ADDRESS4||', '||CITY||', '||COUNTRY ADDRESS  FROM XX_AR_CUSTOMER_SITE_V 
                                                                 WHERE SITE_USE_CODE = 'BILL_TO' AND PRIMARY_FLAG = 'Y' AND CUSTOMER_ID =WIRTF.GRN_CUS_ID 
                                                                 AND ORG_ID =(SELECT DISTINCT OPERATING_UNIT_ID FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID= :P_ORGANIZATION_ID) ) ) SUPPLIER_ADDRESS
,WIRTF.PREPAYMENT_AMOUNT
,WIRTF.LC_CERTIF_OF_ORIGIN CERTIF_OF_ORGN
,NVL(XLD.LC_NUMBER,WIRTF.LC_NO_IOT) LC_NUMBER
,NVL(XLD.LC_OPENING_DATE,WIRTF.LC_OPENING_DATE_IOT) LC_DATE
,DECODE(XLD.LC_TYPE,'D','Defferd','S','Sight','U','UPass','C','CAD',NULL) LC_TYPE
,WIRTF.LC_AIR_VSL_NAME AIR_VSL_NAME
,WIRTF.LC_BL_NO
,WIRTF.LC_BL_DATE BL_DATE
,(SELECT  DISTINCT INV_ORGANIZATION_CODE||'-'||INVENTORY_ORGANIZATION_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WIRTF.ORGANIZATION_ID) INV_ORG_NAME
,(SELECT  DISTINCT INV_ORG_ADDRESS FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WIRTF.ORGANIZATION_ID) ORG_ADDRESS
,(SELECT DISTINCT OPERATING_UNIT_NAME FROM WBI_INV_ORG_DETAIL WHERE INV_ORGANIZATION_ID=WIRTF.ORGANIZATION_ID) ORG_NAME
,WIRTF.DEPARTMENT
,WIRTF.GATE_ENTRY_NO
,TO_CHAR(TO_DATE(WIRTF.GATE_ENTRY_DATE,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YYYY') GATE_ENTRY_DATE
,WIRTF.RELEASE_NUMBER RELEASE_NO
,WIRTF.RELEASE_DATE RELEASE_DATE
,WIRTF.INVENTORY_ITEM_ID
,WIRTF.ITEM_CODE
,WIRTF.ITEM_DESC
,WIRTF.UOM
,WIRTF.PR_NO
,WIRTF.PO_PRICE
,WIRTF.PR_QTY
,NVL(WIRTF.PO_QTY,WIRTF.IOT_QTY)  PO_QTY
,WIRTF.RECEIPT_QTY RECEIPT_QTY
,(NVL(WIRTF.DELIVER_QTY,0)-NVL(WIRTF.DLV_RETURN_QTY,0)) DELIVER_QTY
,WIRTF.PO_PRICE * (NVL(WIRTF.DELIVER_QTY,0)-NVL(WIRTF.DLV_RETURN_QTY,0)) Total_Price
,WIRTF.DLV_RETURN_QTY
,WIRTF.ACCEPTED_QTY
,(NVL(WIRTF.REJECTED_QTY,0)-NVL(WIRTF.RETURN_QTY,0)) REJECTED_QTY
,WIRTF.RETURN_QTY
,WIRTF.SUBINVENTORY
,WIRTF.LOCATOR_NAME
,WIRTF.ACCEPTED_QTY DELIVER_TO_SI
,WIRTF.RATE
,(NVL((NVL(WIRTF.DELIVER_QTY,0)-NVL(WIRTF.DLV_RETURN_QTY,0)),0) * NVL(WIRTF.RATE,0) ) AMOUNT
,WIRTF.CHALLAN_NUMBER_RT CHALLAN_NO
,WIRTF.CHALLAN_QUANTITY_RT CHALLAN_QTY
,TO_CHAR(TO_DATE(WIRTF.CHALLAN_DATE,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YYYY') CHALLAN_DATE
,WIRTF.VEHICLE_NUMBER_RT
,WIRTF.BRAND 
,WIRTF.ORIGIN 
,WIRTF.LOT_NO LOT_NUMBER
,WIRTF.SERIAL_NO SERIAL_NUM
,NULL EXPIRY_DATE
,WIRTF.INSPECTION_DATE
,WIRTF.INSPECTION_BY
,WIRTF.REMARKS
,WIRTF.PREPARED_BY
,WIRTF.LC_LDT_WT
,WIRTF.LC_DWT_WT
,WIRTF.LC_CUTTING_WT
,WIRTF.LOT_NO
,DECODE(WIRTF.GRN_SOURCE,'INVENTORY','Inter Org Transfer','VENDOR','Purchase Order',WIRTF.GRN_SOURCE)  GRN_SOURCE
,XX_INV_PKG.XXGET_ENAME (TO_CHAR (:P_USER)) USER_NAME
FROM WBI_INV_RCV_TRANSACTIONS_F WIRTF
,XX_LC_DETAILS XLD
,MTL_ITEM_CATEGORIES_V MIC
WHERE WIRTF.PO_HEADER_ID=XLD.PO_HEADER_ID(+)
AND MIC.INVENTORY_ITEM_ID =WIRTF.INVENTORY_ITEM_ID
AND WIRTF.ORGANIZATION_ID=:P_ORGANIZATION_ID
AND WIRTF.TRANSACTION_TYPE IN ('RECEIVE','UNORDERED')
AND NVL(WIRTF.RECEIPT_NO,'A') =NVL(NVL(:P_RECEIPT_NO,WIRTF.RECEIPT_NO),'A')
AND TO_DATE(WIRTF.RECEIPT_DATE) BETWEEN NVL(:P_TRANSACTION_DATE_FROM,TO_DATE(WIRTF.RECEIPT_DATE))  AND NVL(:P_TRANSACTION_DATE_TO,TO_DATE(WIRTF.RECEIPT_DATE))
AND NVL(WIRTF.PO_NO,'A')=NVL(NVL(:P_PO_NO,PO_NO),'A')
AND NVL(WIRTF.LC_NO,'A')=NVL(NVL(:P_LC_NO,LC_NO),'A')
AND NVL(WIRTF.CHALLAN_NUMBER_RT ,'A')=NVL(NVL(:P_CHALLAN_NO,WIRTF.CHALLAN_NUMBER_RT),'A')
AND NVL(WIRTF.VENDOR_ID,0)=NVL(NVL(:P_VENDOR_ID,WIRTF.VENDOR_ID),0)
AND WIRTF.ITEM_CODE=NVL(:P_ITEM_CODE,WIRTF.ITEM_CODE)
AND NVL(WIRTF.LOT_NO,'XX')=NVL(:P_LOT_NO,NVL(WIRTF.LOT_NO,'XX'))
AND WIRTF.RECEIPT_NO = '80000001'
ORDER BY WIRTF.RECEIPT_DATE,WIRTF.RECEIPT_NO



--==================================================================== 



